import type { EpisodeStage } from '../../components/ui'
import { W_CORE_EDGES, WN, wAs, we } from './episode-whatsapp-stage-nodes'
import { WHATSAPP_SRC as S } from './episode-whatsapp-sources'

// Stages 1–6: launch through the 2014 architecture. Numbers are from the cited sources unless marked "estimate".
export const WHATSAPP_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'v0 · Launch on an open-source chat server',
    era: '2009',
    scale: 'a few friends · iPhone only',
    summary: 'Start from an existing XMPP chat server instead of writing one.',
    nodes: [WN.sender, wAs(WN.chat, 'ejabberd', 'open-source XMPP'), WN.recv],
    edges: [we('sender', 'chat'), we('chat', 'recv')],
    flows: [{ name: 'Send', path: ['sender', 'chat', 'recv'], steps: ['Phone sends the message to the chat server', 'Server pushes it to the online recipient'] }],
    problem: <p>Two founders want a messaging app that feels like SMS but works over the internet. They have no time to build a messaging server from scratch.</p>,
    decision: <p>Run <strong>ejabberd</strong>, an open-source XMPP server written in Erlang. Phones hold a connection to it and exchange messages through it.</p>,
    tradeoff: <p>XMPP is chatty and generic. It was built for desktop chat, not for phones on flaky mobile networks with tiny data plans.</p>,
    realWorld: <p>Jan Koum incorporated WhatsApp in February 2009. Public write-ups of its architecture say the backend started as ejabberd.</p>,
    walkthrough: ['Phone opens a long-lived connection to the server.', 'User sends a message addressed to a phone number.', 'Server looks up the recipient’s connection and forwards it.'],
    numbers: [{ label: 'Founded', value: 'Feb 2009', note: 'Wikipedia' }, { label: 'Protocol', value: 'XMPP', note: 'via ejabberd' }],
    components: [{ name: 'ejabberd', role: 'A proven Erlang chat server: presence, routing, and connections out of the box.' }],
    alternatives: [{ option: 'Write a server from scratch', verdict: 'Months of work before learning whether anyone wants the product.' }, { option: 'Build on SMS', verdict: 'Costs per message and no rich media.' }],
    breaksNext: <p>Generic XMPP wastes bytes and battery on mobile, and one box can only hold so many connections.</p>,
    interview: { q: 'Why start from an off-the-shelf server?', a: <p>It proves the product fast. You pay back the shortcut later, once you know exactly which parts to rewrite.</p> },
    sources: [S.wiki, S.hs19b],
  },
  {
    title: 'v1 · Two million phones on one box',
    era: '2011–2012',
    scale: 'tens of millions of users',
    summary: 'Tune Erlang and FreeBSD until one server holds millions of open connections.',
    added: ['chat'],
    nodes: [WN.sender, wAs(WN.chat, 'Chat servers', 'Erlang · FreeBSD'), WN.recv],
    edges: [we('sender', 'chat'), we('chat', 'recv')],
    flows: [{ name: 'Send', path: ['sender', 'chat', 'recv'], steps: ['Phone sends over its persistent connection', 'The server holding the recipient’s connection delivers it'] }],
    problem: <p>Every phone keeps a connection open so messages arrive instantly. Connections, not messages per second, become the unit of cost.</p>,
    decision: <p>Replace generic XMPP with a <strong>compact custom protocol</strong>. Profile and patch Erlang and FreeBSD so each machine holds far more sockets.</p>,
    tradeoff: <p>Deep OS and runtime tuning is specialist work. It ties the system to one platform and a small group of experts.</p>,
    realWorld: <p>A January 2012 WhatsApp blog post showed 2,277,845 open TCP sockets on one FreeBSD machine with 24 cores, with CPU and memory to spare.</p>,
    walkthrough: ['Each connected phone is one lightweight Erlang process.', 'The process owns that phone’s socket and routes its messages.', 'Kernel and VM tuning raise the per-machine connection ceiling.'],
    numbers: [{ label: 'Connections, one box', value: '2.28M', note: 'Jan 2012 blog' }, { label: 'Cores', value: '24', note: 'Xeon X5675' }, { label: 'OS', value: 'FreeBSD 8.2' }],
    components: [{ name: 'Erlang processes', role: 'Millions of cheap, isolated processes: one per connection, crash one without harming others.' }, { name: 'FreeBSD tuning', role: 'Kernel limits and network stack settings sized for millions of sockets.' }],
    alternatives: [{ option: 'More, smaller servers', verdict: 'More machines to run and more cross-server routing.' }, { option: 'Stay on plain XMPP', verdict: 'Too many bytes per message for mobile data.' }],
    breaksNext: <p>Phones go offline constantly. Messages need somewhere to wait.</p>,
    interview: { q: 'What limits a push-style chat server?', a: <p>Concurrent connections: memory per socket, file descriptors, and kernel limits. Size servers by connections, then messages.</p> },
    sources: [S.twoMillion, S.hs19b],
  },
  {
    title: 'v2 · Store and forward',
    era: 'Documented by 2014',
    scale: 'hundreds of millions of phones',
    summary: 'Hold a message only until the recipient’s phone takes it, then delete it.',
    added: ['queue'],
    nodes: [WN.sender, WN.chat, WN.queue, WN.recv],
    edges: W_CORE_EDGES,
    flows: [
      { name: 'Offline', path: ['sender', 'chat', 'queue'], steps: ['Sender uploads the message', 'Recipient is offline, so the server queues it'] },
      { name: 'Reconnect', path: ['queue', 'chat', 'recv'], steps: ['Recipient reconnects; the queue drains', 'Phone confirms receipt and the server deletes its copy'] },
    ],
    problem: <p>Phones sleep, lose signal, and switch networks. A message sent to an offline phone must not be lost.</p>,
    decision: <p>Queue undelivered messages on the server. Delete each one as soon as the phone acknowledges it. <strong>The phone, not the server, is the archive.</strong></p>,
    tradeoff: <p>No server-side history means no easy restore to a new phone. That later forces a separate backup design.</p>,
    realWorld: <p>WhatsApp’s 2014 talks describe messages being stored only while they are being delivered, then wiped once the client accepts them.</p>,
    walkthrough: ['Server receives a message for an offline phone.', 'It appends the message to that phone’s offline queue.', 'When the phone reconnects, the server sends queued messages in order.', 'Each acknowledgement deletes the stored copy.'],
    numbers: [{ label: 'Messages per day', value: '19B in · 40B out', note: '2014 talk' }, { label: 'Stored after delivery', value: 'none', note: 'transient by design' }],
    components: [{ name: 'Offline queue', role: 'Per-recipient buffer for messages that could not be delivered yet.' }, { name: 'Delivery acks', role: 'The phone’s receipt is what allows the server to delete.' }],
    alternatives: [{ option: 'Keep full history on servers', verdict: 'Huge storage cost and a privacy liability.' }, { option: 'Drop messages for offline phones', verdict: 'Unacceptable for a messenger.' }],
    breaksNext: <p>Routing needs to know, fast, which server holds which phone, and who is in which group.</p>,
    interview: { q: 'Why does “out” exceed “in” for messages?', a: <p>Group messages fan out. One incoming message becomes one outgoing copy per recipient.</p> },
    sources: [S.hs500m, S.hs19b],
  },
  {
    title: 'v3 · State in Mnesia',
    era: 'Documented by 2014',
    scale: 'billions of routing records',
    summary: 'Keep routing and account state in Erlang’s in-memory database, split into partitions.',
    added: ['mnesia'],
    nodes: [WN.sender, WN.chat, WN.mnesia, WN.queue, WN.recv],
    edges: [...W_CORE_EDGES, we('chat', 'mnesia')],
    flows: [{ name: 'Route', path: ['sender', 'chat', 'mnesia'], steps: ['Message arrives for a phone number', 'Server looks up routing and account state in memory'] }],
    problem: <p>Every message needs lookups: which account, which session, which group members. Disk-based lookups would add latency to every hop.</p>,
    decision: <p>Store this state in <strong>Mnesia</strong>, Erlang’s built-in distributed database, held in RAM and partitioned across machines.</p>,
    tradeoff: <p>RAM is expensive, and in-memory data needs careful replication and recovery. It is a niche database with few operators outside Erlang shops.</p>,
    realWorld: <p>The 2014 talk describes about 2 TB of RAM of Mnesia data across 16 partitions, holding about 18 billion records.</p>,
    walkthrough: ['Chat server receives a message.', 'It reads routing state from the right Mnesia partition.', 'It forwards to the recipient’s server or the offline queue.'],
    numbers: [{ label: 'Mnesia RAM', value: '≈ 2 TB', note: '2014 talk' }, { label: 'Partitions', value: '16' }, { label: 'Records', value: '≈ 18B' }],
    components: [{ name: 'Mnesia', role: 'Erlang-native tables in memory. No serialization gap between app and database.' }],
    alternatives: [{ option: 'External SQL database', verdict: 'Extra network hop and a different operational stack.' }, { option: 'Redis-style cache + DB', verdict: 'Two systems to keep consistent.' }],
    breaksNext: <p>Photos and voice notes are far bigger than text. They don’t belong on chat servers.</p>,
    interview: { q: 'When is an in-memory primary store reasonable?', a: <p>When the working set fits in RAM, reads are hot, and you have replication plus a recovery plan for node loss.</p> },
    sources: [S.hs500m],
  },
  {
    title: 'v4 · Media on its own servers',
    era: 'Documented by 2014',
    scale: 'hundreds of millions of media files a day',
    summary: 'Send photos and voice notes over HTTP to media servers; chat carries only a pointer.',
    added: ['media'],
    nodes: [WN.sender, WN.chat, WN.mnesia, WN.queue, WN.media, WN.recv],
    edges: [...W_CORE_EDGES, we('chat', 'mnesia'), we('sender', 'media'), we('media', 'recv')],
    flows: [
      { name: 'Upload', path: ['sender', 'media'], steps: ['Phone uploads the file over HTTP'] },
      { name: 'Notify', path: ['sender', 'chat', 'recv'], steps: ['Phone sends a small message with the file reference and a thumbnail', 'Recipient gets the message instantly'] },
      { name: 'Download', path: ['media', 'recv'], steps: ['Recipient fetches the file when it chooses'] },
    ],
    problem: <p>A photo is thousands of times bigger than a text. Pushing it through chat servers would clog the connection path everyone depends on.</p>,
    decision: <p>Split the <strong>data plane</strong>. Media goes over HTTP to dedicated media servers. The chat message carries a reference and a small thumbnail.</p>,
    tradeoff: <p>Two systems must agree. A message can arrive before its file is ready, or after the file has expired.</p>,
    realWorld: <p>The 2014 talk lists about 250 multimedia servers alongside about 150 chat servers. Daily volume was about 600M photos, 200M voice messages, and 100M videos.</p>,
    walkthrough: ['Phone uploads the media file to a media server.', 'Phone sends a chat message with the file’s reference.', 'Recipient sees the thumbnail at once.', 'Recipient downloads the full file on demand.'],
    numbers: [{ label: 'Photos per day', value: '≈ 600M', note: '2014 talk' }, { label: 'Voice notes per day', value: '≈ 200M' }, { label: 'Media servers', value: '≈ 250' }],
    components: [{ name: 'Media servers', role: 'Plain HTTP upload and download, scaled separately from chat.' }, { name: 'Thumbnail in message', role: 'The chat stays instant even if the full file is slow.' }],
    alternatives: [{ option: 'Send media through chat servers', verdict: 'Large payloads delay every small message behind them.' }, { option: 'Peer-to-peer transfer', verdict: 'Fails when the recipient is offline.' }],
    breaksNext: <p>Hundreds of servers need a way to scale and fail over without a big operations team.</p>,
    interview: { q: 'Why separate media from messaging?', a: <p>Different size, latency, and storage profiles. Isolating them keeps the small, latency-critical path fast.</p> },
    sources: [S.hs500m, S.hs19b],
  },
  {
    title: 'v5 · Partitioned pairs, tiny team',
    era: 'By early 2014',
    scale: '465M monthly users · 147M peak connections',
    summary: 'Split every backend service into partitions, each run as a primary and secondary pair.',
    added: ['backend'],
    nodes: [WN.sender, WN.chat, WN.mnesia, WN.backend, WN.queue, WN.media, WN.recv],
    edges: [...W_CORE_EDGES, we('chat', 'mnesia'), we('chat', 'backend'), we('sender', 'media'), we('media', 'recv')],
    flows: [{ name: 'Route', path: ['sender', 'chat', 'backend'], steps: ['Message arrives at a chat server', 'Chat server calls the backend partition that owns the data'] }],
    problem: <p>Growth is explosive, but the team is tiny. Any design that needs constant manual care will not survive.</p>,
    decision: <p>Partition backend services (up to 32 ways). Run nodes as <strong>primary–secondary pairs</strong>. Keep each piece simple enough to reason about under pressure.</p>,
    tradeoff: <p>Fixed partition counts are hard to change later. Pairs mean some capacity always sits idle as standby.</p>,
    realWorld: <p>The March 2014 talk describes about 550 servers and more than 11,000 cores. About 10 people worked on the Erlang system, covering both development and operations.</p>,
    walkthrough: ['Each service splits its data into a fixed number of partitions.', 'Every partition runs on a primary node with a secondary ready.', 'Chat servers route each call to the owning partition.', 'On failure, the secondary takes over.'],
    numbers: [{ label: 'Servers', value: '≈ 550', note: '2014 talk' }, { label: 'Peak connections', value: '147M' }, { label: 'Peak logins', value: '230K/s' }],
    components: [{ name: 'Partitioned services', role: 'Each piece of data has one owner, so there is no global lock.' }, { name: 'Primary–secondary pairs', role: 'Simple failover without a consensus system.' }],
    alternatives: [{ option: 'Consistent hashing with many replicas', verdict: 'More flexible, but more moving parts for a tiny team.' }, { option: 'Scale up single machines further', verdict: 'Hits hardware limits and has no redundancy.' }],
    breaksNext: <p>A new owner and a much larger audience bring new expectations, above all privacy.</p>,
    interview: { q: 'How can ~10 engineers run hundreds of millions of connections?', a: <p>Few features, one language and runtime, simple partitioning, and ruthless focus on the core path.</p> },
    sources: [S.hs500m, S.billionB],
  },
]
