import type { EpisodeStage } from '../../components/ui'
import { F_CORE_EDGES, FN, fAs, fe } from './episode-figma-stage-nodes'
import { FIGMA_SRC as S } from './episode-figma-sources'

// Stages 7–12: scaling the databases, real-time data, and durability. Numbers are from the cited sources.
export const FIGMA_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'v6 · Buy time on one database',
    era: '2020',
    scale: 'DB traffic growing ≈ 3× a year',
    summary: 'Bigger machine, read replicas, and a connection pooler keep one Postgres alive a little longer.',
    added: ['replicas'],
    nodes: [FN.editor, FN.peer, FN.api, FN.mp, FN.s3, fAs(FN.pg, 'Postgres', 'one RDS instance'), FN.replicas],
    edges: [...F_CORE_EDGES, fe('api', 'replicas')],
    flows: [
      { name: 'Write', path: ['editor', 'api', 'pg'], steps: ['User renames a file', 'API writes the change to the primary'] },
      { name: 'Read', path: ['editor', 'api', 'replicas'], steps: ['User opens the file browser', 'API serves the list from a read replica'] },
    ],
    problem: <p>A single Postgres instance holds files, teams, and permissions. It runs at over 65% CPU at peak, and traffic grows about 3× a year.</p>,
    decision: <p>Take the quick wins first: move to the <strong>largest instance</strong>, add <strong>read replicas</strong>, and put <strong>PgBouncer</strong> in front to pool thousands of connections.</p>,
    tradeoff: <p>These fixes buy months, not years. Replicas lag slightly, so code must know which reads can be stale.</p>,
    realWorld: <p>Figma’s 2023 post describes moving from an r5.12xlarge to an r5.24xlarge, adding replicas and PgBouncer, and putting new features on new databases.</p>,
    walkthrough: ['Writes go to the single primary.', 'Read-heavy queries go to replicas.', 'PgBouncer shares a small pool of real connections across many app servers.', 'New features get their own databases from day one.'],
    numbers: [{ label: 'Peak CPU', value: '> 65%', note: 'Figma, 2020' }, { label: 'DB traffic growth', value: '≈ 3× / year', note: 'Figma' }],
    components: [{ name: 'Read replicas', role: 'Take read load off the primary, near real time.' }, { name: 'PgBouncer', role: 'Connection pooling so thousands of clients don’t exhaust Postgres.' }],
    alternatives: [{ option: 'Shard immediately', verdict: 'Months of work while the fire burns; quick wins came first.' }, { option: 'Switch databases', verdict: 'Too risky for the core product data.' }],
    breaksNext: <p>The biggest instance is still one machine. The next step must split the data itself.</p>,
    interview: { q: 'What do you try before sharding?', a: <p>Vertical scaling, replicas for reads, connection pooling, caching, and moving new or separable data elsewhere.</p> },
    sources: [S.multipleDbs],
  },
  {
    title: 'v7 · Vertical partitioning',
    era: '2020 → Oct 2022',
    scale: 'a dozen databases',
    summary: 'Move groups of related tables into their own databases, with under a minute of impact each time.',
    nodes: [FN.editor, FN.peer, FN.api, FN.mp, FN.s3, fAs(FN.pg, 'Partitioned DBs', 'a dozen · by table group'), FN.replicas],
    edges: [...F_CORE_EDGES, fe('api', 'replicas')],
    flows: [{ name: 'Write', path: ['editor', 'api', 'pg'], steps: ['User edits a comment', 'API routes the write to the database that now owns comment tables'] }],
    problem: <p>Tactical fixes are exhausted. The data must be split, but without downtime for a product people use all day.</p>,
    decision: <p><strong>Vertical partitioning</strong>: move groups of related tables to separate databases. Copy with logical replication, then switch traffic in a short, coordinated cutover.</p>,
    tradeoff: <p>Queries that joined across the moved tables must be rewritten. And a single table can still outgrow its own database.</p>,
    realWorld: <p>Figma reported under one minute of availability impact per move. After the moves, the largest partition dropped to about 10% CPU.</p>,
    walkthrough: ['Pick a group of tables with few joins to the rest.', 'Copy them to a new database with logical replication.', 'Pause writes briefly and switch app routing.', 'Drop the old copies once verified.'],
    numbers: [{ label: 'Impact per move', value: '< 1 min', note: 'Figma' }, { label: 'Largest partition CPU', value: '≈ 10%', note: 'after moves' }],
    components: [{ name: 'Logical replication', role: 'Streams table changes to the new database until cutover.' }, { name: 'Routing config', role: 'Tells thousands of app instances which database owns which tables.' }],
    alternatives: [{ option: 'Horizontal sharding first', verdict: 'Harder, and not yet needed for most tables.' }, { option: 'Downtime migrations', verdict: 'Unacceptable for a collaborative tool.' }],
    breaksNext: <p>Beyond the canvas, users expect comments and file lists to update live too.</p>,
    interview: { q: 'Vertical or horizontal partitioning first?', a: <p>Vertical when load comes from different table groups; horizontal when one table is too big for any single machine.</p> },
    sources: [S.multipleDbs, S.sharding],
  },
  {
    title: 'v8 · LiveGraph for everything else',
    era: 'Oct 2021',
    scale: 'real-time outside the canvas',
    summary: 'Push database changes to browsers by tailing Postgres’s replication stream.',
    added: ['lg'],
    nodes: [FN.editor, FN.peer, FN.api, FN.mp, FN.s3, FN.pg, FN.lg],
    edges: [...F_CORE_EDGES, fe('pg', 'lg', { async: true }), fe('lg', 'editor')],
    flows: [{ name: 'Live list', path: ['editor', 'api', 'pg', 'lg', 'editor'], steps: ['A teammate adds a file', 'API writes it to Postgres', 'LiveGraph sees the change in the replication stream', 'It pushes the updated list to subscribed browsers'] }],
    problem: <p>The canvas is live, but comments and the file browser need a refresh. Polling the database from every browser would be expensive.</p>,
    decision: <p>Build <strong>LiveGraph</strong>: clients subscribe with GraphQL-like queries, and the service tails Postgres’s <strong>replication log</strong> to push changes.</p>,
    tradeoff: <p>A new stateful service to run, and query results must be recomputed or updated as the underlying rows change.</p>,
    realWorld: <p>Figma’s October 2021 post says LiveGraph powers comments, the file browser, and mobile, but not the document canvas, which stays on multiplayer.</p>,
    walkthrough: ['Browser subscribes to a query, such as “files in this project”.', 'A write lands in Postgres.', 'LiveGraph reads it from the replication stream.', 'It updates affected subscriptions and pushes the change.'],
    numbers: [{ label: 'Update latency', value: 'milliseconds', note: 'Figma, 2021' }, { label: 'Scope', value: 'non-canvas data' }],
    components: [{ name: 'LiveGraph', role: 'Turns database changes into live query results for clients.' }],
    alternatives: [{ option: 'Client polling', verdict: 'Slow to update and heavy on the database.' }, { option: 'Publish events from app code', verdict: 'Easy to forget one write path; the log never forgets.' }],
    breaksNext: <p>Losing 30–60 seconds of canvas work on a crash is no longer acceptable.</p>,
    interview: { q: 'Why tail the database log for live updates?', a: <p>Every committed write appears there exactly once, in order, whatever code path wrote it.</p> },
    sources: [S.liveGraph],
  },
  {
    title: 'v9 · A journal for every edit',
    era: 'Oct 2022',
    scale: '2.2B+ changes a day',
    summary: 'Log each batch of edits to a journal within milliseconds instead of waiting for the next checkpoint.',
    added: ['journal'],
    nodes: [FN.editor, FN.peer, FN.api, FN.mp, FN.journal, FN.s3, FN.pg],
    edges: [...F_CORE_EDGES, fe('mp', 'journal')],
    flows: [
      { name: 'Edit', path: ['editor', 'mp', 'journal'], steps: ['Edit reaches the file’s process', 'The process appends the batch to the journal with a sequence number'] },
      { name: 'Recover', path: ['s3', 'mp', 'journal'], steps: ['After a crash, load the last checkpoint', 'Replay journal entries after it'] },
    ],
    problem: <p>With checkpoints every 30–60 seconds, a crashed multiplayer process could lose up to a minute of work, and deploys caused checkpoint spikes.</p>,
    decision: <p>Add a <strong>write-ahead journal</strong> in DynamoDB. Batch incoming updates, append them with sequence numbers, and keep S3 checkpoints for the full file.</p>,
    tradeoff: <p>Another datastore on the hot path. Recovery now means checkpoint plus replay, which must be tested.</p>,
    realWorld: <p>Figma reported that 95% of edits are saved within 600 ms, with over 2.2 billion changes received daily.</p>,
    walkthrough: ['Clients send updates, up to about 30 per second.', 'The file’s process batches them into one journal entry.', 'The entry is written to DynamoDB with a sequence number.', 'Checkpoints to S3 still happen, folding in the journal.'],
    numbers: [{ label: 'Edits saved', value: '95% < 600 ms', note: 'Figma, 2022' }, { label: 'Changes per day', value: '2.2B+', note: 'Figma, 2022' }],
    components: [{ name: 'Journal', role: 'Durable, ordered log of recent changes since the last checkpoint.' }, { name: 'Checkpoints', role: 'Full snapshots in S3, replicated across regions.' }],
    alternatives: [{ option: 'Checkpoint more often', verdict: 'Rewriting whole files constantly is wasteful.' }, { option: 'Keep the file in a database row', verdict: 'Large documents and constant updates fit poorly.' }],
    breaksNext: <p>Some single tables have grown too large for any one database, even after partitioning.</p>,
    interview: { q: 'How do you cut data loss for an in-memory service?', a: <p>Snapshot plus a write-ahead log: small appends are fast, and recovery replays the log over the snapshot.</p> },
    sources: [S.journal],
  },
  {
    title: 'v10 · Horizontal sharding',
    era: 'Sep 2023 → 2024',
    scale: 'DB stack ≈ 100× since 2020',
    summary: 'Shard the biggest tables by user, file, or org, behind a proxy that routes each query.',
    added: ['proxy'],
    nodes: [FN.editor, FN.peer, FN.api, FN.mp, FN.journal, FN.s3, FN.proxy, fAs(FN.pg, 'Sharded Postgres', 'colos by shard key')],
    edges: [fe('editor', 'mp'), fe('mp', 'peer'), fe('mp', 's3', { async: true }), fe('mp', 'journal'), fe('editor', 'api'), fe('api', 'proxy'), fe('proxy', 'pg')],
    flows: [{ name: 'Query', path: ['editor', 'api', 'proxy', 'pg'], steps: ['User opens a file', 'API sends SQL to DBProxy', 'DBProxy routes it to the shard for that file, or scatters and gathers'] }],
    problem: <p>A few tables will outgrow the largest machine. But rewriting the app for sharding would take years.</p>,
    decision: <p>Build horizontal sharding on existing RDS Postgres. Group related tables into <strong>colos</strong> sharing a shard key (UserID, FileID, or OrgID). Route every query through <strong>DBProxy</strong>.</p>,
    tradeoff: <p>Cross-shard queries become scatter-gather, and joins only work within a colo. A custom query engine is a big thing to own.</p>,
    realWorld: <p>Figma sharded its first table in September 2023, about nine months after starting. It separated logical sharding (via Postgres views) from physical sharding so each could change independently.</p>,
    walkthrough: ['Choose a shard key per group of related tables.', 'Expose logical shards to the app through views.', 'Map logical shards onto physical databases.', 'DBProxy routes each query, or scatters and gathers when it must.'],
    numbers: [{ label: 'Growth since 2020', value: '≈ 100×', note: 'Figma, 2024' }, { label: 'First sharded table', value: 'Sep 2023' }, { label: 'Failover', value: '≈ 10 s partial', note: 'on primaries' }],
    components: [{ name: 'DBProxy', role: 'Parses SQL, routes by shard key, sheds load, and runs scatter-gather.' }, { name: 'Colos', role: 'Tables sharing a key keep joins and transactions within one shard.' }],
    alternatives: [{ option: 'Move to a distributed SQL database', verdict: 'Considered; staying on known RDS Postgres cut risk.' }, { option: 'Vitess', verdict: 'Built for MySQL, not their Postgres stack.' }],
    breaksNext: <p>LiveGraph now has to follow data across many shards and keep up with far more traffic.</p>,
    interview: { q: 'How do you shard without rewriting the application?', a: <p>Put a proxy between app and database that understands the shard key, and change shard layout underneath without changing queries.</p> },
    sources: [S.sharding],
  },
  {
    title: 'v11 · LiveGraph at 100×',
    era: 'May 2024',
    scale: 'sessions 3× since 2021',
    summary: 'Split LiveGraph into an edge, a query cache, and invalidators that follow each database shard.',
    added: ['lgcache'],
    nodes: [FN.editor, FN.api, FN.mp, FN.proxy, fAs(FN.pg, 'Sharded Postgres', 'WAL per shard'), fAs(FN.lg, 'LiveGraph edge', 'expands views'), FN.lgcache],
    edges: [fe('editor', 'mp'), fe('editor', 'api'), fe('api', 'proxy'), fe('proxy', 'pg'), fe('editor', 'lg'), fe('lg', 'lgcache'), fe('pg', 'lgcache', { async: true, label: 'invalidate' })],
    flows: [
      { name: 'Subscribe', path: ['editor', 'lg', 'lgcache'], steps: ['Browser subscribes to a view', 'The edge splits it into queries and reads them from the cache'] },
      { name: 'Invalidate', path: ['pg', 'lgcache', 'lg', 'editor'], steps: ['An invalidator tails one shard’s replication stream', 'The cache evicts affected queries and the edge re-fetches', 'Clients get the fresh result'] },
    ],
    problem: <p>Client sessions tripled since 2021 and view requests grew 5× in a year. The original LiveGraph can’t follow data spread across many shards.</p>,
    decision: <p>Three services: an <strong>edge</strong> that expands views into queries, a <strong>cache</strong> sharded by query hash, and <strong>invalidators</strong> sharded like the databases.</p>,
    tradeoff: <p>Invalidation means re-querying instead of patching results in place: more reads, but far simpler logic, since most results never change.</p>,
    realWorld: <p>Figma’s May 2024 post describes the move from mutation-based to invalidation-based caching, because most query results never change after first load.</p>,
    walkthrough: ['Edge receives a view request and expands it.', 'Queries are read through the cache.', 'Invalidators tail each shard’s WAL and evict affected entries.', 'Edge re-fetches evicted queries and pushes updates.'],
    numbers: [{ label: 'Client sessions', value: '3× since 2021', note: 'Figma, 2024' }, { label: 'View requests', value: '5× in a year', note: 'Figma, 2024' }],
    components: [{ name: 'Edge', role: 'Client-facing; turns views into cacheable queries.' }, { name: 'Cache', role: 'Read-through, sharded by query hash, unaware of DB topology.' }, { name: 'Invalidator', role: 'One per shard stream; emits evictions on writes.' }],
    alternatives: [{ option: 'Keep mutation-based updates', verdict: 'Complex to get right across many shards.' }, { option: 'Poll every shard', verdict: 'Doesn’t scale with sessions.' }],
    breaksNext: <p>Every new surface, from whiteboards to developer handoff, adds more live, sharded data to serve.</p>,
    interview: { q: 'Invalidate or update cached query results?', a: <p>Invalidate when most results rarely change: simpler, and the extra reads are affordable.</p> },
    sources: [S.liveGraph100x],
  },
]
