import type { EpisodeStage } from '../../components/ui'
import { F_CORE_EDGES, FN, fAs, fe } from './episode-figma-stage-nodes'
import { FIGMA_SRC as S } from './episode-figma-sources'

// Stages 1–6: the editor, multiplayer, and plugins. Numbers are from the cited sources unless marked "estimate".
export const FIGMA_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'v0 · A browser inside a browser',
    era: '2012–2015',
    scale: 'invite-only preview',
    summary: 'Write the editor in C++, compile it for the browser, and draw everything with WebGL.',
    nodes: [FN.editor, fAs(FN.api, 'Web servers', 'accounts · files')],
    edges: [fe('editor', 'api')],
    flows: [{ name: 'Open', path: ['editor', 'api'], steps: ['Browser loads the editor and fetches the file'] }],
    problem: <p>Professional design tools were desktop apps. Browsers of the time were too slow and inconsistent at drawing complex vector graphics at 60 frames per second.</p>,
    decision: <p>Write the editor in <strong>C++</strong>, compile it to JavaScript (asm.js) with Emscripten, and render with a custom <strong>WebGL</strong> engine instead of the DOM, SVG, or Canvas 2D.</p>,
    tradeoff: <p>You rebuild what browsers give for free: text layout, hit testing, masking. It is a huge engineering bet for a startup.</p>,
    realWorld: <p>Co-founder Evan Wallace wrote in December 2015 that the team had “basically ended up building a browser inside a browser”. The invite-only preview opened that same month.</p>,
    walkthrough: ['Browser downloads the compiled editor.', 'The editor loads the document into its own memory.', 'A GPU renderer draws the canvas in tiles with WebGL.', 'Edits change the in-memory document and redraw.'],
    numbers: [{ label: 'Preview opened', value: 'Dec 2015', note: 'Wikipedia' }, { label: 'Target frame rate', value: '60 fps' }],
    components: [{ name: 'C++ core', role: 'Predictable performance, 32-bit floats, and no garbage-collection pauses.' }, { name: 'WebGL renderer', role: 'Masking, blurs, and blend modes that browser APIs couldn’t do consistently.' }],
    alternatives: [{ option: 'DOM / SVG rendering', verdict: 'Too slow and inconsistent across browsers for large files.' }, { option: 'Desktop app', verdict: 'Loses instant sharing and collaboration through a link.' }],
    breaksNext: <p>A design tool in the browser invites a new feature: several people in the same file at once.</p>,
    interview: { q: 'When is it worth bypassing the platform’s UI stack?', a: <p>When the platform can’t meet the core requirement, here 60 fps vector rendering, and the gap is the product’s edge.</p> },
    sources: [S.webTool, S.wiki],
  },
  {
    title: 'v1 · Multiplayer from launch',
    era: '2015–2016',
    scale: 'public launch Sep 2016',
    summary: 'Every open file gets its own server process that all collaborators connect to.',
    added: ['mp', 'peer', 's3'],
    nodes: [FN.editor, FN.peer, FN.api, fAs(FN.mp, 'Multiplayer', 'TypeScript · per file'), FN.s3],
    edges: [fe('editor', 'mp'), fe('mp', 'peer'), fe('mp', 's3', { async: true }), fe('editor', 'api')],
    flows: [
      { name: 'Edit', path: ['editor', 'mp', 'peer'], steps: ['Editor sends a change over a WebSocket', 'The file’s process relays it to every collaborator'] },
      { name: 'Save', path: ['mp', 's3'], steps: ['The process periodically writes a checkpoint of the whole file'] },
    ],
    problem: <p>Designers pass files back and forth and lose track of versions. The browser makes live co-editing possible, but someone must decide the true state of the file.</p>,
    decision: <p>Run <strong>one server process per open file</strong>. All clients of that file connect to it over WebSockets. It holds the document in memory and saves checkpoints.</p>,
    tradeoff: <p>A single process per file is simple but single-threaded. One slow operation stalls everyone in that file.</p>,
    realWorld: <p>Figma launched publicly in September 2016. Its 2018 Rust post says the multiplayer server was originally written in TypeScript. Its 2022 post says checkpoints went to S3 every 30–60 seconds.</p>,
    walkthrough: ['User opens a file; the browser connects to that file’s process.', 'The process loads the latest checkpoint into memory.', 'Edits stream in; the process applies and broadcasts them.', 'Every 30–60 seconds it writes a checkpoint to S3.'],
    numbers: [{ label: 'Checkpoint interval', value: '30–60 s', note: 'Figma, 2022' }, { label: 'Processes per file', value: '1' }],
    components: [{ name: 'Per-file process', role: 'A single authority orders every change to one document.' }, { name: 'S3 checkpoints', role: 'The durable copy of the file, written periodically.' }],
    alternatives: [{ option: 'Peer-to-peer syncing', verdict: 'No authority to resolve conflicts or enforce permissions.' }, { option: 'Save to a database on every edit', verdict: 'Far too many writes for continuous dragging.' }],
    breaksNext: <p>Two people will edit the same object at the same moment. The rules for that decide whether multiplayer feels solid or broken.</p>,
    interview: { q: 'Why one process per document?', a: <p>It gives a single ordering point per file with no cross-machine locking. The cost is hotspots on huge files and a failover story.</p> },
    sources: [S.wiki, S.rust, S.journal],
  },
  {
    title: 'v2 · Properties, not operations',
    era: 'Since launch; described 2019',
    scale: 'many cursors per file',
    summary: 'Resolve conflicts per property: the last value the server receives wins.',
    nodes: [FN.editor, FN.peer, FN.api, FN.mp, FN.s3],
    edges: [fe('editor', 'mp'), fe('mp', 'peer'), fe('mp', 's3', { async: true }), fe('editor', 'api')],
    flows: [{ name: 'Conflict', path: ['editor', 'mp', 'peer'], steps: ['Two clients change the same property; the server applies them in arrival order', 'Everyone converges on the last value received'] }],
    problem: <p>Text editors use complex transformation algorithms to merge edits. A design file is different: a tree of objects, each with properties like position, color, and name.</p>,
    decision: <p>Model the file as <code>Map&lt;ObjectID, Map&lt;Property, Value&gt;&gt;</code>. The server is the authority; <strong>last writer wins per property</strong>. Clients show their own edits instantly.</p>,
    tradeoff: <p>Two people typing in the same text box at once can overwrite each other. Figma accepts that for a far simpler, faster system.</p>,
    realWorld: <p>Figma’s 2019 post explains that the design is inspired by CRDTs but is not a true CRDT, because a central server removes much of the overhead.</p>,
    walkthrough: ['Client applies its edit locally and sends it.', 'While unacknowledged, the client ignores server updates to that property.', 'Server applies updates in arrival order and broadcasts them.', 'New objects get IDs that include the client’s ID, so no server round-trip is needed.'],
    numbers: [{ label: 'Conflict unit', value: 'one property' }, { label: 'Child order', value: 'fractional index', note: 'a number between 0 and 1' }],
    components: [{ name: 'Unacked-change guard', role: 'Stops the view flickering back to an older value.' }, { name: 'Fractional indexing', role: 'Insert between siblings without renumbering the others.' }],
    alternatives: [{ option: 'Operational transformation', verdict: 'Powerful but complex; unnecessary for property edits.' }, { option: 'Whole-object replace', verdict: 'Concurrent edits to different properties would erase each other.' }],
    breaksNext: <p>Large files take too long to load in the browser, and startup time hurts every session.</p>,
    interview: { q: 'Why is per-property LWW enough for a design tool?', a: <p>Concurrent edits usually touch different properties. When two touch the same one, “last wins” matches what users expect.</p> },
    sources: [S.multiplayer],
  },
  {
    title: 'v3 · WebAssembly',
    era: 'Jun 2017',
    scale: 'files of every size',
    summary: 'Ship the C++ editor as WebAssembly so the browser loads it much faster.',
    added: ['editor'],
    nodes: [fAs(FN.editor, 'Browser editor', 'C++ → WebAssembly'), FN.peer, FN.api, FN.mp, FN.s3],
    edges: [fe('editor', 'mp'), fe('mp', 'peer'), fe('mp', 's3', { async: true }), fe('editor', 'api')],
    flows: [{ name: 'Open', path: ['editor', 'mp'], steps: ['The browser compiles a compact WebAssembly binary, then connects to the file'] }],
    problem: <p>Large asm.js bundles take a long time to download and parse before the editor can even start.</p>,
    decision: <p>Compile the same C++ code to <strong>WebAssembly</strong>, a compact binary format browsers parse far faster.</p>,
    tradeoff: <p>At the time only some browsers supported it by default, so a fallback path had to stay in place.</p>,
    realWorld: <p>Figma reported in June 2017 that load time improved by more than 3× after switching, regardless of document size.</p>,
    walkthrough: ['Browser downloads the .wasm binary.', 'It compiles the binary to machine code quickly.', 'The editor starts and loads the file.'],
    numbers: [{ label: 'Load time', value: '> 3× faster', note: 'Figma, 2017' }, { label: 'Parsing vs asm.js', value: '≈ 20× faster', note: 'Figma, 2017' }],
    components: [{ name: 'WebAssembly build', role: 'Same C++ source, smaller and faster-to-parse output.' }],
    alternatives: [{ option: 'Rewrite in JavaScript', verdict: 'Throws away a tuned C++ engine and adds GC pauses.' }],
    breaksNext: <p>The multiplayer server now lags on big files, because one slow operation blocks everyone in them.</p>,
    interview: { q: 'How would you speed up an app’s cold start?', a: <p>Measure download, parse, and init separately. Here parse time dominated, so a faster-to-parse format paid off.</p> },
    sources: [S.wasm],
  },
  {
    title: 'v4 · Rust inside multiplayer',
    era: 'May 2018',
    scale: 'large, busy files',
    summary: 'Move the heavy document work into a Rust process per file; keep networking in Node.js.',
    nodes: [FN.editor, FN.peer, FN.api, fAs(FN.mp, 'Multiplayer', 'Node.js + Rust per file'), FN.s3],
    edges: [fe('editor', 'mp'), fe('mp', 'peer'), fe('mp', 's3', { async: true }), fe('editor', 'api')],
    flows: [{ name: 'Edit', path: ['editor', 'mp', 'peer'], steps: ['Node.js receives the change and passes it to the file’s Rust process', 'Rust applies it and the update goes out to collaborators'] }],
    problem: <p>The TypeScript server had unpredictable latency spikes. Being single-threaded, one slow operation locked the whole worker.</p>,
    decision: <p>Keep networking in Node.js, but move document work into a <strong>separate Rust child process per document</strong>, talking over stdin/stdout.</p>,
    tradeoff: <p>Two languages and a process boundary to maintain. Figma rewrote only the hot parts rather than the whole server.</p>,
    realWorld: <p>Figma’s May 2018 post reports serialization over 10× faster, plus large drops in peak CPU and memory.</p>,
    walkthrough: ['Node.js holds the WebSocket connections.', 'Each document gets its own Rust child process.', 'Messages cross the boundary over stdin/stdout.', 'Documents now run in parallel instead of blocking one worker.'],
    numbers: [{ label: 'Serialization', value: '> 10× faster', note: 'Figma, 2018' }, { label: 'Rust processes', value: '1 per document' }],
    components: [{ name: 'Rust document process', role: 'No garbage-collection pauses and low memory overhead.' }, { name: 'Node.js front', role: 'Existing networking code kept as is.' }],
    alternatives: [{ option: 'Full rewrite in Rust', verdict: 'More risk; the hot path was a small part.' }, { option: 'More Node.js workers', verdict: 'Doesn’t fix one slow file blocking its own worker.' }],
    breaksNext: <p>Users want to extend Figma with plugins, which means running untrusted code next to their documents.</p>,
    interview: { q: 'How do you fix tail latency in a single-threaded server?', a: <p>Isolate slow work so it can’t block others, for example a process per document, and move the hot path to a runtime without GC pauses.</p> },
    sources: [S.rust],
  },
  {
    title: 'v5 · A sandbox for plugins',
    era: 'Aug 2019',
    scale: 'third-party code in every file',
    summary: 'Run plugin logic in an isolated realm on the main thread, and plugin UI in a sandboxed iframe.',
    added: ['plugin'],
    nodes: [FN.editor, FN.plugin, FN.api, FN.mp, FN.s3],
    edges: [...F_CORE_EDGES.filter((e) => e.to !== 'peer' && e.to !== 'pg'), fe('editor', 'plugin')],
    flows: [{ name: 'Run plugin', path: ['plugin', 'editor', 'mp'], steps: ['Plugin calls the document API synchronously from its sandbox', 'Resulting edits flow to the multiplayer server like any other edit'] }],
    problem: <p>Plugins need fast, synchronous access to the document. But they are untrusted code that must not read cookies or call arbitrary APIs.</p>,
    decision: <p>Split each plugin in two: logic in a <strong>Realms-based sandbox</strong> on the main thread, UI in a <strong>null-origin iframe</strong>. They talk by message passing.</p>,
    tradeoff: <p>The security boundary is custom code that must be audited carefully. Figma kept it small, about 500 lines.</p>,
    realWorld: <p>Figma’s 2019 post: an iframe-only design needed 14 seconds just to serialize one large file, and a JavaScript interpreter compiled to WebAssembly was secure but slow.</p>,
    walkthrough: ['User runs a plugin.', 'Its logic starts in an isolated realm with no browser globals.', 'It reads and edits the document through a whitelisted API.', 'Its UI runs in a sandboxed iframe and messages the logic.'],
    numbers: [{ label: 'iframe-only serialize', value: '14 s', note: 'one large file, Figma 2019' }, { label: 'Security layer', value: '≈ 500 lines', note: 'Figma, 2019' }],
    components: [{ name: 'Realm sandbox', role: 'Hides browser globals while allowing synchronous document calls.' }, { name: 'Null-origin iframe', role: 'Gives UI code browser APIs without access to Figma’s origin.' }],
    alternatives: [{ option: 'iframe only', verdict: 'Every call becomes async and large documents must be copied.' }, { option: 'JS interpreter in WebAssembly', verdict: 'Strong isolation, but too slow.' }],
    breaksNext: <p>Growth is now straining the one Postgres database behind files, teams, and permissions.</p>,
    interview: { q: 'How would you run untrusted code in a web app?', a: <p>Choose the isolation boundary by required latency and API surface, keep the boundary tiny, and audit it once.</p> },
    sources: [S.plugins],
  },
]
