import type { EpisodeStage } from '../../components/ui'
import { S } from './episode-youtube-sources'
import { N, as, e } from './episode-youtube-stage-nodes'

const conv = as(N.encode, 'Converter', 'to a web format')
const shards = as(N.mysql, 'MySQL shards', 'split by user')

export const YOUTUBE_EARLY: EpisodeStage[] = [
  {
    title: 'One small web app',
    era: '2005',
    summary: 'A Python web app, a MySQL database, and a few servers that store and send video files.',
    scale: 'Founded February 2005',
    nodes: [N.client, N.creators, N.web, N.mysql, N.video, conv],
    edges: [e('client', 'web'), e('creators', 'web'), e('web', 'mysql'), e('web', 'encode'), e('encode', 'video'), e('client', 'video')],
    flows: [
      { name: 'Upload', path: ['creators', 'web', 'encode', 'video'], steps: ['A creator uploads a file', 'The app hands it to a converter', 'The converted file is stored on a video server'] },
      { name: 'Watch', path: ['client', 'web', 'mysql'], steps: ['A viewer opens a watch page', 'The app reads title, tags, and comments from MySQL'] },
    ],
    problem: <p>Anyone should be able to upload a clip and share a link that plays in a browser. There is no budget and almost no team.</p>,
    decision: <p>Keep it boring: Python for fast development, MySQL for metadata, and plain servers holding the video files. Convert every upload into one format browsers can play.</p>,
    tradeoff: <p>One kind of server does very different jobs. Pages are small and dynamic; videos are huge and static. They will soon fight for the same machines.</p>,
    realWorld: <p>YouTube was founded in February 2005. Early talks describe a stack of Python, Apache, Linux, and MySQL.</p>,
    walkthrough: [
      'A creator uploads a video through the web app.',
      'A converter re-encodes it into a single web-playable format.',
      'The file lands on a video server; the metadata row lands in MySQL.',
      'Viewers load the page from the app and the video from the video server.',
    ],
    numbers: [
      { label: 'Founded', value: 'Feb 2005' },
      { label: 'Language for the app', value: 'Python', note: 'chosen for development speed' },
    ],
    components: [
      { name: 'Web app (Python + Apache)', role: 'Pages, accounts, uploads, and search.' },
      { name: 'MySQL', role: 'Video metadata, users, comments.' },
      { name: 'Video servers', role: 'Store and send the converted files.' },
    ],
    alternatives: [
      { option: 'Rent a video host', verdict: 'Too expensive and too slow for a site whose whole product is video.' },
      { option: 'Keep every upload in its original format', verdict: 'Browsers could not play most formats; one target format made playback reliable.' },
    ],
    breaksNext: <p>Video traffic grows far faster than page traffic, and the web servers choke on large file transfers.</p>,
    interview: { q: 'What would you build first for a video-sharing MVP?', a: <p>Upload, one transcode target, metadata store, and a watch page. Separate the byte-serving path early, because it will grow 1000× faster than the API.</p> },
    sources: [S.acquisition, S.cordes],
  },
  {
    title: 'Split video from pages',
    era: '2005–2006',
    summary: 'Pages stay on Apache; video moves to lighttpd servers, and the most popular videos go to a CDN.',
    scale: '30M → 100M pages/day in ~4 months (2006)',
    added: ['cdn'],
    nodes: [N.client, N.creators, as(N.web, 'Web app', 'Apache for pages'), N.mysql, as(N.video, 'Video servers', 'lighttpd, in colos'), conv, N.cdn],
    edges: [e('client', 'web'), e('creators', 'web'), e('web', 'mysql'), e('web', 'encode'), e('encode', 'video'), e('client', 'video'), e('client', 'cdn')],
    flows: [
      { name: 'Popular video', path: ['client', 'cdn'], steps: ['A hit video streams from the nearest CDN edge'] },
      { name: 'Long-tail video', path: ['client', 'video'], steps: ['A rarely watched video streams from YouTube’s own servers'] },
    ],
    problem: <p>Traffic more than triples in a few months. Apache is fine for pages but poor at pushing large files to many viewers at once.</p>,
    decision: <p>Use different servers for different jobs. Apache serves pages. Lighttpd, an event-driven web server, serves video. Push the most popular videos to a CDN and keep the long tail on YouTube’s own machines.</p>,
    tradeoff: <p>Two delivery paths to run and monitor. Deciding which videos go where needs popularity data.</p>,
    realWorld: <p>Talks from 2007 describe popular content on a CDN and less popular videos (1–20 views a day) on YouTube servers in colocation sites. A 2012 talk recalls an in-house CDN built from lighttpd in two weeks.</p>,
    walkthrough: [
      'The watch page comes from Apache and the Python app.',
      'The player URL points to the CDN for hits, or to YouTube’s lighttpd servers for everything else.',
      'Lighttpd streams the file without tying up a process per viewer.',
    ],
    numbers: [
      { label: 'Page views, summer 2006', value: '30M → 100M / day', note: 'in about 4 months' },
      { label: '“Long tail” served in-house', value: '1–20 views / day' },
      { label: 'In-house CDN, first day', value: '60 Gbit/s', note: 'built in two weeks' },
    ],
    components: [
      { name: 'Lighttpd video servers', role: 'Event-driven server for large, static files.' },
      { name: 'Commercial CDN', role: 'Caches the hottest videos close to viewers.' },
    ],
    alternatives: [
      { option: 'Everything on a CDN', verdict: 'Costly for millions of videos watched a few times a day; caches miss on the long tail anyway.' },
      { option: 'More Apache servers', verdict: 'Throws hardware at a design problem; process-per-connection is the bottleneck.' },
    ],
    breaksNext: <p>Each watch page also shows dozens of tiny thumbnail images, and those are harder to serve than the videos.</p>,
    interview: { q: 'Why serve popular and long-tail videos differently?', a: <p>Hits have high cache hit rates, so a CDN is cheap per view. The long tail misses every cache, so it is cheaper to serve from your own storage near the origin.</p> },
    sources: [S.cordes, S.hsArch, S.hs7years],
  },
  {
    title: 'Read replicas, then lag',
    era: '2006',
    summary: 'MySQL gets read replicas to absorb traffic, and stale reads start to appear.',
    scale: '100M+ video views / day',
    added: ['replicas'],
    nodes: [N.client, N.creators, N.web, as(N.mysql, 'MySQL primary', 'all writes'), N.replicas, as(N.video, 'Video servers', 'lighttpd'), N.cdn],
    edges: [e('client', 'web'), e('creators', 'web'), e('web', 'mysql'), e('web', 'replicas'), e('mysql', 'replicas', { label: 'replication', async: true }), e('client', 'video'), e('client', 'cdn')],
    flows: [
      { name: 'Read', path: ['client', 'web', 'replicas'], steps: ['A viewer loads a page', 'The app reads metadata from a replica'] },
      { name: 'Write', path: ['creators', 'web', 'mysql', 'replicas'], steps: ['A creator edits a title', 'The write goes to the primary', 'Replicas copy it a little later'] },
    ],
    problem: <p>One MySQL server cannot handle all the reads. Most traffic is people watching, not people writing.</p>,
    decision: <p>Send writes to one primary and spread reads across several <strong>replicas</strong>. Add replicas as read traffic grows.</p>,
    tradeoff: <p>Replication is asynchronous. Under load, replicas fall behind, so a creator can edit a title and not see the change.</p>,
    realWorld: <p>Google agreed to buy YouTube in October 2006 for $1.65B in stock. YouTube was serving over 100 million views and 65,000 new uploads a day.</p>,
    walkthrough: [
      'All inserts and updates go to the primary.',
      'Replicas replay the primary’s log asynchronously.',
      'Page reads go to any replica.',
      'When the primary is busy, the log backs up and replicas serve old data.',
    ],
    numbers: [
      { label: 'Daily video views (Oct 2006)', value: '100M+' },
      { label: 'Daily uploads (Oct 2006)', value: '65,000' },
      { label: 'Acquisition price', value: '$1.65B', note: 'in stock' },
    ],
    components: [{ name: 'Read replicas', role: 'Copies of the primary that serve reads.' }],
    alternatives: [
      { option: 'A bigger database server', verdict: 'Buys months, not years, and remains a single point of failure.' },
      { option: 'Cache every page', verdict: 'Helps reads, but writes still funnel through one primary.' },
    ],
    breaksNext: <p>Write traffic keeps growing, and one primary can only take so many writes.</p>,
    interview: { q: 'A user edits a title and refreshes, but sees the old one. Why, and what do you do?', a: <p>Replica lag. Route that user’s reads to the primary for a short window after they write (read-your-writes), or read from a replica known to be caught up.</p> },
    sources: [S.acquisition, S.hsArch, S.vitessHistory],
  },
  {
    title: 'The thumbnail problem',
    era: '2006–2008',
    summary: 'Millions of tiny images overwhelm file systems, so thumbnails move to Google’s BigTable.',
    scale: 'Up to 60 thumbnails per page',
    added: ['thumbs'],
    nodes: [N.client, N.web, N.mysql, N.replicas, as(N.thumbs, 'Thumbnails', 'Google BigTable'), as(N.video, 'Video servers', 'lighttpd'), N.cdn],
    edges: [e('client', 'web'), e('web', 'mysql'), e('web', 'replicas'), e('mysql', 'replicas', { async: true }), e('client', 'thumbs'), e('client', 'video'), e('client', 'cdn')],
    flows: [{ name: 'Load page', path: ['client', 'web', 'replicas'], steps: ['The browser requests the page', 'The app reads the list of videos to show'] }, { name: 'Thumbnails', path: ['client', 'thumbs'], steps: ['The browser fetches dozens of small images, now served from BigTable'] }],
    problem: <p>A single page can show dozens of thumbnails. Serving millions of tiny files from disk causes endless seeks, directory limits, and cache thrashing.</p>,
    decision: <p>Stop storing each thumbnail as a separate file. Put them in <strong>BigTable</strong>, Google’s distributed store, which packs small objects together and caches them at several levels.</p>,
    tradeoff: <p>A dependency on Google infrastructure, and a migration of every existing thumbnail.</p>,
    realWorld: <p>Reported fixes along the way: a hierarchical directory layout, a Squid proxy (which slowed from 300 to 20 requests per second under load), and finally BigTable.</p>,
    walkthrough: [
      'The browser loads the page, then requests each thumbnail.',
      'Each thumbnail used to be a separate file, meaning a disk seek and an inode lookup.',
      'BigTable groups many small objects and serves them from memory caches.',
    ],
    numbers: [
      { label: 'Thumbnails on one page', value: 'up to 60' },
      { label: 'Squid proxy under load', value: '300 → 20 req/s' },
      { label: 'Setting up a new image server', value: '> 24 hours' },
    ],
    components: [{ name: 'BigTable for thumbnails', role: 'Packs small objects to avoid per-file disk overhead.' }],
    alternatives: [
      { option: 'Reverse proxy cache in front', verdict: 'Tried: throughput collapsed as the working set grew.' },
      { option: 'Tune the file system', verdict: 'Tried: helped, but copying millions of files to new machines took more than a day.' },
    ],
    breaksNext: <p>Replicas help reads, but the primary still takes every write for every user.</p>,
    interview: { q: 'Why are millions of small files hard to serve?', a: <p>Per-file overhead dominates: a metadata lookup and a disk seek for a few kilobytes. Pack small objects into larger blocks (like Haystack or BigTable) and cache the hot set.</p> },
    sources: [S.hsArch],
  },
  {
    title: 'Shard MySQL by user',
    era: '2006–2008',
    summary: 'Users are split across many MySQL databases, each with its own replicas.',
    scale: 'Writes outgrow one primary',
    nodes: [N.client, N.creators, as(N.web, 'Web app', 'picks the shard'), shards, as(N.replicas, 'Shard replicas'), as(N.video, 'Video servers', 'lighttpd'), N.cdn],
    edges: [e('client', 'web'), e('creators', 'web'), e('web', 'mysql'), e('web', 'replicas'), e('mysql', 'replicas', { async: true }), e('client', 'video'), e('client', 'cdn')],
    flows: [{ name: 'Write', path: ['creators', 'web', 'mysql'], steps: ['A creator updates their channel', 'The app maps the user to a shard and writes there'] }],
    problem: <p>A single primary cannot take every write, and replicas copying the full dataset lag behind.</p>,
    decision: <p><strong>Shard</strong> by user: each user’s data lives on one of many MySQL databases. The application code decides which shard to query.</p>,
    tradeoff: <p>Queries across users need to touch many shards. Every part of the code must know about shard routing.</p>,
    realWorld: <p>A 2008 summary reports that sharding cut hardware by about 30% and brought replica lag to zero.</p>,
    walkthrough: [
      'The app computes which shard owns this user.',
      'It opens a connection to that shard’s primary for writes.',
      'Reads go to that shard’s replicas.',
      'Each shard is small, so replication keeps up.',
    ],
    numbers: [
      { label: 'Hardware after sharding', value: '≈ −30%' },
      { label: 'Replica lag after sharding', value: '≈ 0' },
    ],
    components: [{ name: 'Shard routing in app code', role: 'Maps a user to the database that stores them.' }],
    alternatives: [
      { option: 'Shard by video', verdict: 'Pages that list a user’s uploads would touch every shard.' },
      { option: 'Keep scaling up one primary', verdict: 'The write ceiling does not move far enough.' },
    ],
    breaksNext: <p>Shard logic spread through the codebase becomes risky to change, and connection counts explode.</p>,
    interview: { q: 'How would you pick a shard key for YouTube metadata?', a: <p>By owner (user or channel): most writes and many reads are per-owner. Keep a separate index or cache for cross-owner lookups like “videos by tag”.</p> },
    sources: [S.hsArch, S.vitessHistory],
  },
  {
    title: 'Content ID',
    era: '2007',
    summary: 'Every upload is compared against fingerprints of copyrighted works before it goes live.',
    scale: 'Every upload is scanned',
    added: ['cid'],
    nodes: [N.client, N.creators, N.web, shards, N.cid, conv, as(N.video, 'Video servers', 'lighttpd'), N.cdn],
    edges: [e('client', 'web'), e('creators', 'web'), e('web', 'mysql'), e('web', 'encode'), e('encode', 'cid'), e('encode', 'video'), e('client', 'video'), e('client', 'cdn')],
    flows: [{ name: 'Upload check', path: ['creators', 'web', 'encode', 'cid'], steps: ['A creator uploads', 'The app queues processing', 'The processed video is fingerprinted and matched against reference files'] }],
    problem: <p>Rights holders need a way to find their music and video in millions of uploads. Manual review cannot keep up.</p>,
    decision: <p>Rights holders submit reference files. YouTube fingerprints them and compares every upload against those fingerprints. On a match, the owner’s policy applies: monetize, track, or block.</p>,
    tradeoff: <p>Large compute on every upload, plus false matches and disputes that need a human process.</p>,
    realWorld: <p>Content ID launched in 2007. YouTube’s help pages describe reference files, fingerprints, and the monetize, track, or block policies.</p>,
    walkthrough: [
      'A rights holder uploads reference files with ownership metadata.',
      'YouTube builds fingerprints from the references.',
      'Each new upload is fingerprinted and compared.',
      'A match applies the owner’s policy before the video is published.',
    ],
    numbers: [
      { label: 'Launched', value: '2007' },
      { label: 'Policies on a match', value: '3', note: 'monetize, track, block' },
    ],
    components: [{ name: 'Content ID', role: 'Fingerprint index plus a matcher in the upload pipeline.' }],
    alternatives: [
      { option: 'Takedown requests only', verdict: 'Reactive and slow for rights holders; still offered as a web form.' },
      { option: 'Exact file hashes', verdict: 'Any re-encode or crop changes the hash; perceptual fingerprints survive them.' },
    ],
    breaksNext: <p>Application-level shard routing is now the hardest part of the database layer to operate.</p>,
    interview: { q: 'How would you detect re-uploads of a copyrighted clip?', a: <p>Perceptual fingerprints (robust to re-encoding) indexed for nearest-neighbor lookup, run asynchronously in the upload pipeline, with a policy engine and a dispute path.</p> },
    sources: [S.contentIdWiki, S.contentIdHelp],
  },
]
