import type { EpisodeStage } from '../../components/ui'
import { U, ue } from './episode-uber-stage-nodes'
import { UBER_SRC as S } from './episode-uber-sources'

// Stages 1–6: from one Python app to typed service contracts (roughly 2010s, first half).
export const UBER_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'v0 · One app, one database',
    era: 'Early days',
    scale: 'a few cities (estimate)',
    summary: 'One program and one database do everything, which is the right call while nobody knows if the idea works.',
    nodes: [U.rider, U.driver, U.mono, U.pg],
    edges: [ue('rider', 'mono'), ue('driver', 'mono', { label: 'position' }), ue('mono', 'pg')],
    flows: [
      { name: 'Request ride', path: ['rider', 'mono', 'pg'], steps: ['Rider taps “Request”', 'The monolith queries the database for the closest free driver'] },
      { name: 'Driver ping', path: ['driver', 'mono', 'pg'], steps: ['Driver app sends its position', 'Each ping becomes a database write'] },
    ],
    problem: <p>Prove that riders will tap a button and a car will come. The team is tiny and ships every week.</p>,
    decision: <p>One Python app and one PostgreSQL database hold riders, drivers, trips, and payments. Matching is a query for the closest free driver.</p>,
    tradeoff: <p>Simple and transactional. But every new city adds rows to scan, and every GPS ping is a write on the trip database.</p>,
    realWorld: <p>Uber has written that its early backend was a monolithic Python application using Postgres.</p>,
    walkthrough: [
      'The rider taps Request; the app calls the monolith.',
      'The monolith queries Postgres for available drivers and sorts them by distance.',
      'It writes a trip row and notifies the chosen driver.',
      'Meanwhile every driver app sends its position, and each one is an UPDATE.',
    ],
    numbers: [
      { label: 'Drivers online', value: '100s–1,000s', note: 'estimate' },
      { label: 'Ping interval', value: '~4–5 s', note: 'estimate, per driver' },
      { label: 'Ping writes at 2K drivers', value: '≈ 400–500/s', note: 'estimate' },
    ],
    components: [
      { name: 'Monolith', role: 'One deployable for every feature. Fast to change while the team is small.' },
      { name: 'PostgreSQL', role: 'Single source of truth, with transactions for trips and payments.' },
    ],
    alternatives: [
      { option: 'Microservices from day one', verdict: 'Too slow for a tiny team, and the right boundaries are unknown yet.' },
      { option: 'A NoSQL store', verdict: 'No need yet. Transactions keep trips and payments simple.' },
    ],
    breaksNext: <p>GPS pings grow with every driver and hammer the same database that stores trips.</p>,
    interview: {
      q: 'Your MVP is one app and one database. When is that the right call?',
      a: <p>When the product is unproven and the team is small. Say which limit you expect to hit first (here, ping writes) and how you would see it coming: database CPU, lock waits, p99 latency.</p>,
    },
    sources: [S.postgres],
  },
  {
    title: 'v1 · Dispatch splits from the API',
    era: 'Early growth',
    scale: 'dozens of cities (estimate)',
    summary: 'Fast-changing driver positions move into their own in-memory service, away from the business database.',
    added: ['api', 'dispatch', 'geo'],
    nodes: [U.rider, U.driver, U.api, U.dispatch, U.geo, U.pg],
    edges: [ue('rider', 'api'), ue('driver', 'dispatch', { label: 'position' }), ue('api', 'pg'), ue('api', 'dispatch'), ue('dispatch', 'geo')],
    flows: [
      { name: 'Driver ping', path: ['driver', 'dispatch', 'geo'], steps: ['Driver app sends its position to dispatch', 'Dispatch overwrites that driver’s last position in memory'] },
      { name: 'Request ride', path: ['rider', 'api', 'dispatch', 'geo'], steps: ['Rider requests a trip', 'The API records it and asks dispatch for a match', 'Dispatch reads nearby drivers from memory'] },
    ],
    problem: <p>Positions change every few seconds and matching needs them instantly. A CRUD app on a relational database is the wrong home for that loop.</p>,
    decision: <p>Split into two services. <strong>Dispatch</strong> keeps each driver’s latest position in memory and does matching. The <strong>API</strong> handles accounts, trips, and payments on Postgres.</p>,
    tradeoff: <p>Now there are two services and two languages. Dispatch memory is lost on restart, which is fine: drivers re-report within seconds.</p>,
    realWorld: <p>In a 2015 talk, Uber described dispatch running on Node.js, with Python used for many other services.</p>,
    walkthrough: [
      'A driver app sends its position to dispatch.',
      'Dispatch overwrites that driver’s last known position in memory. Nothing is written to disk.',
      'A rider requests a trip; the API records it in Postgres.',
      'The API asks dispatch for a match; dispatch scans nearby drivers in memory.',
    ],
    numbers: [
      { label: 'State per driver', value: '~100 bytes', note: 'estimate' },
      { label: 'State for 100K drivers', value: '≈ 10 MB', note: 'fits in RAM easily' },
    ],
    components: [
      { name: 'Dispatch service', role: 'Owns live positions and matching. Optimized for low latency, not durability.' },
      { name: 'API service', role: 'Owns durable business data: accounts, trips, payments.' },
    ],
    alternatives: [
      { option: 'Keep pings in Postgres', verdict: 'Write load and lock contention on the trip database.' },
      { option: 'Cache positions inside the API', verdict: 'Mixes a real-time loop into every CRUD deploy.' },
    ],
    breaksNext: <p>Dispatch is sharded by city and assumes one rider per car. That blocks pooled rides and hundreds of new cities.</p>,
    interview: {
      q: 'Why is driver location a different kind of data from a trip?',
      a: <p>Location is latest-value-wins and cheap to lose: the next ping replaces it. A trip is low-volume and must never be lost. Different durability needs deserve different stores.</p>,
    },
    sources: [S.ranney, S.hs],
  },
  {
    title: 'v2 · Rewrite dispatch around cells',
    era: '2014–2015',
    scale: '~1M location writes/s (2015 talk)',
    summary: 'Dispatch is rebuilt as supply, demand, and a matcher, with the map cut into small cells so load spreads evenly.',
    added: ['gw', 'demand', 'supply', 'eta'],
    nodes: [U.rider, U.driver, U.gw, U.demand, { ...U.dispatch, label: 'DISCO', sub: 'matcher · Ringpop' }, U.supply, { ...U.geo, sub: 'S2 cells' }, U.eta],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'demand'), ue('gw', 'supply'), ue('supply', 'geo'), ue('demand', 'dispatch'), ue('dispatch', 'geo'), ue('dispatch', 'eta')],
    flows: [
      { name: 'Match', path: ['rider', 'gw', 'demand', 'dispatch', 'geo'], steps: ['Rider requests a trip', 'The edge routes to the demand service', 'Demand hands the order to DISCO', 'DISCO gathers drivers in the rider’s cell and its neighbours'] },
      { name: 'Supply update', path: ['driver', 'gw', 'supply', 'geo'], steps: ['Driver pings', 'Routed to the supply service', 'Supply updates the vehicle’s state and cell'] },
    ],
    problem: <p>Old dispatch assumed one rider per vehicle and one shard per city. Both assumptions block pooled rides, delivery, and growth.</p>,
    decision: <p>Split dispatch into a <strong>supply</strong> service, a <strong>demand</strong> service, and a matcher called DISCO. Index positions by Google S2 cells and shard by cell ID. Spread state across processes with <strong>Ringpop</strong>, a hash ring with gossip.</p>,
    tradeoff: <p>Cell sharding removes the per-city limit but adds work at cell borders. A gossip ring needs careful handling when nodes join or leave.</p>,
    realWorld: <p>Uber’s 2015 QCon talk describes this rewrite: about a million location writes per second, level-12 S2 cells, and Ringpop, which Uber open-sourced.</p>,
    walkthrough: [
      'A driver pings; the supply service updates that vehicle’s state and cell.',
      'A rider requests; the demand service records the order.',
      'DISCO collects supply from the rider’s cell and the cells around it.',
      'It ranks candidates by estimated time of arrival (ETA) on real roads, not straight-line distance.',
      'Ringpop forwards each request to whichever process owns that cell.',
    ],
    numbers: [
      { label: 'Location writes', value: '~1M/s', note: '2015 talk' },
      { label: 'S2 level-12 cell', value: '≈ 3–6 km²', note: 'varies by latitude' },
      { label: 'Matching goals', value: 'less waiting', note: 'and less extra driving' },
    ],
    components: [
      { name: 'Supply / demand services', role: 'Model vehicles and orders generally, so pooled rides and delivery fit.' },
      { name: 'DISCO', role: 'The matcher. It can plan ahead, for example with a driver who is about to finish a trip.' },
      { name: 'Ringpop', role: 'Consistent hashing plus SWIM-style gossip, so any node can route to the owner of a key.' },
    ],
    alternatives: [
      { option: 'Shard by city', verdict: 'Big cities become hotspots, and new products span cities.' },
      { option: 'Central database for positions', verdict: 'Cannot absorb a million writes per second cheaply.' },
    ],
    breaksNext: <p>Trips still live in one Postgres database, and it is running out of room.</p>,
    interview: {
      q: 'Why shard a geo index by cell instead of by city?',
      a: <p>Cells are small and uniform, so load spreads evenly and a busy city spans many shards. A query reads the rider’s cell plus its neighbours. City sharding turns every big city into a hotspot.</p>,
    },
    sources: [S.ranney, S.hs, S.ringpop],
  },
  {
    title: 'v3 · Trips move to Schemaless',
    era: '2014–2016',
    scale: 'trip growth outruns one database',
    summary: 'Trips get a custom, append-only datastore on many MySQL servers, because losing a trip is never acceptable.',
    added: ['trips', 'store'],
    nodes: [U.rider, U.driver, U.gw, U.demand, U.trips, U.dispatch, U.supply, U.geo, U.eta, U.store],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'demand'), ue('gw', 'supply'), ue('gw', 'trips'), ue('supply', 'geo'), ue('demand', 'dispatch'),
      ue('dispatch', 'geo'), ue('dispatch', 'eta'), ue('dispatch', 'trips'), ue('trips', 'store', { label: 'append' })],
    flows: [{ name: 'Accept trip', path: ['driver', 'gw', 'trips', 'store'], steps: ['Driver taps Accept', 'The edge routes to the trip service', 'The new trip state is appended as a new cell version'] }],
    problem: <p>In early 2014, Uber projected that its single Postgres instance would run out of space for trips by the end of the year.</p>,
    decision: <p>Build <strong>Schemaless</strong>: an append-only store of immutable JSON cells, sharded across MySQL. Writes never overwrite; each change is a new version. Triggers turn changes into events, for example to start billing.</p>,
    tradeoff: <p>Append-only data grows forever and needs archiving. The team now owns a custom datastore, including its tooling and on-call.</p>,
    realWorld: <p>Uber described Schemaless in 2016. It also explained moving many workloads from Postgres to MySQL, citing write amplification, replication, and upgrade pain.</p>,
    walkthrough: [
      'Dispatch assigns a driver, and the trip service records the new state.',
      'The write appends a new cell version. Nothing is overwritten.',
      'If a MySQL primary is down, the write is buffered elsewhere and retried.',
      'A trigger fires on the new cell, and downstream work such as billing starts.',
    ],
    numbers: [
      { label: 'Postgres runway (early 2014)', value: '< 1 year', note: 'as projected by Uber' },
      { label: 'Write model', value: 'append-only', note: 'immutable JSON cells' },
    ],
    components: [
      { name: 'Trip service', role: 'Owns the trip state machine: requested, accepted, arrived, on trip, completed.' },
      { name: 'Schemaless', role: 'Sharded MySQL with buffered writes and change triggers.' },
    ],
    alternatives: [
      { option: 'A bigger Postgres server', verdict: 'Buys months, not years, and stays one failure domain.' },
      { option: 'An unfamiliar NoSQL database', verdict: 'Uber weighed operational trust heavily and built on MySQL, which it knew well.' },
    ],
    breaksNext: <p>A whole datacenter can fail. Where does a trip in progress come back from?</p>,
    interview: {
      q: 'Why would you make trip storage append-only?',
      a: <p>Every state change is a new version, so history comes for free and concurrent writes never overwrite each other. It also gives you a change log for billing and analytics. The cost is growth and compaction.</p>,
    },
    sources: [S.schemaless1, S.schemaless2, S.postgres],
  },
  {
    title: 'v4 · Survive a datacenter loss',
    era: '2015 (as described)',
    scale: 'multiple datacenters',
    summary: 'Driver phones keep an encrypted copy of their trip, so a backup datacenter can rebuild trips after a failure.',
    added: ['dc2'],
    nodes: [U.rider, U.driver, U.gw, U.trips, U.dispatch, U.geo, U.eta, U.store, U.dc2],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'trips'), ue('gw', 'dispatch'), ue('dispatch', 'geo'), ue('dispatch', 'eta'), ue('trips', 'store'),
      ue('gw', 'dc2', { label: 'failover' }), ue('dc2', 'driver', { label: 'ask for digest' })],
    flows: [{ name: 'Failover', path: ['driver', 'gw', 'dc2', 'driver'], steps: ['The driver’s next ping reaches the edge', 'The primary is down, so the edge routes to the backup', 'The backup asks the phone for its state digest and rebuilds the trip'] }],
    problem: <p>A datacenter outage must not strand riders mid-trip or lose fares. Replicating every live trip across sites in real time is costly.</p>,
    decision: <p>Keep a backup datacenter ready, and use <strong>driver phones as a recovery store</strong>. The server sends each driver app an encrypted digest of its trip state. After failover, the backup collects digests and rebuilds trips.</p>,
    tradeoff: <p>Recovery depends on phones reconnecting, and a digest can be slightly stale. It only works if it is drilled regularly.</p>,
    realWorld: <p>Uber’s 2015 QCon talk described sending an encrypted “state digest” to driver phones and reading it back after a datacenter failover.</p>,
    walkthrough: [
      'During a trip, the server sends an encrypted state digest to the driver app.',
      'The primary datacenter fails.',
      'The edge shifts traffic to the backup datacenter.',
      'Driver pings arrive; the backup asks each phone for its digest.',
      'Trips resume from the digests, and the phones never knew the server changed.',
    ],
    numbers: [
      { label: 'State on each phone', value: '1 digest', note: 'current trip, encrypted' },
      { label: 'Recovery source', value: 'the fleet itself', note: 'no cross-site replication needed' },
    ],
    components: [
      { name: 'Backup datacenter', role: 'Takes traffic when the primary fails.' },
      { name: 'State digest', role: 'A small, encrypted snapshot the phone stores but cannot read or change.' },
    ],
    alternatives: [
      { option: 'Synchronous cross-site replication', verdict: 'Adds latency to every trip write.' },
      { option: 'Accept losing live trips', verdict: 'Unacceptable for money and rider safety.' },
    ],
    breaksNext: <p>Hundreds of services now call each other with ad-hoc JSON. Nobody knows what will break.</p>,
    interview: {
      q: 'How can clients help with disaster recovery?',
      a: <p>Treat the phone as a replica of its own session. Give it a small encrypted or signed digest and rebuild server state from phones after failover. Validate digests and reconcile conflicts deterministically.</p>,
    },
    sources: [S.ranney, S.hs],
  },
  {
    title: 'v5 · Typed contracts for 500+ services',
    era: '2015',
    scale: '500+ services',
    summary: 'Services agree on typed, code-generated interfaces, so one team’s change does not silently break another.',
    added: ['svcs'],
    nodes: [U.rider, U.driver, U.gw, U.trips, U.dispatch, U.geo, U.eta, U.store, U.svcs],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'trips'), ue('gw', 'dispatch'), ue('dispatch', 'geo'), ue('dispatch', 'eta'), ue('trips', 'store'),
      ue('trips', 'svcs', { label: 'Thrift' }), ue('dispatch', 'svcs')],
    flows: [{ name: 'Service call', path: ['rider', 'gw', 'trips', 'svcs'], steps: ['A rider action hits the edge', 'The edge calls the trip service', 'The trip service calls other services over typed contracts'] }],
    problem: <p>Splitting the monolith produced 500+ services with loose JSON contracts. Uber said it had turned a monolithic API into a <em>distributed</em> monolithic API.</p>,
    decision: <p>Define every interface in an interface definition language, <strong>Apache Thrift</strong>. Clients are generated for Python, Node.js, Go, and more. The stated goal was to retire the monolith’s repository.</p>,
    tradeoff: <p>Thrift tooling was young for Python and Node.js, so Uber had to build tools. Typed contracts also slow casual changes, which is partly the point.</p>,
    realWorld: <p>Uber’s 2015 post explains the move to a service-oriented architecture and the choice of Thrift.</p>,
    walkthrough: [
      'Each service publishes a Thrift file describing its methods and types.',
      'Client code is generated from it for every language.',
      'Calls are type-checked when code is built.',
      'Breaking changes show up in code review, not in production.',
    ],
    numbers: [
      { label: 'Services (2015)', value: '500+', note: 'Uber SOA post' },
      { label: 'Languages in use', value: 'Python, Node.js, Go, …' },
    ],
    components: [
      { name: 'Interface definitions', role: 'The contract between teams, reviewed like code.' },
      { name: 'Generated clients', role: 'Remove hand-written request code and its bugs.' },
    ],
    alternatives: [
      { option: 'Keep free-form JSON over HTTP', verdict: 'No shared types; breaks are found in production.' },
      { option: 'Build an in-house format', verdict: 'More control, but slower at that growth stage.' },
    ],
    breaksNext: <p>A single rider action now crosses dozens of services. When it is slow, nobody can tell where the time went.</p>,
    interview: {
      q: 'What is a “distributed monolith”, and how do you avoid it?',
      a: <p>Services that must deploy or fail together because their contracts are implicit. Avoid it with explicit, versioned interfaces, backward-compatible changes, and clear ownership.</p>,
    },
    sources: [S.soa],
  },
]
