import type { ArchEdge, ArchNode, EpisodeStage } from '../../components/ui'

// Stage graphs are cumulative: each stage re-lists the nodes it keeps so positions stay stable.
const N = {
  client: { id: 'client', label: 'Clients', sub: 'desktop · mobile · web', kind: 'client', x: 10, y: 50 },
  mono: { id: 'mono', label: 'Chat server', sub: 'API + sockets', kind: 'service', x: 45, y: 50 },
  mongo: { id: 'mongo', label: 'Document DB', sub: 'one replica set', kind: 'db', x: 80, y: 18 },
  api: { id: 'api', label: 'HTTP API', sub: 'writes + history', kind: 'service', x: 30, y: 18 },
  gw: { id: 'gw', label: 'Gateway', sub: 'WebSocket sessions', kind: 'lb', x: 30, y: 50 },
  guild: { id: 'guild', label: 'Guild processes', sub: 'one per server', kind: 'service', x: 55, y: 50 },
  presence: { id: 'presence', label: 'Presence', sub: 'who is online', kind: 'cache', x: 55, y: 82 },
  cass: { id: 'cass', label: 'Wide-column DB', sub: '(channel, bucket)', kind: 'db', x: 80, y: 18 },
  ds: { id: 'ds', label: 'Data services', sub: 'coalesce reads', kind: 'service', x: 55, y: 18 },
  scylla: { id: 'scylla', label: 'Messages store', sub: 'no JVM GC pauses', kind: 'db', x: 80, y: 18 },
  voice: { id: 'voice', label: 'Voice servers', sub: 'SFU, WebRTC', kind: 'external', x: 82, y: 82 },
  relay: { id: 'relay', label: 'Fan-out relays', sub: 'huge servers', kind: 'worker', x: 30, y: 82 },
} satisfies Record<string, ArchNode>

const e = (from: string, to: string, extra: Partial<ArchEdge> = {}): ArchEdge => ({ from, to, ...extra })

export const DISCORD_STAGES: EpisodeStage[] = [
  {
    title: 'v0 · One chat server',
    scale: 'a few thousand gamers',
    nodes: [N.client, N.mono, N.mongo],
    edges: [e('client', 'mono'), e('mono', 'mongo')],
    flows: [{ name: 'Send', path: ['client', 'mono', 'mongo'], steps: ['Client sends a message over its socket', 'The server stores it and pushes it to everyone else connected'] }],
    problem: <p>Ship a voice and text chat app for gaming groups fast. There is a tiny team and no idea which features will stick.</p>,
    decision: <p>One process holds every WebSocket, handles the API, and writes messages to a single document database. Everyone is in memory in one place.</p>,
    tradeoff: <p>Connections, state, and storage share one box. A deploy drops every socket, and a memory spike in one busy server hurts everyone.</p>,
  },
  {
    title: 'v1 · Gateway + guild processes',
    scale: '~1M concurrent connections',
    added: ['api', 'gw', 'guild'],
    nodes: [N.client, N.api, N.gw, N.guild, N.mongo],
    edges: [e('client', 'api'), e('client', 'gw'), e('api', 'mongo'), e('api', 'guild'), e('guild', 'gw')],
    flows: [
      { name: 'Send', path: ['client', 'api', 'mongo'], steps: ['Client POSTs the message over HTTP', 'API validates, assigns a time-sortable ID, and persists it'] },
      { name: 'Deliver', path: ['api', 'guild', 'gw', 'client'], steps: ['API hands the event to the owning guild process', 'Guild process fans out to member sessions', 'Gateways push it down each open socket'] },
    ],
    problem: <p>Holding sockets and running business logic in one process doesn’t scale. Every guild (community server) needs a single, consistent view of its members, channels, and permissions.</p>,
    decision: <p>Split into a <strong>gateway</strong> tier that only holds persistent connections and a <strong>guild process</strong> per server that owns that server’s state and fans events out. Writes go through a stateless HTTP API; the socket is mostly for receiving.</p>,
    tradeoff: <p>You now route every event to the right guild process across a cluster. A guild process is a single owner, which is simple and consistent, but it is also a potential hotspot.</p>,
    realWorld: <p>Discord has written about building its gateway and guild processes in <strong>Elixir</strong> on the Erlang VM, with one lightweight process per guild and per session. Its public API docs also describe the split: messages are sent via HTTP, and events arrive over the gateway WebSocket.</p>,
  },
  {
    title: 'v2 · Big servers, lazy fan-out',
    scale: 'guilds with 100K+ members',
    added: ['presence'],
    nodes: [N.client, N.api, N.gw, N.guild, N.presence, N.mongo],
    edges: [e('client', 'api'), e('client', 'gw'), e('api', 'mongo'), e('api', 'guild'), e('guild', 'gw'), e('guild', 'presence')],
    flows: [{ name: 'Deliver', path: ['api', 'guild', 'presence', 'guild', 'gw'], steps: ['A message arrives for a huge guild', 'Guild asks which members are online and actually viewing', 'Only those sessions are targeted', 'Gateways push to that much smaller set'] }],
    problem: <p>A message in a 100K-member server naively means 100K deliveries. Sending the full member list to every client that opens the server is even worse, and presence updates (online/offline) multiply everything.</p>,
    decision: <p>Only push to sessions that are <strong>online and looking</strong>. Send member lists lazily, a visible window at a time. Offline members fetch history on reconnect instead of receiving pushes.</p>,
    tradeoff: <p>Clients must handle partial state and fetch on demand. The server tracks subscriptions per session, which is more bookkeeping for far less bandwidth.</p>,
  },
  {
    title: 'v3 · Messages in a wide-column store',
    scale: 'billions of stored messages',
    added: ['cass'],
    nodes: [N.client, N.api, N.gw, N.guild, N.presence, N.cass],
    edges: [e('client', 'api'), e('client', 'gw'), e('api', 'cass'), e('api', 'guild'), e('guild', 'gw'), e('guild', 'presence')],
    flows: [{ name: 'History', path: ['client', 'api', 'cass'], steps: ['Client scrolls up in a channel', 'API reads one partition, (channel, time bucket), newest first'] }],
    problem: <p>The document database’s working set no longer fits in memory, and reads for old messages turn random and slow. The access pattern is simple: <em>latest messages in one channel</em>.</p>,
    decision: <p>Move messages to a <strong>wide-column</strong> store. Use partition key <code>(channel_id, time_bucket)</code> and clustering key <code>message_id</code> (time-sortable), so a channel’s recent history is one sequential read.</p>,
    tradeoff: <p>You give up ad-hoc queries and joins. Time buckets must be sized so busy channels don’t make giant partitions and quiet channels don’t need many empty reads.</p>,
    realWorld: <p>Discord’s 2017 post described exactly this: starting on MongoDB, then moving messages to <strong>Cassandra</strong> partitioned by channel and a static time bucket, keyed by Snowflake-style IDs.</p>,
  },
  {
    title: 'v4 · Hot partitions, new store',
    scale: 'trillions of messages',
    added: ['ds', 'scylla'],
    nodes: [N.client, N.api, N.gw, N.guild, N.presence, N.ds, N.scylla],
    edges: [e('client', 'api'), e('client', 'gw'), e('api', 'ds'), e('ds', 'scylla'), e('api', 'guild'), e('guild', 'gw'), e('guild', 'presence')],
    flows: [{ name: 'History', path: ['client', 'api', 'ds', 'scylla'], steps: ['Thousands of clients open the same busy channel', 'API routes by channel to the owning data service', 'One coalesced query hits the store; the result fans back out'] }],
    problem: <p>A few enormous servers produce <strong>hot partitions</strong>. When a big announcement drops, everyone reads the same channel at once. Tail latency spikes, compaction falls behind, and JVM garbage-collection pauses make it worse.</p>,
    decision: <p>Put a <strong>data-services</strong> layer in front of the database that routes by channel and <strong>coalesces</strong> identical in-flight reads into one query. Migrate to a store with lower, steadier tail latency.</p>,
    tradeoff: <p>A new tier to run, plus a live migration of a huge dataset with no downtime. Coalesced reads can miss a write that lands mid-query; that is fine for chat, not for money.</p>,
    realWorld: <p>Discord’s 2023 post described migrating messages to <strong>ScyllaDB</strong> and adding data services written in <strong>Rust</strong> with request coalescing and consistent-hash routing. It reported a much smaller cluster (177 Cassandra nodes down to 72 ScyllaDB nodes) and far lower p99 latency.</p>,
  },
  {
    title: 'v5 · Voice and video',
    scale: 'millions in voice at once',
    added: ['voice'],
    nodes: [N.client, N.api, N.gw, N.guild, N.presence, N.ds, N.scylla, N.voice],
    edges: [e('client', 'api'), e('client', 'gw'), e('api', 'ds'), e('ds', 'scylla'), e('api', 'guild'), e('guild', 'gw'), e('guild', 'presence'), e('client', 'voice', { label: 'UDP media' })],
    flows: [{ name: 'Join voice', path: ['client', 'gw', 'guild', 'voice'], steps: ['Client asks to join a voice channel over the gateway', 'Guild process checks permissions and picks a voice server', 'Client streams media directly to that server'] }],
    problem: <p>Voice is real-time media: tens of milliseconds matter, packet loss is normal, and peer-to-peer meshes collapse beyond a handful of people.</p>,
    decision: <p>Run separate <strong>media servers</strong> as a Selective Forwarding Unit (SFU). Each client uploads one stream, and the SFU forwards it to others without transcoding. Signaling stays on the gateway; media flows over UDP straight to the SFU.</p>,
    tradeoff: <p>A second global fleet placed by latency rather than by cost, with its own failover. Media and chat now scale on completely different curves.</p>,
    realWorld: <p>Discord has written about its WebRTC-based voice stack using SFU media servers, deployed across many regions so users connect to a nearby server.</p>,
  },
  {
    title: 'v6 · Million-member servers',
    scale: 'single guilds with 1M+ online',
    added: ['relay'],
    nodes: [N.client, N.api, N.gw, N.guild, N.presence, N.ds, N.scylla, N.voice, N.relay],
    edges: [e('client', 'api'), e('client', 'gw'), e('api', 'ds'), e('ds', 'scylla'), e('api', 'guild'), e('guild', 'relay'), e('relay', 'gw'), e('guild', 'presence'), e('client', 'voice')],
    flows: [{ name: 'Deliver', path: ['api', 'guild', 'relay', 'gw', 'client'], steps: ['Event reaches the guild process', 'Guild hands fan-out to a set of relays', 'Each relay handles a slice of sessions', 'Gateways push to clients'] }],
    problem: <p>Even with lazy fan-out, one guild process for a server with over a million members online becomes CPU-bound. Every event it emits is expensive, and every join or leave updates huge structures.</p>,
    decision: <p>Split the guild’s fan-out work across <strong>relay</strong> processes, each owning a slice of sessions, while the guild keeps authoritative state. Treat idle members as passive, and rate-limit what a single server can emit.</p>,
    tradeoff: <p>More moving parts on the hottest path and new consistency edges between the guild and its relays. It exists only because a few servers are huge; most guilds never need it.</p>,
    realWorld: <p>Discord has written publicly about pushing single servers past a million online members, including splitting fan-out work and reducing updates for users who aren’t actively viewing the server.</p>,
  },
]
