import type { EpisodeStage } from '../../components/ui'
import { A, ae } from './episode-airbnb-stage-nodes'
import { AIRBNB_SRC as S } from './episode-airbnb-sources'

// Stages 7–11: correctness for bookings, services, pricing, ranking, and money.
export const AIRBNB_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'v6 · Never double-book',
    era: 'Design step',
    scale: 'peak seasons, hot listings',
    summary: 'The database itself refuses overlapping bookings, and a short hold protects the nights while the guest pays.',
    added: ['hold'],
    nodes: [A.guest, A.host, A.mono, { ...A.db, sub: 'no-overlap constraint' }, A.search, { ...A.index, sub: 'geo + nights bitmap' }, A.cdc, A.hold],
    edges: [ae('guest', 'search'), ae('search', 'index'), ae('guest', 'mono'), ae('host', 'mono'), ae('mono', 'db'), ae('mono', 'hold'),
      ae('db', 'cdc', { async: true }), ae('cdc', 'index')],
    flows: [{ name: 'Checkout', path: ['guest', 'mono', 'hold', 'mono', 'db'], steps: ['Guest starts checkout', 'A short hold is placed on those nights', 'The guest pays while the hold is active', 'The booking commits only if no overlapping booking exists'] }],
    problem: <p>Two guests see the same free nights and both check out. Payment takes seconds, so check-then-insert races produce two confirmations.</p>,
    decision: <p>Let the database decide. Guard bookings with an <strong>exclusion constraint</strong> on listing and night range. Place a <strong>short hold</strong> while the guest pays, then confirm.</p>,
    tradeoff: <p>Abandoned holds block real guests, so keep them short. Constraint errors must become helpful messages, such as nearby dates.</p>,
    realWorld: <p>This is a design step using standard PostgreSQL features: range types and exclusion constraints make overlapping ranges impossible to insert.</p>,
    walkthrough: [
      'The guest starts checkout.',
      'A pending booking with an expiry is inserted under the same constraint.',
      'Payment runs with an idempotency key.',
      'On success the booking is confirmed; on failure or timeout the hold is released.',
      'A concurrent overlapping insert fails with an exclusion violation, and the guest sees alternatives.',
    ],
    numbers: [
      { label: 'Hold length', value: 'minutes', note: 'estimate' },
      { label: 'Winners per night range', value: 'exactly 1', note: 'enforced by the database' },
    ],
    components: [
      { name: 'Exclusion constraint', role: 'Makes overlapping stays for one listing impossible, even with buggy app code.' },
      { name: 'Hold with expiry', role: 'Reserves the nights during payment, then disappears if abandoned.' },
    ],
    alternatives: [
      { option: 'Check, then insert, in app code', verdict: 'A race lets both guests succeed.' },
      { option: 'Lock the whole listing', verdict: 'Also blocks bookings for other dates.' },
    ],
    breaksNext: <p>Hundreds of engineers now ship into one Rails codebase and one deploy train.</p>,
    interview: {
      q: 'Two guests book overlapping nights at the same moment. Walk me through it.',
      a: <p>An exclusion constraint on (listing, nights) lets the database pick exactly one winner. Add a short hold during payment, release it on expiry, and turn the loser’s error into alternative dates.</p>,
    },
    sources: [S.pgConstraints, S.pgRange],
  },
  {
    title: 'v7 · Break up the monolith',
    era: 'Presented 2018–2019',
    scale: '~200 → ~1,000 engineers',
    summary: 'The monolith is carved into services that each own their data, one path at a time.',
    added: ['gw', 'listing', 'booking'],
    nodes: [A.guest, A.host, A.gw, A.search, { ...A.index, sub: 'geo + nights bitmap' }, A.listing, A.booking, A.db, A.hold, A.cdc],
    edges: [ae('guest', 'gw'), ae('host', 'gw'), ae('gw', 'search'), ae('gw', 'listing'), ae('gw', 'booking'), ae('search', 'index'),
      ae('listing', 'db'), ae('booking', 'db'), ae('booking', 'hold'), ae('db', 'cdc', { async: true }), ae('cdc', 'index')],
    flows: [
      { name: 'Book', path: ['guest', 'gw', 'booking', 'db'], steps: ['Guest reserves', 'The gateway routes to the booking service', 'The booking service owns holds, constraints, and the booking lifecycle'] },
      { name: 'Edit listing', path: ['host', 'gw', 'listing', 'db'], steps: ['Host edits a listing', 'The gateway routes to the listing service', 'Only the listing service writes listing data'] },
    ],
    problem: <p>Hundreds of engineers ship into one codebase and one deploy train. Builds are slow, one bug blocks everyone, and ownership is blurry.</p>,
    decision: <p>Move to <strong>services with clear data ownership</strong>: listings, booking, search, payments. Migrate path by path, with the monolith calling new services until its code can be deleted.</p>,
    tradeoff: <p>Network calls replace function calls. Cross-service changes need sagas, and platform work such as tooling and tracing becomes mandatory.</p>,
    realWorld: <p>Airbnb presented its move from the Rails “monorail” to services at QCon SF 2018. InfoQ reported engineering growth from about 200 (2015) to 1,000, and traffic shifted gradually from 1% with results compared.</p>,
    walkthrough: [
      'Pick one read path and build a service that owns its data.',
      'Send 1% of traffic to the new service and compare its answers with the monolith’s.',
      'Raise the share until the comparison is clean at 100%.',
      'For writes, write to a shadow database first and compare reads from both.',
      'Delete the monolith’s version of that path, then repeat.',
    ],
    numbers: [
      { label: 'Engineers', value: '~200 → 1,000', note: '2015 → 2019, per InfoQ' },
      { label: 'First traffic slice', value: '1%', note: 'then ramped with comparison' },
      { label: 'Migration length', value: 'multi-year' },
    ],
    components: [
      { name: 'API gateway', role: 'One entry point that routes each path to its owner.' },
      { name: 'Listing and booking services', role: 'Each owns its data and its rules.' },
    ],
    alternatives: [
      { option: 'Big-bang rewrite', verdict: 'Stops product work and concentrates risk.' },
      { option: 'Stay monolithic', verdict: 'Slows every team as headcount grows.' },
    ],
    breaksNext: <p>Hosts struggle to set good prices, and many nights go empty.</p>,
    interview: {
      q: 'How do you break up a monolith without stopping product work?',
      a: <p>Carve one path at a time, run old and new side by side to compare, move reads before writes, and measure progress by traffic moved, not services created.</p>,
    },
    sources: [S.qcon, S.infoq, S.infoqNews],
  },
  {
    title: 'v8 · Help hosts price',
    era: '2018 (published)',
    scale: 'price per listing-night',
    summary: 'Models predict whether a night will book at a price, then suggest a price the host can accept or ignore.',
    added: ['pricing'],
    nodes: [A.guest, A.host, A.gw, A.listing, A.booking, A.db, A.pricing, A.wh, A.airflow],
    edges: [ae('guest', 'gw'), ae('host', 'gw'), ae('gw', 'listing'), ae('gw', 'booking'), ae('listing', 'db'), ae('booking', 'db'),
      ae('db', 'wh', { async: true }), ae('airflow', 'wh'), ae('wh', 'pricing', { label: 'demand signals' }), ae('pricing', 'listing', { label: 'price tips' })],
    flows: [{ name: 'Price tip', path: ['host', 'gw', 'listing', 'pricing'], steps: ['Host opens their calendar', 'The gateway routes to the listing service', 'The listing service shows the latest suggested prices'] }],
    problem: <p>Every home is different, so there is no simple demand curve. Hosts over- or under-price, and nights go empty.</p>,
    decision: <p>Suggest prices per listing-night. One model predicts <strong>booking probability</strong>. Another predicts a good <strong>price</strong> with a custom loss. Personalization produces the final tip; hosts stay in control.</p>,
    tradeoff: <p>Suggestions shift host income, so they need careful testing and trust. Prices change constantly, so pipelines must keep up.</p>,
    realWorld: <p>Airbnb’s KDD 2018 paper describes the models behind Price Tips and Smart Pricing, and reports online A/B test results.</p>,
    walkthrough: [
      'Daily pipelines gather demand signals: searches, bookings, seasonality.',
      'A classifier predicts whether a listing-night will book at a given price.',
      'A regression model suggests a price, trained with a custom loss.',
      'Personalization adjusts for each host’s settings.',
      'Hosts see tips, or turn on automatic pricing.',
    ],
    numbers: [
      { label: 'Model stages', value: '2', note: '+ personalization' },
      { label: 'Pricing unit', value: 'listing × night' },
    ],
    components: [
      { name: 'Pricing models', role: 'Booking-probability and price models, retrained on fresh data.' },
      { name: 'Listing service', role: 'Shows tips and applies automatic prices when hosts opt in.' },
    ],
    alternatives: [
      { option: 'Only fixed host prices', verdict: 'Leaves bookings and income on the table.' },
      { option: 'Classic revenue management', verdict: 'Assumes identical products; homes are all different.' },
    ],
    breaksNext: <p>Sorting available homes by price is not what guests want. Which few homes should appear first?</p>,
    interview: {
      q: 'How would you suggest prices for unique items like homes?',
      a: <p>Model booking probability per night, then choose a price that balances revenue and occupancy. Keep the host in control and A/B test the effect on both sides.</p>,
    },
    sources: [S.pricing, S.pricingSummary],
  },
  {
    title: 'v9 · Learn to rank and retrieve',
    era: '2018–2019 and later',
    scale: 'millions of candidate homes',
    summary: 'Search learns from what guests actually book, first to rank results, later to pick candidates with embeddings.',
    added: ['ranker', 'retr'],
    nodes: [A.guest, A.host, A.gw, A.search, A.ranker, A.retr, { ...A.index, sub: 'geo + nights bitmap' }, A.wh, A.airflow],
    edges: [ae('guest', 'gw'), ae('host', 'gw'), ae('gw', 'search'), ae('search', 'retr'), ae('retr', 'index', { label: 'filters' }), ae('search', 'ranker'),
      ae('airflow', 'wh'), ae('wh', 'ranker', { label: 'training data' })],
    flows: [{ name: 'Search', path: ['guest', 'gw', 'search', 'retr', 'index'], steps: ['Guest searches', 'The gateway routes to search', 'Retrieval builds a candidate pool with embeddings', 'Filters (map area, nights free) apply in the index'] },
      { name: 'Rank', path: ['search', 'ranker'], steps: ['The ranker scores candidates with a neural network, and the best few are shown'] }],
    problem: <p>Guests book the homes they like, not the cheapest ones. Out of millions, which few should appear first?</p>,
    decision: <p>Train <strong>ranking models</strong> on what guests actually book. Airbnb moved from gradient-boosted trees to deep neural networks and added listing embeddings. Later, embedding-based <strong>retrieval</strong> narrows candidates before ranking.</p>,
    tradeoff: <p>Ranking changes shift income between hosts, so they need A/B tests and guardrails. Retrieval indexes must absorb frequent price and availability updates.</p>,
    realWorld: <p>Airbnb published listing embeddings (KDD 2018) and its move to deep learning for search ranking (KDD 2019). A later post explains choosing IVF over HNSW for retrieval, because of frequent updates and geo filters.</p>,
    walkthrough: [
      'Retrieval builds a candidate pool using filters and embeddings.',
      'The ranker scores each candidate with a neural network.',
      'Recent session clicks adjust personalization in real time.',
      'The top results are shown; clicks and bookings become training data.',
    ],
    numbers: [
      { label: 'Ranking model (2019)', value: 'deep neural net', note: 'replaced tree ensembles' },
      { label: 'Retrieval index', value: 'IVF', note: 'chosen over HNSW' },
    ],
    components: [
      { name: 'Retrieval', role: 'Finds a manageable candidate pool from millions of homes.' },
      { name: 'Ranker', role: 'Orders candidates by the chance a guest books them.' },
    ],
    alternatives: [
      { option: 'Sort by price or distance', verdict: 'Ignores what guests actually book.' },
      { option: 'HNSW for retrieval', verdict: 'Airbnb found its memory grew too large under frequent updates.' },
    ],
    breaksNext: <p>Money now crosses many services, and one retried request can charge a guest twice.</p>,
    interview: {
      q: 'What changes when search ranking uses deep learning?',
      a: <p>Features and training pipelines dominate the work. You need offline metrics that predict online wins, fast rollback, and guardrails for both hosts and guests.</p>,
    },
    sources: [S.embeddings, S.deepSearch, S.retrieval],
  },
  {
    title: 'v10 · Payments that never double-charge',
    era: '2019',
    scale: 'many payment services',
    summary: 'Every payment call carries an idempotency key, so a retry after a timeout returns the first result instead of charging again.',
    added: ['pay', 'psp', 'idem'],
    nodes: [A.guest, A.host, A.gw, A.booking, A.db, A.pay, A.psp, A.idem],
    edges: [ae('guest', 'gw'), ae('host', 'gw'), ae('gw', 'booking'), ae('booking', 'db'), ae('booking', 'pay', { label: 'charge + key' }),
      ae('pay', 'idem'), ae('pay', 'psp'), ae('psp', 'host', { label: 'payout', async: true })],
    flows: [{ name: 'Charge', path: ['guest', 'gw', 'booking', 'pay', 'idem'], steps: ['Guest confirms the booking', 'The gateway routes to booking', 'Booking asks payments to charge, with an idempotency key', 'The key is recorded and locked before calling the processor'] },
      { name: 'Call processor', path: ['pay', 'psp'], steps: ['The processor is called; its result is stored under the same key'] }],
    problem: <p>Payments span services and external processors. After a timeout you cannot tell whether the charge happened, and a blind retry may charge twice.</p>,
    decision: <p>Make every payment request idempotent with a shared library, <strong>Orpheus</strong>. The library records the request key, makes the external call, and stores the result. A retry returns the stored result.</p>,
    tradeoff: <p>Idempotency data must be read from the primary database, never a lagging replica. The store then needed sharding by key to scale.</p>,
    realWorld: <p>Airbnb’s 2019 post “Avoiding Double Payments in a Distributed Payments System” describes Orpheus and its pre-RPC, RPC, and post-RPC phases.</p>,
    walkthrough: [
      'The client sends a charge with an idempotency key.',
      'Pre-RPC: the key and request are recorded and the row is locked.',
      'RPC: the payment processor is called.',
      'Post-RPC: the response is stored under the key.',
      'A retry with the same key returns the stored result; no second charge.',
    ],
    numbers: [
      { label: 'Phases per request', value: '3', note: 'pre-RPC, RPC, post-RPC' },
      { label: 'Shard key', value: 'idempotency key', note: 'high cardinality, even spread' },
    ],
    components: [
      { name: 'Orpheus', role: 'An idempotency library embedded in each payment service.' },
      { name: 'Idempotency store', role: 'Keys and results, read from primaries only.' },
      { name: 'Payment processor', role: 'The external system that actually moves money.' },
    ],
    alternatives: [
      { option: 'A central idempotency service', verdict: 'Adds latency and inherits the same failure modes.' },
      { option: 'Retry blindly', verdict: 'Double charges.' },
    ],
    breaksNext: <p>Next comes reconciling every ledger entry with processor settlement files across currencies. The Stripe episode covers that part.</p>,
    interview: {
      q: 'A payment call timed out. Do you retry?',
      a: <p>Only with the same idempotency key, so the second attempt is deduplicated. Read the key from the primary, not a replica, and classify errors as retryable or not.</p>,
    },
    sources: [S.orpheus],
  },
]
