import type { EpisodeStage } from '../../components/ui'
import { N, S, as, e } from './episode-netflix-stage-library'

export const NETFLIX_LATE: EpisodeStage[] = [
  {
    title: 'Practice losing a region',
    era: '2015–2018',
    summary: 'Netflix regularly pretends a whole AWS region is gone, and moves users away.',
    scale: 'Region evacuation drills',
    added: ['chaos'],
    nodes: [N.dns, as(N.chaos, 'Chaos Kong', 'simulated region loss'), N.region, N.client, N.edge, N.api, N.svc, N.cass, N.evc, N.oca],
    edges: [e('client', 'dns'), e('dns', 'edge'), e('dns', 'region'), e('chaos', 'dns', { label: 'evacuate', async: true }), e('edge', 'api'), e('api', 'svc'), e('svc', 'cass'), e('svc', 'evc'), e('cass', 'region', { async: true }), e('client', 'oca')],
    flows: [{ name: 'Evacuation', path: ['chaos', 'dns', 'region'], steps: ['An exercise marks one region as failed', 'DNS shifts that region’s users to the others'] }],
    problem: <p>Multi-region only helps if failover really works, under real load, on short notice.</p>,
    decision: <p>Run Chaos Kong: simulate the loss of a whole region in production and evacuate its traffic. Later, make evacuation much faster by keeping capacity ready.</p>,
    tradeoff: <p>Exercises carry real risk and need strong monitoring. Spare capacity in every region costs money.</p>,
    realWorld: <p>In September 2015 a DynamoDB problem disrupted many AWS services in us-east-1. Netflix reported only a brief blip, crediting these drills. Project Nimble (2018) sped evacuation up.</p>,
    walkthrough: [
      'Operators pick a region to “fail”.',
      'Other regions scale up to absorb its traffic.',
      'DNS steers that region’s users away.',
      'Teams watch metrics and fix whatever broke, then restore traffic.',
    ],
    numbers: [
      { label: 'Chaos Kong described', value: 'Sept 2015' },
      { label: 'Nimble (faster evacuation)', value: '2018' },
    ],
    components: [{ name: 'Chaos Kong', role: 'Simulates a full region outage; its big sibling Chaos Monkey kills single instances.' }],
    alternatives: [
      { option: 'Annual disaster-recovery test', verdict: 'Too rare to catch drift in hundreds of services.' },
      { option: 'Game days in staging', verdict: 'Staging lacks real traffic and data.' },
    ],
    breaksNext: <p>Every service now emits events, and batch data pipelines can’t keep up.</p>,
    interview: { q: 'How would you validate a multi-region design?', a: <p>Regular, scheduled failover of real traffic with abort criteria. Measure time to evacuate and the error budget spent.</p> },
    sources: [S.chaosKong, S.nimble],
  },
  {
    title: 'A data pipeline for everything',
    era: '2015–2018',
    summary: 'Every event flows through one Kafka-based pipeline into storage and real-time consumers.',
    scale: 'Hundreds of billions of events a day',
    added: ['kafka', 'stream'],
    nodes: [N.client, N.edge, N.api, N.svc, N.cass, N.kafka, as(N.s3, 'S3 + Iceberg', 'data warehouse'), N.stream, N.oca],
    edges: [e('client', 'edge'), e('edge', 'api'), e('api', 'svc'), e('svc', 'cass'), e('svc', 'kafka', { async: true }), e('kafka', 's3', { label: 'batch' }), e('kafka', 'stream', { label: 'real-time' }), e('client', 'oca')],
    flows: [{ name: 'Event', path: ['client', 'edge', 'api', 'svc', 'kafka', 's3'], steps: ['A play or scroll happens on a device', 'The request passes the edge', 'The API calls services', 'Services publish events to Keystone', 'Keystone routes them to S3 for analytics'] }],
    problem: <p>Every team needs event data, for dashboards, experiments, and models. Point-to-point pipelines don’t scale.</p>,
    decision: <p>Build Keystone: a Kafka-fronted pipeline that collects events from every app and routes them to S3, search, and stream processors. Store analytics tables in a new table format, Iceberg.</p>,
    tradeoff: <p>Kafka at this size is its own operations problem. Netflix even weighed fewer replicas for topics that tolerate small losses.</p>,
    realWorld: <p>Keystone ran in production from late 2015. Netflix created Apache Iceberg and donated it to Apache in 2018.</p>,
    walkthrough: [
      'Every service publishes events to “fronting” Kafka clusters.',
      'A routing layer copies them to sinks: S3, Elasticsearch, or other Kafka clusters.',
      'Batch jobs query S3 through Iceberg tables.',
      'Stream processors react within seconds.',
    ],
    numbers: [
      { label: 'Messages per day', value: '700B+', note: 'average, April 2016' },
      { label: 'Kafka clusters', value: '36', note: '4,000+ brokers, 2016' },
    ],
    components: [
      { name: 'Keystone', role: 'One pipeline for event collection and routing.' },
      { name: 'Iceberg tables', role: 'Reliable, atomic tables over files in S3.' },
    ],
    alternatives: [
      { option: 'Each team builds its own pipeline', verdict: 'Duplicated work and inconsistent data.' },
      { option: 'Hive tables on S3', verdict: 'Weak atomicity and slow listings; the reason Iceberg was built.' },
    ],
    breaksNext: <p>The next jump is geographic: most of the world can’t subscribe yet.</p>,
    interview: { q: 'Why put Kafka in front of the warehouse?', a: <p>It decouples producers from consumers, absorbs bursts, and lets many sinks read the same events.</p> },
    sources: [S.pipeline, S.kafka, S.iceberg],
  },
  {
    title: 'Global in one day',
    era: 'Jan 2016',
    summary: 'Netflix switches on 130+ new countries at once, the same month its cloud move finishes.',
    scale: '190+ countries',
    nodes: [N.dns, N.region, as(N.client, 'Devices worldwide'), N.edge, N.api, N.svc, N.cass, N.evc, N.oca, N.steer],
    edges: [e('client', 'dns'), e('dns', 'edge'), e('dns', 'region'), e('edge', 'api'), e('api', 'svc'), e('svc', 'cass'), e('svc', 'evc'), e('api', 'steer'), e('client', 'oca')],
    flows: [{ name: 'New country', path: ['client', 'dns', 'edge', 'api', 'steer'], steps: ['A new member resolves Netflix', 'DNS routes to the nearest region', 'The edge forwards to the API', 'Steering finds the closest caches'] }],
    problem: <p>Launching country by country is slow. Every new market needs capacity, content delivery, and local payments.</p>,
    decision: <p>Rely on elastic cloud capacity and the existing multi-region setup. Launch everywhere at once and expand caches as demand appears.</p>,
    tradeoff: <p>Some regions start with less local cache capacity, so early quality varies by market.</p>,
    realWorld: <p>On January 6, 2016, Netflix went live in more than 130 new countries. It finished its cloud migration that same month.</p>,
    walkthrough: ['The service turns on in new countries at a keynote.', 'New traffic lands on existing regions.', 'Streams come from caches in exchanges and ISPs, which grow over time.'],
    numbers: [
      { label: 'New countries', value: '130+', note: 'Jan 6, 2016' },
      { label: 'Total countries', value: '190+' },
    ],
    components: [{ name: 'No new component', role: 'This launch tests the earlier investments.' }],
    alternatives: [{ option: 'Phased country launches', verdict: 'Lower risk per launch, but years slower.' }],
    breaksNext: <p>A global audience on every kind of network makes bandwidth efficiency matter even more.</p>,
    interview: { q: 'What must be true before a “launch everywhere” day?', a: <p>Elastic compute, tested regional failover, and delivery capacity you can grow after launch.</p> },
    sources: [S.global, S.migration],
  },
  {
    title: 'Fewer bits, same quality',
    era: '2015–2021',
    summary: 'Netflix tunes encoding to each title, then each shot, then adopts the AV1 codec.',
    scale: 'Every stream, every night',
    added: ['encode'],
    nodes: [N.client, N.edge, N.api, N.svc, N.s3, N.oca, N.steer, N.encode],
    edges: [e('client', 'edge'), e('edge', 'api'), e('api', 'svc'), e('api', 'steer'), e('client', 'oca'), e('s3', 'encode'), e('encode', 's3', { label: 'renditions' }), e('s3', 'oca', { label: 'fill', async: true })],
    flows: [{ name: 'Encode', path: ['s3', 'encode', 's3', 'oca'], steps: ['A studio master lands in S3', 'Shots are encoded in parallel at tuned bitrates', 'Renditions are pushed to caches off-peak'] }],
    problem: <p>A fixed bitrate ladder wastes bits on simple scenes and starves complex ones. Mobile users pay for data.</p>,
    decision: <p>Choose bitrates per title (2015), then per shot (2018). Add more efficient codecs, including AV1.</p>,
    tradeoff: <p>Much more encoding compute and more files to store. It pays back on every stream.</p>,
    realWorld: <p>AV1 reached Android in 2020 and TVs in late 2021. Netflix says AV1 is about 20% more efficient than its VP9 encodes.</p>,
    walkthrough: [
      'The master is split into shots.',
      'Each shot is encoded at several quality and bitrate points.',
      'An optimizer picks the best points for the whole title.',
      'The results are packaged into streams per codec and device.',
    ],
    numbers: [
      { label: 'AV1 vs VP9', value: '~20% better', note: 'compression, 2020 post' },
      { label: 'AV1 share of streaming', value: '~30%', note: 'Netflix, 2025' },
    ],
    components: [{ name: 'Encoding pipeline', role: 'Parallel, per-shot encoding tuned by perceived quality.' }],
    alternatives: [
      { option: 'One fixed ladder', verdict: 'Simple, but wastes bandwidth on easy content.' },
      { option: 'Encode on demand', verdict: 'Too slow and costly at playback time.' },
    ],
    breaksNext: <p>Delivering well isn’t enough; members must find something to watch quickly.</p>,
    interview: { q: 'Why spend more on encoding to save bandwidth?', a: <p>You encode once and deliver millions of times. Savings multiply across every stream.</p> },
    sources: [S.perTitle, S.dynOpt, S.av1Android, S.av1Share],
  },
  {
    title: 'Personalize everything',
    era: '2016–2017',
    summary: 'Rows, order, and even the artwork are chosen per member.',
    scale: 'Per member, per title',
    added: ['ml'],
    nodes: [N.client, N.edge, N.api, N.svc, N.evc, N.ml, N.kafka, N.s3, N.oca],
    edges: [e('client', 'edge'), e('edge', 'api'), e('api', 'svc'), e('svc', 'evc'), e('svc', 'kafka', { async: true }), e('kafka', 's3'), e('s3', 'ml', { label: 'training' }), e('ml', 'evc', { label: 'precomputed' }), e('client', 'oca')],
    flows: [
      { name: 'Home screen', path: ['client', 'edge', 'api', 'svc', 'evc'], steps: ['The TV asks for its home screen', 'Edge routes it', 'The API calls services', 'Precomputed rows and artwork come from cache'] },
      { name: 'Learn', path: ['svc', 'kafka', 's3', 'ml'], steps: ['Plays and scrolls become events', 'Events land in S3', 'Models train on them'] },
    ],
    problem: <p>With thousands of titles on a TV remote, members give up fast. What you show first matters most.</p>,
    decision: <p>Rank rows and titles per member. Pick the artwork for each title per member too, using online learning (contextual bandits). Precompute and cache results.</p>,
    tradeoff: <p>Precomputed pages go stale. Experiments and models add a lot of pipeline complexity.</p>,
    realWorld: <p>Netflix described personalized artwork in December 2017: models predict play probability per image, and the choice is precomputed and cached.</p>,
    walkthrough: [
      'Every play, pause, and scroll is logged as an event.',
      'Models learn which rows and images lead to plays.',
      'Choices are precomputed per member and cached.',
      'The home screen reads from cache, so it stays fast.',
    ],
    numbers: [
      { label: 'Artwork choice', value: 'per member', note: 'from a pool of images per title' },
      { label: 'Selection method', value: 'contextual bandits', note: 'online learning' },
    ],
    components: [{ name: 'Personalization', role: 'Offline training plus precomputed, cached results.' }],
    alternatives: [
      { option: 'Same page for everyone', verdict: 'Cheap, but poor discovery.' },
      { option: 'Fully online ranking per request', verdict: 'Fresher, but hard to keep latency low on TVs.' },
    ],
    breaksNext: <p>A new business model arrives: a cheaper plan paid for by ads.</p>,
    interview: { q: 'Personalization is down. What does the home screen do?', a: <p>Serve the last cached page, or popular rows by region. Never block playback on it.</p> },
    sources: [S.artwork],
  },
  {
    title: 'An ad-supported plan',
    era: '2022–2025',
    summary: 'A cheaper plan with ads, first with a partner, then on Netflix’s own ad tech.',
    scale: '12 launch countries',
    added: ['ads'],
    nodes: [N.client, N.edge, N.api, N.ads, as(N.region, 'Ad partner', 'Microsoft, 2022–24'), N.svc, N.kafka, N.oca, N.steer],
    edges: [e('client', 'edge'), e('edge', 'api'), e('api', 'ads'), e('ads', 'region', { label: 'demand' }), e('api', 'svc'), e('ads', 'kafka', { async: true, label: 'impressions' }), e('api', 'steer'), e('client', 'oca')],
    flows: [{ name: 'Ad break', path: ['client', 'edge', 'api', 'ads', 'region'], steps: ['The player reaches an ad break', 'The edge forwards the request', 'The API asks ad decisioning', 'Decisioning picks an ad from available demand'] }],
    problem: <p>Some members want a lower price. Ads bring new needs: targeting, frequency caps, measurement, and advertiser reporting.</p>,
    decision: <p>Launch quickly with an ad-tech and sales partner, then build ad tech in-house for control over the experience and data.</p>,
    tradeoff: <p>Ad decisions sit on the playback path, so their latency matters. Advertisers need third-party measurement.</p>,
    realWorld: <p>Basic with Ads launched in November 2022 with Microsoft as partner. Netflix then began moving to its own ad tech in late 2024, starting in Canada.</p>,
    walkthrough: [
      'The player reaches an ad break.',
      'Ad decisioning picks an ad using targeting and frequency caps.',
      'The ad video streams like any other file.',
      'Impressions are logged for billing and measurement.',
    ],
    numbers: [
      { label: 'Launch', value: 'Nov 3, 2022', note: '12 countries' },
      { label: 'US launch price', value: '$6.99 / month' },
      { label: 'In-house ad tech', value: 'Canada 2024 → all ad markets 2025' },
    ],
    components: [
      { name: 'Ad decisioning', role: 'Chooses which ad plays, within latency limits.' },
      { name: 'Impression events', role: 'Feed billing, reporting, and caps.' },
    ],
    alternatives: [
      { option: 'Build ad tech first', verdict: 'Slower to market.' },
      { option: 'Stay with a partner forever', verdict: 'Less control over experience and data.' },
    ],
    breaksNext: <p>Live events arrive, where everyone watches the same second at once.</p>,
    interview: { q: 'How do you keep ads from hurting playback?', a: <p>Tight timeouts, prefetching ads before the break, and a no-ad fallback if decisioning is slow.</p> },
    sources: [S.adsPartner, S.adsLaunch, S.adsInHouse],
  },
  {
    title: 'Live events',
    era: '2023–2025',
    summary: 'Netflix streams live events, where millions join in the same minute.',
    scale: 'Peak 65M concurrent streams (Nov 2024)',
    added: ['live', 'origin'],
    nodes: [as(N.region, 'Venue feed'), N.live, N.client, N.edge, N.api, N.origin, N.oca, N.steer, N.kafka],
    edges: [e('region', 'live', { label: 'redundant paths' }), e('live', 'origin', { label: 'segments' }), e('origin', 'oca'), e('client', 'oca'), e('client', 'edge'), e('edge', 'api'), e('api', 'steer'), e('api', 'kafka', { async: true })],
    flows: [{ name: 'Live', path: ['region', 'live', 'origin', 'oca', 'client'], steps: ['The venue feed arrives over redundant paths', 'Cloud pipelines encode and package segments', 'The live origin serves segments to caches', 'Devices fetch the newest segments every few seconds'] }],
    problem: <p>Live traffic can’t be pre-filled overnight. Millions start within minutes, and every second of delay is visible.</p>,
    decision: <p>Ingest in two cloud regions over redundant paths, run parallel pipelines, and add a live origin that feeds Open Connect.</p>,
    tradeoff: <p>Redundancy doubles the pipeline cost. Peaks are huge and brief, so capacity sits idle most of the time.</p>,
    realWorld: <p>The Paul–Tyson fight in November 2024 peaked at 65 million concurrent streams, and many viewers reported buffering. Netflix later described its live architecture in a 2025 series.</p>,
    walkthrough: [
      'The feed enters two cloud regions, each over two network paths.',
      'Parallel pipelines produce interchangeable segments.',
      'The live origin picks good segments and serves them to caches.',
      'Devices poll for new segments and play slightly behind real time.',
    ],
    numbers: [
      { label: 'Peak concurrent streams', value: '65M', note: 'Nov 2024, per Netflix' },
      { label: 'Independent ingest feeds', value: '4', note: '2 regions × 2 paths' },
    ],
    components: [
      { name: 'Live ingest + pipelines', role: 'Redundant encoding in two regions.' },
      { name: 'Live origin', role: 'Bridge between cloud pipelines and Open Connect.' },
    ],
    alternatives: [
      { option: 'Third-party live CDN', verdict: 'Fast to start, but splits operations from the main delivery network.' },
      { option: 'Single pipeline', verdict: 'Cheaper, but one failure ends the broadcast.' },
    ],
    breaksNext: <p>The next challenges are bigger live peaks and tighter latency.</p>,
    interview: { q: 'How is live delivery different from on-demand?', a: <p>No pre-fill, a synchronized thundering herd, and no second chance. Design for redundancy and fast failover, not cache hit rate.</p> },
    sources: [S.tyson, S.live1, S.live2, S.liveOrigin],
  },
]
