import type { EpisodeStage } from '../../components/ui'
import { AN as N, ae as e } from './episode-amazon-nodes'
import { AMAZON_SRC as S } from './episode-amazon-sources'

export const AMAZON_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'v6 · Orders as a workflow',
    era: 'Design step',
    scale: 'Payment, warehouses, carriers',
    summary: 'An order is a series of small steps, and each step knows how to undo itself.',
    added: ['orders', 'pay', 'fulfil'],
    nodes: [N.shopper, N.gw, N.cart, N.inv, N.invdb, N.orders, N.pay, N.fulfil, N.orderdb],
    edges: [e('shopper', 'gw'), e('gw', 'cart'), e('gw', 'orders'), e('orders', 'inv'), e('inv', 'invdb'), e('orders', 'pay'), e('orders', 'orderdb'), e('orders', 'fulfil', { async: true })],
    flows: [
      { name: 'Place order', path: ['shopper', 'gw', 'orders', 'inv'], steps: ['Shopper clicks Place order', 'Web tier starts the workflow with an order id', 'Step 1 turns the hold into a reservation'] },
      { name: 'Compensate', path: ['orders', 'pay', 'orders', 'inv'], steps: ['Payment is declined', 'The workflow runs its undo steps', 'The reservation is released back to stock'] },
    ],
    problem: <p>An order spans inventory, payment, fraud checks, warehouses, and shipping. They belong to different teams and databases, so one transaction cannot cover them.</p>,
    decision: <p>Model the order as a <strong>saga</strong>: local steps in order, each with a <strong>compensating</strong> step (release stock, refund, cancel shipment). A durable workflow engine runs it and survives crashes.</p>,
    tradeoff: <p>In-between states become visible, such as “payment pending”. Every step must be idempotent because the engine will retry.</p>,
    realWorld: <p>AWS guidance describes the saga orchestration pattern with an order, inventory, and payment example: when payment fails, the orchestrator runs compensating steps.</p>,
    walkthrough: [
      'The workflow saves “started” and reserves stock.',
      'It authorizes payment, using the order id as the idempotency key.',
      'On success it commits the order and starts fulfillment in the background.',
      'On failure it runs compensations in reverse order and marks the order failed.',
    ],
    numbers: [
      { label: 'Steps that fit a saga well', value: '3–5', note: 'AWS guidance' },
      { label: 'Compensations per step', value: '1' },
    ],
    components: [
      { name: 'Order workflow', role: 'Durable state machine; persists each step before the next.' },
      { name: 'Fulfillment', role: 'Picks a warehouse and ships, hours or days later.' },
    ],
    alternatives: [
      { option: 'Two-phase commit across services', verdict: 'Locks resources across teams and blocks when one party fails.' },
      { option: 'Events only (choreography)', verdict: 'No central brain, but harder to see where an order is stuck.' },
    ],
    breaksNext: <p>Charging at the wrong moment causes refunds and angry customers when items do not ship.</p>,
    interview: { q: 'Why a saga instead of a distributed transaction?', a: <p>The steps span teams and external providers. A saga keeps each step local and undoes work explicitly instead of holding locks.</p> },
    sources: [S.saga],
  },
  {
    title: 'v7 · Charge at the right moment',
    era: 'Design step',
    scale: 'Orders ship days later',
    summary: 'The card is authorized at checkout, but money is only captured when the item ships.',
    added: ['networks'],
    nodes: [N.shopper, N.gw, N.inv, N.orders, N.pay, N.networks, N.fulfil, N.orderdb],
    edges: [e('shopper', 'gw'), e('gw', 'orders'), e('orders', 'inv'), e('orders', 'pay'), e('pay', 'networks'), e('orders', 'orderdb'), e('orders', 'fulfil', { async: true })],
    flows: [
      { name: 'Authorize', path: ['orders', 'pay', 'networks'], steps: ['Workflow asks payments to authorize the total', 'The card network places a hold on the customer’s card'] },
      { name: 'Capture', path: ['fulfil', 'orders', 'pay', 'networks'], steps: ['The warehouse reports the item shipped', 'Workflow moves to “shipped”', 'Payments captures the authorized amount'] },
    ],
    problem: <p>Items can go out of stock or be damaged after checkout. Charging immediately forces refunds when an item never ships.</p>,
    decision: <p><strong>Authorize</strong> at checkout to confirm the customer can pay. <strong>Capture</strong> only the amount that ships, when it ships. Every payment call carries an idempotency key.</p>,
    tradeoff: <p>Authorizations expire after a while, so long delays need re-authorization. Split shipments need partial captures.</p>,
    walkthrough: [
      'Checkout authorizes the order total; the bank holds the funds.',
      'The order waits for fulfillment.',
      'Each shipment triggers a capture for its items only.',
      'Unshipped items release their share of the hold.',
    ],
    numbers: [
      { label: 'Payment calls per order', value: '≥ 2', note: 'authorize, then capture per shipment' },
      { label: 'Retries allowed', value: 'yes, with the same key' },
    ],
    components: [
      { name: 'Payments service', role: 'Wraps card networks; authorize, capture, void, refund.' },
      { name: 'Card networks', role: 'Hold and move money between banks.' },
    ],
    alternatives: [
      { option: 'Charge in full at checkout', verdict: 'Simple, but many refunds when items do not ship.' },
      { option: 'Charge only at shipment, no authorization', verdict: 'No refunds, but some cards fail after you already shipped.' },
    ],
    breaksNext: <p>One bad deploy or a single overloaded dependency can still take down the whole store.</p>,
    interview: { q: 'Why separate authorize and capture?', a: <p>Authorization proves the money is there without taking it. Capture at shipment means you only charge for what ships.</p> },
    sources: [S.saga],
  },
  {
    title: 'v8 · Cells and shuffle sharding',
    era: 'Design step',
    scale: 'Failures must stay small',
    summary: 'Customers are split across independent copies of the stack, so one failure hits only a slice.',
    added: ['cellA', 'cellB', 'cellC', 'deploy'],
    nodes: [N.shopper, N.gwCell, N.cellA, N.cellB, N.cellC, N.deploy],
    edges: [e('shopper', 'gw'), e('gw', 'cellA'), e('gw', 'cellB'), e('gw', 'cellC'), e('deploy', 'cellA', { async: true }), e('deploy', 'cellB', { async: true }), e('deploy', 'cellC', { async: true })],
    flows: [
      { name: 'Route', path: ['shopper', 'gw', 'cellB'], steps: ['A request arrives with a customer id', 'The router sends it to that customer’s cell'] },
      { name: 'Deploy', path: ['deploy', 'cellA'], steps: ['A new version goes to one cell first; others wait for health checks'] },
    ],
    problem: <p>A poison request, a bad deploy, or one noisy customer can overload a shared fleet. Then every customer suffers.</p>,
    decision: <p>Split into <strong>cells</strong>: full, independent copies of the stack, each serving some customers. Assign customers with <strong>shuffle sharding</strong> so any two customers rarely share all their workers.</p>,
    tradeoff: <p>More copies to run and deploy. The router becomes critical and must be very simple.</p>,
    realWorld: <p>AWS publishes guidance on cell-based architecture. Its Builders’ Library explains shuffle sharding with Route 53: 2,048 virtual name servers, four per domain, giving about 730 billion possible shards.</p>,
    walkthrough: [
      'Each customer is mapped to a cell by a small, stable lookup.',
      'Within shared fleets, each customer gets a random small set of workers (a shuffle shard).',
      'A poison request only affects that customer’s workers.',
      'Deploys roll out one cell at a time, watching health before continuing.',
    ],
    numbers: [
      { label: 'Impact with 8 workers, shards of 2', value: '1/28', note: 'vs 1/4 with plain sharding, AWS' },
      { label: 'Route 53 possible shards', value: '~730 billion', note: 'AWS Builders’ Library' },
    ],
    components: [
      { name: 'Cell router', role: 'Thin mapping from customer to cell; no business logic.' },
      { name: 'Deploy pipeline', role: 'Ships to one cell, waits, then continues.' },
    ],
    alternatives: [
      { option: 'One big fleet with autoscaling', verdict: 'Efficient, but a single bad input can hit everyone.' },
      { option: 'Plain sharding', verdict: 'Limits impact to one shard, but everyone on that shard fails together.' },
    ],
    breaksNext: <p>Once a year, a planned sale multiplies traffic in minutes.</p>,
    interview: { q: 'Why is shuffle sharding better than plain sharding?', a: <p>Customers overlap on few workers. A failure caused by one customer affects only those who share its exact set, a much smaller slice.</p> },
    sources: [S.cells, S.shuffle],
  },
  {
    title: 'v9 · Surviving Prime Day',
    era: '2015 → today',
    scale: 'Planned peak, many times normal',
    summary: 'Scale up early, shed low-value work, and queue hot checkouts instead of timing out.',
    added: ['waitq'],
    nodes: [N.shopper, N.cdn, N.gwPeak, N.waitq, N.catalog, N.catcache, N.cart, N.inv, N.orders, N.pay],
    edges: [e('shopper', 'cdn'), e('shopper', 'gw'), e('gw', 'catalog'), e('catalog', 'catcache'), e('gw', 'cart'), e('gw', 'waitq'), e('waitq', 'orders'), e('orders', 'inv'), e('orders', 'pay')],
    flows: [{ name: 'Peak checkout', path: ['shopper', 'gw', 'waitq', 'orders', 'inv'], steps: ['Traffic spikes as a deal opens', 'The web tier admits what downstream can handle', 'Queued checkouts drain at a safe rate', 'Inventory decides who gets the stock'] }],
    problem: <p>A planned event multiplies traffic, and hot deals focus it on a few items. One overloaded dependency can cascade across the site.</p>,
    decision: <p><strong>Pre-scale</strong> before the event. <strong>Shed</strong> low-value work early, such as recommendations before checkout. <strong>Queue</strong> checkouts for hot items. Rely on cells to contain failures.</p>,
    tradeoff: <p>Shoppers sometimes wait or see a simpler page. That beats everyone timing out together.</p>,
    realWorld: <p>The first Prime Day, on 15 July 2015, saw 34.4 million items ordered, peaking at 398 items per second. For Prime Day 2023, AWS reported DynamoDB peaking at 126 million requests per second for Amazon.</p>,
    walkthrough: [
      'Weeks before, load tests at target traffic find the weakest dependency.',
      'Capacity is added ahead of time; autoscaling is too slow for a sudden peak.',
      'During the event, low-priority features switch off first.',
      'Hot-item checkouts enter a queue that drains at the inventory service’s safe rate.',
    ],
    numbers: [
      { label: 'Items ordered, Prime Day 2015', value: '34.4M', note: 'Amazon' },
      { label: 'Peak, 2015', value: '398 items/s', note: 'Amazon' },
      { label: 'DynamoDB peak, 2023', value: '126M req/s', note: 'AWS' },
      { label: 'SQS peak, 2023', value: '86M msgs/s', note: 'AWS' },
    ],
    components: [
      { name: 'Load shedding', role: 'Rejects low-value work quickly and cheaply under stress.' },
      { name: 'Checkout queue', role: 'Admission control for hot items.' },
    ],
    alternatives: [
      { option: 'Reactive autoscaling only', verdict: 'New capacity arrives after the spike has already hurt.' },
      { option: 'Let every request through', verdict: 'Everyone times out together.' },
    ],
    breaksNext: <p>Getting the order right is not enough; shoppers also want to know when it will arrive.</p>,
    interview: { q: 'What do you shed first on a peak day?', a: <p>Anything that does not make money right now: recommendations, reviews, analytics. Keep cart, checkout, and payment.</p> },
    sources: [S.prime2015, S.prime2023, S.shedding],
  },
  {
    title: 'v10 · Promise a delivery date',
    era: '2022',
    scale: 'Hundreds of millions of products',
    summary: 'Before you buy, the site computes where the item will ship from and when it will arrive.',
    added: ['promise', 'plan'],
    nodes: [N.shopper, N.gw, N.cart, N.promise, N.plan, N.inv, N.orders, N.fulfil],
    edges: [e('shopper', 'gw'), e('gw', 'cart'), e('gw', 'promise'), e('promise', 'inv'), e('promise', 'plan'), e('gw', 'orders'), e('orders', 'fulfil', { async: true }), e('plan', 'fulfil', { async: true })],
    flows: [
      { name: 'Promise', path: ['shopper', 'gw', 'promise', 'plan'], steps: ['Shopper views an item', 'The web tier asks for a delivery promise', 'The promise uses stock by warehouse and the network plan'] },
      { name: 'Keep it', path: ['orders', 'fulfil'], steps: ['The order is assigned to a warehouse that can meet the promise'] },
    ],
    problem: <p>“In stock” is not enough. Shoppers decide based on when the item will arrive. A wrong promise means a late package and a lost customer.</p>,
    decision: <p>A <strong>promise service</strong> combines stock per warehouse, transport routes, and cut-off times into a delivery date. Orders go to a warehouse that can keep that promise.</p>,
    tradeoff: <p>Computing promises for every page view is expensive. Too cautious loses sales; too optimistic breaks trust.</p>,
    realWorld: <p>Amazon Science wrote in 2022 that its Supply Chain Optimization Technologies team computes the delivery promises shoppers see. It said these systems optimize millions of promises every second.</p>,
    walkthrough: [
      'The page asks for a promise for this item and address.',
      'The service finds warehouses with stock that can reach the address.',
      'It adds pick, pack, and transport time plus cut-offs.',
      'The fastest reliable option becomes the promise shown.',
      'At order time, the order is assigned to a warehouse that can meet it.',
    ],
    numbers: [
      { label: 'Promises optimized', value: 'millions / s', note: 'Amazon Science, 2022' },
      { label: 'Fulfillment plans', value: 'billions / day', note: 'Amazon Science, 2022' },
      { label: 'Inventory updates tracked', value: '> 1B / day', note: 'Amazon Science, 2022' },
    ],
    components: [
      { name: 'Promise service', role: 'Turns stock and network state into a delivery date.' },
      { name: 'Fulfillment planner', role: 'Decides which warehouses should serve which areas.' },
    ],
    alternatives: [
      { option: 'Fixed “ships in 3–5 days” text', verdict: 'Cheap, but loses to precise promises.' },
      { option: 'Compute only at checkout', verdict: 'Fewer calls, but shoppers choose before checkout.' },
    ],
    breaksNext: <p>The loop continues: new pressure, new split, new isolation.</p>,
    interview: { q: 'How would you cache delivery promises?', a: <p>Cache by item, region, and time bucket, and expire on stock or cut-off changes. Recheck at checkout.</p> },
    sources: [S.scot],
  },
]
