import type { EpisodeStage } from '../../components/ui'
import { W_CORE_EDGES, WN, wAs, we } from './episode-whatsapp-stage-nodes'
import { WHATSAPP_SRC as S } from './episode-whatsapp-sources'

// Stages 7–12: acquisition through encrypted backups. Numbers are from the cited sources unless marked "estimate".
export const WHATSAPP_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'v6 · Acquired, kept independent',
    era: 'Feb 2014',
    scale: '450M+ monthly users · 1M new per day',
    summary: 'A new owner buys the company but leaves the product and its lean architecture alone.',
    nodes: [WN.sender, WN.chat, WN.mnesia, WN.backend, WN.queue, WN.media, WN.recv],
    edges: [...W_CORE_EDGES, we('chat', 'mnesia'), we('chat', 'backend'), we('sender', 'media'), we('media', 'recv')],
    flows: [{ name: 'Send', path: ['sender', 'chat', 'recv'], steps: ['Same path as before the deal', 'Delivery works exactly as it did'] }],
    problem: <p>A huge acquisition could easily trigger a rewrite onto the parent company’s stack, stalling a product that is still growing fast.</p>,
    decision: <p>Keep WhatsApp operating <strong>independently</strong>, with its own app, team, and systems. Migrate infrastructure later, on its own schedule.</p>,
    tradeoff: <p>Two infrastructures to run in parallel for years. The cost of not integrating is deferred, not avoided.</p>,
    realWorld: <p>Facebook announced the deal on February 19, 2014. WhatsApp then had over 450 million monthly users, about 70% active daily, and added over a million registrations a day.</p>,
    walkthrough: ['Nothing changes on the message path.', 'Teams keep shipping on the existing Erlang stack.', 'Integration work is planned separately from product work.'],
    numbers: [{ label: 'Monthly users', value: '450M+', note: 'Feb 2014' }, { label: 'Daily active', value: '≈ 70%', note: 'of monthly users' }],
    components: [{ name: 'Status quo architecture', role: 'The system that worked stays in place while ownership changes.' }],
    alternatives: [{ option: 'Immediate rewrite onto the parent’s stack', verdict: 'High risk during hypergrowth for no user benefit.' }],
    breaksNext: <p>With a billion users, privacy becomes a core product promise, not a feature.</p>,
    interview: { q: 'How do you plan a migration after an acquisition?', a: <p>Separate it from product work, migrate one layer at a time, and keep a rollback path at each step.</p> },
    sources: [S.acquisition, S.wiki],
  },
  {
    title: 'v7 · End-to-end encryption',
    era: 'Apr 2016',
    scale: '1B+ monthly users',
    summary: 'Encrypt on the phone so the server relays messages it cannot read.',
    added: ['keys'],
    nodes: [WN.sender, WN.chat, WN.keys, WN.queue, WN.media, WN.recv],
    edges: [...W_CORE_EDGES, we('sender', 'keys'), we('sender', 'media'), we('media', 'recv')],
    flows: [
      { name: 'Keys', path: ['sender', 'keys'], steps: ['Sender fetches the recipient’s public keys once to start a session'] },
      { name: 'Send', path: ['sender', 'chat', 'recv'], steps: ['Sender encrypts on the phone and uploads ciphertext', 'Server forwards bytes it cannot decrypt'] },
    ],
    problem: <p>Messages pass through the company’s servers. Users need a guarantee that nobody else, including the operator, can read them.</p>,
    decision: <p>Adopt the <strong>Signal Protocol</strong> for every chat, call, and attachment. Servers store only public keys and relay ciphertext.</p>,
    tradeoff: <p>The server can no longer search, scan, or recover content. Features like backups and multiple devices become much harder.</p>,
    realWorld: <p>WhatsApp and Signal announced on April 5, 2016 that the integration was complete, covering over a billion monthly users.</p>,
    walkthrough: ['Each phone registers public identity and one-time keys with the server.', 'A sender fetches the recipient’s keys and sets up a session.', 'Each message is encrypted with a fresh key from that session.', 'The server stores and forwards only ciphertext.'],
    numbers: [{ label: 'Users covered', value: '1B+', note: 'Apr 2016' }, { label: 'Server can read', value: 'nothing', note: 'by design' }],
    components: [{ name: 'Key directory', role: 'Public keys only, so the server can connect people without holding secrets.' }, { name: 'Signal Protocol', role: 'Per-message keys give forward secrecy.' }],
    alternatives: [{ option: 'Transport encryption only (TLS)', verdict: 'Protects the wire, not the server.' }, { option: 'Opt-in secret chats', verdict: 'Most users never switch them on.' }],
    breaksNext: <p>Encrypting a group message separately for every member gets expensive in big groups.</p>,
    interview: { q: 'What does the server still know under E2EE?', a: <p>Metadata such as who talks to whom and when, plus public keys. Content stays on the devices.</p> },
    sources: [S.signal, S.e2ee, S.whitepaper],
  },
  {
    title: 'v8 · Groups with Sender Keys',
    era: '2016',
    scale: 'groups up to about 1,000 members',
    summary: 'Encrypt a group message once and let the server copy that one ciphertext to everyone.',
    nodes: [WN.sender, WN.chat, WN.keys, WN.queue, WN.recv],
    edges: [...W_CORE_EDGES, we('sender', 'keys')],
    flows: [
      { name: 'Share key', path: ['sender', 'chat', 'recv'], steps: ['Sender sends its sender key to each member, pairwise-encrypted', 'Members store it for future messages'] },
      { name: 'Group send', path: ['sender', 'chat', 'queue'], steps: ['Sender uploads one ciphertext', 'Server fans it out to every member, queueing for those offline'] },
    ],
    problem: <p>With pairwise encryption, a message to a 200-person group means 200 separate encryptions and uploads from one phone.</p>,
    decision: <p>Use <strong>Sender Keys</strong>. Each member shares a sender key once, over pairwise sessions. Afterwards each message is encrypted once and the server fans it out.</p>,
    tradeoff: <p>When someone leaves, keys must be rotated and redistributed. Sender Keys also lack the self-healing of pairwise sessions.</p>,
    realWorld: <p>The whitepaper describes this scheme: a one-time pairwise distribution, then a single signed ciphertext per message with <strong>server-side fan-out</strong>.</p>,
    walkthrough: ['First message: sender creates a chain key and signing key.', 'It sends them to each member over pairwise sessions.', 'Each later message: derive a key, encrypt once, sign, upload.', 'Server copies the ciphertext to every member.'],
    numbers: [{ label: 'Encryptions per message', value: '1', note: 'after key setup' }, { label: 'Practical group size', value: '≈ 1,000', note: 'Sender Keys article' }],
    components: [{ name: 'Sender key', role: 'A hash-ratcheted chain key per sender, per group.' }, { name: 'Server fan-out', role: 'The server copies one ciphertext instead of the phone uploading many.' }],
    alternatives: [{ option: 'Client fan-out for every message', verdict: 'Cost grows with group size on the sender’s phone.' }, { option: 'One shared group key', verdict: 'Weak forward secrecy and hard membership changes.' }],
    breaksNext: <p>The encrypted system must eventually move into the parent’s data centers without breaking any guarantee.</p>,
    interview: { q: 'Why do Sender Keys struggle with churny groups?', a: <p>Every leave forces all members to rotate and redistribute their sender keys pairwise.</p> },
    sources: [S.senderKeys, S.whitepaper],
  },
  {
    title: 'v9 · Into Meta’s data centers',
    era: 'After 2014 (exact date not public)',
    scale: 'billions of users',
    summary: 'Move from the original FreeBSD fleet onto the parent company’s shared infrastructure.',
    added: ['meta'],
    nodes: [WN.sender, wAs(WN.chat, 'Chat servers', 'Erlang'), WN.keys, WN.queue, WN.meta, WN.recv],
    edges: [...W_CORE_EDGES, we('sender', 'keys'), we('chat', 'meta')],
    flows: [{ name: 'Send', path: ['sender', 'chat', 'recv'], steps: ['Same protocol and encryption', 'Now running on shared data-center infrastructure'] }],
    problem: <p>Running a separate fleet duplicates hardware, tooling, and on-call work that the parent company already has at huge scale.</p>,
    decision: <p>Migrate servers into the parent’s data centers and operating system, while keeping the Erlang application and the encryption design.</p>,
    tradeoff: <p>Years of careful tuning for FreeBSD must be redone on a new platform, without any user-visible regression.</p>,
    realWorld: <p>Wikipedia notes WhatsApp originally ran Erlang on FreeBSD and now runs on Red Hat-based systems inside Meta’s infrastructure. The exact migration dates are not public.</p>,
    walkthrough: ['Stand up the Erlang services on the new platform.', 'Shift traffic gradually while watching connection and latency metrics.', 'Retire the old fleet once parity is proven.'],
    numbers: [{ label: 'Monthly users', value: '3B', note: 'May 2025, Wikipedia' }],
    components: [{ name: 'Shared infrastructure', role: 'Common hardware, networking, and tooling across the parent’s apps.' }],
    alternatives: [{ option: 'Keep a separate fleet forever', verdict: 'Duplicated cost and expertise.' }],
    breaksNext: <p>People want WhatsApp on laptops and tablets, even when the phone is off.</p>,
    interview: { q: 'How do you migrate platforms without regressions?', a: <p>Define parity metrics first, shift traffic in small steps, and keep instant rollback until the old fleet is gone.</p> },
    sources: [S.wiki],
  },
  {
    title: 'v10 · Multi-device',
    era: 'Jul 2021 → Apr 2023',
    scale: 'phone + up to 4 companions',
    summary: 'Give every device its own keys; the sender encrypts separately for each device.',
    added: ['companion'],
    nodes: [WN.sender, WN.companion, WN.chat, WN.keys, WN.queue, WN.recv],
    edges: [...W_CORE_EDGES, we('sender', 'keys'), we('chat', 'companion')],
    flows: [
      { name: 'Send', path: ['sender', 'chat', 'recv'], steps: ['Sender encrypts once per recipient device', 'Server routes each copy to its device'] },
      { name: 'Companion', path: ['sender', 'chat', 'companion'], steps: ['Sender also encrypts for its own linked devices', 'The laptop gets its copy even if the phone goes offline'] },
    ],
    problem: <p>Laptops and tablets used to mirror the phone, so they stopped working when the phone’s battery died. But E2EE rules out keeping readable copies on the server.</p>,
    decision: <p>Every device gets its <strong>own identity key</strong>. The server keeps a list of each account’s devices. Senders encrypt a copy per device (client fan-out).</p>,
    tradeoff: <p>More encryptions per message, and devices must verify each other. New devices get history via an encrypted bundle from the phone, not the server.</p>,
    realWorld: <p>A July 2021 Meta engineering post describes per-device identity keys, client fan-out, and up to four companion devices. Wikipedia notes the rollout to all users by April 2023.</p>,
    walkthrough: ['User links a laptop by scanning a QR code.', 'The laptop registers its own identity key.', 'Senders fetch the full device list and encrypt for each device.', 'The phone sends recent history to the laptop in an encrypted bundle.'],
    numbers: [{ label: 'Companion devices', value: 'up to 4', note: 'Meta, 2021' }, { label: 'Copies per 1:1 message', value: 'one per device', note: 'client fan-out' }],
    components: [{ name: 'Device list', role: 'The server maps each account to all its device identities.' }, { name: 'History sync', role: 'Phone-to-device transfer, encrypted end to end.' }],
    alternatives: [{ option: 'Keep the phone as a relay', verdict: 'Breaks whenever the phone is offline.' }, { option: 'Store readable history on servers', verdict: 'Breaks the E2EE promise.' }],
    breaksNext: <p>With history living only on devices, losing your phone means losing your chats, unless backups are also encrypted.</p>,
    interview: { q: 'How does multi-device change fan-out?', a: <p>Each message becomes one ciphertext per device. Costs scale with total devices, not just people.</p> },
    sources: [S.multiDevice, S.wiki],
  },
  {
    title: 'v11 · Encrypted backups',
    era: 'Sep 2021',
    scale: 'backups to the user’s cloud storage',
    summary: 'Encrypt chat backups with a key only the user can unlock, guarded by hardware security modules.',
    added: ['vault', 'backup'],
    nodes: [WN.sender, WN.chat, WN.keys, WN.recv, WN.vault, WN.backup],
    edges: [we('sender', 'chat'), we('chat', 'recv'), we('sender', 'keys'), we('sender', 'backup'), we('sender', 'vault')],
    flows: [
      { name: 'Backup', path: ['sender', 'backup'], steps: ['Phone encrypts the chat history and uploads the blob'] },
      { name: 'Restore', path: ['sender', 'vault'], steps: ['New phone proves the password; the vault releases the key or locks after too many tries'] },
    ],
    problem: <p>End-to-end encryption protects messages in transit, but plain backups in cloud storage would leak them. Users still need a way to restore.</p>,
    decision: <p>Encrypt backups on the phone. Protect the key with a <strong>64-digit key</strong> the user keeps, or a password checked by an <strong>HSM-based vault</strong> that locks after limited attempts.</p>,
    tradeoff: <p>Forget both the password and the key, and the backup is gone for good. There is no recovery desk that can help.</p>,
    realWorld: <p>Meta described the HSM-based Backup Key Vault in September 2021. Neither WhatsApp nor the backup provider can read the backup or its key.</p>,
    walkthrough: ['Phone generates a random backup key.', 'It encrypts the history and uploads the blob to cloud storage.', 'The key is stored in the vault, gated by the user’s password.', 'On restore, the vault verifies the password and releases the key.'],
    numbers: [{ label: 'Manual key length', value: '64 digits', note: 'Meta, 2021' }, { label: 'Password guesses', value: 'limited', note: 'then the key is inaccessible' }],
    components: [{ name: 'Backup Key Vault', role: 'Hardware security modules that store keys and enforce guess limits.' }, { name: 'Encrypted blob', role: 'Stored with a third-party cloud provider, unreadable to them.' }],
    alternatives: [{ option: 'Unencrypted cloud backups', verdict: 'A side door around end-to-end encryption.' }, { option: 'Key held by the company', verdict: 'Recoverable, but breaks the promise.' }],
    breaksNext: <p>Every new feature, from channels to AI, must now fit around keys that live only on devices.</p>,
    interview: { q: 'How can a server protect a password it never sees in plain form?', a: <p>Keep the check inside tamper-resistant HSMs with a strict attempt limit, so brute force is impossible even for the operator.</p> },
    sources: [S.backups],
  },
]
