import type { EpisodeStage } from '../../components/ui'
import { SN as N, se as e } from './episode-stripe-nodes'
import { STRIPE_SRC as S } from './episode-stripe-sources'

export const STRIPE_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'v0 · One charge endpoint',
    era: '2011',
    scale: 'A few merchants · ~1 payment/s (estimate)',
    summary: 'A developer sends one HTTP request, and a card gets charged.',
    nodes: [N.merchant, N.api, N.db, N.psp],
    edges: [e('merchant', 'api'), e('api', 'db'), e('api', 'psp')],
    flows: [{ name: 'Charge', path: ['merchant', 'api', 'psp'], steps: ['Merchant sends the card and amount', 'API asks the card processor and returns its answer'] }],
    problem: <p>Taking cards online meant weeks of bank paperwork and awkward processor integrations. Developers wanted a single, clean API call.</p>,
    decision: <p>A small REST API in front of one card processor. Save each payment as a database row. Return the processor’s answer right away.</p>,
    tradeoff: <p>It ships fast. But every network hiccup becomes a money bug, and one processor is a single point of failure.</p>,
    realWorld: <p>Stripe says it has kept every version of its API compatible since the company started in 2011. The API itself was the product.</p>,
    walkthrough: [
      'The merchant’s server sends POST /charges with a card and an amount.',
      'The API validates the input and inserts a payment row.',
      'The API calls the card processor and waits for approve or decline.',
      'The API updates the row and returns the result to the merchant.',
    ],
    numbers: [
      { label: 'API calls to charge', value: '1' },
      { label: 'Payment rate', value: '~1/s', note: 'estimate for an early launch' },
      { label: 'Processors', value: '1', note: 'single point of failure' },
    ],
    components: [
      { name: 'Payments API', role: 'Authenticates the merchant key, validates input, and calls the processor.' },
      { name: 'Payments DB', role: 'One row per payment with its current status.' },
    ],
    alternatives: [
      { option: 'Hosted payment page only', verdict: 'Easier for compliance, but developers lose control of the checkout.' },
      { option: 'SDKs per language first', verdict: 'An HTTP API works from any language; SDKs can wrap it later.' },
    ],
    breaksNext: <p>The merchant’s request times out. Did the charge happen? They retry, and the customer may pay twice.</p>,
    interview: { q: 'What is the hardest part of a “simple” charge API?', a: <p>The unknown outcome. A timeout does not tell you whether money moved, so the API needs a way to retry safely.</p> },
    sources: [S.versioning],
  },
  {
    title: 'v1 · Safe retries',
    era: 'Design step',
    scale: 'Thousands of merchants',
    summary: 'Every write carries a key, so a retry returns the first answer instead of charging again.',
    added: ['idem'],
    nodes: [N.merchant, N.api, N.idem, N.db, N.psp],
    edges: [e('merchant', 'api'), e('api', 'idem'), e('api', 'db'), e('api', 'psp')],
    flows: [{ name: 'Retry', path: ['merchant', 'api', 'idem'], steps: ['Merchant retries with the same Idempotency-Key', 'API finds the key and replays the stored response'] }],
    problem: <p>A request times out and the merchant retries. The customer is charged twice. Timeouts are ambiguous, so blind retries are dangerous.</p>,
    decision: <p>Accept an <strong>idempotency key</strong> on every write. Store the key with the first response and replay it on retries. Model each payment as a <strong>state machine</strong> so each step happens once.</p>,
    tradeoff: <p>Every write needs an extra lookup. Keys must live longer than any sane retry window. A reused key with a different body must be rejected.</p>,
    realWorld: <p>Stripe accepts an <code>Idempotency-Key</code> on every POST. It saves the status code and body of the first request, including errors, and may prune keys after 24 hours.</p>,
    walkthrough: [
      'The merchant generates a random key (for example a UUID) for this charge.',
      'The API tries to claim the key atomically before doing anything with side effects.',
      'If the key is new, the charge runs and the final response is saved under the key.',
      'If the key exists with the same body, the saved response is returned. No second charge.',
      'If the key exists with a different body, the API returns an error.',
    ],
    numbers: [
      { label: 'Key retention', value: '≥ 24 h', note: 'Stripe docs' },
      { label: 'Max key length', value: '255 chars', note: 'Stripe docs' },
      { label: 'Extra lookups per write', value: '1' },
    ],
    components: [
      { name: 'Idempotency store', role: 'Maps key → request fingerprint → in-flight marker → final response.' },
      { name: 'Payment state machine', role: 'created → processing → succeeded or failed. Transitions are conditional writes.' },
    ],
    alternatives: [
      { option: 'Server-side dedupe by amount + card + time', verdict: 'Guesses intent. Two real purchases of the same item would be merged.' },
      { option: 'Tell merchants not to retry', verdict: 'Networks fail anyway. Merchants would lose sales or double-charge.' },
    ],
    breaksNext: <p>Some outcomes arrive minutes or days later. Merchants poll constantly and still miss changes.</p>,
    interview: { q: 'When exactly should the idempotency key be claimed?', a: <p>Before any side effect, in one atomic step (put-if-absent). Claiming after the processor call leaves a window for duplicates.</p> },
    sources: [S.idemDocs, S.idemBlog],
  },
  {
    title: 'v2 · Events and webhooks',
    era: 'Design step',
    scale: 'Async payment methods, disputes',
    summary: 'Every change becomes an event, and merchants get pushed a signed notification.',
    added: ['events', 'hooks'],
    nodes: [N.merchant, N.api, N.idem, N.db, N.psp, N.events, N.hooks],
    edges: [e('merchant', 'api'), e('api', 'idem'), e('api', 'db'), e('api', 'psp'), e('api', 'events', { async: true }), e('events', 'hooks'), e('hooks', 'merchant', { label: 'POST', async: true })],
    flows: [{ name: 'Notify', path: ['api', 'events', 'hooks', 'merchant'], steps: ['A state change is appended to the event log', 'The webhook sender picks it up', 'Signed POST to the merchant, retried until it gets a 2xx'] }],
    problem: <p>Many results arrive later: bank debits that settle in days, disputes weeks afterward. Polling wastes both sides and still misses changes.</p>,
    decision: <p>Record each state change as an immutable <strong>event</strong>. A delivery service pushes <strong>signed webhooks</strong> and retries with backoff. Delivery is at-least-once, so merchants dedupe by event id.</p>,
    tradeoff: <p>Events can arrive out of order or twice. Merchants must verify signatures. You now run a retry queue for millions of flaky endpoints.</p>,
    realWorld: <p>Stripe signs webhooks with a <code>Stripe-Signature</code> header and retries live deliveries for up to three days with exponential backoff. Its docs say event order is not guaranteed.</p>,
    walkthrough: [
      'The payment changes state, and the API appends an event in the same transaction.',
      'A delivery worker reads new events and signs each payload with the endpoint’s secret.',
      'It POSTs to the merchant and waits for a 2xx response.',
      'On failure it schedules a retry with exponential backoff.',
      'The merchant verifies the signature, checks the event id, and processes it once.',
    ],
    numbers: [
      { label: 'Retry window (live)', value: 'up to 3 days', note: 'Stripe docs' },
      { label: 'Delivery guarantee', value: 'at-least-once' },
      { label: 'Ordering', value: 'not guaranteed', note: 'Stripe docs' },
    ],
    components: [
      { name: 'Event log', role: 'Append-only record of every state change; the source for webhooks.' },
      { name: 'Webhook sender', role: 'Signs, delivers, and retries notifications per endpoint.' },
    ],
    alternatives: [
      { option: 'Polling APIs only', verdict: 'Simple, but slow to notice changes and costly at scale.' },
      { option: 'Exactly-once delivery', verdict: 'Not achievable over HTTP to third parties. Dedupe on the receiver instead.' },
    ],
    breaksNext: <p>Platforms like marketplaces need to pay many sellers, not just accept money.</p>,
    interview: { q: 'How should a merchant handle a duplicate webhook?', a: <p>Store processed event ids and skip repeats. Make the handler idempotent, and fetch the latest object if order matters.</p> },
    sources: [S.webhooks],
  },
  {
    title: 'v3 · Platforms and payouts',
    era: '2012',
    scale: 'Marketplaces with many sellers',
    summary: 'A platform takes a payment and routes the money to the right seller’s bank.',
    added: ['sellers', 'payouts', 'bank'],
    nodes: [N.platform, N.sellers, N.api, N.idem, N.db, N.psp, N.events, N.hooks, N.payouts, N.bank],
    edges: [e('merchant', 'api'), e('sellers', 'api', { label: 'onboard' }), e('api', 'idem'), e('api', 'db'), e('api', 'psp'), e('api', 'events', { async: true }), e('events', 'hooks'), e('hooks', 'merchant', { async: true }), e('db', 'payouts'), e('payouts', 'bank', { async: true })],
    flows: [{ name: 'Split + payout', path: ['merchant', 'api', 'db', 'payouts', 'bank'], steps: ['Platform charges a customer on behalf of a seller', 'API records the charge and the seller’s share', 'The seller’s balance feeds the payout scheduler', 'Payout batches go out over bank rails'] }],
    problem: <p>Marketplaces must accept money from buyers and pay many sellers. Paying out adds identity checks, tax reporting, and slow bank transfers.</p>,
    decision: <p>Model <strong>connected accounts</strong> for each seller. A charge can be split between platform and seller. A payout scheduler moves each seller’s balance to their bank.</p>,
    tradeoff: <p>Balances now matter as much as charges. Bank transfers fail days later, so payouts need their own state machine.</p>,
    realWorld: <p>Stripe launched Connect in 2012 for platforms. By 2024 it said Connect supports platforms serving more than eight million businesses.</p>,
    walkthrough: [
      'The seller onboards through the platform and gets a connected account.',
      'A buyer pays; the charge names the seller and the platform’s fee.',
      'The seller’s share becomes pending, then available balance.',
      'On schedule, available balance is batched into a payout to the seller’s bank.',
    ],
    numbers: [
      { label: 'Connect launched', value: '2012', note: 'Stripe blog' },
      { label: 'Businesses served via platforms', value: '8M+', note: 'Stripe, 2024' },
    ],
    components: [
      { name: 'Connected accounts', role: 'One account per seller, with its own balance and bank details.' },
      { name: 'Payouts', role: 'Batches available balances into bank transfers with a state machine.' },
    ],
    alternatives: [
      { option: 'Platform pays sellers manually', verdict: 'Works for ten sellers, not ten thousand, and mixes funds.' },
      { option: 'Balance column on each account', verdict: 'Fast to build, but updates get lost and nothing is auditable.' },
    ],
    breaksNext: <p>Balances drift from reality. Fees, refunds, and disputes settle differently from what was recorded.</p>,
    interview: { q: 'Why do payouts need their own state machine?', a: <p>Bank transfers are slow and can fail days later. Paid, failed, and returned must be tracked and reconciled.</p> },
    sources: [S.connect, S.marketplace],
  },
  {
    title: 'v4 · A ledger you can trust',
    era: 'Design step',
    scale: 'Real money at scale',
    summary: 'Every money movement is written twice, as a debit and a matching credit, and never edited.',
    added: ['ledger', 'recon'],
    nodes: [N.merchant, N.apiIdem, N.db, N.psp, N.events, N.hooks, N.ledger, N.recon, N.payouts, N.bank],
    edges: [e('merchant', 'api'), e('api', 'db'), e('api', 'psp'), e('api', 'events', { async: true }), e('events', 'hooks'), e('db', 'ledger'), e('psp', 'recon', { label: 'settlement file', async: true }), e('recon', 'ledger'), e('ledger', 'payouts'), e('payouts', 'bank', { async: true })],
    flows: [{ name: 'Reconcile', path: ['psp', 'recon', 'ledger'], steps: ['The processor sends its daily settlement report', 'Reconciliation matches each line to ledger entries and flags gaps'] }],
    problem: <p>Balances computed from mutable rows drift. Fees, refunds, currency conversion, and disputes settle differently. Finance cannot close the books.</p>,
    decision: <p>An append-only <strong>double-entry ledger</strong> becomes the source of truth. Every movement is balanced debits and credits. Daily <strong>reconciliation</strong> compares it with processor and bank reports.</p>,
    tradeoff: <p>Corrections are new entries, never edits. The ledger writes several times more rows than there are payments.</p>,
    realWorld: <p>Stripe’s 2024 post describes Ledger as an immutable, double-entry log that sees about five billion events per day. It flags “clearing” accounts that should be empty but are not.</p>,
    walkthrough: [
      'A payment succeeds; the workflow writes balanced entries (customer funds, fees, merchant balance).',
      'Intermediate “clearing” accounts should return to zero once money finishes moving.',
      'Each day, processor and bank reports are loaded and matched to ledger entries.',
      'Unmatched lines or non-zero clearing accounts open exceptions for humans.',
    ],
    numbers: [
      { label: 'Ledger events per day', value: '~5 billion', note: 'Stripe, 2024' },
      { label: 'Dollar volume verified within 4 days', value: '99.99%', note: 'Stripe, 2024' },
      { label: 'Invariant', value: 'Σ debits = Σ credits' },
    ],
    components: [
      { name: 'Ledger', role: 'Immutable double-entry records; balances are derived, never stored as truth.' },
      { name: 'Reconciliation', role: 'Matches external reports to entries and raises exceptions.' },
    ],
    alternatives: [
      { option: 'Balance column with UPDATEs', verdict: 'Lost updates and no history. Auditors cannot trace money.' },
      { option: 'Recompute from payments table', verdict: 'Payments rows drive workflow; they do not model fees or FX.' },
    ],
    breaksNext: <p>Fraudsters start testing stolen cards in bursts, and chargebacks pile up.</p>,
    interview: { q: 'How do you fix a wrong ledger entry?', a: <p>Never edit it. Post a reversing entry and a correct one, so the history explains every change.</p> },
    sources: [S.ledger],
  },
  {
    title: 'v5 · Fraud in the hot path',
    era: '2016',
    scale: 'Card-testing attacks, chargebacks',
    summary: 'Every charge is scored for fraud in milliseconds before it reaches the card network.',
    added: ['risk'],
    nodes: [N.merchant, N.apiIdem, N.db, N.risk, N.psp, N.eventsHooks, N.ledger, N.recon, N.payoutsBank],
    edges: [e('merchant', 'api'), e('api', 'db'), e('api', 'risk'), e('risk', 'psp'), e('api', 'events', { async: true }), e('events', 'merchant', { async: true }), e('db', 'ledger'), e('psp', 'recon', { async: true }), e('recon', 'ledger'), e('ledger', 'payouts')],
    flows: [{ name: 'Charge', path: ['merchant', 'api', 'risk', 'psp'], steps: ['Charge request arrives', 'Risk scores it with network-wide signals', 'Allowed charges go on to the processor'] }],
    problem: <p>Fraudsters test stolen cards in bursts. Each chargeback costs fees plus the goods. Blocking too much loses real customers.</p>,
    decision: <p>Score every charge <strong>inline</strong> with a machine-learning model plus merchant rules, under a strict time budget. If the model is slow, rules decide alone.</p>,
    tradeoff: <p>A little latency and some false declines, in exchange for lower fraud loss. Features must be fresh enough to catch an attack mid-burst.</p>,
    realWorld: <p>Stripe launched Radar in 2016. It said a card new to a business had an 80% chance of having been seen elsewhere on Stripe. Radar 2.0 (2018) retrains models nightly.</p>,
    walkthrough: [
      'The API builds features: card, device, amount, and the card’s history across the network.',
      'The model returns a risk score within a few milliseconds.',
      'Merchant rules combine the score with their own limits.',
      'Low risk goes to the processor. High risk is blocked or sent for review.',
      'Later chargebacks become labels for the next training run.',
    ],
    numbers: [
      { label: 'Card seen before on network', value: '80%', note: 'Stripe, 2016' },
      { label: 'Fraud reduction, Radar 2.0 models', value: '>25%', note: 'vs prior models, Stripe 2018' },
      { label: 'Model retraining', value: 'nightly', note: 'Stripe 2018' },
    ],
    components: [
      { name: 'Risk scoring', role: 'Model + rules with a hard timeout and a rules-only fallback.' },
      { name: 'Feature store', role: 'Network-wide counters and history, updated in near real time.' },
    ],
    alternatives: [
      { option: 'Score after authorization', verdict: 'Cheaper latency, but fraud already reached the card network.' },
      { option: 'Rules only', verdict: 'Easy to explain, but attackers adapt faster than humans write rules.' },
    ],
    breaksNext: <p>Raw card numbers still pass through merchant servers, pulling them into strict security audits.</p>,
    interview: { q: 'What happens when the fraud model times out?', a: <p>Fail to a simpler path, such as rules only, within the budget. Never block every charge because one dependency is slow.</p> },
    sources: [S.radarPrimer, S.radar2],
  },
]
