import type { EpisodeStage } from '../../components/ui'
import { FRONT, IN, ie, shards } from './episode-instagram-stage-nodes'
import { IG_SRC as S } from './episode-instagram-sources'

// Stages 7–12: multiple data centers through Reels.
export const INSTAGRAM_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'v6 · From one data center to three',
    era: '2015–2016',
    scale: 'hundreds of millions of users',
    summary: 'Run in several data centers by separating data every region needs from data that can stay local.',
    added: ['dc'],
    nodes: [IN.client, IN.lb, IN.web, shards, IN.cdn, IN.s3, IN.redis, IN.cass, IN.dc],
    edges: [...FRONT, ie('web', 'pg'), ie('web', 's3'), ie('client', 'cdn'), ie('cdn', 's3'), ie('web', 'redis'), ie('web', 'cass'), ie('pg', 'dc', { label: 'replication', async: true })],
    flows: [
      { name: 'Write', path: ['client', 'lb', 'web', 'pg'], steps: ['User likes a photo', 'Request reaches the nearest app servers', 'Write goes to the shard’s primary'] },
      { name: 'Replicate', path: ['pg', 'dc'], steps: ['Primary ships changes to replicas in other data centers'] },
    ],
    problem: <p>A single data center is a single disaster domain. Capacity is only available where Facebook has room.</p>,
    decision: <p>Split data into <strong>global</strong> (replicated everywhere) and <strong>local</strong> (stays in one region, like queued jobs). Replicate databases across sites.</p>,
    tradeoff: <p>Tens of milliseconds between sites hurt database replication and cross-site writes.</p>,
    realWorld: <p>Instagram went from one to three data centers in 2015. Its 2016 “Instagration Pt. 2” post explains the global vs local data split and how cross-site latency affected Postgres replication.</p>,
    walkthrough: ['Each data center runs app servers, caches, and replicas.', 'Reads are served locally.', 'Writes go to the primary for that shard.', 'Background jobs run where they were created.'],
    numbers: [{ label: 'Data centers', value: '1 → 3', note: '2015, Opensource.com' }, { label: 'Cross-site latency', value: 'tens of ms', note: 'example in the 2016 post' }],
    components: [{ name: 'Global vs local data', role: 'Decides what must replicate and what may differ per region.' }],
    alternatives: [{ option: 'Active-passive standby', verdict: 'Idle capacity and untested failover.' }, { option: 'Stay single-site', verdict: 'One outage takes everything down.' }],
    breaksNext: <p>A reverse-chronological feed buries posts people care about.</p>,
    interview: { q: 'What changes when you add a second data center?', a: <p>Classify data as global or local, decide where writes go, and design for replication lag in the product.</p> },
    sources: [S.europe, S.multiDc, S.scalingTalk],
  },
  {
    title: 'v7 · Ranked feed',
    era: 'Mar 2016',
    scale: 'people missed ~70% of their feed',
    summary: 'Order the feed by predicted interest instead of time.',
    added: ['feed'],
    nodes: [IN.client, IN.lb, IN.web, IN.feed, shards, IN.redis, IN.cass, IN.q, IN.workers, IN.cdn],
    edges: [...FRONT, ie('web', 'feed'), ie('feed', 'redis'), ie('feed', 'cass'), ie('feed', 'pg'), ie('web', 'q', { async: true }), ie('q', 'workers'), ie('workers', 'redis'), ie('client', 'cdn')],
    flows: [{ name: 'Open feed', path: ['client', 'lb', 'web', 'feed', 'redis'], steps: ['App opens the feed', 'Request reaches an app server', 'App server asks the feed service', 'Feed service gathers candidates, scores them, and returns the top items'] }],
    problem: <p>Users follow many accounts. In time order, most posts scroll by unseen.</p>,
    decision: <p>Add a <strong>feed service</strong> that collects candidate posts, scores them with a model, and returns the best first.</p>,
    tradeoff: <p>Ranking adds latency and compute per open. Users lose a predictable order.</p>,
    realWorld: <p>Instagram announced the ranked feed on March 15, 2016, noting people missed on average 70% of their feeds.</p>,
    walkthrough: ['Collect candidates from followees (precomputed lists plus pulls).', 'Fetch features for each candidate.', 'Score with a ranking model.', 'Hydrate the top items and return a page.'],
    numbers: [{ label: 'Feed missed (before)', value: '≈ 70%', note: 'Instagram, 2016' }, { label: 'Candidates per open', value: 'hundreds', note: 'estimate' }],
    components: [{ name: 'Feed service', role: 'Candidate generation, scoring, and hydration.' }],
    alternatives: [{ option: 'Keep chronological', verdict: 'Simple, but most content goes unseen.' }, { option: 'Rank on the client', verdict: 'Too much data and model logic on the phone.' }],
    breaksNext: <p>People want to share casual moments that disappear, not permanent posts.</p>,
    interview: { q: 'Design a ranked feed service.', a: <p>Two stages: cheap candidate generation, then expensive scoring on a few hundred items. Cache features and bound latency.</p> },
    sources: [S.feed],
  },
  {
    title: 'v8 · Stories',
    era: 'Aug 2016',
    scale: 'content that expires in 24 hours',
    summary: 'Serve short-lived content from memory and let it expire automatically.',
    added: ['stories'],
    nodes: [IN.client, IN.lb, IN.web, IN.feed, shards, IN.redis, IN.stories, IN.cdn, IN.s3],
    edges: [...FRONT, ie('web', 'feed'), ie('feed', 'redis'), ie('feed', 'pg'), ie('web', 'stories'), ie('client', 'cdn'), ie('cdn', 's3')],
    flows: [{ name: 'Story tray', path: ['client', 'lb', 'web', 'stories'], steps: ['App loads the story tray', 'Request reaches an app server', 'Stories service returns active stories and seen state'] }],
    problem: <p>Stories are read heavily right after posting, then worthless. Per-viewer “seen” state is huge.</p>,
    decision: <p>A dedicated <strong>stories service</strong> keeps active stories and seen markers with <strong>TTLs</strong>. Media still goes through the CDN.</p>,
    tradeoff: <p>Memory-heavy by design. Billions of keys expiring together can cause load spikes.</p>,
    realWorld: <p>Instagram launched Stories in August 2016. Stories disappear after 24 hours.</p>,
    walkthrough: ['Author posts; media goes to storage, metadata to the stories service.', 'Followers’ trays list authors with active stories.', 'Viewing marks a seen watermark per viewer.', 'After 24 hours, TTLs remove the story.'],
    numbers: [{ label: 'Lifetime', value: '24 hours', note: 'Instagram, 2016' }, { label: 'Seen state', value: 'per viewer × author', note: 'design choice' }],
    components: [{ name: 'Stories service', role: 'Active set, tray ordering, seen state.' }],
    alternatives: [{ option: 'Rows plus nightly cleanup', verdict: 'Deletes lag and cost more I/O.' }, { option: 'Reuse the feed service', verdict: 'Different access pattern and lifetime.' }],
    breaksNext: <p>Python web servers use more memory and CPU than they should.</p>,
    interview: { q: 'How would you store “seen” state for Stories?', a: <p>A compact per-viewer, per-author watermark, not a row per story view.</p> },
    sources: [S.stories],
  },
  {
    title: 'v9 · Python at scale',
    era: '2017',
    scale: 'huge Django fleet',
    summary: 'Tune the Python runtime and move the whole codebase to Python 3 without downtime.',
    nodes: [IN.client, IN.lb, { ...IN.web, sub: 'Django · Python 3' }, IN.feed, shards, IN.redis, IN.cass, IN.q, IN.workers],
    edges: [...FRONT, ie('web', 'feed'), ie('feed', 'redis'), ie('feed', 'cass'), ie('feed', 'pg'), ie('web', 'q', { async: true }), ie('q', 'workers')],
    flows: [{ name: 'Request', path: ['client', 'lb', 'web', 'feed'], steps: ['App makes an API call', 'Load balancer picks a worker process', 'Worker handles it and calls the feed service'] }],
    problem: <p>Forked worker processes lose shared memory as Python’s garbage collector touches objects. Python 2 is nearing end of life.</p>,
    decision: <p>Stop the cyclic <strong>garbage collector</strong> from running in web workers. Make the codebase run on both Python 2 and 3, then switch.</p>,
    tradeoff: <p>Reference cycles are no longer collected automatically. The migration takes months of shared effort.</p>,
    realWorld: <p>Instagram wrote in January 2017 that disabling GC made its web tier about 10% more efficient. The New Stack reports it ran fully on Python 3 by February 2017 after a 10-month migration.</p>,
    walkthrough: ['A master process forks many uWSGI workers.', 'Memory pages are shared until written (copy-on-write).', 'GC writes to object headers, breaking sharing.', 'With GC off, more memory stays shared and caches work better.'],
    numbers: [{ label: 'Efficiency gain', value: '≈ 10%', note: 'GC change, 2017' }, { label: 'Python 3 migration', value: '10 months', note: 'The New Stack' }],
    components: [{ name: 'uWSGI pre-fork', role: 'Master forks workers to share memory.' }],
    alternatives: [{ option: 'Rewrite in another language', verdict: 'Far bigger risk than tuning.' }, { option: 'Separate Python 3 branch', verdict: 'Merge hell; they made master run on both.' }],
    breaksNext: <p>European users suffer high write latency to US master regions.</p>,
    interview: { q: 'How do you run a language migration safely?', a: <p>Make code work on both versions, test both in CI, and ramp traffic gradually.</p> },
    sources: [S.gc, S.python3],
  },
  {
    title: 'v10 · Data centers in Europe',
    era: '2018',
    scale: 'US and EU regions',
    summary: 'Keep European reads and many writes local, instead of crossing the ocean.',
    added: ['eu'],
    nodes: [IN.client, IN.lb, IN.web, IN.feed, shards, IN.cass, IN.eu],
    edges: [...FRONT, ie('web', 'feed'), ie('feed', 'pg'), ie('web', 'cass'), ie('cass', 'eu', { label: 'regional partitions', async: true }), ie('client', 'eu')],
    flows: [
      { name: 'EU user', path: ['client', 'eu'], steps: ['European users are served by EU data centers'] },
      { name: 'Write', path: ['client', 'lb', 'web', 'cass'], steps: ['User writes', 'Request reaches app servers', 'Data is written to a Cassandra partition kept in the user’s region'] },
    ],
    problem: <p>All writes went to a master region in the US. For Europe, write latency is limited by the speed of light.</p>,
    decision: <p><strong>Partition</strong> Cassandra data by region so quorums stay local. Let some writes land locally first, then propagate asynchronously.</p>,
    tradeoff: <p>Users must be mapped to a home region. Cross-region reads may see slightly old data.</p>,
    realWorld: <p>An Instagram engineer described this at LISA 2018: expanding to EU data centers, partitioning Cassandra so quorum requests stay local, and local writes to TAO (Facebook’s graph store).</p>,
    walkthrough: ['Assign each user a home region.', 'Store their Cassandra data with replicas in that region.', 'Quorum reads and writes stay within the region.', 'Global data syncs asynchronously.'],
    numbers: [{ label: 'Regions', value: 'US + EU', note: 'Opensource.com, 2018' }, { label: 'Transatlantic RTT', value: '≈ 70–100 ms', note: 'estimate' }],
    components: [{ name: 'Regional partitions', role: 'Data placed near its users.' }, { name: 'TAO', role: 'Facebook’s graph data store with local writes.' }],
    alternatives: [{ option: 'US master for all writes', verdict: 'Slow for every European write.' }, { option: 'Multi-master everything', verdict: 'Conflict handling everywhere.' }],
    breaksNext: <p>Short-form video becomes the main format, and video bytes dwarf photos.</p>,
    interview: { q: 'How do you cut write latency for a new region?', a: <p>Give users a home region, keep quorums local, and replicate globally in the background.</p> },
    sources: [S.europe],
  },
  {
    title: 'v11 · Reels and smarter encoding',
    era: '2020–2021',
    scale: 'video-first',
    summary: 'Transcode each video into several qualities and spend expensive encoding only where it pays off.',
    added: ['transcode'],
    nodes: [IN.client, IN.cdn, IN.lb, IN.web, IN.feed, IN.q, IN.transcode, IN.s3, IN.redis, shards],
    edges: [...FRONT, ie('web', 'q', { async: true }), ie('q', 'transcode'), ie('transcode', 's3'), ie('client', 'cdn'), ie('cdn', 's3'), ie('web', 'feed'), ie('feed', 'redis'), ie('feed', 'pg')],
    flows: [
      { name: 'Publish reel', path: ['client', 'lb', 'web', 'q', 'transcode', 's3'], steps: ['App uploads the video', 'Request reaches app servers', 'Server enqueues processing', 'Pipeline encodes several bitrates', 'Segments land in storage'] },
      { name: 'Watch', path: ['client', 'cdn', 's3'], steps: ['Player fetches segments from the CDN', 'Misses pull from storage'] },
    ],
    problem: <p>Video is far bigger than photos. Networks change mid-scroll. Encoding everything at top quality is too costly.</p>,
    decision: <p>Encode a <strong>ladder</strong> of qualities for adaptive playback. Use costly advanced codecs only for videos likely to be watched a lot.</p>,
    tradeoff: <p>Compute and storage rise. Predictions can be wrong for a video that suddenly goes viral.</p>,
    realWorld: <p>Instagram launched Reels in August 2020. Meta has described prioritising advanced encodings for Facebook videos by predicted watch time; roughly a third of videos drew most watch time.</p>,
    walkthrough: ['Upload the original.', 'Encode a basic ladder quickly so it can play.', 'Predict future watch time.', 'Re-encode popular videos with a better codec.'],
    numbers: [{ label: 'Reels launch', value: 'Aug 2020', note: 'Instagram' }, { label: 'Watch-time skew', value: '≈ ⅓ of videos → most views', note: 'Facebook video, Meta 2021' }],
    components: [{ name: 'Video pipeline', role: 'Transcode, package, and store segments.' }, { name: 'Priority model', role: 'Benefit ÷ cost decides which videos get advanced encodes.' }],
    alternatives: [{ option: 'Best codec for all', verdict: 'Wastes compute on videos few people watch.' }, { option: 'Single file per video', verdict: 'Stalls on weak networks.' }],
    breaksNext: <p>That is where this episode ends: the next walls are cost and personalization at video scale.</p>,
    interview: { q: 'How do you control video encoding cost?', a: <p>Encode a cheap ladder for everything, then spend on better codecs by predicted watch time.</p> },
    sources: [S.reels, S.encoding],
  },
]
