import type { EpisodeStage } from '../../components/ui'
import { U, ue } from './episode-uber-stage-nodes'
import { UBER_SRC as S } from './episode-uber-sources'

// Stages 7–12: hexagons, tracing, streams, ML, domains, and a transactional core.
export const UBER_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'v7 · Hexagons and surge',
    era: '2018 (H3 open-sourced)',
    scale: 'global',
    summary: 'The world is cut into hexagons, and prices react to supply and demand inside each one.',
    added: ['surge'],
    nodes: [U.rider, U.driver, U.gw, U.surge, U.trips, U.dispatch, U.supply, { ...U.geo, sub: 'H3 hexagons' }, U.eta, U.store],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'surge'), ue('surge', 'geo', { label: 'supply/demand' }), ue('gw', 'trips'), ue('gw', 'supply'),
      ue('supply', 'geo'), ue('dispatch', 'geo'), ue('dispatch', 'eta'), ue('trips', 'dispatch'), ue('trips', 'store')],
    flows: [{ name: 'Price quote', path: ['rider', 'gw', 'surge', 'geo'], steps: ['Rider sets a pickup point', 'The edge asks pricing for a quote', 'Pricing reads supply and demand for that hexagon and its neighbours'] }],
    problem: <p>Pricing needs supply and demand per small area. Square grids and city polygons distort distance, and “neighbouring area” is awkward.</p>,
    decision: <p>Index the world with <strong>H3</strong>, a hierarchical grid of hexagons. Compute surge per hexagon from recent requests and available drivers, then smooth across neighbours.</p>,
    tradeoff: <p>Prices can still jump across a hexagon edge. Surge is also a fairness and policy question, not only an algorithm.</p>,
    realWorld: <p>Uber open-sourced H3 in 2018. Its post says surge is calculated from supply and demand in hexagons, and that a hexagon has a single distance to all its neighbours.</p>,
    walkthrough: [
      'The rider sets a pickup point, and the app asks for a price.',
      'Pricing maps the point to an H3 cell at a chosen resolution.',
      'It reads recent requests and open drivers for that cell and its ring of neighbours.',
      'It returns a multiplier, bounded by policy caps.',
    ],
    numbers: [
      { label: 'Neighbour distances', value: '1', note: 'squares have 2, triangles 3' },
      { label: 'H3 resolutions', value: '16 (0–15)' },
      { label: 'Avg cell, resolution 7', value: '≈ 5.2 km²', note: 'H3 docs' },
      { label: 'Avg cell, resolution 9', value: '≈ 0.1 km²', note: 'H3 docs' },
    ],
    components: [
      { name: 'H3 index', role: 'Maps any point to a cell ID; parents and children nest across resolutions.' },
      { name: 'Pricing service', role: 'Turns per-cell supply and demand into a bounded multiplier.' },
    ],
    alternatives: [
      { option: 'Square cells (e.g. geohash)', verdict: 'Edge and corner neighbours sit at different distances, so smoothing is uneven.' },
      { option: 'City districts', verdict: 'Uneven sizes hide local shortages.' },
    ],
    breaksNext: <p>Every team builds its own pipeline to move events around. The same data is copied many times.</p>,
    interview: {
      q: 'Why use hexagons for geo aggregation?',
      a: <p>Every neighbour is the same distance away, so rings approximate a radius and smoothing is simple. Squares have edge and corner neighbours at different distances.</p>,
    },
    sources: [S.h3, S.h3docs],
  },
  {
    title: 'v6 · Tracing thousands of services',
    era: '2015–2017',
    scale: '~500 services → 2,000+',
    summary: 'Every request carries an ID, so engineers can see its whole path through thousands of services.',
    added: ['jaeger'],
    nodes: [U.rider, U.driver, U.gw, U.trips, U.dispatch, U.eta, U.store, U.svcs, U.jaeger],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'trips'), ue('trips', 'dispatch'), ue('dispatch', 'eta'), ue('trips', 'store'), ue('trips', 'svcs'),
      ue('gw', 'jaeger', { label: 'spans', async: true }), ue('svcs', 'jaeger', { async: true })],
    flows: [{ name: 'Trace a request', path: ['rider', 'gw', 'trips', 'svcs', 'jaeger'], steps: ['The request enters with a new trace ID', 'The edge passes the ID to the trip service', 'Downstream calls carry the same ID', 'Every service reports its timing spans to the tracing backend'] }],
    problem: <p>One rider action fans out across many services. When it is slow, per-service logs cannot show the whole path.</p>,
    decision: <p>Add <strong>distributed tracing</strong>. Each request carries a trace ID, and every service reports timed spans. Engineers see the full call tree and where the time went.</p>,
    tradeoff: <p>Instrumentation must reach every service and library. Traces are sampled, so rare problems can be missed.</p>,
    realWorld: <p>Uber built <strong>Jaeger</strong>, adopted internally in 2016 and open-sourced in 2017. Its post counts about 500 services in late 2015 and over 2,000 by early 2017. Jaeger later graduated in the CNCF.</p>,
    walkthrough: [
      'The edge starts a trace and adds its ID to request headers.',
      'Each service records a span: start, end, and tags.',
      'Client libraries pass the context along on every outgoing call.',
      'Spans are sent asynchronously to collectors, off the request path.',
      'Engineers search traces by ID, service, or latency.',
    ],
    numbers: [
      { label: 'Services, fall 2015', value: '~500' },
      { label: 'Services, early 2017', value: '2,000+' },
      { label: 'Traces recorded (2017)', value: 'thousands/s' },
    ],
    components: [
      { name: 'Tracing libraries', role: 'Create spans and propagate context across calls.' },
      { name: 'Jaeger backend', role: 'Collects, stores, and visualizes traces.' },
    ],
    alternatives: [
      { option: 'Logs with a request ID', verdict: 'Requires manual stitching across services.' },
      { option: 'Zipkin as-is', verdict: 'Uber evaluated it first, but its backend needed technologies Uber did not operate then.' },
    ],
    breaksNext: <p>Pricing needs a consistent way to measure supply and demand everywhere on the map.</p>,
    interview: {
      q: 'How would you debug a slow request in a system with 2,000 services?',
      a: <p>Distributed tracing: propagate a trace ID, collect spans, and look at the critical path. Use metrics to decide which requests to trace, and logs for the details.</p>,
    },
    sources: [S.tracing, S.jaeger],
  },
  {
    title: 'v8 · One event backbone',
    era: 'by 2020 (as described)',
    scale: 'trillions of messages/day',
    summary: 'Events from every region flow through Kafka, then get copied into clusters that see the whole world.',
    added: ['kafka', 'agg'],
    nodes: [U.rider, U.driver, U.gw, U.trips, U.dispatch, U.geo, U.eta, U.store, U.kafka, U.agg],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'trips'), ue('gw', 'dispatch'), ue('dispatch', 'geo'), ue('dispatch', 'eta'), ue('trips', 'store'),
      ue('dispatch', 'kafka', { async: true }), ue('trips', 'kafka', { async: true }), ue('kafka', 'agg', { label: 'replicate', async: true })],
    flows: [{ name: 'Event flow', path: ['driver', 'gw', 'dispatch', 'kafka', 'agg'], steps: ['A driver ping arrives', 'The edge routes it to dispatch', 'Dispatch publishes the event to its region’s Kafka', 'Events are replicated into aggregate clusters with a global view'] }],
    problem: <p>Pings, trip events, and logs feed ETAs, fraud checks, pricing, and analytics. Point-to-point pipelines multiply, and each fails differently.</p>,
    decision: <p>Publish events to <strong>Kafka</strong> in each region. Replicate regional clusters into aggregate clusters that hold a global view. Consumers choose active/active or active/passive reading.</p>,
    tradeoff: <p>Kafka becomes critical shared infrastructure. Replication is asynchronous, so a regional failure can delay or duplicate messages. Consumers must handle both.</p>,
    realWorld: <p>Uber’s 2020 post describes one of the largest Kafka deployments: trillions of messages and petabytes of data per day, replicated with its uReplicator tool.</p>,
    walkthrough: [
      'Services publish events to the Kafka cluster in their region.',
      'uReplicator copies regional topics into aggregate clusters.',
      'Consumers that need a global view read the aggregate cluster.',
      'If a region fails, active/active consumers keep going elsewhere; active/passive ones fail over.',
    ],
    numbers: [
      { label: 'Messages per day (2020)', value: 'trillions' },
      { label: 'Data per day (2020)', value: 'multiple PB' },
    ],
    components: [
      { name: 'Regional clusters', role: 'Low-latency publishing close to producers.' },
      { name: 'Aggregate clusters', role: 'A global copy for consumers that need every region.' },
      { name: 'uReplicator', role: 'Uber’s replication tool, built on Kafka MirrorMaker.' },
    ],
    alternatives: [
      { option: 'Point-to-point pipelines', verdict: 'Every team copies data; failures multiply.' },
      { option: 'One global cluster', verdict: 'Cross-region latency and one huge blast radius.' },
    ],
    breaksNext: <p>Teams hand-build models for ETA and fraud, each with its own features and serving.</p>,
    interview: {
      q: 'Active/active vs active/passive consumers: when do you use each?',
      a: <p>Active/active when each region can process independently, like refreshing a regional cache. Active/passive when a job must run in exactly one place, like payment reconciliation, and you accept a failover step.</p>,
    },
    sources: [S.kafka],
  },
  {
    title: 'v9 · Machine learning as a platform',
    era: '2015–2022',
    scale: 'millions of predictions/s (2018)',
    summary: 'A shared ML platform trains and serves models, and arrival times become a routing estimate plus a learned correction.',
    added: ['ml'],
    nodes: [U.rider, U.driver, U.gw, U.trips, U.dispatch, U.geo, { ...U.eta, sub: 'routing + DeepETA' }, U.kafka, U.ml],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'trips'), ue('gw', 'dispatch'), ue('dispatch', 'geo'), ue('dispatch', 'eta'),
      ue('trips', 'kafka', { async: true }), ue('kafka', 'ml', { label: 'features' }), ue('ml', 'eta', { label: 'models' })],
    flows: [
      { name: 'ETA', path: ['rider', 'gw', 'dispatch', 'eta'], steps: ['Rider asks for a pickup time', 'The edge asks dispatch', 'Routing computes a base ETA; the model adds a learned correction'] },
      { name: 'Train', path: ['kafka', 'ml', 'eta'], steps: ['Completed trips stream in as training data', 'The platform trains, evaluates, and deploys the new model'] },
    ],
    problem: <p>Teams built one-off models with different tools. Training was limited to one machine, and every deployment was custom work.</p>,
    decision: <p>Build <strong>Michelangelo</strong>, a shared platform to manage data, train, deploy, and monitor models. ETA becomes a hybrid: routing gives a base estimate, and <strong>DeepETA</strong> predicts the correction.</p>,
    tradeoff: <p>A central platform must serve many use cases at once. DeepETA must answer within milliseconds, which limits model size.</p>,
    realWorld: <p>Uber introduced Michelangelo in 2017. A 2018 follow-up reported thousands of models and millions of predictions per second. Its 2022 DeepETA post calls it Uber’s highest-QPS model.</p>,
    walkthrough: [
      'Trips and pings stream in and become training data.',
      'Michelangelo builds features and trains models on a cluster.',
      'Models are deployed to online prediction services.',
      'Routing computes a base ETA along the best path.',
      'DeepETA predicts the gap between that estimate and reality; the sum is shown to the rider.',
    ],
    numbers: [
      { label: 'Predictions (2018)', value: 'millions/s' },
      { label: 'Models in production (2018)', value: 'thousands' },
      { label: 'DeepETA latency budget', value: 'a few ms', note: '2022 post' },
    ],
    components: [
      { name: 'Michelangelo', role: 'One workflow for data, training, deployment, and monitoring.' },
      { name: 'DeepETA', role: 'Learns the residual between routing ETA and the real arrival time.' },
    ],
    alternatives: [
      { option: 'Predict ETA with ML alone', verdict: 'Throws away what the routing engine already knows about roads.' },
      { option: 'Separate ML stack per team', verdict: 'Duplicated work and no standard serving.' },
    ],
    breaksNext: <p>About 2,200 microservices mean even a simple feature touches many teams.</p>,
    interview: {
      q: 'Why predict a correction to a routing ETA instead of the ETA itself?',
      a: <p>The routing engine already captures road structure and live traffic. The model only learns what routing misses, which is easier to train, update, and explain.</p>,
    },
    sources: [S.michelangelo, S.scalingMl, S.deepeta],
  },
  {
    title: 'v10 · Group services into domains',
    era: '2020',
    scale: '~2,200 critical services',
    summary: 'Related services are grouped behind one gateway each, so callers depend on a few stable doors instead of many rooms.',
    added: ['dFul', 'dMkt', 'dMaps', 'dPay', 'many'],
    nodes: [U.rider, U.driver, U.gw, U.dFul, U.dMkt, U.dMaps, U.dPay, U.many],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'dFul'), ue('gw', 'dMkt'), ue('dFul', 'dPay'), ue('dMkt', 'dMaps'),
      ue('dFul', 'many'), ue('dMkt', 'many'), ue('dMaps', 'many')],
    flows: [{ name: 'Request', path: ['rider', 'gw', 'dFul', 'dPay'], steps: ['A rider action hits the edge', 'The edge calls the Fulfillment domain’s gateway', 'Fulfillment calls Payments through its gateway, never its internals'] }],
    problem: <p>With about 2,200 critical microservices, a simple feature could need calls to many services. Half of all services churned every 1.5 years, breaking callers.</p>,
    decision: <p>Group related services into about 70 <strong>domains</strong>. Each domain exposes one gateway, and callers depend only on it. Layers limit which domains may call which.</p>,
    tradeoff: <p>Gateways add a network hop and need discipline. Drawing domain boundaries is hard, and partly organizational.</p>,
    realWorld: <p>Uber described Domain-Oriented Microservice Architecture (DOMA) in 2020. It reported 25–50% faster onboarding for platform integrations.</p>,
    walkthrough: [
      'Product code calls the Fulfillment domain gateway.',
      'The gateway routes to the right internal service.',
      'Fulfillment calls Payments only through the Payments gateway.',
      'Internal services can be replaced without breaking any caller.',
    ],
    numbers: [
      { label: 'Critical microservices', value: '~2,200' },
      { label: 'Domains', value: '~70' },
      { label: 'Service half-life', value: '~1.5 years' },
      { label: 'Onboarding time saved', value: '25–50%' },
    ],
    components: [
      { name: 'Domain gateway', role: 'The single, stable entry point to a group of services.' },
      { name: 'Layers', role: 'Rules on which domains may depend on which, preventing cycles.' },
    ],
    alternatives: [
      { option: 'Merge back into a monolith', verdict: 'Loses independent deploys at Uber’s size.' },
      { option: 'Keep flat microservices', verdict: 'Callers stay coupled to churning internals.' },
    ],
    breaksNext: <p>Fulfillment, the core of every trip, still sits on storage built around NoSQL assumptions.</p>,
    interview: {
      q: 'Microservices sprawl: what do you do at 2,000+ services?',
      a: <p>Group services by domain behind stable gateways, layer the dependencies, and measure churn. Do not swing back to a monolith; shrink the surface callers can see.</p>,
    },
    sources: [S.doma],
  },
  {
    title: 'v11 · A transactional core on Spanner',
    era: '2021',
    scale: 'billions of DB transactions/day',
    summary: 'The system that runs every trip is rebuilt on a database with real transactions across regions.',
    added: ['ful', 'spanner', 'late'],
    nodes: [U.rider, U.driver, U.gw, U.ful, U.dispatch, U.eta, U.spanner, U.late],
    edges: [ue('rider', 'gw'), ue('driver', 'gw'), ue('gw', 'ful'), ue('ful', 'dispatch'), ue('dispatch', 'eta'),
      ue('ful', 'spanner', { label: 'transaction' }), ue('spanner', 'late', { label: 'change feed', async: true }), ue('late', 'ful', { label: 'tasks' })],
    flows: [
      { name: 'Accept trip', path: ['driver', 'gw', 'ful', 'spanner'], steps: ['Driver taps Accept', 'The edge calls the fulfillment platform', 'Order and session updates commit in one transaction'] },
      { name: 'After commit', path: ['spanner', 'late', 'ful'], steps: ['The commit appears on a change feed', 'LATE runs follow-up tasks outside the transaction'] },
    ],
    problem: <p>Fulfillment manages every live order and driver session. Uber wanted transactional consistency, horizontal scale, and low operational overhead in one store.</p>,
    decision: <p>Rebuild fulfillment on <strong>Google Cloud Spanner</strong>, a NewSQL database, in a multi-region setup. Related changes commit together. Follow-up work runs asynchronously through <strong>LATE</strong>, fed by change data capture.</p>,
    tradeoff: <p>Each transaction crosses into Google Cloud, so network paths and latency need careful engineering. The rebuild took about two years and 30+ teams.</p>,
    realWorld: <p>Uber’s 2021 two-part series describes the rebuild on Cloud Spanner. InfoQ reported the two-year, 30+ team effort and a 99.99% availability target.</p>,
    walkthrough: [
      'The driver accepts; fulfillment opens a transaction.',
      'It updates the order and the driver’s session together.',
      'Spanner commits across replicas in its multi-region configuration.',
      'A change feed hands the commit to LATE.',
      'LATE runs follow-up tasks asynchronously, outside the critical path.',
    ],
    numbers: [
      { label: 'Availability target', value: '99.99%' },
      { label: 'Effort', value: '~2 years', note: '30+ teams' },
      { label: 'Scale (2021)', value: 'billions/day', note: 'DB transactions' },
    ],
    components: [
      { name: 'Fulfillment platform', role: 'Owns the lifecycle of orders and driver sessions.' },
      { name: 'Cloud Spanner', role: 'Transactions with strong consistency, including across regions.' },
      { name: 'LATE', role: 'Runs post-commit work reliably from change data capture.' },
    ],
    alternatives: [
      { option: 'NoSQL plus consistency in app code', verdict: 'Complex, bug-prone logic for every entity.' },
      { option: 'Self-hosted NewSQL', verdict: 'Uber weighed operational overhead heavily when comparing options.' },
    ],
    breaksNext: <p>Running a core database in another company’s cloud, reached from every Uber region, puts the network itself inside the design.</p>,
    interview: {
      q: 'When would you move from NoSQL to a NewSQL database?',
      a: <p>When invariants span several entities and app-level consistency is costing bugs and speed. You pay with latency and cost, so measure cross-region commit times before committing.</p>,
    },
    sources: [S.fulfillment1, S.fulfillment2, S.fulfillmentInfoq],
  },
]
