import type { ArchEdge, ArchNode, EpisodeStage } from '../../components/ui'

// Stage graphs are cumulative: each stage re-lists the nodes it keeps so positions stay stable.
const N = {
  client: { id: 'client', label: 'Devices', sub: 'TV · web · mobile', kind: 'client', x: 10, y: 50 },
  app: { id: 'app', label: 'Monolith', sub: 'catalog + play', kind: 'service', x: 42, y: 50 },
  db: { id: 'db', label: 'Relational DB', kind: 'db', x: 75, y: 30 },
  files: { id: 'files', label: 'Video files', sub: 'on app disks', kind: 'storage', x: 75, y: 72 },
  s3: { id: 's3', label: 'Object storage', sub: 'masters + renditions', kind: 'storage', x: 88, y: 66 },
  cdn: { id: 'cdn', label: 'Commercial CDN', kind: 'cdn', x: 34, y: 16 },
  encode: { id: 'encode', label: 'Encoding farm', sub: 'parallel chunks', kind: 'worker', x: 64, y: 88 },
  gw: { id: 'gw', label: 'API gateway', kind: 'lb', x: 30, y: 50 },
  svc: { id: 'svc', label: 'Microservices', sub: 'hundreds', kind: 'service', x: 52, y: 50 },
  cass: { id: 'cass', label: 'Cassandra', sub: 'viewing history', kind: 'db', x: 76, y: 38 },
  cache: { id: 'cache', label: 'EVCache', sub: 'memcached tier', kind: 'cache', x: 76, y: 14 },
  oca: { id: 'oca', label: 'Open Connect', sub: 'boxes inside ISPs', kind: 'cdn', x: 30, y: 84 },
  steer: { id: 'steer', label: 'Steering', sub: 'pick best OCA', kind: 'service', x: 52, y: 20 },
  events: { id: 'events', label: 'Event stream', sub: 'Kafka', kind: 'queue', x: 52, y: 80 },
  ml: { id: 'ml', label: 'Personalization', sub: 'rows + artwork', kind: 'worker', x: 76, y: 62 },
  region: { id: 'region', label: 'Other regions', sub: 'active-active', kind: 'external', x: 90, y: 88 },
} satisfies Record<string, ArchNode>

const e = (from: string, to: string, extra: Partial<ArchEdge> = {}): ArchEdge => ({ from, to, ...extra })

export const NETFLIX_STAGES: EpisodeStage[] = [
  {
    title: 'v0 · The monolith',
    scale: '~10K subscribers',
    nodes: [N.client, N.app, N.db, N.files],
    edges: [e('client', 'app'), e('app', 'db'), e('app', 'files')],
    flows: [{ name: 'Play', path: ['client', 'app', 'files'], steps: ['Device asks the app to play a title', 'The app streams the file straight off its own disk'] }],
    problem: <p>Launch streaming quickly. There is one team, a catalog of a few thousand titles, and nobody knows if people will watch movies on a laptop.</p>,
    decision: <p>One app server does everything: catalog, auth, billing, and serving the video bytes from local disk. It is boring on purpose.</p>,
    tradeoff: <p>Video bytes and API calls compete for the same CPU, NIC, and deploys. One bad release takes down browsing <em>and</em> playback.</p>,
  },
  {
    title: 'v1 · Split bytes from brains',
    scale: '~1M subscribers',
    added: ['s3', 'cdn'],
    nodes: [N.client, N.app, N.db, N.s3, N.cdn],
    edges: [e('client', 'app'), e('client', 'cdn'), e('cdn', 's3'), e('app', 'db')],
    flows: [
      { name: 'Play', path: ['client', 'app', 'db'], steps: ['Device requests playback', 'App checks entitlement, returns a CDN URL'] },
      { name: 'Stream', path: ['client', 'cdn', 's3'], steps: ['Device fetches segments from the nearest CDN edge', 'Cache miss pulls from origin object storage'] },
    ],
    problem: <p>Video egress is 1000× the size of API traffic. The app tier melts every evening at peak, and scaling it for bytes wastes money on CPU.</p>,
    decision: <p>Separate the <strong>control plane</strong> (API, small, stateful) from the <strong>data plane</strong> (bytes, huge, stateless). Masters and encoded files go to object storage, and a commercial CDN serves them.</p>,
    tradeoff: <p>Now there are two systems to keep consistent: a title can be “available” in the API before its files reach the edge.</p>,
  },
  {
    title: 'v2 · An encoding pipeline',
    scale: '~10M subscribers · 1000s of devices',
    added: ['encode'],
    nodes: [N.client, N.app, N.db, N.s3, N.cdn, N.encode],
    edges: [e('client', 'app'), e('client', 'cdn'), e('cdn', 's3'), e('app', 'db'), e('encode', 's3', { label: 'renditions' }), e('s3', 'encode', { async: true })],
    flows: [{ name: 'Ingest', path: ['s3', 'encode', 's3'], steps: ['A studio master lands in storage', 'The master is split into chunks and encoded in parallel into every rendition, then packaged'] }],
    problem: <p>Every device family wants different codecs, resolutions, and DRM, and network speeds vary second to second. One file per title no longer works.</p>,
    decision: <p>Split each master into chunks and encode them in parallel into a <strong>bitrate ladder</strong> × codecs. Package the results as segmented streams so players can switch quality mid-stream (adaptive bitrate).</p>,
    tradeoff: <p>Storage multiplies (dozens of renditions per title) and encoding compute becomes a major cost. That is worth it, because every bit saved is multiplied by every stream.</p>,
    realWorld: <p>Netflix publicly described moving from a fixed ladder to <strong>per-title</strong> (2015) and later <strong>shot-based</strong> encoding. The ladder is tuned to each title’s complexity, which saves bandwidth at equal perceived quality.</p>,
  },
  {
    title: 'v3 · Cloud + microservices',
    scale: '~50M subscribers · many teams',
    added: ['gw', 'svc', 'cass', 'cache'],
    nodes: [N.client, N.gw, N.svc, N.cass, N.cache, N.s3, N.cdn, N.encode],
    edges: [e('client', 'gw'), e('gw', 'svc'), e('svc', 'cache'), e('svc', 'cass'), e('client', 'cdn'), e('cdn', 's3'), e('encode', 's3')],
    flows: [{ name: 'Browse', path: ['client', 'gw', 'svc', 'cache'], steps: ['Home screen request hits the edge gateway', 'Gateway fans out to catalog, ratings, and row services', 'Most reads are served from the cache tier'] }],
    problem: <p>A single relational database and a monolith deploy train can’t keep up with hundreds of engineers or a global audience. A database corruption incident shows how fragile the single-DB design is.</p>,
    decision: <p>Rebuild the control plane as stateless microservices behind an edge gateway, on elastic cloud capacity. High-volume writes such as viewing history go to <strong>Cassandra</strong>, and a memcached-based tier absorbs reads.</p>,
    tradeoff: <p>Operational complexity explodes: service discovery, partial failures, and fan-out latency. You now need resilience engineering as a discipline.</p>,
    realWorld: <p>Netflix publicly described migrating to AWS starting after a 2008 database outage, finishing around 2016. Its open-source stack from that era includes Zuul (gateway), Eureka (discovery), Hystrix (circuit breakers, now in maintenance), and EVCache.</p>,
  },
  {
    title: 'v4 · Build your own CDN',
    scale: '~100M+ subscribers · large share of evening internet traffic',
    added: ['oca', 'steer'],
    nodes: [N.client, N.gw, N.svc, N.cass, N.cache, N.s3, N.oca, N.steer, N.encode],
    edges: [e('client', 'gw'), e('gw', 'svc'), e('svc', 'cache'), e('svc', 'cass'), e('svc', 'steer'), e('client', 'oca'), e('s3', 'oca', { label: 'off-peak fill', async: true }), e('encode', 's3')],
    flows: [{ name: 'Play', path: ['client', 'gw', 'svc', 'steer'], steps: ['Device asks for a playback session', 'Playback service checks entitlement and DRM', 'Steering returns a ranked list of nearby appliances'] },
      { name: 'Stream', path: ['client', 'oca'], steps: ['Device streams segments from an appliance inside its own ISP'] }],
    problem: <p>At this volume, commercial CDN bills are enormous and last-mile congestion ruins quality. Streaming traffic has a trait generic CDNs ignore: the catalog is <em>known in advance</em>.</p>,
    decision: <p>Put your own caching servers <strong>inside ISP networks</strong> and at exchange points. Pre-position popular files during off-peak hours using predicted demand. A steering service tells each device which appliances to use.</p>,
    tradeoff: <p>You become a hardware and logistics company: thousands of boxes, ISP partnerships, fill scheduling. That only pays off at massive scale.</p>,
    realWorld: <p>This is Netflix <strong>Open Connect</strong>, announced in 2012. Its appliances are offered to ISPs, and content is filled proactively during low-traffic windows.</p>,
  },
  {
    title: 'v5 · Personalization everywhere',
    scale: 'Global · 190+ countries',
    added: ['events', 'ml'],
    nodes: [N.client, N.gw, N.svc, N.cass, N.cache, N.oca, N.steer, N.events, N.ml],
    edges: [e('client', 'gw'), e('gw', 'svc'), e('svc', 'cache'), e('svc', 'cass'), e('svc', 'steer'), e('client', 'oca'), e('svc', 'events', { async: true }), e('events', 'ml'), e('ml', 'cache', { label: 'precomputed rows' })],
    flows: [{ name: 'Learn', path: ['client', 'gw', 'svc', 'events', 'ml', 'cache'], steps: ['Every play, pause, and scroll is an event', 'Services publish events', 'The stream feeds batch and near-real-time pipelines', 'Models rank rows and pick artwork', 'Results are precomputed into the cache for instant home pages'] }],
    problem: <p>With thousands of titles and a TV remote, users give up within seconds. What you show first matters more than what exists.</p>,
    decision: <p>Instrument everything into an event stream. Train ranking models offline, precompute each member’s home page, and personalize even the <strong>artwork</strong> per member.</p>,
    tradeoff: <p>Precomputed pages go stale, so you need a hybrid of batch plus online re-ranking. Data pipelines become as critical as the serving path.</p>,
  },
  {
    title: 'v6 · Survive anything',
    scale: 'Peak concurrent streams in the tens of millions',
    added: ['region'],
    nodes: [N.client, N.gw, N.svc, N.cass, N.cache, N.oca, N.steer, N.events, N.ml, N.region],
    edges: [e('client', 'gw'), e('gw', 'svc'), e('svc', 'cache'), e('svc', 'cass'), e('cass', 'region', { label: 'replication', async: true }), e('svc', 'steer'), e('client', 'oca'), e('svc', 'events', { async: true }), e('events', 'ml')],
    flows: [{ name: 'Evacuate', path: ['client', 'gw', 'region'], steps: ['A region degrades, so DNS and the gateway shift traffic', 'Other regions absorb the load; replicated data is already there'] }],
    problem: <p>A single cloud region outage would black out a continent. At this scale, <em>something</em> is always failing.</p>,
    decision: <p>Run <strong>active-active across regions</strong> with data replicated asynchronously, and practice evacuating a region. Inject failure deliberately in production so resilience is tested continuously, not assumed.</p>,
    tradeoff: <p>Async replication means brief inconsistency (e.g. your “continue watching” position lags). Chaos engineering needs strong observability and a culture that tolerates it.</p>,
    realWorld: <p>Netflix popularized <strong>chaos engineering</strong> with Chaos Monkey and has written publicly about regional evacuation exercises and multi-region active-active on AWS.</p>,
  },
]
