import type { EpisodeStage } from '../../components/ui'
import { A, ae } from './episode-airbnb-stage-nodes'
import { AIRBNB_SRC as S } from './episode-airbnb-sources'

// Stages 1–6: a Rails monolith grows risk scoring, experiments, pipelines, and a real search index.
export const AIRBNB_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'v0 · A Rails monolith',
    era: 'Early years',
    scale: 'hundreds of listings (estimate)',
    summary: 'One web app and one database hold everything while the team finds out if the idea works.',
    nodes: [A.guest, A.host, A.mono, A.db],
    edges: [ae('guest', 'mono'), ae('host', 'mono'), ae('mono', 'db')],
    flows: [
      { name: 'Search & book', path: ['guest', 'mono', 'db'], steps: ['Guest searches a city and dates', 'The app queries listings, drops those with overlapping bookings, then inserts the new booking'] },
      { name: 'List a home', path: ['host', 'mono', 'db'], steps: ['Host creates a listing with photos and a calendar', 'Stored as rows in the same database'] },
    ],
    problem: <p>Find out whether strangers will pay to stay in each other’s homes. Speed of iteration beats everything else.</p>,
    decision: <p>One Ruby on Rails app and one relational database. Search is a SQL query with a map bounding box, filters, and a check for overlapping bookings.</p>,
    tradeoff: <p>Simple and transactional. But search, the busiest path, runs expensive date checks on the same database that takes bookings.</p>,
    realWorld: <p>Airbnb engineers have described the early product as a Ruby on Rails monolith, later nicknamed the “monorail”.</p>,
    walkthrough: [
      'A guest searches a city and dates.',
      'The app finds listings inside the map area, then drops any with overlapping bookings.',
      'The guest reserves; the app inserts a booking row.',
      'Hosts edit listings and calendars in the same app and database.',
    ],
    numbers: [
      { label: 'Searches per booking', value: '~50', note: 'estimate' },
      { label: 'Deployables', value: '1', note: 'one app, one deploy train' },
    ],
    components: [
      { name: 'Rails monolith', role: 'Every feature in one codebase: fast to change while the team is small.' },
      { name: 'Relational database', role: 'Single source of truth for listings, calendars, and bookings.' },
    ],
    alternatives: [
      { option: 'Services from day one', verdict: 'Premature; nobody knows the right boundaries yet.' },
      { option: 'A separate search engine now', verdict: 'Not worth it at hundreds of listings.' },
    ],
    breaksNext: <p>As the marketplace grows, so do stolen cards, fake accounts, and chargebacks.</p>,
    interview: {
      q: 'What usually breaks first in a marketplace monolith?',
      a: <p>The busiest read path, here search, competing with writes on one database. Watch query latency and database CPU, and split reads out first.</p>,
    },
    sources: [S.qcon],
  },
  {
    title: 'v1 · Score risk in real time',
    era: '~2014',
    scale: 'many markets',
    summary: 'A separate service scores risky actions during the request, using models trained offline.',
    added: ['risk', 'models'],
    nodes: [A.guest, A.host, A.mono, A.db, A.risk, A.models],
    edges: [ae('guest', 'mono'), ae('host', 'mono'), ae('mono', 'db'), ae('mono', 'risk', { label: 'score?' }), ae('db', 'models', { async: true }), ae('models', 'risk', { label: 'new model' })],
    flows: [
      { name: 'Book with scoring', path: ['guest', 'mono', 'risk'], steps: ['Guest attempts a booking', 'The app asks the fraud service for a score before confirming'] },
      { name: 'Retrain', path: ['db', 'models', 'risk'], steps: ['Outcomes such as chargebacks become labels', 'A new model is trained offline and pushed to the scorer'] },
    ],
    problem: <p>Stolen cards and fake accounts cause chargebacks and unsafe stays. Checks must run inside the booking request without slowing it down.</p>,
    decision: <p>Build a separate <strong>fraud prediction service</strong>. It gathers features and scores each risky action in near real time. Models are trained offline and pushed into it.</p>,
    tradeoff: <p>Serving needs speed and reliability; model building needs flexibility. The two halves must be designed separately.</p>,
    realWorld: <p>Airbnb’s 2014 post “Architecting a Machine Learning System for Risk” describes a separate fraud prediction service in its service-oriented stack.</p>,
    walkthrough: [
      'A guest attempts a booking.',
      'The app asks the risk service for a score.',
      'The service gathers features: account age, payment signals, behaviour.',
      'A model returns a score; high scores add friction or block the action.',
      'Outcomes such as chargebacks later become training labels.',
    ],
    numbers: [
      { label: 'Scoring budget', value: 'tens of ms', note: 'estimate' },
      { label: 'Label delay', value: 'weeks', note: 'chargebacks arrive late (estimate)' },
    ],
    components: [
      { name: 'Fraud prediction service', role: 'Computes features and serves model scores inline.' },
      { name: 'Offline training', role: 'Builds and evaluates new models from labelled outcomes.' },
    ],
    alternatives: [
      { option: 'Rules only', verdict: 'Easy to explain, and easy for fraudsters to learn.' },
      { option: 'Score in an overnight batch', verdict: 'Too late: the stay is already booked.' },
    ],
    breaksNext: <p>Every team ships changes, and nobody can tell which ones actually help bookings.</p>,
    interview: {
      q: 'Where do you run a fraud model in a booking flow?',
      a: <p>Inline, with a tight timeout and a safe default. Score only risky actions, prefer adding friction over hard blocks, and log every decision for future labels.</p>,
    },
    sources: [S.risk],
  },
  {
    title: 'v2 · Experiment on everything',
    era: '2014',
    scale: 'many product teams',
    summary: 'Changes ship as controlled experiments, with a tool that computes results and hides statistical traps.',
    added: ['erf', 'wh'],
    nodes: [A.guest, A.host, A.mono, A.db, A.erf, A.wh],
    edges: [ae('guest', 'mono'), ae('host', 'mono'), ae('mono', 'db'), ae('mono', 'wh', { label: 'events', async: true }), ae('db', 'wh', { async: true }), ae('wh', 'erf')],
    flows: [{ name: 'Measure', path: ['guest', 'mono', 'wh', 'erf'], steps: ['Guest is assigned to a variant', 'The app logs exposures and actions', 'Daily jobs compute metrics per variant for the report'] }],
    problem: <p>A marketplace is noisy. A change can look like a win for days, then fade to nothing. Teams need answers they can trust.</p>,
    decision: <p>Build an <strong>experiment reporting framework</strong>. Users are assigned to variants, events are logged, and metrics are computed automatically, with common statistical pitfalls built out.</p>,
    tradeoff: <p>Experiments take time and traffic. In a two-sided market, treated and control users compete for the same homes, which can bias simple A/B tests.</p>,
    realWorld: <p>Airbnb’s 2014 posts describe its experiment practice and reporting framework, including an early “win” whose effect later shrank to about zero.</p>,
    walkthrough: [
      'A user is assigned to control or treatment.',
      'The app logs which variant each user saw and what they did.',
      'Daily jobs compute metrics per variant.',
      'The report shows effect sizes over time, not one lucky day.',
      'Finished experiments are retired and their code paths removed.',
    ],
    numbers: [
      { label: 'Typical test length', value: '1–4 weeks', note: 'estimate' },
      { label: '2014 example', value: 'early win → ~0', note: 'why peeking misleads' },
    ],
    components: [
      { name: 'Variant assignment', role: 'Stable, random bucketing per user.' },
      { name: 'Reporting framework', role: 'Automates metric computation and guards against pitfalls.' },
    ],
    alternatives: [
      { option: 'Before/after comparisons', verdict: 'Seasonality and marketing changes fool you.' },
      { option: 'Stop as soon as it looks significant', verdict: 'Peeking inflates false positives.' },
    ],
    breaksNext: <p>Metrics, experiments, and models all depend on batch jobs wired together by hand.</p>,
    interview: {
      q: 'Why can A/B tests mislead in a two-sided marketplace?',
      a: <p>Treatment and control share the same supply. If treated guests book more, control guests find fewer homes. Use market-level or cluster designs, and watch guardrail metrics.</p>,
    },
    sources: [S.experiments, S.erf],
  },
  {
    title: 'v3 · Pipelines as code',
    era: '2014–2015',
    scale: 'hundreds of batch jobs (estimate)',
    summary: 'Batch jobs become Python-defined graphs that a scheduler runs in dependency order, with retries and backfills.',
    added: ['airflow'],
    nodes: [A.guest, A.host, A.mono, A.db, A.erf, A.wh, A.airflow],
    edges: [ae('guest', 'mono'), ae('host', 'mono'), ae('mono', 'db'), ae('db', 'wh', { async: true }), ae('airflow', 'wh', { label: 'runs jobs' }), ae('wh', 'erf')],
    flows: [{ name: 'Daily run', path: ['airflow', 'wh', 'erf'], steps: ['The scheduler starts today’s run when upstream data is ready', 'Tables refresh, and experiment reports recompute'] }],
    problem: <p>Hundreds of scheduled jobs feed metrics, experiments, and models. Their dependencies live in cron files and in people’s heads.</p>,
    decision: <p>Build <strong>Airflow</strong>. Pipelines are Python code describing a graph of tasks. A scheduler runs tasks when their dependencies finish, with retries, backfills, and a UI.</p>,
    tradeoff: <p>Pipelines as code need engineering discipline. The scheduler becomes critical infrastructure for the whole company.</p>,
    realWorld: <p>Maxime Beauchemin started Airflow at Airbnb in late 2014. Airbnb open-sourced it in June 2015, and it later became an Apache project.</p>,
    walkthrough: [
      'An engineer writes a Python file that declares tasks and their dependencies.',
      'The scheduler creates a run for each day.',
      'Each task starts when its upstream tasks succeed.',
      'Failures retry, then alert a person.',
      'After a fix, a backfill reruns the affected days.',
    ],
    numbers: [
      { label: 'Tasks per pipeline', value: '10s–100s', note: 'estimate' },
      { label: 'Open-sourced', value: 'June 2015' },
    ],
    components: [
      { name: 'Task graphs (DAGs)', role: 'Pipelines defined in reviewed, versioned Python.' },
      { name: 'Scheduler and workers', role: 'Run tasks in dependency order and track their state.' },
    ],
    alternatives: [
      { option: 'Cron plus scripts', verdict: 'No dependencies, retries, or visibility.' },
      { option: 'Drag-and-drop workflow tools', verdict: 'Hard to review, test, and version.' },
    ],
    breaksNext: <p>Search, the busiest path, still runs on the booking database.</p>,
    interview: {
      q: 'How do you make daily data pipelines reliable?',
      a: <p>Explicit dependencies, idempotent tasks keyed by date, retries with alerts, and backfills. Treat pipeline code like product code: review and test it.</p>,
    },
    sources: [S.airflow, S.airflowDocs],
  },
  {
    title: 'v4 · Search gets its own index',
    era: '2016 (as described)',
    scale: 'millions of listings (estimate)',
    summary: 'Search moves to sharded index files, built offline from daily snapshots and deployed like code.',
    added: ['search', 'index', 'nebula'],
    nodes: [A.guest, A.host, A.mono, A.db, A.search, A.index, A.nebula, A.wh, A.airflow],
    edges: [ae('guest', 'search'), ae('search', 'index'), ae('guest', 'mono'), ae('host', 'mono'), ae('mono', 'db'), ae('db', 'wh', { async: true }),
      ae('wh', 'nebula'), ae('nebula', 'index', { label: 'daily build' }), ae('airflow', 'nebula', { label: 'triggers' })],
    flows: [
      { name: 'Search', path: ['guest', 'search', 'index'], steps: ['Guest searches a city and dates', 'Search queries index shards, not the database'] },
      { name: 'Build index', path: ['wh', 'nebula', 'index'], steps: ['A daily snapshot merges listings and features', 'The builder writes new shards, and servers load them like a deploy'] },
    ],
    problem: <p>Search traffic dwarfs bookings. Filtering many listings with SQL is slow, and it loads the database that takes bookings.</p>,
    decision: <p>Build a dedicated, sharded <strong>search index</strong>. Listing data and features are merged from a daily snapshot, built into index files offline, and deployed like a binary.</p>,
    tradeoff: <p>A snapshot index is stale between builds. Fields that change often, like prices and availability, need a faster update path.</p>,
    realWorld: <p>Airbnb’s 2016 post on Nebula describes building search indexes offline from versioned snapshots, deploying them like binaries, and rolling back bad index data quickly.</p>,
    walkthrough: [
      'A daily snapshot merges listings and features from the warehouse.',
      'An index builder creates sharded index files.',
      'Search servers download the new index, like a code deploy.',
      'Guests query the index; the primary database only serves writes and detail pages.',
      'If the new index is bad, servers roll back to the previous snapshot.',
    ],
    numbers: [
      { label: 'Index rebuild (2016)', value: 'daily' },
      { label: 'Rollback', value: 'previous snapshot', note: 'no re-indexing needed' },
    ],
    components: [
      { name: 'Search service', role: 'Serves queries from index shards.' },
      { name: 'Index builder', role: 'Turns versioned snapshots into deployable index files.' },
    ],
    alternatives: [
      { option: 'Keep querying the primary database', verdict: 'Search load slows bookings.' },
      { option: 'Only update the index in place', verdict: 'Harder to audit and roll back.' },
    ],
    breaksNext: <p>Guests click homes that turn out to be booked for their dates.</p>,
    interview: {
      q: 'Why build a search index offline and ship it like a binary?',
      a: <p>Builds are reproducible and versioned, rollback is instant, and new servers start fast. You pay with staleness, so add a real-time path for fields that change often.</p>,
    },
    sources: [S.nebula],
  },
  {
    title: 'v5 · Availability inside the index',
    era: '2018 (CDC described)',
    scale: '365 nights per listing',
    summary: 'Each listing’s calendar becomes one bit per night in the index, kept fresh by streaming database changes.',
    added: ['cdc'],
    nodes: [A.guest, A.host, A.mono, { ...A.db, sub: 'source of truth' }, A.search, { ...A.index, sub: 'geo + nights bitmap' }, A.cdc],
    edges: [ae('guest', 'search'), ae('search', 'index'), ae('guest', 'mono'), ae('host', 'mono'), ae('mono', 'db'),
      ae('db', 'cdc', { label: 'log', async: true }), ae('cdc', 'index', { label: 'flip nights' })],
    flows: [{ name: 'Booking → index', path: ['guest', 'mono', 'db', 'cdc', 'index'], steps: ['A guest books nights 10–12', 'The app writes the booking', 'The change is read from the database log', 'The index marks those nights unavailable'] }],
    problem: <p>“Free for my dates” is part of nearly every search. The index knows location and price but not the calendar, so results include booked homes.</p>,
    decision: <p>Store each listing’s calendar in the index as <strong>one bit per night</strong>. A search ANDs the requested nights against it. Booking changes reach the index in seconds through change data capture.</p>,
    tradeoff: <p>The index still lags the database by seconds. The booking path must re-check availability against the source of truth.</p>,
    realWorld: <p>Airbnb’s 2018 post on SpinalTap, its change data capture service, gives this exact example: an availability service blocks a listing’s dates by subscribing to reservation changes. The one-bit-per-night index is this episode’s design choice.</p>,
    walkthrough: [
      'A booking commits in the database.',
      'Change data capture reads it from the database’s log.',
      'The index flips those nights to unavailable for that listing.',
      'A search ANDs the requested nights with each listing’s bits.',
      'Only listings with every night free go on to ranking.',
    ],
    numbers: [
      { label: 'Calendar bits, 7M listings × 365', value: '≈ 320 MB', note: 'estimate' },
      { label: 'Index lag target', value: 'seconds', note: 'estimate' },
    ],
    components: [
      { name: 'Change stream (CDC)', role: 'Reads committed changes from the database log, so no code path can forget to reindex.' },
      { name: 'Nights bitmap', role: 'Constant-cost availability check per listing.' },
    ],
    alternatives: [
      { option: 'Join against bookings at query time', verdict: 'Cost grows with the number of bookings.' },
      { option: 'App code calls “reindex”', verdict: 'Easy to forget in one code path.' },
    ],
    breaksNext: <p>Two guests can still pay for the same nights at the same moment.</p>,
    interview: {
      q: 'How do you filter millions of listings by date availability quickly?',
      a: <p>Precompute availability as one bit per night in the index and AND the requested nights. Keep it fresh with change data capture, and re-check at booking time.</p>,
    },
    sources: [S.spinaltap, S.spinaltapRepo, S.retrieval],
  },
]
