import type { EpisodeStage } from '../../components/ui'
import { N, S, as, e } from './episode-netflix-stage-library'

const mono = as(N.api, 'Web app', 'one codebase')
const rdb = as(N.ml, 'Relational DB', 'in own data center')

export const NETFLIX_EARLY: EpisodeStage[] = [
  {
    title: 'Streaming launches',
    era: '2007',
    summary: 'Netflix adds a “Watch Now” button next to its DVD-by-mail business, for PCs only.',
    scale: '~1,000 streaming titles',
    nodes: [as(N.client, 'PC browsers', 'Windows + IE'), mono, rdb, N.cdn],
    edges: [e('client', 'api'), e('api', 'ml'), e('client', 'cdn')],
    flows: [
      { name: 'Play', path: ['client', 'api', 'ml'], steps: ['The browser asks the web app to play a title', 'The app checks the account and viewing-hour allowance in the database'] },
      { name: 'Stream', path: ['client', 'cdn'], steps: ['The player downloads the video from a content delivery network'] },
    ],
    problem: <p>Streaming is an experiment. It must work on PCs, reuse the existing DVD systems, and not need a new company.</p>,
    decision: <p>Bolt streaming onto the existing web application and relational database in Netflix’s own data centers. Rent video delivery from CDNs.</p>,
    tradeoff: <p>Fast to launch, but DVD shipping and streaming now share one database. A failure there hits both businesses.</p>,
    realWorld: <p>“Watch Now” launched in January 2007 for Windows PCs, with a small catalog and a gradual rollout to subscribers.</p>,
    walkthrough: [
      'A subscriber clicks Watch Now in the browser.',
      'The web app checks the plan and remaining streaming hours in the relational database.',
      'The browser player fetches the video file from a CDN.',
    ],
    numbers: [
      { label: 'Streaming titles at launch', value: '~1,000', note: 'about 1% of the DVD library' },
      { label: 'DVD subscribers then', value: '6M+', note: 'Associated Press, Jan 2007' },
      { label: 'Rollout pace', value: '~250K / week', note: 'new users enabled weekly' },
    ],
    components: [{ name: 'Web app + relational DB', role: 'The existing DVD stack, extended with streaming entitlements.' }],
    alternatives: [
      { option: 'Separate streaming stack', verdict: 'Cleaner, but slower to ship for an unproven product.' },
      { option: 'Own video servers', verdict: 'Too much capital for a small catalog; CDNs were enough.' },
    ],
    breaksNext: <p>The single relational database is now critical to <em>everything</em>.</p>,
    interview: { q: 'When is a monolith the right first design?', a: <p>When the product is unproven and one team owns it. Name the seam you will split later (here: data plane vs control plane).</p> },
    sources: [S.watchNow],
  },
  {
    title: 'The three-day outage',
    era: '2008',
    summary: 'A corrupted database stops DVD shipping for three days and forces a rethink.',
    scale: 'Single-point-of-failure database',
    nodes: [as(N.client, 'PC + early devices'), mono, as(rdb, 'Relational DB', 'corrupted'), N.cdn],
    edges: [e('client', 'api'), e('api', 'ml'), e('client', 'cdn')],
    flows: [{ name: 'Failure', path: ['client', 'api', 'ml'], steps: ['Requests reach the app as usual', 'Every path depends on one database, so everything stops'] }],
    problem: <p>In August 2008 a major database corruption stopped DVD shipments for three days. One vertically scaled database was a single point of failure.</p>,
    decision: <p>Move away from vertically scaled single points of failure. Rebuild on horizontally scalable, distributed systems in a public cloud (AWS).</p>,
    tradeoff: <p>A multi-year migration while the business keeps growing. Engineers must learn to design for failing instances.</p>,
    realWorld: <p>Netflix names this incident as the trigger for its move to AWS. The migration took about seven years, finishing in January 2016.</p>,
    walkthrough: [
      'Order, account, and streaming logic all read and write one relational database.',
      'The database is corrupted.',
      'Every feature that touches it fails, and recovery takes days.',
    ],
    numbers: [
      { label: 'DVD shipping halted', value: '3 days' },
      { label: 'Cloud migration length', value: '~7 years', note: '2008 → Jan 2016' },
    ],
    components: [{ name: 'Nothing new yet', role: 'This stage is the decision point that shapes the next eight years.' }],
    alternatives: [
      { option: 'Bigger database + better backups', verdict: 'Fixes this incident, not the class of problem.' },
      { option: 'Build more data centers', verdict: 'Slow to add capacity for a business growing this fast.' },
      { option: 'Public cloud, rebuilt as distributed services', verdict: 'Chosen: elastic capacity and no single box to lose.' },
    ],
    breaksNext: <p>A lift-and-shift would copy the same fragility into the cloud. The system has to be redesigned.</p>,
    interview: { q: 'Your core database just caused a multi-day outage. What do you change?', a: <p>Remove the single point of failure, not just the bug: partition data by domain, replicate it, and make services stateless so any instance can die.</p> },
    sources: [S.migration],
  },
  {
    title: 'Rebuild on AWS',
    era: '2009–2011',
    summary: 'Netflix rewrites itself as many small stateless services running on AWS.',
    scale: 'Streaming members growing fast',
    added: ['svc', 'disc', 'cass', 's3', 'edge'],
    nodes: [N.client, as(N.edge, 'AWS load balancer'), N.svc, N.disc, N.cass, N.s3, N.cdn],
    edges: [e('client', 'edge'), e('edge', 'svc'), e('svc', 'disc'), e('svc', 'cass'), e('svc', 's3'), e('client', 'cdn')],
    flows: [{ name: 'Browse', path: ['client', 'edge', 'svc', 'cass'], steps: ['A device calls the service', 'The load balancer picks any healthy instance', 'The service reads member data from Cassandra'] }],
    problem: <p>A single database and a single codebase cannot keep up. Capacity must grow in minutes, not months.</p>,
    decision: <p>Split the monolith into stateless services on AWS. Services find each other through Eureka (service discovery). Member data moves to Cassandra, a distributed NoSQL database.</p>,
    tradeoff: <p>No more joins or single-database transactions. Every call can now fail or be slow, which needs new habits.</p>,
    realWorld: <p>Netflix benchmarked Cassandra on AWS in 2011 at over a million writes per second. It later open-sourced Eureka.</p>,
    walkthrough: [
      'A device request hits an AWS load balancer.',
      'Any healthy instance of the service can answer, since none hold session state.',
      'The service looks up its dependencies in Eureka.',
      'Member data is read from Cassandra, replicated across three availability zones.',
    ],
    numbers: [
      { label: 'Cassandra benchmark', value: '1.1M writes/s', note: '288 nodes, 2011' },
      { label: 'With 3× replication', value: '3.3M writes/s', note: 'across the cluster' },
      { label: 'Members, 2008 → 2015', value: '8× growth', note: 'streaming members' },
    ],
    components: [
      { name: 'Stateless services', role: 'Scale by adding instances; any instance can be killed.' },
      { name: 'Eureka', role: 'Registry where instances announce themselves and find each other.' },
      { name: 'Cassandra', role: 'Write-heavy member data, replicated across zones, no single master.' },
    ],
    alternatives: [
      { option: 'Sharded relational DB', verdict: 'Resharding and failover are manual and risky at this growth rate.' },
      { option: 'Keep the monolith, run it on AWS', verdict: 'Moves the fragility instead of removing it.' },
    ],
    breaksNext: <p>Devices multiply, and one general-purpose API starts to strain.</p>,
    interview: { q: 'Why pick Cassandra for viewing history?', a: <p>The workload is write-heavy, keyed by member, and time-ordered. It needs multi-zone replication more than joins or strong transactions.</p> },
    sources: [S.migration, S.cassandra, S.eureka],
  },
  {
    title: 'Open Connect: a CDN inside ISPs',
    era: '2011–2012',
    summary: 'Netflix places its own cache servers inside internet providers and fills them overnight.',
    scale: 'A large share of ISP traffic',
    added: ['oca', 'steer'],
    nodes: [N.client, as(N.edge, 'AWS load balancer'), N.api, N.svc, N.cass, N.s3, N.oca, N.steer],
    edges: [e('client', 'edge'), e('edge', 'api'), e('api', 'svc'), e('svc', 'cass'), e('api', 'steer'), e('client', 'oca'), e('steer', 'oca', { label: 'nightly fill', async: true }), e('s3', 'oca', { async: true })],
    flows: [
      { name: 'Play', path: ['client', 'edge', 'api', 'steer'], steps: ['Device asks to play a title', 'Request reaches the playback API in AWS', 'Steering picks the best caches and returns their URLs'] },
      { name: 'Stream', path: ['client', 'oca'], steps: ['The device streams video from a cache inside its own ISP'] },
    ],
    problem: <p>Video is most of the bytes. Generic CDNs cache on demand and bill per gigabyte. Netflix traffic also loads ISP networks heavily.</p>,
    decision: <p>Build Open Connect: purpose-built caches (OCAs) inside ISPs and at internet exchanges. The catalog is known in advance, so content is pushed off-peak.</p>,
    tradeoff: <p>Netflix now runs a global hardware fleet and ISP partnerships. It only pays off at very large scale.</p>,
    realWorld: <p>Netflix began Open Connect in 2011. It gives appliances free to qualifying ISPs, which supply power, space, and connectivity.</p>,
    walkthrough: [
      'Each OCA reports its health, learned network routes, and stored files to the control plane in AWS.',
      'A device asks the playback service in AWS to play a title.',
      'Playback checks the account and licensing, then picks the files this device needs.',
      'Steering uses the OCA reports to choose caches and generates URLs for them.',
      'The device streams from the chosen OCA. Popular files were filled there during off-peak hours.',
    ],
    numbers: [
      { label: 'Program started', value: '2011' },
      { label: 'Appliance cost to ISP', value: '$0', note: 'ISP provides power, space, connectivity' },
      { label: 'Upstream demand', value: '“several orders of magnitude” less', note: 'Netflix’s own claim' },
    ],
    components: [
      { name: 'OCAs (appliances)', role: 'Store and serve encoded video; hold no member data.' },
      { name: 'Steering + fill (in AWS)', role: 'Picks caches per request and schedules nightly fills.' },
    ],
    alternatives: [
      { option: 'Commercial CDNs only', verdict: 'Simple, but cost and quality depend on someone else’s network.' },
      { option: 'Own data centers for video', verdict: 'Still far from users; does not relieve ISP links.' },
    ],
    breaksNext: <p>With hundreds of services, one slow dependency can now take down playback.</p>,
    interview: { q: 'Why can Netflix pre-fill caches when most CDNs cannot?', a: <p>Its catalog is finite and demand is predictable. It can predict what will be watched where, and push it at night.</p> },
    sources: [S.ocOverview, S.ocAppliances],
  },
  {
    title: 'Design for failure',
    era: '2011–2012',
    summary: 'Assume every dependency will fail, and test that assumption in production.',
    scale: 'Hundreds of service dependencies',
    added: ['chaos'],
    nodes: [N.client, as(N.edge, 'AWS load balancer'), as(N.api, 'Netflix API', 'Hystrix per dependency'), N.svc, N.cass, as(N.chaos, 'Chaos Monkey', 'kills instances'), N.oca, N.steer],
    edges: [e('client', 'edge'), e('edge', 'api'), e('api', 'svc'), e('svc', 'cass'), e('api', 'steer'), e('client', 'oca'), e('chaos', 'svc', { async: true, label: 'terminate' })],
    flows: [{ name: 'Fallback', path: ['client', 'edge', 'api', 'svc'], steps: ['Home screen request arrives', 'Edge routes to the API', 'A slow dependency trips its circuit breaker; the API serves a fallback'] }],
    problem: <p>In a distributed system, some dependency is always failing. Without isolation, one slow service ties up threads and cascades.</p>,
    decision: <p>Wrap every dependency call with timeouts, bulkheads, circuit breakers, and fallbacks (Hystrix). Randomly kill production instances (Chaos Monkey) so teams must build for it.</p>,
    tradeoff: <p>More code paths to design and test. Fallback responses must be designed per feature.</p>,
    realWorld: <p>Netflix described the Simian Army in 2011 and open-sourced Hystrix in November 2012. Hystrix is now in maintenance mode.</p>,
    walkthrough: [
      'The API calls dozens of services to build one screen.',
      'Each call runs in its own small thread pool with a timeout (a bulkhead).',
      'If a dependency keeps failing, its circuit opens and calls fail fast.',
      'The API returns a fallback, such as cached or default data.',
      'Chaos Monkey keeps killing instances so these paths stay exercised.',
    ],
    numbers: [
      { label: 'Hystrix calls per day', value: 'tens of billions', note: 'thread-isolated, 2012' },
      { label: 'Simian Army described', value: '2011' },
    ],
    components: [
      { name: 'Hystrix', role: 'Latency and fault isolation per dependency, with fallbacks.' },
      { name: 'Chaos Monkey', role: 'Terminates random instances during business hours.' },
    ],
    alternatives: [
      { option: 'Just add retries', verdict: 'Retries amplify load on a struggling service.' },
      { option: 'Test failures only in staging', verdict: 'Staging never matches production traffic or scale.' },
    ],
    breaksNext: <p>Hundreds of device types each need different data. A one-size-fits-all API is too chatty.</p>,
    interview: { q: 'How do you stop one slow service from taking down the API?', a: <p>Timeouts, a bounded thread pool per dependency, a circuit breaker, and a designed fallback. Then prove it with fault injection.</p> },
    sources: [S.simian, S.hystrix],
  },
  {
    title: 'An API for every device',
    era: '2012–2013',
    summary: 'Each device team gets its own endpoint, shaped for that screen.',
    scale: 'Hundreds of device types',
    nodes: [N.client, as(N.edge, 'Zuul edge'), as(N.api, 'API + adapters', 'per-device endpoints'), N.svc, N.cass, N.evc, N.oca, N.steer],
    edges: [e('client', 'edge'), e('edge', 'api'), e('api', 'svc'), e('svc', 'cass'), e('svc', 'evc'), e('api', 'steer'), e('client', 'oca')],
    flows: [{ name: 'Home screen', path: ['client', 'edge', 'api', 'svc', 'evc'], steps: ['The TV makes one call for its home screen', 'The edge routes it to the API', 'The TV’s adapter fans out to services in parallel', 'Most data comes from the cache tier'] }],
    problem: <p>API traffic grew about 37× in 13 months. Devices made many round trips, each one slow on TVs and consoles.</p>,
    decision: <p>Replace the one-size-fits-all REST API. Device teams write adapter code on the server that returns exactly what their screen needs, in one call.</p>,
    tradeoff: <p>The API server now runs code from many teams. It needs isolation, safe deploys, and ownership rules.</p>,
    realWorld: <p>Netflix described this redesign in 2011–2012. Its later Java API was fully asynchronous, modeled on Rx Observables.</p>,
    walkthrough: [
      'The device calls its own endpoint once.',
      'The adapter, owned by that device team, runs on the API server.',
      'It calls the needed services in parallel and merges the results.',
      'It returns a response shaped exactly for that screen.',
    ],
    numbers: [{ label: 'API growth', value: '~37× in 13 months', note: 'reported Feb 2011' }],
    components: [
      { name: 'Device adapters', role: 'Server-side code per device family; a backend-for-frontend.' },
      { name: 'Zuul edge', role: 'Front door for routing, filtering, and traffic shifting.' },
      { name: 'EVCache', role: 'Memcached-based cache in front of hot data.' },
    ],
    alternatives: [
      { option: 'Keep one generic REST API', verdict: 'Chatty on slow devices; every change affects everyone.' },
      { option: 'Let devices call services directly', verdict: 'Leaks internal structure and multiplies round trips.' },
    ],
    breaksNext: <p>On Christmas Eve 2012, a failure in one AWS region’s load balancers takes TV playback down.</p>,
    interview: { q: 'When is a backend-for-frontend worth it?', a: <p>When clients differ a lot in data needs and network cost. It trades a generic contract for fewer, bigger calls owned by client teams.</p> },
    sources: [S.apiRedesign, S.apiDifferences, S.zuul],
  },
  {
    title: 'Surviving a region',
    era: '2012–2013',
    summary: 'After a regional outage, Netflix runs in several AWS regions at once.',
    scale: 'Multi-region, active-active',
    added: ['dns', 'region'],
    nodes: [N.dns, N.region, N.client, N.edge, N.api, N.svc, N.cass, N.evc, N.oca, N.steer],
    edges: [e('client', 'dns'), e('dns', 'edge'), e('dns', 'region'), e('edge', 'api'), e('api', 'svc'), e('svc', 'cass'), e('svc', 'evc'), e('cass', 'region', { label: 'replication', async: true }), e('client', 'oca')],
    flows: [{ name: 'Failover', path: ['client', 'dns', 'region'], steps: ['The device resolves the Netflix endpoint', 'DNS now points it at a healthy region'] }],
    problem: <p>On December 24, 2012, an AWS load-balancer failure in one region stopped TV playback in the Americas for hours. The services were healthy; traffic just couldn’t reach them.</p>,
    decision: <p>Run active-active in more than one region. Replicate Cassandra across regions, invalidate caches remotely, and shift users between regions with DNS.</p>,
    tradeoff: <p>Double the capacity planning. Cross-region data is only eventually consistent.</p>,
    realWorld: <p>Netflix wrote up the outage, then Isthmus (mid-2013), then active-active across regions (December 2013).</p>,
    walkthrough: [
      'DNS sends each user to a home region.',
      'Writes land in that region and replicate to others asynchronously.',
      'Caches in other regions get invalidation messages.',
      'If a region fails, DNS moves its users to the survivors.',
    ],
    numbers: [
      { label: 'Christmas Eve outage start', value: '~12:24 PM PT', note: 'Dec 24, 2012' },
      { label: 'Regions active', value: '2+', note: 'from late 2013' },
    ],
    components: [
      { name: 'DNS routing', role: 'Maps users to regions; the lever for evacuation.' },
      { name: 'Cross-region replication', role: 'Cassandra copies data; EVCache gets remote invalidation.' },
    ],
    alternatives: [
      { option: 'Active-passive standby', verdict: 'Cheaper, but the standby is untested until the disaster.' },
      { option: 'Trust one region with three zones', verdict: 'Christmas Eve showed a whole region can fail.' },
    ],
    breaksNext: <p>Failover that is never practiced will fail when needed.</p>,
    interview: { q: 'What goes wrong in active-active?', a: <p>Conflicting writes, lagging replicas, and capacity: survivors must absorb the failed region’s load.</p> },
    sources: [S.christmas, S.isthmus, S.activeActive],
  },
]
