import type { EpisodeStage } from '../../components/ui'
import { AN as N, ae as e } from './episode-amazon-nodes'
import { AMAZON_SRC as S } from './episode-amazon-sources'

export const AMAZON_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'v0 · One store, one database',
    era: '1995',
    scale: 'A bookstore on the web',
    summary: 'One app and one database handle browsing, carts, and orders.',
    nodes: [N.shopper, N.mono, N.bigdb],
    edges: [e('shopper', 'mono'), e('mono', 'bigdb')],
    flows: [{ name: 'Buy', path: ['shopper', 'mono', 'bigdb'], steps: ['Shopper browses and checks out', 'Catalog, cart, and orders all live in one database'] }],
    problem: <p>Sell books online quickly with a small team. Correctness and speed of change matter more than scale.</p>,
    decision: <p>One application and one relational database for catalog, carts, inventory, and orders. Database transactions keep checkout consistent for free.</p>,
    tradeoff: <p>Every team ships the same codebase. The database is both the bottleneck and the single point of failure.</p>,
    realWorld: <p>Amazon opened as an online bookseller in 1995. Its October 1995 press release advertised more than one million titles.</p>,
    walkthrough: [
      'The shopper loads a product page; the app queries the database.',
      'Add to cart writes a row in the same database.',
      'Checkout runs one transaction: order row, stock update, payment record.',
    ],
    numbers: [
      { label: 'Titles offered', value: '1M+', note: 'Amazon, Oct 1995' },
      { label: 'Databases', value: '1', note: 'bottleneck and single point of failure' },
    ],
    components: [
      { name: 'Store app', role: 'Renders pages and runs all business logic.' },
      { name: 'Relational DB', role: 'Holds everything; transactions make checkout simple.' },
    ],
    alternatives: [
      { option: 'Separate services from day one', verdict: 'Too much overhead for a small team and unknown demand.' },
    ],
    breaksNext: <p>Browsing traffic grows far faster than buying, and every page view hits the database checkout depends on.</p>,
    interview: { q: 'When is a monolith the right answer?', a: <p>When the team is small and requirements change weekly. Split later along clear seams, once load or team size forces it.</p> },
    sources: [S.launch1995],
  },
  {
    title: 'v1 · Cache the catalog',
    era: 'Design step',
    scale: 'Page views ≫ orders',
    summary: 'Product pages come from a cache and a CDN, so browsing stops hurting checkout.',
    added: ['cdn', 'catalog', 'catcache'],
    nodes: [N.shopper, N.cdn, N.mono, N.bigdb, N.catalog, N.catcache],
    edges: [e('shopper', 'cdn'), e('shopper', 'mono'), e('mono', 'bigdb'), e('mono', 'catalog'), e('catalog', 'catcache')],
    flows: [{ name: 'Browse', path: ['shopper', 'mono', 'catalog', 'catcache'], steps: ['Product page request', 'The app asks the catalog service', 'Served from cache; images come from the CDN'] }],
    problem: <p>Browsing outnumbers buying by a wide margin. Every product page hammers the same database checkout needs.</p>,
    decision: <p>Split the read-heavy <strong>catalog</strong> into its own service with a cache. Move images and static files to a <strong>CDN</strong>.</p>,
    tradeoff: <p>Cached prices and stock can be slightly stale, so checkout must re-check them against the source of truth.</p>,
    realWorld: <p>The Amazon Builders’ Library article on caching warns about caches that services come to depend on, such as cold starts after a cache flush.</p>,
    walkthrough: [
      'Images and scripts come from the nearest CDN edge.',
      'The app asks the catalog service for product details.',
      'The catalog answers from cache; on a miss it reads the database and fills the cache.',
      'Checkout still reads the live price and stock.',
    ],
    numbers: [
      { label: 'Page views per order', value: '~50', note: 'estimate' },
      { label: 'Target cache hit rate', value: '> 90%', note: 'estimate for a hot catalog' },
    ],
    components: [
      { name: 'Catalog service', role: 'Owns product data and serves reads.' },
      { name: 'Catalog cache', role: 'Absorbs repeat reads; entries expire or are invalidated on change.' },
      { name: 'CDN', role: 'Serves images and static files close to shoppers.' },
    ],
    alternatives: [
      { option: 'Read replicas only', verdict: 'Helps, but every page still costs a database query.' },
      { option: 'Pre-render every page', verdict: 'Fast, but prices and stock change too often.' },
    ],
    breaksNext: <p>With a huge catalog, shoppers need help finding things they did not search for.</p>,
    interview: { q: 'What goes wrong when a cache becomes load-bearing?', a: <p>If it empties, all traffic hits the database at once. Warm caches before cutover and cap misses per second.</p> },
    sources: [S.caching],
  },
  {
    title: 'v2 · “Customers who bought this…”',
    era: '2003',
    scale: 'Millions of products',
    summary: 'A table of similar items is built offline, so each page only needs quick lookups.',
    added: ['recs'],
    nodes: [N.shopper, N.cdn, N.mono, N.bigdb, N.catalog, N.catcache, N.recs],
    edges: [e('shopper', 'cdn'), e('shopper', 'mono'), e('mono', 'bigdb'), e('mono', 'catalog'), e('catalog', 'catcache'), e('bigdb', 'recs', { label: 'order history', async: true }), e('recs', 'catcache')],
    flows: [{ name: 'Build + serve', path: ['bigdb', 'recs', 'catcache'], steps: ['An offline job reads purchase history', 'It stores each item’s similar items where pages can read them fast'] }],
    problem: <p>Comparing each shopper with millions of other shoppers is far too slow to run on every page view.</p>,
    decision: <p>Compare <strong>items</strong>, not shoppers. Offline, find items often bought together. Online, look up items similar to what this shopper bought.</p>,
    tradeoff: <p>The table lags new trends until the next build. Brand-new items have no history yet.</p>,
    realWorld: <p>Amazon engineers published “item-to-item collaborative filtering” in 2003. They wrote that its online computation scales independently of the number of customers and catalog items.</p>,
    walkthrough: [
      'Offline, count pairs of items bought by the same customers.',
      'Score how similar each pair is and keep the top matches per item.',
      'On a page view, take the shopper’s recent items.',
      'Look up their similar items, merge, and remove what they already own.',
    ],
    numbers: [
      { label: 'Published', value: '2003', note: 'IEEE Internet Computing' },
      { label: 'Online cost grows with', value: 'shopper’s own items', note: 'not catalog size' },
    ],
    components: [
      { name: 'Similar-items builder', role: 'Batch job over purchase history; writes the table.' },
      { name: 'Recommendation lookup', role: 'Reads a few table rows per page view.' },
    ],
    alternatives: [
      { option: 'Shopper-to-shopper similarity', verdict: 'Quality is good, but online cost grows with the customer base.' },
      { option: 'Bestseller lists only', verdict: 'Cheap, but the same for everyone.' },
    ],
    breaksNext: <p>One codebase for hundreds of engineers means every release is a big, slow, risky event.</p>,
    interview: { q: 'Where should expensive recommendation work run?', a: <p>Offline. Precompute the heavy similarity step and keep the page-time work to a few lookups.</p> },
    sources: [S.recs],
  },
  {
    title: 'v3 · Services with owners',
    era: 'By 2006',
    scale: 'Many teams',
    summary: 'The store is split into services, each owned end to end by one team.',
    added: ['gw', 'cart', 'cartdb', 'orderdb'],
    nodes: [N.shopper, N.cdn, N.gw, N.catalog, N.catcache, N.recs, N.cart, N.cartdb, N.orderdb],
    edges: [e('shopper', 'cdn'), e('shopper', 'gw'), e('gw', 'catalog'), e('catalog', 'catcache'), e('recs', 'catcache'), e('gw', 'cart'), e('cart', 'cartdb'), e('gw', 'orderdb')],
    flows: [{ name: 'Render page', path: ['shopper', 'gw', 'catalog', 'catcache'], steps: ['A page request reaches the web tier', 'The web tier calls many services, including the catalog', 'Each service answers from its own data'] }],
    problem: <p>The shared codebase slows every team. A change in one area can break checkout for everyone.</p>,
    decision: <p>Split into <strong>services</strong> behind APIs. Each team owns one service and its data, from design to running it in production. No team reads another team’s database directly.</p>,
    tradeoff: <p>A single page now depends on many network calls. Latency and partial failures become everyday problems.</p>,
    realWorld: <p>In a 2006 interview, CTO Werner Vogels described Amazon’s service-oriented architecture and the rule “You build it, you run it.” The 2007 Dynamo paper says one page can call over 150 services.</p>,
    walkthrough: [
      'The web tier receives a page request.',
      'It calls catalog, cart, recommendations, and more in parallel.',
      'Each service reads only its own store.',
      'The page renders with whatever answers arrive in time; missing parts degrade gracefully.',
    ],
    numbers: [
      { label: 'Services behind one page', value: '> 150', note: 'Dynamo paper, 2007' },
      { label: 'Direct DB access across teams', value: 'none', note: 'services only' },
    ],
    components: [
      { name: 'Web tier', role: 'Fans out to services and assembles the page.' },
      { name: 'Cart service', role: 'Owns the cart and its storage.' },
      { name: 'Orders DB', role: 'Owned by the order team; others use its API.' },
    ],
    alternatives: [
      { option: 'Shared database, split code', verdict: 'Teams still collide on schemas and locks.' },
      { option: 'Keep the monolith, add release trains', verdict: 'Fewer network hops, but slow, coupled releases.' },
    ],
    breaksNext: <p>The cart must accept writes even when servers or networks fail, or sales are lost.</p>,
    interview: { q: 'Why forbid reading another team’s database?', a: <p>The API becomes the contract. Owners can change storage, scale, or schema without breaking callers.</p> },
    sources: [S.vogels, S.dynamo],
  },
  {
    title: 'v4 · A cart that never says no',
    era: '2007',
    scale: 'Holiday peaks',
    summary: 'Add-to-cart always succeeds; if copies disagree, the cart merges them later.',
    added: ['cartdb'],
    nodes: [N.shopper, N.cdn, N.gw, N.catalog, N.catcache, N.recs, N.cart, N.cartKv, N.orderdb],
    edges: [e('shopper', 'cdn'), e('shopper', 'gw'), e('gw', 'catalog'), e('catalog', 'catcache'), e('recs', 'catcache'), e('gw', 'cart'), e('cart', 'cartdb'), e('gw', 'orderdb')],
    flows: [{ name: 'Add to cart', path: ['shopper', 'gw', 'cart', 'cartdb'], steps: ['Shopper adds an item', 'Web tier calls the cart service', 'Write accepted by available replicas; conflicts merged on read'] }],
    problem: <p>A failed “add to cart” is a lost sale. A strongly consistent database refuses writes during failures.</p>,
    decision: <p>Store carts in a key-value store that <strong>always accepts writes</strong>. It keeps conflicting versions and <strong>merges</strong> them on read, for example by taking the union of items.</p>,
    tradeoff: <p>Merging by union can bring back an item the shopper deleted. That is a deliberate product choice: a returning item is cheaper than a lost one.</p>,
    realWorld: <p>Amazon’s 2007 Dynamo paper uses the shopping cart as its main example and notes that deleted items can resurface. It reports the cart service handling over three million checkouts in a single day.</p>,
    walkthrough: [
      'The cart service writes to several replicas and succeeds once enough of them reply.',
      'During a network split, two replicas can accept different versions.',
      'Each version carries a vector clock showing its history.',
      'On read, conflicting versions are returned together and merged.',
    ],
    numbers: [
      { label: 'Checkouts in one day', value: '> 3M', note: 'Dynamo paper, 2007' },
      { label: 'Latency goal example', value: '300 ms @ 99.9%', note: 'Dynamo paper SLA example' },
    ],
    components: [
      { name: 'Always-writable cart store', role: 'Replicated key-value store that prefers availability.' },
      { name: 'Merge logic', role: 'Combines conflicting cart versions on read.' },
    ],
    alternatives: [
      { option: 'Strongly consistent SQL row', verdict: 'Simple, but rejects writes when a primary is unreachable.' },
      { option: 'Last write wins', verdict: 'Easy merge, but silently drops items.' },
    ],
    breaksNext: <p>Two shoppers buy the last unit at the same moment, and both get a confirmation.</p>,
    interview: { q: 'Why can a relaxed cart still produce correct orders?', a: <p>Checkout re-checks price and stock against strict systems. The loose model applies only to the cart itself.</p> },
    sources: [S.dynamo],
  },
  {
    title: 'v5 · Don’t sell what you don’t have',
    era: 'Design step',
    scale: 'Limited-stock deals',
    summary: 'Stock is decremented atomically, and unpaid holds expire back into stock.',
    added: ['inv', 'invdb'],
    nodes: [N.shopper, N.gw, N.catalog, N.catcache, N.cart, N.cartKv, N.inv, N.invdb, N.orderdb],
    edges: [e('shopper', 'gw'), e('gw', 'catalog'), e('catalog', 'catcache'), e('gw', 'cart'), e('cart', 'cartdb'), e('gw', 'inv'), e('inv', 'invdb'), e('gw', 'orderdb')],
    flows: [{ name: 'Reserve', path: ['shopper', 'gw', 'inv', 'invdb'], steps: ['Shopper starts checkout', 'Web tier asks inventory for a hold', 'A conditional decrement creates a hold with an expiry'] }],
    problem: <p>Two shoppers buy the last unit at once and both are confirmed. Or abandoned checkouts lock units, and a deal shows “sold out” while stock sits unpaid.</p>,
    decision: <p>Inventory gets its own service with <strong>atomic conditional decrements</strong> and <strong>time-limited holds</strong> that expire back into stock. The cart is optimistic; inventory is the strict gate.</p>,
    tradeoff: <p>Hold length is a trade-off. Too short and paying customers lose their unit. Too long and stock sits locked.</p>,
    walkthrough: [
      'Checkout asks inventory to hold one unit of the item.',
      'Inventory runs a single conditional update: decrement only if stock is above zero.',
      'Success creates a hold with an expiry time.',
      'Paid orders turn the hold permanent; expired holds return the unit.',
    ],
    numbers: [
      { label: 'Hold time', value: '~10 min', note: 'estimate; longer than a normal payment' },
      { label: 'Hot-deal writes on one item', value: '~17K/s', note: 'illustrative: 1M tries in 60 s' },
    ],
    components: [
      { name: 'Inventory service', role: 'The only writer of stock counts.' },
      { name: 'Stock table', role: 'Available units per item and warehouse, plus holds.' },
    ],
    alternatives: [
      { option: 'Read, then write', verdict: 'Two buyers read the same count; both succeed; oversold.' },
      { option: 'Decrement only at payment', verdict: 'No locking, but shoppers find out at the last step.' },
    ],
    breaksNext: <p>An order touches inventory, payment, and warehouses owned by different teams. No single transaction covers them.</p>,
    interview: { q: 'How do you stop overselling without a global lock?', a: <p>Use one conditional write per unit (decrement where stock &gt; 0). Zero rows updated means sold out.</p> },
    sources: [S.conditional],
  },
]
