import type { EpisodeStage } from '../../components/ui'
import { SN as N, se as e } from './episode-stripe-nodes'
import { STRIPE_SRC as S } from './episode-stripe-sources'

export const STRIPE_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'v6 · Card data never touches you',
    era: '2017',
    scale: 'Millions of checkouts',
    summary: 'The card number goes straight from the shopper’s browser to a vault; everyone else sees a token.',
    added: ['browser', 'vault'],
    nodes: [N.browser, N.merchant, N.apiIdem, N.vault, N.db, N.risk, N.psp, N.eventsHooks, N.ledger],
    edges: [e('browser', 'vault', { label: 'card number' }), e('browser', 'merchant', { label: 'token' }), e('merchant', 'api'), e('api', 'vault'), e('api', 'db'), e('api', 'risk'), e('risk', 'psp'), e('api', 'events', { async: true }), e('db', 'ledger')],
    flows: [{ name: 'Tokenize + charge', path: ['browser', 'vault', 'api', 'risk', 'psp'], steps: ['The browser sends the card straight to the vault', 'The merchant charges with the token; the API resolves it inside the vault', 'Risk scores the charge', 'The processor receives the real card number from the secure zone'] }],
    problem: <p>If raw card numbers pass through a merchant’s servers, those servers fall under the full PCI DSS audit. Most merchants cannot afford that.</p>,
    decision: <p>Collect card fields in an iframe served by the payment provider. The card goes straight to an isolated <strong>token vault</strong>. Merchants and most internal services only ever handle <strong>tokens</strong>.</p>,
    tradeoff: <p>The vault becomes the most sensitive system you run. It needs its own network zone, keys, and audits.</p>,
    realWorld: <p>Stripe launched Elements in October 2017. Its payment fields send card data straight to Stripe, so merchants qualify for the simplest PCI questionnaire, SAQ A.</p>,
    walkthrough: [
      'Stripe.js renders card fields in an iframe on the merchant’s page.',
      'On submit, the card goes directly to the vault, which returns a token.',
      'The merchant’s server sends the token, not the card, with the charge request.',
      'Inside the secure zone, the token is swapped for the card to call the processor.',
    ],
    numbers: [
      { label: 'Merchant PCI questionnaire', value: 'SAQ A', note: 'Stripe' },
      { label: 'Controls if you handle cards', value: '300+', note: 'PCI DSS, per Stripe guide' },
    ],
    components: [
      { name: 'Token vault', role: 'Stores card numbers encrypted in an isolated zone; issues and resolves tokens.' },
      { name: 'Hosted card fields', role: 'Iframes on the merchant page that post straight to the vault.' },
    ],
    alternatives: [
      { option: 'Encrypt cards in every service', verdict: 'Every service stays in audit scope, and keys spread everywhere.' },
      { option: 'Redirect to a hosted page', verdict: 'Smallest scope, but merchants lose control of the checkout UX.' },
    ],
    breaksNext: <p>The API must keep changing, but millions of integrations cannot all be rewritten.</p>,
    interview: { q: 'How does tokenization shrink compliance scope?', a: <p>Only systems that store or see card numbers are in scope. If they are isolated in the vault, everything else handles harmless tokens.</p> },
    sources: [S.elements, S.pci],
  },
  {
    title: 'v7 · Change without breaking',
    era: '2017',
    scale: 'Years of old integrations',
    summary: 'Each account stays on its API version, and data models are migrated live without downtime.',
    added: ['newint', 'compat', 'dbnew', 'migrate'],
    nodes: [N.merchant, N.newint, N.api, N.compat, N.db, N.dbnew, N.migrate, N.events],
    edges: [e('merchant', 'api', { label: 'pinned version' }), e('newint', 'api'), e('api', 'compat', { label: 'transform' }), e('api', 'db'), e('api', 'dbnew', { label: 'dual write' }), e('migrate', 'db'), e('migrate', 'dbnew'), e('api', 'events', { async: true })],
    flows: [
      { name: 'Old client', path: ['merchant', 'api', 'compat'], steps: ['An older integration calls the API with its pinned version', 'The response is built in the current shape, then transformed back step by step'] },
      { name: 'Migrate', path: ['migrate', 'db', 'migrate', 'dbnew'], steps: ['Backfill jobs read old records', 'Each record is converted', 'Converted records land in the new model while live writes go to both'] },
    ],
    problem: <p>The product must evolve, but a breaking change breaks thousands of businesses. Data models also need redesigns that cannot pause a live service.</p>,
    decision: <p>Pin each account to a <strong>date-based API version</strong>. Keep old behavior in small <strong>version change modules</strong>. Migrate data with <strong>dual writes</strong> and backfills instead of downtime.</p>,
    tradeoff: <p>Old versions never truly die, so the transform layer grows. Migrations take weeks and need careful verification.</p>,
    realWorld: <p>Stripe wrote in 2017 that accounts are pinned to the latest version on their first request, with changes kept in version change modules. That year it also described migrating hundreds of millions of subscription objects online.</p>,
    walkthrough: [
      'The first API call pins the account to the current version.',
      'Every later request is handled by the current code.',
      'The response passes back through version modules until it matches the pinned version.',
      'For a data redesign: dual-write old and new models, backfill, switch reads, switch writes, then delete old data.',
    ],
    numbers: [
      { label: 'API compatibility kept since', value: '2011', note: 'Stripe 2017' },
      { label: 'Objects migrated online', value: 'hundreds of millions', note: 'Stripe 2017' },
      { label: 'Serial at 1 s per object', value: '> 3 years', note: 'for 100M objects, Stripe’s example' },
    ],
    components: [
      { name: 'Version modules', role: 'Each one undoes a single breaking change for older versions.' },
      { name: 'Migration jobs', role: 'Parallel backfills with checks that old and new data match.' },
    ],
    alternatives: [
      { option: 'URL versions (/v1, /v2)', verdict: 'Each jump is big and painful, so customers delay upgrades for years.' },
      { option: 'Maintenance windows', verdict: 'Payments never sleep; any downtime is lost revenue for merchants.' },
    ],
    breaksNext: <p>A new law says payment data from one country must stay in that country.</p>,
    interview: { q: 'How do you ship a breaking API change safely?', a: <p>Add it behind a new version, keep a transform for old versions, and let customers upgrade on their own schedule.</p> },
    sources: [S.versioning, S.migrations],
  },
  {
    title: 'v8 · Data stays in-country',
    era: '2018',
    scale: 'Regulated markets',
    summary: 'Merchants are pinned to regional copies of the stack, called cells, so data stays where the law requires.',
    added: ['grouter', 'cellUS', 'cellEU', 'cellIN'],
    nodes: [N.merchant, N.grouter, N.cellUS, N.cellEU, N.cellIN],
    edges: [e('merchant', 'grouter'), e('grouter', 'cellUS'), e('grouter', 'cellEU'), e('grouter', 'cellIN', { label: 'by account' })],
    flows: [{ name: 'Route', path: ['merchant', 'grouter', 'cellIN'], steps: ['A request arrives with the merchant’s account id', 'The router looks up the account’s home cell and forwards it there'] }],
    problem: <p>Some regulators require payment data to stay inside the country. Separately, one bad deploy should not take down every merchant on Earth.</p>,
    decision: <p>Split the platform into <strong>cells</strong>: independent copies of the stack, each serving a set of accounts in a region. A thin global router sends each request to its home cell.</p>,
    tradeoff: <p>Features that span cells become distributed problems, such as global reports and platforms with sellers in many regions. Every deploy rolls out cell by cell.</p>,
    realWorld: <p>On 6 April 2018 the Reserve Bank of India directed that all payment system data be stored only in India, with six months to comply.</p>,
    walkthrough: [
      'Each account gets a home cell when it is created.',
      'The router maps account id → cell and forwards the request.',
      'Payments, ledger, and events for that account live only in its cell.',
      'Deploys go to one cell first, then the rest after health checks pass.',
    ],
    numbers: [
      { label: 'RBI directive', value: '6 Apr 2018', note: 'RBI' },
      { label: 'Time to comply', value: '6 months', note: 'RBI' },
    ],
    components: [
      { name: 'Account router', role: 'A small, highly available lookup from account to cell.' },
      { name: 'Cells', role: 'Full copies of the stack; failures stay inside one cell.' },
    ],
    alternatives: [
      { option: 'One global database with row-level rules', verdict: 'Data still crosses borders in backups and replicas.' },
      { option: 'Separate company per country', verdict: 'Compliant, but features and fixes diverge fast.' },
    ],
    breaksNext: <p>Europe starts requiring banks to challenge many online card payments.</p>,
    interview: { q: 'Why do cells help reliability, not just compliance?', a: <p>A failure or bad deploy hits one cell’s accounts. The blast radius is a slice of customers instead of everyone.</p> },
    sources: [S.rbi],
  },
  {
    title: 'v9 · Payments that need a customer step',
    era: '2019',
    scale: 'Europe: Strong Customer Authentication',
    summary: 'A payment can pause while the customer confirms with their bank, then resume.',
    added: ['acs'],
    nodes: [N.browser, N.merchant, N.apiIdem, N.dbIntent, N.risk, N.psp, N.acs, N.eventsHooks],
    edges: [e('browser', 'merchant'), e('merchant', 'api'), e('api', 'db'), e('api', 'risk'), e('risk', 'psp'), e('psp', 'acs', { label: '3DS' }), e('browser', 'acs', { label: 'challenge' }), e('api', 'events', { async: true })],
    flows: [{ name: 'Confirm', path: ['merchant', 'api', 'risk', 'psp', 'acs'], steps: ['Merchant confirms the PaymentIntent', 'API records the attempt and scores it', 'Processor asks the card issuer to authenticate', 'The issuer requires a challenge, so the intent moves to requires_action'] }],
    problem: <p>A new European rule requires many online payments to be authenticated by the customer’s bank. A synchronous charge call cannot wait for a person.</p>,
    decision: <p>Replace one-shot charges with a <strong>PaymentIntent</strong>: a state machine that can pause in <code>requires_action</code>, wait for the customer, and resume. Webhooks report the final result.</p>,
    tradeoff: <p>Integrations become asynchronous. Merchants must handle more states and rely on webhooks for the final outcome.</p>,
    realWorld: <p>In April 2019 Stripe announced the Payment Intents API for SCA, which came into force in Europe on 14 September 2019. It noted that similar rules in India in 2014 caused some businesses a conversion drop of over 25%.</p>,
    walkthrough: [
      'The merchant creates a PaymentIntent for the amount.',
      'Confirming it sends the payment to the processor and card issuer.',
      'If the issuer wants proof, the intent moves to requires_action.',
      'The browser shows the bank’s challenge; the customer approves.',
      'The intent resumes, succeeds or fails, and a webhook reports it.',
    ],
    numbers: [
      { label: 'SCA in force', value: '14 Sep 2019', note: 'Stripe newsroom' },
      { label: 'Conversion drop, India 2014', value: '>25%', note: 'some businesses, per Stripe' },
    ],
    components: [
      { name: 'PaymentIntent', role: 'Tracks one payment’s lifecycle across attempts, pauses, and retries.' },
      { name: 'Issuer 3DS', role: 'The customer’s bank decides whether to challenge.' },
    ],
    alternatives: [
      { option: 'Keep the synchronous charge API', verdict: 'Cannot represent “waiting for the customer”. Declines would rise.' },
      { option: 'Always challenge', verdict: 'Compliant but hurts conversion; exemptions exist for low-risk payments.' },
    ],
    breaksNext: <p>A card processor has a bad hour, and every payment on it fails.</p>,
    interview: { q: 'Why model a payment as an intent rather than a charge?', a: <p>A payment may take several attempts and a human step. An intent keeps one stable id and state across all of them.</p> },
    sources: [S.sca, S.intents],
  },
  {
    title: 'v10 · Failover without double charges',
    era: 'Design step',
    scale: 'Enterprise merchants, strict uptime',
    summary: 'Payments move to a backup processor, but only when the first one provably did not charge.',
    added: ['router', 'psp2'],
    nodes: [N.merchant, N.apiIdem, N.vault, N.db, N.risk, N.router, N.psp, N.psp2, N.eventsHooks, N.recon],
    edges: [e('merchant', 'api'), e('api', 'vault'), e('api', 'db'), e('api', 'risk'), e('risk', 'router'), e('router', 'psp'), e('router', 'psp2'), e('api', 'events', { async: true }), e('psp', 'recon', { async: true }), e('psp2', 'recon', { async: true })],
    flows: [{ name: 'Failover', path: ['merchant', 'api', 'risk', 'router', 'psp2'], steps: ['Charge arrives with a token', 'API records the attempt', 'Risk approves', 'Router sees processor A refusing connections and uses B'] }],
    problem: <p>A processor outage becomes your outage. But a timeout does not prove the charge failed. Blind retries on another processor charge customers twice.</p>,
    decision: <p>A <strong>router</strong> picks a processor by health, cost, and approval rate. It fails over only on errors that prove nothing happened. After a timeout it checks status first.</p>,
    tradeoff: <p>Some payments sit in “pending” while status is checked. Two processors mean two settlement formats to reconcile.</p>,
    walkthrough: [
      'The router tracks error rates and latency per processor.',
      'Connection refused or an explicit “not processed” error: safe to try processor B.',
      'Timeout: mark the payment pending and ask processor A for its status.',
      'If A did charge, keep it. If not, retry on B with the same payment id.',
      'Reconciliation voids any stray authorizations.',
    ],
    numbers: [
      { label: 'Outcomes per external call', value: '3', note: 'success · failure · unknown' },
      { label: 'Safe to fail over after', value: 'refused / not processed', note: 'never after a bare timeout' },
    ],
    components: [
      { name: 'Processor router', role: 'Health-aware routing with a circuit breaker per processor.' },
      { name: 'Status checker', role: 'Resolves unknown outcomes before any retry elsewhere.' },
    ],
    alternatives: [
      { option: 'Retry anything on the backup', verdict: 'Sounds resilient, but double-charges on every timeout.' },
      { option: 'Single processor, no failover', verdict: 'Safe from duplicates, but every outage stops payments.' },
    ],
    breaksNext: <p>Holiday peaks bring many times normal traffic, and every second of downtime costs merchants.</p>,
    interview: { q: 'Your primary processor times out. Do you retry on the backup?', a: <p>Not blindly. A timeout is “unknown”. Check status first, and fail over only on errors that prove no charge happened.</p> },
    sources: [S.retries],
  },
  {
    title: 'v11 · Surviving the busiest weekend',
    era: '2024',
    scale: 'Black Friday → Cyber Monday',
    summary: 'The system is pre-scaled and protected so the biggest shopping days feel like any other day.',
    nodes: [N.merchant, N.apiPeak, N.idem, N.dbSharded, N.risk, N.router, N.psp, N.psp2, N.events, N.ledger],
    edges: [e('merchant', 'api'), e('api', 'idem'), e('api', 'db'), e('api', 'risk'), e('risk', 'router'), e('router', 'psp'), e('router', 'psp2'), e('api', 'events', { async: true }), e('db', 'ledger')],
    flows: [{ name: 'Peak charge', path: ['merchant', 'api', 'risk', 'router', 'psp'], steps: ['A holiday checkout hits the API', 'Payments are prioritized; low-value traffic is shed first', 'Risk scores it under load', 'The router sends it to the healthiest processor'] }],
    problem: <p>A few days bring several times normal traffic. Any slowdown means lost sales for thousands of merchants at once.</p>,
    decision: <p>Pre-scale capacity, shard the payments data, and shed low-priority traffic before payment traffic. Idempotency keys make client retries during spikes harmless.</p>,
    tradeoff: <p>Capacity sits idle much of the year. Shedding rules must be tested so they never drop payment requests.</p>,
    realWorld: <p>Stripe reported processing 465 million transactions and over $31 billion from Black Friday through Cyber Monday 2024. It peaked at 137,000 transactions per minute with API uptime above 99.9999%.</p>,
    walkthrough: [
      'Forecast peak load and scale up ahead of time.',
      'Classify traffic: payments first, reporting and bulk jobs last.',
      'Under stress, reject the lowest priority requests quickly and cheaply.',
      'Clients retry with the same idempotency key, so nothing is charged twice.',
    ],
    numbers: [
      { label: 'Transactions, BFCM 2024', value: '465M', note: 'Stripe' },
      { label: 'Peak', value: '137K / min', note: '≈ 2,300 per second' },
      { label: 'API uptime', value: '> 99.9999%', note: 'Stripe' },
    ],
    components: [
      { name: 'Load shedding', role: 'Drops low-value work first so payments keep their capacity.' },
      { name: 'Sharded payments DB', role: 'Spreads writes so no single database is the ceiling.' },
    ],
    alternatives: [
      { option: 'Autoscale only when load arrives', verdict: 'Scaling lags a sudden spike; users time out first.' },
      { option: 'Queue all payments', verdict: 'Protects servers, but shoppers expect an answer in seconds.' },
    ],
    breaksNext: <p>Growth continues, so the cycle of measuring, splitting, and isolating repeats.</p>,
    interview: { q: 'What do you shed first under overload?', a: <p>Work that can wait, such as reports, exports, and dashboard refreshes. Keep capacity for requests that move money.</p> },
    sources: [S.bfcm],
  },
]
