import type { ArchEdge, ArchNode, EpisodeStage } from '../../components/ui'

// Stable positions across stages; each stage lists only the nodes it keeps.
const N = {
  merchant: { id: 'merchant', label: 'Merchant server', kind: 'client', x: 10, y: 50 },
  api: { id: 'api', label: 'Payments API', sub: 'stateless', kind: 'service', x: 30, y: 50 },
  idem: { id: 'idem', label: 'Idempotency store', sub: 'key → response', kind: 'cache', x: 30, y: 14 },
  db: { id: 'db', label: 'Payments DB', sub: 'state machine', kind: 'db', x: 52, y: 14 },
  ledger: { id: 'ledger', label: 'Ledger', sub: 'double-entry', kind: 'db', x: 72, y: 14 },
  recon: { id: 'recon', label: 'Reconciliation', sub: 'daily jobs', kind: 'worker', x: 90, y: 14 },
  risk: { id: 'risk', label: 'Risk scoring', sub: 'ms budget', kind: 'service', x: 52, y: 38 },
  router: { id: 'router', label: 'Processor router', kind: 'service', x: 72, y: 50 },
  psp: { id: 'psp', label: 'Processor A', sub: 'card networks', kind: 'external', x: 90, y: 38 },
  psp2: { id: 'psp2', label: 'Processor B', kind: 'external', x: 90, y: 62 },
  vault: { id: 'vault', label: 'Token vault', sub: 'PCI zone', kind: 'storage', x: 52, y: 62 },
  events: { id: 'events', label: 'Event log', kind: 'queue', x: 52, y: 86 },
  hooks: { id: 'hooks', label: 'Webhook sender', sub: 'signed, retried', kind: 'worker', x: 30, y: 86 },
  payouts: { id: 'payouts', label: 'Payouts + FX', kind: 'worker', x: 72, y: 86 },
  bank: { id: 'bank', label: 'Bank rails', kind: 'external', x: 90, y: 86 },
  cells: { id: 'cells', label: 'Regional cells', sub: 'EU · IN · US…', kind: 'external', x: 10, y: 86 },
} satisfies Record<string, ArchNode>

const e = (from: string, to: string, extra: Partial<ArchEdge> = {}): ArchEdge => ({ from, to, ...extra })

const CORE = [e('merchant', 'api'), e('api', 'idem'), e('api', 'db')]
const HOOKS = [e('api', 'events', { async: true }), e('events', 'hooks'), e('hooks', 'merchant', { label: 'POST', async: true })]
const MONEY = [e('db', 'ledger'), e('psp', 'recon', { label: 'settlement file', async: true }), e('recon', 'ledger')]

export const STRIPE_STAGES: EpisodeStage[] = [
  {
    title: 'v0 · One API, one processor',
    scale: 'A few merchants · 1 payment/s',
    nodes: [N.merchant, N.api, N.db, N.psp],
    edges: [e('merchant', 'api'), e('api', 'db'), e('api', 'psp')],
    flows: [{ name: 'Charge', path: ['merchant', 'api', 'psp'], steps: ['Merchant sends card details and an amount', 'API forwards the authorization to the card processor and returns the answer'] }],
    problem: <p>Accepting cards online means months of bank paperwork and a pile of processor-specific integrations. Developers just want to charge a card with one HTTP call.</p>,
    decision: <p>A thin, well-designed REST API in front of a single processor. Store every payment as a row and return the processor’s answer synchronously.</p>,
    tradeoff: <p>Fast to ship, but every network hiccup becomes a money bug, and the single processor is a single point of failure.</p>,
    realWorld: <p>Stripe’s early pitch was famously that you could start accepting payments with a handful of lines of code. The developer experience <em>was</em> the product.</p>,
  },
  {
    title: 'v1 · Idempotency + a state machine',
    scale: 'Thousands of merchants',
    added: ['idem'],
    nodes: [N.merchant, N.api, N.idem, N.db, N.psp],
    edges: [...CORE, e('api', 'psp')],
    flows: [{ name: 'Retry', path: ['merchant', 'api', 'idem'], steps: ['The merchant retries after a timeout with the same Idempotency-Key', 'The API finds the key and replays the stored response. The card is not charged twice'] }],
    problem: <p>A merchant’s request times out, so they retry, and the customer is charged twice. Timeouts are ambiguous: the first charge may or may not have happened.</p>,
    decision: <p>Require an <strong>idempotency key</strong> on every mutating call and store key → request fingerprint → final response. Model each payment as an explicit <strong>state machine</strong> (created → processing → succeeded / failed) so transitions happen only once.</p>,
    tradeoff: <p>Every write now does an extra lookup. Keys must outlive realistic retry windows, and replaying a key with a different body must be rejected, not silently accepted.</p>,
    realWorld: <p>Stripe’s public API accepts an <code>Idempotency-Key</code> header on POST requests. Its docs say keys can be pruned once they are at least 24 hours old.</p>,
  },
  {
    title: 'v2 · Events and webhooks',
    scale: 'Async payment methods, disputes',
    added: ['events', 'hooks'],
    nodes: [N.merchant, N.api, N.idem, N.db, N.psp, N.events, N.hooks],
    edges: [...CORE, e('api', 'psp'), ...HOOKS],
    flows: [{ name: 'Notify', path: ['api', 'events', 'hooks', 'merchant'], steps: ['A state change is appended to the event log', 'The webhook sender picks it up', 'Signed POST to the merchant, retried with backoff until it gets a 2xx'] }],
    problem: <p>Many outcomes arrive later: 3-D Secure challenges, bank debits that settle in days, disputes weeks afterwards. Merchants poll constantly and still miss changes.</p>,
    decision: <p>Every state change becomes an immutable <strong>event</strong>. A delivery service pushes signed webhooks with exponential-backoff retries. Delivery is at-least-once, so merchants dedupe by event id.</p>,
    tradeoff: <p>Ordering isn’t guaranteed across events, and merchants must handle duplicates and verify signatures. Your platform now owns a retry queue for millions of flaky endpoints.</p>,
    realWorld: <p>Stripe signs webhooks with a <code>Stripe-Signature</code> header. Its docs describe retrying failed live-mode deliveries for up to three days with exponential backoff.</p>,
  },
  {
    title: 'v3 · A ledger you can trust',
    scale: 'Real money at scale',
    added: ['ledger', 'recon'],
    nodes: [N.merchant, N.api, N.idem, N.db, N.ledger, N.recon, N.psp, N.events, N.hooks],
    edges: [...CORE, e('api', 'psp'), ...HOOKS, ...MONEY],
    flows: [{ name: 'Reconcile', path: ['psp', 'recon', 'ledger'], steps: ['The processor sends its daily settlement file', 'Reconciliation matches every line against ledger entries and flags mismatches'] }],
    problem: <p>Balances computed from mutable payment rows drift. Fees, refunds, FX, and chargebacks settle differently from what you recorded. Finance can’t close the books.</p>,
    decision: <p>An append-only <strong>double-entry ledger</strong> is the source of truth for money: every movement is balanced debits and credits. Daily <strong>reconciliation</strong> compares it with processor and bank reports and opens exceptions for humans.</p>,
    tradeoff: <p>Corrections become new entries, never edits, so reversals and adjustments need careful modeling. The ledger’s write volume is several times the payment volume.</p>,
    realWorld: <p>Stripe has published an engineering post about its internal ledger for tracking and validating money movement across its systems.</p>,
  },
  {
    title: 'v4 · Fraud in the hot path',
    scale: 'Card-testing attacks, chargebacks',
    added: ['risk'],
    nodes: [N.merchant, N.api, N.idem, N.db, N.ledger, N.recon, N.risk, N.psp, N.events, N.hooks],
    edges: [...CORE, e('api', 'risk'), e('risk', 'psp'), ...HOOKS, ...MONEY],
    flows: [{ name: 'Charge', path: ['merchant', 'api', 'risk', 'psp'], steps: ['Charge request arrives', 'Risk scores it against features from the whole network', 'Allowed charges go on to the processor'] }],
    problem: <p>Fraudsters test stolen cards in bursts, and every chargeback costs the merchant fees plus the goods. Blocking too aggressively loses real customers.</p>,
    decision: <p>Score every charge <strong>inline</strong> with an ML model plus merchant rules, under a strict latency budget. If the model is slow, fall back to rules instead of blocking the charge.</p>,
    tradeoff: <p>You trade a little latency and some false declines for fraud loss, and you need feature stores fresh enough to catch an attack mid-burst.</p>,
    realWorld: <p>Stripe Radar is publicly described as using machine learning trained on signals across Stripe’s network of businesses.</p>,
  },
  {
    title: 'v5 · Multiple processors + a vault',
    scale: 'Enterprise merchants, strict uptime',
    added: ['router', 'psp2', 'vault'],
    nodes: [N.merchant, N.api, N.idem, N.db, N.ledger, N.recon, N.risk, N.router, N.psp, N.psp2, N.vault, N.events, N.hooks],
    edges: [...CORE, e('api', 'risk'), e('api', 'vault'), e('risk', 'router'), e('router', 'psp'), e('router', 'psp2'), ...HOOKS, ...MONEY],
    flows: [{ name: 'Failover', path: ['merchant', 'api', 'risk', 'router', 'psp2'], steps: ['Charge arrives with a card token, not the raw number', 'Risk approves', 'Router sees processor A failing and routes to B', 'B authorizes'] }],
    problem: <p>A processor outage is your outage. And because raw card numbers flow through every service, all of them sit in PCI DSS audit scope.</p>,
    decision: <p><strong>Tokenize</strong> card data at the edge into an isolated vault so most services only see tokens. A <strong>router</strong> picks a processor per payment by health, cost, and approval rate, and fails over on hard errors.</p>,
    tradeoff: <p>Failover is only safe when you <em>know</em> no charge happened. Timeouts need a status check first (see the demo below). Multiple processors also mean multiple settlement formats to reconcile.</p>,
  },
  {
    title: 'v6 · Payouts and currencies',
    scale: 'Merchants in dozens of countries',
    added: ['payouts', 'bank'],
    nodes: [N.merchant, N.api, N.idem, N.db, N.ledger, N.recon, N.risk, N.router, N.psp, N.psp2, N.vault, N.events, N.hooks, N.payouts, N.bank],
    edges: [...CORE, e('api', 'risk'), e('api', 'vault'), e('risk', 'router'), e('router', 'psp'), e('router', 'psp2'), ...HOOKS, ...MONEY, e('ledger', 'payouts'), e('payouts', 'bank', { async: true })],
    flows: [{ name: 'Payout', path: ['ledger', 'payouts', 'bank'], steps: ['Available balance is computed from the ledger', 'Payout batches are converted at a locked FX rate and sent over local bank rails'] }],
    problem: <p>Charging is only half the job: merchants need the money in their bank accounts, in their currency, on a predictable schedule.</p>,
    decision: <p>A payout scheduler reads <strong>available balance from the ledger</strong>, converts at a rate that is locked and recorded as ledger entries, and submits batches to local bank rails with their own cut-off times.</p>,
    tradeoff: <p>Bank rails are slow, batch-oriented, and fail asynchronously (returned transfers days later), so payouts need their own state machine and reconciliation loop.</p>,
  },
  {
    title: 'v7 · Global cells',
    scale: 'Worldwide, regulated',
    added: ['cells'],
    nodes: [N.merchant, N.api, N.idem, N.db, N.ledger, N.recon, N.risk, N.router, N.psp, N.psp2, N.vault, N.events, N.hooks, N.payouts, N.bank, N.cells],
    edges: [...CORE, e('api', 'risk'), e('api', 'vault'), e('risk', 'router'), e('router', 'psp'), e('router', 'psp2'), ...HOOKS, ...MONEY, e('ledger', 'payouts'), e('payouts', 'bank', { async: true }), e('merchant', 'cells', { label: 'routed by account' })],
    flows: [{ name: 'Route', path: ['merchant', 'cells'], steps: ['Each merchant account is pinned to a cell in its region; data stays in-region'] }],
    problem: <p>Some countries require payment data to stay in-country, and one bad deploy or database failure shouldn’t take down every merchant on Earth.</p>,
    decision: <p>Partition into <strong>cells</strong>: independent copies of the stack, each serving a subset of merchants, pinned to a region where residency rules apply. A thin global layer routes by account.</p>,
    tradeoff: <p>Cross-cell features (platforms paying out to accounts in many regions, global reporting) become distributed problems. Every deploy now rolls cell by cell.</p>,
    realWorld: <p>For example, the Reserve Bank of India’s 2018 directive requires payment system data to be stored only in India, which pushes global processors toward in-country storage.</p>,
  },
]
