import type { ArchEdge, ArchNode, EpisodeStage } from '../../components/ui'

// Positions are fixed per id across stages so the diagram "grows" instead of reshuffling.
const N = {
  rider: { id: 'rider', label: 'Rider app', kind: 'client', x: 10, y: 25 },
  driver: { id: 'driver', label: 'Driver app', kind: 'client', x: 10, y: 75 },
  mono: { id: 'mono', label: 'Monolith', sub: 'trips + dispatch', kind: 'service', x: 50, y: 40 },
  db: { id: 'db', label: 'Single SQL DB', kind: 'db', x: 72, y: 14 },
  gw: { id: 'gw', label: 'API edge', kind: 'lb', x: 28, y: 50 },
  loc: { id: 'loc', label: 'Location ingest', sub: 'every ~4s', kind: 'service', x: 50, y: 76 },
  geo: { id: 'geo', label: 'Geo index', sub: 'in-memory, by area', kind: 'cache', x: 72, y: 64 },
  trips: { id: 'trips', label: 'Trip service', kind: 'service', x: 50, y: 28 },
  dispatch: { id: 'dispatch', label: 'Dispatch', sub: 'match supply/demand', kind: 'service', x: 50, y: 52 },
  eta: { id: 'eta', label: 'ETA / routing', kind: 'service', x: 72, y: 40 },
  store: { id: 'store', label: 'Trip store', sub: 'sharded, replicated', kind: 'db', x: 72, y: 14 },
  pay: { id: 'pay', label: 'Payments', kind: 'external', x: 90, y: 28 },
  surge: { id: 'surge', label: 'Pricing', sub: 'surge per cell', kind: 'service', x: 30, y: 14 },
  kafka: { id: 'kafka', label: 'Event log', sub: 'Kafka', kind: 'queue', x: 72, y: 88 },
  stream: { id: 'stream', label: 'Stream jobs', sub: 'ETA · fraud · supply', kind: 'worker', x: 90, y: 76 },
  region: { id: 'region', label: 'Other region', sub: 'active-active', kind: 'external', x: 90, y: 52 },
} satisfies Record<string, ArchNode>

const geoH3: ArchNode = { ...N.geo, label: 'Geo index', sub: 'hexagonal cells' }
const e = (from: string, to: string, extra: Partial<ArchEdge> = {}): ArchEdge => ({ from, to, ...extra })

const coreEdges = [
  e('rider', 'gw'), e('driver', 'gw'), e('gw', 'trips'), e('gw', 'loc'), e('loc', 'geo'),
  e('trips', 'dispatch'), e('dispatch', 'geo'), e('dispatch', 'eta'),
]

export const UBER_STAGES: EpisodeStage[] = [
  {
    title: 'v0 · One city, one server',
    scale: 'one city · hundreds of drivers',
    nodes: [N.rider, N.driver, N.mono, N.db],
    edges: [e('rider', 'mono'), e('driver', 'mono', { label: 'poll' }), e('mono', 'db')],
    flows: [
      { name: 'Request ride', path: ['rider', 'mono', 'db'], steps: ['Rider taps “Request”', 'The monolith scans every driver row for the closest one'] },
      { name: 'Driver poll', path: ['driver', 'mono'], steps: ['Each driver app asks “any job for me?” every few seconds'] },
    ],
    problem: <p>Prove that people will tap a button and get a car. One city, a small fleet, and a team that must ship weekly.</p>,
    decision: <p>A single app and a single SQL database. Driver apps poll for jobs, and matching is a full scan for the nearest available driver.</p>,
    tradeoff: <p>Polling and full scans are cheap to build but scale with <em>drivers × cities</em>. Every new city makes every request slower.</p>,
  },
  {
    title: 'v1 · Locations are a firehose',
    scale: 'dozens of cities · 10Ks of drivers',
    added: ['gw', 'loc', 'geo'],
    nodes: [N.rider, N.driver, N.gw, N.mono, N.loc, N.geo, N.db],
    edges: [e('rider', 'gw'), e('driver', 'gw'), e('gw', 'mono'), e('gw', 'loc'), e('loc', 'geo'), e('mono', 'geo'), e('mono', 'db')],
    flows: [{ name: 'Location update', path: ['driver', 'gw', 'loc', 'geo'], steps: ['Driver app sends GPS every few seconds', 'The edge routes to location ingest', 'Only the latest position per driver is kept, in memory, bucketed by area'] }],
    problem: <p>Driver GPS pings now dwarf every other write. Storing each one as a row in the main database locks tables and slows trips.</p>,
    decision: <p>Treat location as <strong>ephemeral, latest-value-wins</strong> data. A dedicated ingest service keeps each driver’s last position in an in-memory index bucketed by area, so “who is near X?” reads a few buckets instead of scanning.</p>,
    tradeoff: <p>Losing the index on restart is acceptable, because drivers re-report within seconds. Exact history now needs a separate, asynchronous path.</p>,
  },
  {
    title: 'v2 · Dispatch becomes its own brain',
    scale: '100s of cities',
    added: ['trips', 'dispatch', 'eta'],
    nodes: [N.rider, N.driver, N.gw, N.trips, N.dispatch, N.eta, N.loc, N.geo, N.db],
    edges: [...coreEdges, e('trips', 'db')],
    flows: [{ name: 'Request ride', path: ['rider', 'gw', 'trips', 'dispatch', 'geo'], steps: ['Rider requests a trip', 'Edge routes to the trip service', 'Trip service creates the request and asks dispatch for a match', 'Dispatch pulls nearby candidates, then ranks them by road ETA'] }],
    problem: <p>The straight-line nearest driver is often the wrong one: they are across a river, on a highway going the other way, or about to finish another trip.</p>,
    decision: <p>Split out <strong>dispatch</strong>. It matches on <em>road-network ETA</em> from a routing service, not distance, and it can match a short window of requests together instead of first come, first served.</p>,
    tradeoff: <p>Batching adds a small wait (seconds) before a match in exchange for lower total pickup time. ETA calls add latency and a dependency that must degrade gracefully.</p>,
  },
  {
    title: 'v3 · A trip must never be lost',
    scale: 'millions of trips / day',
    added: ['store', 'pay'],
    nodes: [N.rider, N.driver, N.gw, N.trips, N.dispatch, N.eta, N.loc, N.geo, N.store, N.pay],
    edges: [...coreEdges, e('trips', 'store'), e('trips', 'pay', { async: true })],
    flows: [{ name: 'Accept trip', path: ['driver', 'gw', 'trips', 'store'], steps: ['Driver taps “Accept”', 'Routed to the trip service', 'State moves requested → accepted with a conditional write; retries are no-ops'] }],
    problem: <p>Phones drop off networks, drivers double-tap, and servers restart mid-request. Two drivers accepting the same trip, or a finished trip that is never charged, costs real money and trust.</p>,
    decision: <p>Model a trip as an explicit <strong>state machine</strong> (requested → accepted → arrived → on trip → completed). Every transition is a conditional, idempotent write to a durable, replicated store. Payment is triggered asynchronously from the completed state.</p>,
    tradeoff: <p>Strict transitions reject some “legitimate” edge cases (e.g. a late accept after cancel), and product must define what happens in each one.</p>,
    realWorld: <p>Uber has described building <strong>Schemaless</strong>, an append-only datastore layered on sharded MySQL, for trip data during its hypergrowth years.</p>,
  },
  {
    title: 'v4 · Hexagons and surge',
    scale: 'global · 10,000+ cities',
    added: ['surge'],
    nodes: [N.rider, N.driver, N.gw, N.surge, N.trips, N.dispatch, N.eta, N.loc, geoH3, N.store, N.pay],
    edges: [...coreEdges, e('trips', 'store'), e('trips', 'pay', { async: true }), e('gw', 'surge'), e('surge', 'geo', { label: 'supply/demand' })],
    flows: [{ name: 'Price quote', path: ['rider', 'gw', 'surge', 'geo'], steps: ['Rider opens the app and sets a destination', 'Edge asks pricing for a quote', 'Pricing reads supply and demand for the rider’s cell and nearby cells'] }],
    problem: <p>Ad-hoc city polygons and square grids distort distance and make “neighbouring area” awkward. Pricing needs a consistent way to measure supply and demand everywhere.</p>,
    decision: <p>Index the world into <strong>hexagonal cells</strong> at multiple resolutions. Hexagons have uniform neighbour distances, so smoothing demand across neighbours is simple. Surge multipliers are computed per cell from recent requests vs available drivers.</p>,
    tradeoff: <p>Cell boundaries still create edge effects (a price jump across a street). Surge is also a product and fairness question, not only an engineering one.</p>,
    realWorld: <p>Uber open-sourced <strong>H3</strong>, its hierarchical hexagonal geospatial index, in 2018. It is now widely used beyond Uber.</p>,
  },
  {
    title: 'v5 · Everything is a stream',
    scale: 'millions of events / second (order of magnitude)',
    added: ['kafka', 'stream'],
    nodes: [N.rider, N.driver, N.gw, N.surge, N.trips, N.dispatch, N.eta, N.loc, geoH3, N.store, N.pay, N.kafka, N.stream],
    edges: [...coreEdges, e('trips', 'store'), e('trips', 'pay', { async: true }), e('gw', 'surge'), e('surge', 'geo'),
      e('loc', 'kafka', { async: true }), e('kafka', 'stream'), e('stream', 'eta', { label: 'live speeds' })],
    flows: [{ name: 'Event pipeline', path: ['driver', 'gw', 'loc', 'kafka', 'stream', 'eta'], steps: ['GPS ping arrives', 'Routed to ingest', 'Ingest also publishes to the event log', 'Stream jobs compute live road speeds, fraud signals, and supply heatmaps', 'Fresh speeds feed back into ETA'] }],
    problem: <p>ETA quality, fraud detection, driver incentives, and analytics all need the same live signals, and every team is building its own brittle pipeline.</p>,
    decision: <p>Publish locations and trip events to a <strong>shared durable log</strong>. Stream processors derive features (road speeds, anomaly scores) and feed them back to online services, and the same log lands in the warehouse.</p>,
    tradeoff: <p>The log becomes critical shared infrastructure: schema evolution, retention costs, and consumer lag are now everyone’s problem.</p>,
    realWorld: <p>Uber has written extensively about running one of the largest <strong>Kafka</strong> deployments, used for both real-time and batch pipelines.</p>,
  },
  {
    title: 'v6 · Survive a region outage mid-trip',
    scale: 'multi-region, always on',
    added: ['region'],
    nodes: [N.rider, N.driver, N.gw, N.surge, N.trips, N.dispatch, N.eta, N.loc, geoH3, N.store, N.pay, N.kafka, N.stream, N.region],
    edges: [...coreEdges, e('trips', 'store'), e('trips', 'pay', { async: true }), e('gw', 'surge'), e('surge', 'geo'),
      e('loc', 'kafka', { async: true }), e('kafka', 'stream'), e('store', 'region', { label: 'replicate', async: true }), e('gw', 'region')],
    flows: [{ name: 'Failover', path: ['driver', 'gw', 'region'], steps: ['The primary region degrades mid-trip', 'The edge re-routes the driver and rider to another region, which already has the trip state'] }],
    problem: <p>A data-center outage must not strand a rider in a car with no working app, or lose the fare for a trip already in progress.</p>,
    decision: <p>Run regions <strong>active-active</strong> and replicate trip state across them. Keep enough state on the phones (current trip, last known state) that a new region can resume the trip, reconciling with the server when it is reachable.</p>,
    tradeoff: <p>Replication lag means a failover may briefly show a slightly stale state. The client and server must reconcile deterministically, and that logic is hard to test, so exercise it with drills.</p>,
  },
]
