import type { ArchEdge, ArchNode, EpisodeStage } from '../../components/ui'

// Fixed positions per id so each stage grows the same picture.
const N = {
  guest: { id: 'guest', label: 'Guest', sub: 'web · app', kind: 'client', x: 10, y: 25 },
  host: { id: 'host', label: 'Host', sub: 'web · app', kind: 'client', x: 10, y: 75 },
  mono: { id: 'mono', label: 'Monolith', sub: 'listings + booking', kind: 'service', x: 42, y: 50 },
  db: { id: 'db', label: 'Primary DB', sub: 'listings · bookings', kind: 'db', x: 72, y: 56 },
  search: { id: 'search', label: 'Search', kind: 'service', x: 42, y: 18 },
  index: { id: 'index', label: 'Search index', sub: 'geo + text', kind: 'search', x: 72, y: 18 },
  cdc: { id: 'cdc', label: 'Change stream', sub: 'CDC events', kind: 'queue', x: 72, y: 37 },
  hold: { id: 'hold', label: 'Holds', sub: 'short TTL', kind: 'cache', x: 90, y: 70 },
  pay: { id: 'pay', label: 'Payment provider', kind: 'external', x: 42, y: 86 },
  payout: { id: 'payout', label: 'Payout scheduler', kind: 'worker', x: 72, y: 86 },
  ml: { id: 'ml', label: 'Ranking & pricing', sub: 'ML models', kind: 'worker', x: 90, y: 18 },
  trust: { id: 'trust', label: 'Trust & safety', kind: 'worker', x: 90, y: 42 },
  gw: { id: 'gw', label: 'API gateway', kind: 'lb', x: 26, y: 50 },
  listing: { id: 'listing', label: 'Listing service', kind: 'service', x: 44, y: 38 },
  booking: { id: 'booking', label: 'Booking service', kind: 'service', x: 44, y: 62 },
} satisfies Record<string, ArchNode>

const indexAvail: ArchNode = { ...N.index, sub: 'geo + text + nights' }
const e = (from: string, to: string, extra: Partial<ArchEdge> = {}): ArchEdge => ({ from, to, ...extra })

export const AIRBNB_STAGES: EpisodeStage[] = [
  {
    title: 'v0 · A monolith and a database',
    scale: 'hundreds of listings',
    nodes: [N.guest, N.host, N.mono, N.db],
    edges: [e('guest', 'mono'), e('host', 'mono'), e('mono', 'db')],
    flows: [
      { name: 'Book', path: ['guest', 'mono', 'db'], steps: ['Guest picks dates and taps “Reserve”', 'The monolith checks for overlapping bookings and inserts one'] },
      { name: 'List a home', path: ['host', 'mono', 'db'], steps: ['Host creates a listing with photos and a calendar', 'Stored as rows in the same database'] },
    ],
    problem: <p>Find out whether strangers will pay to sleep in each other’s homes. Speed of iteration beats everything else.</p>,
    decision: <p>One web app and one relational database. Search is a SQL query with a bounding box, a price filter, and a “no overlapping booking” subquery.</p>,
    tradeoff: <p>Everything is simple and transactional, but search, the most-read path, runs expensive date-overlap queries on the same database that takes bookings.</p>,
    realWorld: <p>Airbnb has described its early product as a Ruby on Rails monolith, later nicknamed the “monorail”.</p>,
  },
  {
    title: 'v1 · Search gets its own index',
    scale: '100Ks of listings · many cities',
    added: ['search', 'index'],
    nodes: [N.guest, N.host, N.search, N.index, N.mono, N.db],
    edges: [e('guest', 'search'), e('search', 'index'), e('guest', 'mono'), e('host', 'mono'), e('mono', 'db'), e('mono', 'index', { label: 'reindex', async: true })],
    flows: [{ name: 'Search', path: ['guest', 'search', 'index'], steps: ['Guest searches “Lisbon, 3 guests”', 'Search queries a geo + text index, not the primary DB'] }],
    problem: <p>Search traffic is 100× booking traffic, and SQL overlap queries across hundreds of thousands of listings are slow and hammer the primary database.</p>,
    decision: <p>Move search to a dedicated <strong>search index</strong> (geo, amenities, price, text) fed asynchronously when listings change. The primary database only serves writes and detail pages.</p>,
    tradeoff: <p>The index is eventually consistent. A just-edited listing can show stale info for seconds, which is acceptable for browsing but not for booking.</p>,
  },
  {
    title: 'v2 · Availability is the hard filter',
    scale: 'millions of listings · 365-night calendars',
    added: ['cdc'],
    nodes: [N.guest, N.host, N.search, indexAvail, N.cdc, N.mono, N.db],
    edges: [e('guest', 'search'), e('search', 'index'), e('guest', 'mono'), e('host', 'mono'), e('mono', 'db'),
      e('db', 'cdc', { async: true }), e('cdc', 'index', { label: 'nights bitmap' })],
    flows: [{ name: 'Availability update', path: ['guest', 'mono', 'db', 'cdc', 'index'], steps: ['A guest books nights 10–12', 'The monolith writes the booking', 'The change is captured from the database log', 'The listing’s nightly availability bits are updated in the index'] }],
    problem: <p>“Free for my dates” is the filter every search uses. The index knows geo and price but not the calendar, so results show homes that turn out to be booked.</p>,
    decision: <p>Materialize each listing’s calendar into the index as <strong>per-night availability</strong> (a bitmap or ranges). A search ANDs the requested nights against it. Updates flow from the booking database through <strong>change data capture</strong>, so they never depend on app code remembering to reindex.</p>,
    tradeoff: <p>There is still a lag of seconds between a booking and the index. Search may show a home that was just taken, so the booking path must re-check authoritatively.</p>,
  },
  {
    title: 'v3 · Never double-book',
    scale: 'peak seasons · many concurrent guests per hot listing',
    added: ['hold'],
    nodes: [N.guest, N.host, N.search, indexAvail, N.cdc, N.mono, N.db, N.hold],
    edges: [e('guest', 'search'), e('search', 'index'), e('guest', 'mono'), e('host', 'mono'), e('mono', 'db'),
      e('db', 'cdc', { async: true }), e('cdc', 'index'), e('mono', 'hold')],
    flows: [{ name: 'Book', path: ['guest', 'mono', 'hold', 'mono', 'db'], steps: ['Guest starts checkout', 'A short hold is placed on those nights for this guest', 'The hold protects the nights during payment', 'The booking commits only if no overlapping booking exists'] }],
    problem: <p>Two guests can see the same free nights and both check out, and payment takes seconds. Check-then-insert races give two confirmations for one home.</p>,
    decision: <p>The database is the source of truth. The booking insert is guarded by a constraint or conditional write, such as an exclusion constraint on (listing, night range) or a unique row per listing-night. A <strong>short hold</strong> with a TTL reserves the nights while the guest pays.</p>,
    tradeoff: <p>Holds can block real guests if abandoned, so keep TTLs short and visible. Strict constraints turn races into errors, and the UX must turn those into “try these other dates”.</p>,
  },
  {
    title: 'v4 · Money moves in two directions',
    scale: 'multi-currency · global hosts',
    added: ['pay', 'payout'],
    nodes: [N.guest, N.host, N.search, indexAvail, N.cdc, N.mono, N.db, N.hold, N.pay, N.payout],
    edges: [e('guest', 'search'), e('search', 'index'), e('guest', 'mono'), e('host', 'mono'), e('mono', 'db'),
      e('db', 'cdc', { async: true }), e('cdc', 'index'), e('mono', 'hold'), e('mono', 'pay', { label: 'charge' }),
      e('db', 'payout', { async: true }), e('payout', 'pay', { label: 'payout' }), e('pay', 'host')],
    flows: [
      { name: 'Charge', path: ['guest', 'mono', 'pay'], steps: ['Guest confirms', 'The platform charges the guest via the payment provider, with an idempotency key'] },
      { name: 'Payout', path: ['db', 'payout', 'pay', 'host'], steps: ['After check-in, the stay becomes payable', 'The scheduler batches payouts per host and currency', 'Funds reach the host’s account'] },
    ],
    problem: <p>Guests pay at booking, but hosts should be paid only after the stay starts, in their own currency, with refunds and cancellations possible in between.</p>,
    decision: <p>Charge the guest at booking and hold the funds on the platform. A <strong>payout scheduler</strong> releases money to the host after check-in. Every movement is recorded in a ledger, and every provider call carries an idempotency key.</p>,
    tradeoff: <p>The platform now carries regulatory and reconciliation burden: money in flight, FX, and chargebacks. This deserves its own team (see the Stripe episode).</p>,
  },
  {
    title: 'v5 · Ranking, pricing, and trust',
    scale: 'tens of millions of searches / day (order of magnitude)',
    added: ['ml', 'trust'],
    nodes: [N.guest, N.host, N.search, indexAvail, N.cdc, N.mono, N.db, N.hold, N.pay, N.payout, N.ml, N.trust],
    edges: [e('guest', 'search'), e('search', 'index'), e('guest', 'mono'), e('host', 'mono'), e('mono', 'db'),
      e('db', 'cdc', { async: true }), e('cdc', 'index'), e('mono', 'hold'), e('mono', 'pay'), e('db', 'payout', { async: true }), e('payout', 'pay'),
      e('cdc', 'ml', { async: true }), e('ml', 'index', { label: 'scores' }), e('cdc', 'trust', { async: true }), e('trust', 'mono', { label: 'flag / block' })],
    flows: [{ name: 'Learn', path: ['db', 'cdc', 'ml', 'index'], steps: ['Bookings, clicks, and reviews land as events', 'Models train on what guests actually book', 'Ranking scores and price suggestions are pushed back to the index'] }],
    problem: <p>Showing available homes sorted by price is not enough. Guests need the listings they will actually book, hosts need help pricing, and fraud and fake listings erode trust.</p>,
    decision: <p>Train <strong>ranking models</strong> on booking outcomes and serve scores alongside the index. Offer hosts <strong>smart pricing</strong> suggestions from demand signals, and run trust and safety scoring on the same event stream to flag risky bookings before they happen.</p>,
    tradeoff: <p>Ranking changes are marketplace changes: they shift income between hosts. They need careful A/B testing, fairness review, and guardrail metrics.</p>,
    realWorld: <p>Airbnb has published about its search ranking journey, including a widely cited 2019 paper on applying deep learning to Airbnb search.</p>,
  },
  {
    title: 'v6 · Break up the monolith',
    scale: 'thousands of engineers',
    added: ['gw', 'listing', 'booking'],
    nodes: [N.guest, N.host, N.gw, N.search, indexAvail, N.cdc, N.listing, N.booking, N.db, N.hold, N.pay, N.payout, N.ml, N.trust],
    edges: [e('guest', 'gw'), e('host', 'gw'), e('gw', 'search'), e('gw', 'listing'), e('gw', 'booking'), e('search', 'index'),
      e('listing', 'db'), e('booking', 'db'), e('booking', 'hold'), e('booking', 'pay'), e('db', 'cdc', { async: true }), e('cdc', 'index'),
      e('cdc', 'ml', { async: true }), e('ml', 'index'), e('cdc', 'trust', { async: true }), e('trust', 'booking'), e('db', 'payout', { async: true }), e('payout', 'pay')],
    flows: [
      { name: 'Book', path: ['guest', 'gw', 'booking', 'hold'], steps: ['Guest reserves', 'Gateway routes to the booking service', 'The booking service owns holds, constraints, and the booking lifecycle'] },
      { name: 'Search', path: ['guest', 'gw', 'search', 'index'], steps: ['Guest searches', 'Gateway routes to search', 'Search reads the availability-aware index and ranking scores'] },
    ],
    problem: <p>Hundreds of teams ship into one codebase and deploy train. Builds are slow, one bug blocks everyone, and ownership of core flows like booking is blurry.</p>,
    decision: <p>Carve the monolith into <strong>services with clear data ownership</strong> (listings, booking, payments, search) behind a gateway. Migrate incrementally, path by path, with the monolith proxying to new services until it can be retired.</p>,
    tradeoff: <p>Network calls replace function calls, cross-service transactions become sagas, and platform investment (service framework, tracing, schema contracts) is now mandatory.</p>,
    realWorld: <p>Airbnb has publicly described its multi-year migration from the Rails monolith to a service-oriented architecture, starting around 2018.</p>,
  },
]
