import type { EpisodeStage } from '../../components/ui'
import { SN, SRC, se } from './episode-spotify-stage-nodes'

// Stages 7–11: recommendations, cloud, org scale, new audio, search.
export const SPOTIFY_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'Discover Weekly',
    era: '2015',
    scale: 'One playlist per user, every week',
    summary: 'Recommendations ship as an ordinary playlist, reusing the sync path that already exists.',
    added: ['recs'],
    nodes: [SN.client, SN.ap, SN.meta, SN.keys, SN.playlist, SN.pldb, SN.cdn, SN.events, SN.lake, SN.recs],
    edges: [se('client', 'ap'), se('ap', 'meta'), se('ap', 'keys'), se('ap', 'playlist'), se('playlist', 'pldb'), se('client', 'cdn'), se('ap', 'events', { async: true }), se('events', 'lake'), se('lake', 'recs'), se('recs', 'pldb', { label: 'writes playlist' })],
    flows: [{ name: 'Weekly mix', path: ['lake', 'recs', 'pldb'], steps: ['Batch jobs read listening history', 'They write a fresh personal playlist that syncs like any other'] }],
    problem: <p>A huge catalog is useless if people only replay what they know. Discovery drives retention and helps long-tail artists.</p>,
    decision: <p>Compute recommendations offline from listening history. Deliver them as a personal playlist, so offline, sync, and caching all work with no new client code.</p>,
    tradeoff: <p>Results are days old. Generating a playlist for every user creates a big scheduled compute spike that must be spread out.</p>,
    realWorld: <p>Spotify launched <strong>Discover Weekly</strong> in 2015. By 2020 it said listeners had spent over 2.3 billion hours on these playlists.</p>,
    walkthrough: [
      'Listening events land in the data platform.',
      'Batch jobs compute candidate tracks per user.',
      'Ranking picks a fixed-length list.',
      'The list is written as a normal playlist version.',
      'Devices sync it like any other edit.',
    ],
    numbers: [
      { label: 'Hours streamed (2015–2020)', value: '2.3B+', note: 'Spotify Newsroom' },
      { label: 'Refresh cadence', value: 'weekly' },
    ],
    components: [{ name: 'Recommendations', role: 'Offline jobs that turn listening history into ranked personal playlists.' }],
    alternatives: [
      { option: 'Fully online recommendations', verdict: 'Fresher, but needs new serving, caching, and offline support.' },
      { option: 'A new “recs” feed type', verdict: 'Duplicates the playlist sync stack.' },
    ],
    breaksNext: <p>Running data centers and a growing data platform slows every team down.</p>,
    interview: { q: 'Why ship recommendations as playlists?', a: <p>It reuses a delivery path that already handles sync, offline, and caching. New features should ride trusted rails.</p> },
    sources: [SRC.dw],
  },
  {
    title: 'Move to Google Cloud',
    era: '2016–2018',
    scale: '2,000 services · 100+ PB',
    summary: 'Spotify moved its services and data platform from its own data centers to Google Cloud.',
    added: ['cloud'],
    nodes: [SN.client, SN.ap, SN.meta, SN.playlist, SN.pldb, { ...SN.events, label: 'Cloud Pub/Sub', sub: 'event delivery' }, { ...SN.lake, label: 'Managed data', sub: 'warehouse · pipelines' }, SN.recs, SN.cloud, SN.cdn],
    edges: [se('client', 'ap'), se('ap', 'meta'), se('ap', 'playlist'), se('playlist', 'pldb'), se('client', 'cdn'), se('ap', 'events', { async: true }), se('events', 'lake'), se('lake', 'recs'), se('recs', 'pldb'), se('cloud', 'meta', { label: 'hosts' })],
    flows: [{ name: 'Report', path: ['client', 'ap', 'events', 'lake'], steps: ['Same client events as before, accepted at the edge', 'Now carried by managed pub/sub', 'Processed on managed data services'] }],
    problem: <p>Four data-center regions, around 100 teams, and 20,000 daily data jobs. Operating the hardware and data stack takes effort away from the product.</p>,
    decision: <p>Move to a public cloud. Migrate user-facing services first, then data. Replace the self-run event pipeline with managed pub/sub.</p>,
    tradeoff: <p>A long, risky migration and a strong vendor dependency. Some systems are rewritten rather than lifted.</p>,
    realWorld: <p>Spotify announced the Google Cloud move in 2016. Its engineering blog says traffic was fully on GCP by May 2017. The last of four data centers closed in 2018.</p>,
    walkthrough: [
      'Plan the move per service and per dataset.',
      'Route user-facing traffic to cloud regions first.',
      'Move event delivery onto managed pub/sub.',
      'Migrate data pipelines and storage.',
      'Close the data centers one by one.',
    ],
    numbers: [
      { label: 'Services', value: '~2,000' },
      { label: 'Daily data pipeline runs', value: '20,000' },
      { label: 'Data', value: '100+ PB' },
      { label: 'Traffic fully on GCP', value: 'May 2017' },
    ],
    components: [{ name: 'Google Cloud', role: 'Hosts services and managed data systems (pub/sub, warehouse, pipelines).' }],
    alternatives: [
      { option: 'Stay on-prem', verdict: 'Full control, but teams keep running hardware.' },
      { option: 'Lift-and-shift everything', verdict: 'Faster, but misses managed services; Spotify mixed both.' },
    ],
    breaksNext: <p>Hundreds of teams now own thousands of services. Nobody can find anything.</p>,
    interview: { q: 'How do you migrate a live service to the cloud?', a: <p>Move in slices, user-facing first, with traffic shifting and rollback per service. Keep both sides running until data is verified.</p> },
    sources: [SRC.gcpHistory, SRC.gcpDeal, SRC.events2],
  },
  {
    title: 'Squads + Backstage',
    era: '2012 → 2020',
    scale: 'Hundreds of teams',
    summary: 'Small autonomous teams own services end to end, and a developer portal keeps them discoverable.',
    added: ['portal'],
    nodes: [SN.client, SN.ap, SN.meta, SN.playlist, SN.pldb, SN.events, SN.lake, SN.recs, SN.cloud, { ...SN.portal, x: 70, y: 86 }],
    edges: [se('client', 'ap'), se('ap', 'meta'), se('ap', 'playlist'), se('playlist', 'pldb'), se('ap', 'events', { async: true }), se('events', 'lake'), se('lake', 'recs'), se('cloud', 'meta'), se('portal', 'playlist', { label: 'catalogs' }), se('portal', 'events', { label: 'catalogs' })],
    flows: [{ name: 'Find an owner', path: ['portal', 'events'], steps: ['An engineer looks up the event pipeline’s owner, docs, and on-call in one place'] }],
    problem: <p>Autonomous teams ship fast, but ownership, docs, and tooling scatter. New engineers cannot tell who owns what.</p>,
    decision: <p>Organize around small teams (“squads”) that own services end to end. Add a developer portal that catalogs every service, its owner, docs, and templates.</p>,
    tradeoff: <p>Autonomy breeds duplicated tools. A portal only works if keeping it current is part of the workflow.</p>,
    realWorld: <p>A 2012 paper described squads, tribes, chapters, and guilds. Spotify has said its practice evolved since. It open-sourced <strong>Backstage</strong> in March 2020, and the CNCF accepted it into its Sandbox that September.</p>,
    walkthrough: [
      'Each service registers metadata: owner, docs, APIs.',
      'The portal indexes it into one catalog.',
      'Templates create new services with standard tooling.',
      'Engineers find owners and docs in one place.',
    ],
    numbers: [
      { label: 'Squads paper', value: '2012' },
      { label: 'Backstage open-sourced', value: 'Mar 2020' },
      { label: 'CNCF Sandbox', value: 'Sep 2020' },
    ],
    components: [{ name: 'Backstage', role: 'Service catalog, docs, and software templates in one portal.' }],
    alternatives: [
      { option: 'Central platform team approves everything', verdict: 'Consistent, but becomes a bottleneck.' },
      { option: 'Wiki pages per team', verdict: 'Go stale; not tied to real service metadata.' },
    ],
    breaksNext: <p>Spotify expands beyond music into podcasts and audiobooks.</p>,
    interview: { q: 'How does org design show up in architecture?', a: <p>Service boundaries follow team boundaries. Without a catalog and paved roads, autonomy turns into sprawl.</p> },
    sources: [SRC.squads, SRC.backstage, SRC.backstageCncf],
  },
  {
    title: 'Podcasts + audiobooks',
    era: '2019–2022',
    scale: 'Music, talk, and books',
    summary: 'New audio types reuse streaming and delivery, but bring new catalogs and new business rules.',
    added: ['pod'],
    nodes: [SN.client, SN.ap, SN.pod, SN.meta, SN.playlist, SN.keys, SN.cdn, SN.audio, SN.events, SN.lake],
    edges: [se('client', 'ap'), se('ap', 'pod'), se('ap', 'meta'), se('ap', 'playlist'), se('ap', 'keys'), se('client', 'cdn'), se('cdn', 'audio'), se('ap', 'events', { async: true }), se('events', 'lake')],
    flows: [{ name: 'Play a book', path: ['client', 'ap', 'pod'], steps: ['User opens an audiobook', 'Access point checks the purchase in the new catalog'] }],
    problem: <p>Podcasts are long, episodic, and resume mid-way. Audiobooks were sold per title at launch, unlike music’s subscription model.</p>,
    decision: <p>Add separate catalogs and entitlement rules per content type. Reuse audio delivery, keys, and the event pipeline. Track resume position for long content.</p>,
    tradeoff: <p>Each content type adds rules to the play path. Ranking must mix very different items.</p>,
    realWorld: <p>Spotify bought Gimlet and Anchor in February 2019. It launched audiobooks in the U.S. in September 2022, with over 300,000 titles sold individually.</p>,
    walkthrough: [
      'The app resolves the item and its content type.',
      'Entitlement checks differ: subscription, purchase, or free.',
      'Audio streams through the same delivery path.',
      'Progress events store the resume position.',
    ],
    numbers: [
      { label: 'Podcast deals', value: 'Feb 2019', note: 'Gimlet + Anchor' },
      { label: 'Audiobooks at U.S. launch', value: '300K+ titles', note: 'Sep 2022' },
    ],
    components: [{ name: 'Podcast + book catalog', role: 'Episodes, books, chapters, and per-title purchase rights.' }],
    alternatives: [
      { option: 'Separate app per content type', verdict: 'Simpler rules, but splits users and delivery.' },
    ],
    breaksNext: <p>Users type loose phrases like “electric cars climate impact” and keyword search finds nothing.</p>,
    interview: { q: 'What changes when you add long-form audio to a music platform?', a: <p>Resume position, per-title entitlements, and ranking across unlike items. Delivery can stay the same.</p> },
    sources: [SRC.audioFirst, SRC.audiobooks],
  },
  {
    title: 'Semantic search',
    era: '2022',
    scale: 'Tens of millions of episodes',
    summary: 'Search adds meaning-based matching alongside keyword matching.',
    added: ['search', 'encoder'],
    nodes: [SN.client, SN.ap, SN.pod, SN.meta, SN.search, SN.encoder, SN.playlist, SN.events, SN.lake],
    edges: [se('client', 'ap'), se('ap', 'pod'), se('ap', 'meta'), se('ap', 'search'), se('search', 'encoder'), se('meta', 'search', { async: true, label: 'index' }), se('ap', 'playlist'), se('ap', 'events', { async: true }), se('events', 'lake')],
    flows: [{ name: 'Search', path: ['client', 'ap', 'search', 'encoder'], steps: ['User types a question-like query', 'Access point routes it', 'Search sends the text to the query encoder, then runs keyword and vector retrieval'] }],
    problem: <p>Term matching needs exact words. Aliases and fuzzy matching only go so far.</p>,
    decision: <p>Encode queries and episodes as vectors. Retrieve nearest neighbors, and add them as an extra source next to keyword results.</p>,
    tradeoff: <p>GPU inference cost per query. Vectors miss exact names, so keyword search must stay.</p>,
    realWorld: <p>A 2022 Spotify post describes natural-language search for podcast episodes. Episode vectors are indexed in Vespa for approximate nearest-neighbor search. The query encoder runs on Google Cloud Vertex AI.</p>,
    walkthrough: [
      'Episodes are encoded offline and indexed.',
      'At query time, the text is encoded on a GPU.',
      'Nearest-neighbor search returns semantic matches.',
      'Results merge with keyword matches before ranking.',
    ],
    numbers: [{ label: 'GPU vs CPU inference cost', value: '6× cheaper', note: 'T4 GPU, per the post' }],
    components: [
      { name: 'Search', role: 'Keyword and vector retrieval, then ranking.' },
      { name: 'Query encoder', role: 'Turns query text into a vector on GPUs.' },
    ],
    alternatives: [
      { option: 'Replace keyword search', verdict: 'Loses exact matches like show names.' },
      { option: 'More manual aliases', verdict: 'Does not scale to open-ended questions.' },
    ],
    breaksNext: <p>Each new signal adds latency to the search path, so budgets per stage matter.</p>,
    interview: { q: 'Why keep keyword search next to vector search?', a: <p>Dense retrieval is weak on exact terms. Hybrid retrieval gets both names and meaning.</p> },
    sources: [SRC.nlSearch],
  },
]
