import type { EpisodeStage } from '../../components/ui'
import { S } from './episode-youtube-sources'
import { N, as, e } from './episode-youtube-stage-nodes'

const shards = as(N.mysql, 'MySQL shards', 'many keyspaces')
const tx = as(N.encode, 'Transcoding', 'H.264 · VP9 · AV1')

// Stages 10–13 share one watch-page architecture; only labels change.
const baseNodes = [N.client, N.creators, N.web, N.vitess, shards, N.rec, N.hist, N.store]
const baseEdges = [
  e('client', 'web'), e('creators', 'web'), e('web', 'vitess'), e('vitess', 'mysql'), e('web', 'rec'),
  e('rec', 'hist'), e('client', 'hist', { label: 'watch events', async: true }), e('web', 'encode'), e('encode', 'store'),
]

export const YOUTUBE_LATE: EpisodeStage[] = [
  {
    title: 'Vitess: a proxy for MySQL',
    era: '2010–2012',
    summary: 'A proxy between the app and MySQL takes over shard routing, connection pooling, and query safety.',
    scale: 'Every database request goes through it',
    added: ['vitess'],
    nodes: [N.client, N.creators, N.web, N.vitess, shards, as(N.replicas, 'Shard replicas'), as(N.video, 'Video servers'), N.cdn],
    edges: [e('client', 'web'), e('creators', 'web'), e('web', 'vitess'), e('vitess', 'mysql'), e('vitess', 'replicas'), e('mysql', 'replicas', { async: true }), e('client', 'video'), e('client', 'cdn')],
    flows: [{ name: 'Query', path: ['client', 'web', 'vitess', 'mysql'], steps: ['A viewer loads a page', 'The app sends a normal SQL query to Vitess', 'Vitess routes it to the right shard over a pooled connection'] }],
    problem: <p>Shard routing lives in application code. Thousands of app processes open their own MySQL connections, and one bad query can overload a shard.</p>,
    decision: <p>Put a proxy layer, <strong>Vitess</strong>, between the app and MySQL. It routes queries to shards, pools connections, and protects databases from expensive queries.</p>,
    tradeoff: <p>An extra network hop and a critical new service. The team now owns a database proxy, not just a website.</p>,
    realWorld: <p>Vitess was created at YouTube in 2010 and open-sourced on GitHub in 2012. A 2012 talk said every YouTube database request went through it. It became a CNCF project in 2018 and graduated in November 2019.</p>,
    walkthrough: [
      'The app sends SQL to Vitess as if it were one database.',
      'Vitess looks up which shard owns the key.',
      'It forwards the query over a shared, pooled connection.',
      'Reads can go to replicas; writes go to the shard’s primary.',
    ],
    numbers: [
      { label: 'Created at YouTube', value: '2010' },
      { label: 'CNCF graduation', value: 'Nov 2019', note: '8th graduated project' },
      { label: 'YouTube users since Vitess', value: '> 50×', note: 'per the Vitess docs' },
    ],
    components: [{ name: 'Vitess', role: 'Query routing, connection pooling, and resharding for MySQL.' }],
    alternatives: [
      { option: 'Keep routing in the app', verdict: 'Every service re-implements it, and resharding means code changes everywhere.' },
      { option: 'Move to a NoSQL store', verdict: 'Huge rewrite of relational data and queries; Vitess kept MySQL.' },
    ],
    breaksNext: <p>Viewers want to watch events as they happen, not after upload and processing.</p>,
    interview: { q: 'Why add a proxy in front of sharded MySQL?', a: <p>It centralizes shard routing, pools connections, and enforces query limits, so resharding becomes an operation instead of an application change.</p> },
    sources: [S.vitessHistory, S.hs7years, S.vitessCncf],
  },
  {
    title: 'Live streaming',
    era: '2011',
    summary: 'Streams are ingested, cut into short segments, transcoded on the fly, and fanned out to viewers.',
    scale: 'Seconds of delay, many viewers at once',
    added: ['live'],
    nodes: [N.client, N.creators, N.web, N.vitess, shards, N.live, as(N.video, 'Edge servers'), N.cdn],
    edges: [e('client', 'web'), e('creators', 'live'), e('web', 'vitess'), e('vitess', 'mysql'), e('live', 'video'), e('live', 'cdn'), e('client', 'video'), e('client', 'cdn')],
    flows: [{ name: 'Go live', path: ['creators', 'live', 'cdn', 'client'], steps: ['A streamer sends a continuous feed', 'Ingest cuts it into short segments and transcodes them', 'Viewers pull the newest segments'] }],
    problem: <p>Live video can’t be processed after the fact. Every second of delay matters, and everyone watches the same moment.</p>,
    decision: <p>A separate <strong>live ingest</strong> path: receive the stream, cut it into short segments, transcode each quickly, and publish them for viewers to fetch.</p>,
    tradeoff: <p>No time to pre-position or re-encode carefully. Quality and delay trade against each other.</p>,
    realWorld: <p>YouTube Live launched in April 2011. YouTube later reported that daily livestreams grew 45% in the first half of 2020.</p>,
    walkthrough: [
      'The streamer’s encoder pushes a continuous stream to ingest.',
      'Ingest cuts it into short segments.',
      'Each segment is transcoded into several qualities within seconds.',
      'Players keep fetching the latest segments from edge caches.',
    ],
    numbers: [
      { label: 'YouTube Live launched', value: 'Apr 2011' },
      { label: 'Daily livestreams, H1 2020', value: '+45%' },
    ],
    components: [{ name: 'Live ingest', role: 'Receives streams and produces segments in near real time.' }],
    alternatives: [
      { option: 'Reuse the upload pipeline', verdict: 'Built for minutes of processing, not seconds.' },
      { option: 'Peer-to-peer delivery', verdict: 'Unreliable on mobile networks and hard to secure.' },
    ],
    breaksNext: <p>Bandwidth, not servers, becomes the biggest cost. Every bit saved in encoding pays off on every view.</p>,
    interview: { q: 'What changes when you add live streaming to a VOD platform?', a: <p>Latency budgets drop to seconds, so ingest and transcode must be streaming, not batch. Caches can’t be pre-filled, and a popular stream is a thundering herd on the newest segment.</p> },
    sources: [S.live, S.argos],
  },
  {
    title: 'Better codecs',
    era: '2013–2018',
    summary: 'Newer codecs like VP9 and AV1 cut bandwidth, at the price of much more encoding compute.',
    scale: 'Every view pays for every bit',
    added: ['store'],
    nodes: [N.client, N.creators, N.web, N.vitess, shards, tx, N.store, N.cdn],
    edges: [e('client', 'web'), e('creators', 'web'), e('web', 'vitess'), e('vitess', 'mysql'), e('web', 'encode'), e('encode', 'store'), e('store', 'cdn'), e('client', 'cdn')],
    flows: [{ name: 'Encode', path: ['creators', 'web', 'encode', 'store'], steps: ['A creator uploads', 'The app schedules transcoding', 'Renditions in several codecs and resolutions are stored'] }],
    problem: <p>At this scale, bandwidth dominates the cost of serving video. H.264 needs more bits than newer codecs for the same quality.</p>,
    decision: <p>Encode videos in <strong>VP9</strong>, and later <strong>AV1</strong>, in addition to H.264. Devices that support a newer codec get fewer bits for the same picture.</p>,
    tradeoff: <p>Encoding cost jumps: YouTube says VP9 needs about 5× the compute of H.264. Every video now has more renditions to store.</p>,
    realWorld: <p>VP9 was finalized in June 2013 and YouTube became its main user. YouTube started public AV1 tests in September 2018.</p>,
    walkthrough: [
      'An upload is split into chunks so it can be encoded in parallel.',
      'Each chunk is encoded at several resolutions and codecs.',
      'Renditions are stored; players pick the best codec their device decodes.',
      'Adaptive streaming lets the player change quality as bandwidth changes.',
    ],
    numbers: [
      { label: 'VP9 finalized', value: 'June 2013' },
      { label: 'VP9 encode cost vs H.264', value: '≈ 5×', note: 'per YouTube, 2021' },
      { label: 'First public AV1 tests', value: 'Sept 2018' },
    ],
    components: [{ name: 'Multi-codec transcoding', role: 'Produces H.264, VP9, and AV1 renditions per video.' }],
    alternatives: [
      { option: 'H.264 only', verdict: 'Simplest and universal, but more bits per view forever.' },
      { option: 'New codec for every video immediately', verdict: 'Compute cost is huge; most videos get few views.' },
    ],
    breaksNext: <p>A video that plays perfectly still fails if nobody finds it. What to show next matters more than raw capacity.</p>,
    interview: { q: 'When is it worth encoding a video in an expensive codec?', a: <p>When expected views × bytes saved outweighs the extra encode cost. Popular videos repay it quickly; the long tail may never.</p> },
    sources: [S.vp9, S.av1Test, S.argos],
  },
  {
    title: 'Deep recommendations',
    era: '2016',
    summary: 'Two neural networks pick what to watch next: one finds hundreds of candidates, one ranks them.',
    scale: 'Millions of videos → hundreds → dozens',
    added: ['rec', 'hist'],
    nodes: [...baseNodes, tx, N.cdn],
    edges: [...baseEdges, e('client', 'cdn')],
    flows: [{ name: 'Home feed', path: ['client', 'web', 'rec', 'hist'], steps: ['A viewer opens the app', 'The app asks for recommendations', 'Candidate generation and ranking use the viewer’s watch history'] }],
    problem: <p>The catalog has millions of videos. Scoring each one with a rich model for every page load is impossible.</p>,
    decision: <p>Split recommendation into two stages. <strong>Candidate generation</strong> narrows millions to hundreds using a nearest-neighbor lookup. <strong>Ranking</strong> scores those hundreds with many more features.</p>,
    tradeoff: <p>If a video misses the candidate stage, ranking never sees it. Two models to train, serve, and keep consistent.</p>,
    realWorld: <p>A 2016 RecSys paper describes this two-stage design, about a billion parameters trained on hundreds of billions of examples, and ranking by expected watch time rather than clicks.</p>,
    walkthrough: [
      'The viewer’s recent watches and searches become an embedding.',
      'A nearest-neighbor search returns a few hundred candidate videos.',
      'The ranking model scores each candidate with hundreds of features.',
      'The top results, after business rules, fill the page.',
    ],
    numbers: [
      { label: 'Corpus', value: 'millions' },
      { label: 'Candidates per request', value: 'hundreds' },
      { label: 'Model parameters', value: '≈ 1 billion', note: '2016 paper' },
    ],
    components: [
      { name: 'Candidate generation', role: 'Cheap, broad retrieval from the whole corpus.' },
      { name: 'Ranking', role: 'Expensive, precise scoring of a few hundred items.' },
    ],
    alternatives: [
      { option: 'One model over the whole corpus', verdict: 'Far too slow per request.' },
      { option: 'Rank by click-through rate', verdict: 'Rewards clickbait; watch time was a better signal.' },
    ],
    breaksNext: <p>With viewers everywhere, the bottleneck is the last mile into each internet provider.</p>,
    interview: { q: 'Why two stages instead of one big model?', a: <p>Cost scales with items scored. A cheap retriever shrinks millions to hundreds within a few milliseconds, so an expensive ranker can spend its budget where it matters.</p> },
    sources: [S.recsys, S.recsysNotes],
  },
  {
    title: 'Caches inside ISPs',
    era: 'By 2021',
    summary: 'Google-provided caches sit inside internet providers and serve popular YouTube content locally.',
    scale: '1,300+ cities, 200+ countries',
    added: ['ggc'],
    nodes: [...baseNodes, tx, N.ggc],
    edges: [...baseEdges, e('store', 'ggc', { label: 'fill', async: true }), e('client', 'ggc')],
    flows: [{ name: 'Stream', path: ['client', 'ggc'], steps: ['The player streams popular video from a cache inside the viewer’s own ISP'] }],
    problem: <p>Sending every byte across the internet from Google’s data centers congests ISP peering and transit links.</p>,
    decision: <p><strong>Google Global Cache</strong>: Google supplies cache servers that ISPs host in their own networks. Popular content is served from there.</p>,
    tradeoff: <p>Thousands of remote machines to operate, and a partnership with every ISP that hosts them.</p>,
    realWorld: <p>Google says 70–90% of cacheable traffic can typically be served from these caches. In 2021 it described them in over 1,300 cities, caching content such as YouTube.</p>,
    walkthrough: [
      'The player asks for a video segment.',
      'Google’s serving system directs it to a nearby cache, often inside the viewer’s ISP.',
      'Hits are served locally; misses fill from Google’s network.',
    ],
    numbers: [
      { label: 'Cacheable traffic served locally', value: '70–90%', note: 'typical, per Google' },
      { label: 'Cities with caches (2021)', value: '1,300+' },
    ],
    components: [{ name: 'Google Global Cache', role: 'Google hardware hosted inside ISP networks.' }],
    alternatives: [
      { option: 'Serve everything from Google’s edge', verdict: 'More traffic over peering links and farther from viewers.' },
      { option: 'Commercial CDNs', verdict: 'Pay per byte at a scale where owning caches is cheaper.' },
    ],
    breaksNext: <p>Short vertical videos change how people browse: dozens of clips per session instead of one long video.</p>,
    interview: { q: 'When does it pay to put your own caches inside ISPs?', a: <p>When your traffic is a big share of the ISP’s traffic and highly cacheable. Both sides win: lower latency for users, less transit for the ISP.</p> },
    sources: [S.ggc, S.edge],
  },
  {
    title: 'Shorts',
    era: '2020–2021',
    summary: 'A feed of short vertical clips: each swipe needs the next video ready instantly.',
    scale: '6.5B daily views (Mar 2021)',
    nodes: [as(N.client, 'Phones', 'vertical feed'), N.creators, N.web, N.vitess, shards, as(N.rec, 'Shorts ranker', 'swipe signals'), N.hist, N.store, tx, N.ggc],
    edges: [...baseEdges, e('store', 'ggc', { async: true }), e('client', 'ggc')],
    flows: [
      { name: 'Next clip', path: ['client', 'web', 'rec', 'hist'], steps: ['The app asks for the next batch of clips', 'The ranker scores candidates', 'It uses recent swipes and watches as signals'] },
      { name: 'Play', path: ['client', 'ggc'], steps: ['The app prefetches upcoming clips from the nearest cache'] },
    ],
    problem: <p>A viewer swipes through many clips a minute. Any pause before a clip starts feels broken.</p>,
    decision: <p>Serve a feed, not a page: fetch clips in batches, prefetch the next few, and rank using fast feedback such as swipes and rewatches. This is common practice for short-video feeds.</p>,
    tradeoff: <p>Prefetching wastes bandwidth on clips people skip. The ranker must react within a session, not overnight.</p>,
    realWorld: <p>Shorts launched in beta in India in September 2020 and came to the U.S. in March 2021, when YouTube reported 6.5 billion daily views. It rolled out to more than 100 countries in July 2021.</p>,
    walkthrough: [
      'The app requests a batch of ranked clips.',
      'It prefetches the first seconds of the next few clips.',
      'Each swipe or rewatch is sent back as a signal.',
      'The next batch reflects what this session just did.',
    ],
    numbers: [
      { label: 'India beta', value: 'Sept 2020' },
      { label: 'Daily Shorts views (Mar 2021)', value: '6.5B' },
      { label: 'Global rollout', value: 'Jul 2021', note: '100+ countries' },
    ],
    components: [{ name: 'Shorts ranker', role: 'Ranks clips using in-session signals.' }],
    alternatives: [
      { option: 'Reuse the long-video watch page', verdict: 'One request per video is too slow for swiping.' },
      { option: 'Prefetch whole clips', verdict: 'Fast, but wastes data on skipped clips; prefetch only the start.' },
    ],
    breaksNext: <p>Uploads keep rising, and transcoding every clip into many renditions on CPUs is slow and expensive.</p>,
    interview: { q: 'How do you make a swipe feed start instantly?', a: <p>Return clips in batches, prefetch the opening seconds of the next few, keep them small and cached at the edge, and rank with in-session signals.</p> },
    sources: [S.shortsUs, S.shortsGlobal],
  },
  {
    title: 'Custom transcoding chips',
    era: '2021',
    summary: 'YouTube builds its own video chips, Argos VCUs, to transcode faster and cheaper than CPUs.',
    scale: '500+ hours uploaded every minute',
    nodes: [...baseNodes, as(N.encode, 'Argos VCUs', 'hardware transcode'), N.ggc],
    edges: [...baseEdges, e('store', 'ggc', { async: true }), e('client', 'ggc')],
    flows: [{ name: 'Encode', path: ['creators', 'web', 'encode', 'store'], steps: ['A creator uploads', 'The app schedules transcoding', 'VCU machines produce every rendition and store them'] }],
    problem: <p>More than 500 hours of video arrive every minute. Better codecs multiply the compute per video, and CPUs are an inefficient way to do it.</p>,
    decision: <p>Design a dedicated chip, the <strong>Argos Video (trans)Coding Unit</strong>, and deploy it on its own machines in Google’s data centers.</p>,
    tradeoff: <p>Years of hardware design work, plus a new kind of machine to deploy, schedule, and repair across the fleet.</p>,
    realWorld: <p>YouTube described Argos in April 2021, reporting up to 20–33× better compute efficiency than its previous software system. An ASPLOS 2021 paper reports 8–20× higher encoding throughput than software.</p>,
    walkthrough: [
      'An upload is split into segments.',
      'Segments are sent to machines packed with VCU cards.',
      'Hardware encoders produce each resolution and codec in parallel.',
      'The renditions are stored and replicated for serving.',
    ],
    numbers: [
      { label: 'Uploads', value: '500+ h / min' },
      { label: 'Compute efficiency vs before', value: 'up to 20–33×', note: 'YouTube, 2021' },
      { label: 'Encode throughput vs software', value: '8–20×', note: 'H.264 → VP9, ASPLOS 2021' },
    ],
    components: [{ name: 'Argos VCU', role: 'Custom accelerator for video transcoding.' }],
    alternatives: [
      { option: 'More CPUs', verdict: 'Cost grows linearly with uploads and codec complexity.' },
      { option: 'GPUs', verdict: 'General-purpose; a dedicated video chip was more efficient for this one job.' },
    ],
    breaksNext: <p>The next pressure is cost and freshness at once: more uploads, more codecs, and feeds that adapt in seconds.</p>,
    interview: { q: 'When is building custom hardware justified?', a: <p>When one workload is huge, stable, and a large cost line, and general-purpose chips waste most of their silicon on it. Count design cost over several years of fleet savings.</p> },
    sources: [S.argos, S.asplos],
  },
]
