import type { EpisodeStage } from '../../components/ui'
import { CN, GSRC, ce } from './episode-chatgpt-stage-nodes'

// Stages 1–6: launch through function calling.
export const CHATGPT_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'Research preview',
    era: 'Nov 2022',
    scale: 'Demand far beyond plan',
    summary: 'A chat page sends each message to a large model and shows the reply.',
    nodes: [CN.client, { ...CN.edge, label: 'App server', sub: 'prompt in, text out' }, CN.model],
    edges: [ce('client', 'edge'), ce('edge', 'model')],
    flows: [{ name: 'Ask', path: ['client', 'edge', 'model'], steps: ['User sends a message', 'The server forwards the prompt and returns the model’s answer'] }],
    problem: <p>Find out whether people want a chat interface to a large model. Speed of learning matters more than scale.</p>,
    decision: <p>Keep it thin: one web app, one API layer, one pool of model servers. Collect feedback on every answer.</p>,
    tradeoff: <p>No capacity planning for viral growth. When GPUs run out, users simply wait or get turned away.</p>,
    realWorld: <p>OpenAI released ChatGPT as a free “research preview” on 30 November 2022. Its launch post says the model was trained on Azure AI supercomputing infrastructure.</p>,
    walkthrough: [
      'The browser posts the message.',
      'The server builds a prompt from the conversation so far.',
      'A model server generates the reply.',
      'The reply goes back to the browser.',
    ],
    numbers: [{ label: 'Public launch', value: '30 Nov 2022' }],
    components: [{ name: 'Model servers', role: 'GPU machines running the model. The scarce, expensive resource in every later stage.' }],
    alternatives: [
      { option: 'API only, no chat UI', verdict: 'Reaches developers, not the general public.' },
      { option: 'Invite-only beta', verdict: 'Controls load, but learns slower.' },
    ],
    breaksNext: <p>Answers take many seconds to finish. Users stare at a blank box until the last word is ready.</p>,
    interview: { q: 'What is the first bottleneck of an LLM product?', a: <p>GPU capacity. Everything else (web servers, databases) is cheap in comparison.</p> },
    sources: [GSRC.launch],
  },
  {
    title: 'Stream the answer',
    era: 'Design pattern',
    scale: 'Seconds per answer',
    summary: 'Words appear as the model produces them, so the first ones show up almost at once.',
    added: ['chat'],
    nodes: [CN.client, CN.edge, CN.chat, CN.model],
    edges: [ce('client', 'edge', { label: 'SSE' }), ce('edge', 'chat'), ce('chat', 'model')],
    flows: [{ name: 'Stream', path: ['client', 'edge', 'chat', 'model'], steps: ['Browser opens one HTTP response and keeps it open', 'Edge authenticates and holds the stream', 'Orchestrator relays each token from the model as it arrives'] }],
    problem: <p>A model writes one token at a time. Waiting for the whole answer makes a fast system feel slow.</p>,
    decision: <p>Stream tokens to the client with server-sent events (SSE), a one-way stream over a normal HTTP response. Measure time to first token (TTFT), not total time.</p>,
    tradeoff: <p>Long-lived connections complicate load balancers and timeouts. A dropped stream must be retried or resumed cleanly.</p>,
    realWorld: <p>OpenAI’s API streams responses as server-sent events when you request streaming. This stage describes that general pattern.</p>,
    walkthrough: [
      'The client sends the message and keeps the response open.',
      'The orchestrator starts generation on a model server.',
      'Each new token is written to the stream right away.',
      'A final event marks the end, and the stream closes.',
    ],
    numbers: [
      { label: 'Answer of 400 tokens at 40 tok/s', value: '≈ 10 s', note: 'estimate' },
      { label: 'Time to first token', value: 'sub-second target', note: 'estimate' },
    ],
    components: [{ name: 'Orchestrator', role: 'Builds the prompt, calls the model, and relays tokens. Later, it runs tools too.' }],
    alternatives: [
      { option: 'WebSockets', verdict: 'Two-way, but more moving parts than a request-then-stream flow needs.' },
      { option: 'Polling for partial text', verdict: 'Wasteful and laggy.' },
    ],
    breaksNext: <p>Users edit old messages and hit “regenerate”. A flat message list cannot hold both versions.</p>,
    interview: { q: 'Why SSE instead of WebSockets for chat replies?', a: <p>The reply is one-way and request-scoped. SSE is plain HTTP, works through proxies, and is simpler to scale.</p> },
    sources: [GSRC.streaming, GSRC.sse],
  },
  {
    title: 'Conversations as trees',
    era: 'Design choice',
    scale: 'Many turns per chat',
    summary: 'Each message points to its parent, so edits and regenerations become branches instead of overwrites.',
    added: ['convdb'],
    nodes: [CN.client, CN.edge, CN.chat, CN.convdb, CN.model],
    edges: [ce('client', 'edge'), ce('edge', 'chat'), ce('chat', 'convdb'), ce('chat', 'model')],
    flows: [{ name: 'Edit', path: ['client', 'edge', 'chat', 'convdb'], steps: ['User edits message 3 of 40', 'Routed to the orchestrator', 'A new sibling of message 3 is stored, starting a new branch'] }],
    problem: <p>Users edit earlier messages and regenerate replies. They expect to flip between versions, not lose them.</p>,
    decision: <p>Store messages as a tree: every message has a parent id. The conversation remembers its current leaf. Reads load the path from root to that leaf.</p>,
    tradeoff: <p>Trees are harder to query than lists. Deletion and retention rules must cover every branch.</p>,
    realWorld: <p>OpenAI does not document its storage design. This stage describes a common way to model edit and regenerate.</p>,
    walkthrough: [
      'An edit creates a new message with the same parent as the old one.',
      'The new reply hangs below it as a fresh branch.',
      'The conversation’s “current leaf” moves to the new branch.',
      'Prompt building walks from the root to that leaf.',
    ],
    numbers: [{ label: 'Stored per message', value: '≈ 1–2 KB text', note: 'estimate' }],
    components: [{ name: 'Conversation store', role: 'Message trees keyed by conversation id, with a pointer to the current leaf.' }],
    alternatives: [
      { option: 'Flat list, truncate on edit', verdict: 'Simple, but destroys history users wanted.' },
    ],
    breaksNext: <p>Demand outruns GPUs. Some users need guaranteed access, and request costs vary wildly.</p>,
    interview: { q: 'A user edits message 3 in a 40-turn chat. What happens to the data?', a: <p>A sibling branch is created. Nothing is deleted, and the current leaf moves to the new branch.</p> },
    sources: [],
  },
  {
    title: 'Plans, limits, priority',
    era: 'Feb 2023',
    scale: 'Peak demand exceeds GPUs',
    summary: 'A paid plan gets priority at peak, and usage is limited by tokens, not requests.',
    added: ['quota', 'queue'],
    nodes: [CN.client, CN.edge, CN.quota, CN.chat, CN.convdb, CN.queue, CN.model],
    edges: [ce('client', 'edge'), ce('edge', 'quota'), ce('edge', 'chat'), ce('chat', 'convdb'), ce('chat', 'queue'), ce('queue', 'model')],
    flows: [{ name: 'Admit', path: ['client', 'edge', 'quota'], steps: ['Request arrives', 'Edge checks the user’s remaining budget for their plan'] },
      { name: 'Schedule', path: ['client', 'edge', 'chat', 'queue', 'model'], steps: ['Admitted request', 'Routed to the orchestrator', 'Queued by plan priority', 'Sent to a model server with free capacity'] }],
    problem: <p>At peak, GPUs run out. One request might cost 100 tokens, another 10,000. Counting requests says little about load.</p>,
    decision: <p>Meter usage in tokens per plan. Put a priority scheduler in front of the GPUs, so paid and interactive traffic goes first. Reject fast with a retry hint instead of timing out.</p>,
    tradeoff: <p>Output length is unknown up front, so you admit on an estimate and settle later. Low tiers need protection from starvation.</p>,
    realWorld: <p>OpenAI launched ChatGPT Plus on 1 February 2023 at $20/month, promising access even at peak times and faster responses. Its API documents limits in requests and tokens per minute, grouped into usage tiers.</p>,
    walkthrough: [
      'Estimate the request’s tokens (prompt + expected answer).',
      'Reserve that from the user’s budget.',
      'Queue by plan priority.',
      'After the stream ends, settle to actual tokens used.',
    ],
    numbers: [
      { label: 'ChatGPT Plus launch', value: '1 Feb 2023', note: '$20/month' },
      { label: 'Cost spread between requests', value: '~100×', note: 'estimate' },
    ],
    components: [
      { name: 'Usage limits', role: 'Per-user, per-plan token budgets checked at the edge.' },
      { name: 'Scheduler', role: 'Priority queue that protects GPUs and orders work by plan.' },
    ],
    alternatives: [
      { option: 'Requests per minute only', verdict: 'Ignores the 100× cost spread.' },
      { option: 'First come, first served', verdict: 'Paid users suffer at peak.' },
    ],
    breaksNext: <p>People want answers about today’s news and their own tools, not just what the model already knows.</p>,
    interview: { q: 'How do you rate-limit when requests vary 100× in cost?', a: <p>Limit tokens, reserve an estimate at admission, settle afterwards, and schedule by priority in front of the GPUs.</p> },
    sources: [GSRC.plus, GSRC.rateLimits],
  },
  {
    title: 'Plugins + browsing',
    era: 'Mar 2023',
    scale: 'Third-party integrations',
    summary: 'The model can call outside services, such as a web search, and read the results.',
    added: ['tools', 'web'],
    nodes: [CN.client, CN.edge, CN.quota, CN.chat, CN.convdb, CN.queue, CN.model, CN.tools, CN.web],
    edges: [ce('client', 'edge'), ce('edge', 'quota'), ce('edge', 'chat'), ce('chat', 'convdb'), ce('chat', 'queue'), ce('queue', 'model'), ce('chat', 'tools'), ce('tools', 'web')],
    flows: [{ name: 'Browse', path: ['client', 'edge', 'chat', 'tools', 'web'], steps: ['User asks about today’s news', 'Routed', 'Model requests a search; the orchestrator hands it to the tool runner', 'Tool runner calls the search API and returns pages to the model'] }],
    problem: <p>The model’s knowledge stops at its training data. Users want fresh facts and actions in other apps.</p>,
    decision: <p>Let the model request tools. The platform runs the call, then feeds the result back to the model. Treat every tool result as untrusted input.</p>,
    tradeoff: <p>Each tool step adds a model call, so latency and cost grow. Web pages can carry prompt-injection text.</p>,
    realWorld: <p>OpenAI announced ChatGPT plugins on 23 March 2023. They included a web browser, a code interpreter, and an open-source retrieval plugin.</p>,
    walkthrough: [
      'The model outputs a structured tool request.',
      'The orchestrator checks it against the allowed tools.',
      'The tool runner calls the external API.',
      'The result is added to the context, marked as untrusted.',
      'The model continues its answer.',
    ],
    numbers: [{ label: 'Plugins announced', value: '23 Mar 2023' }],
    components: [
      { name: 'Tool runner', role: 'Executes allowed tool calls with scoped credentials and timeouts.' },
      { name: 'External APIs', role: 'Search engines and partner services.' },
    ],
    alternatives: [
      { option: 'Retrain for fresh facts', verdict: 'Too slow and costly to track the news.' },
    ],
    breaksNext: <p>Developers want the same tool calls in their own apps, with reliable structured output.</p>,
    interview: { q: 'What new risk do tools introduce?', a: <p>Tool output is untrusted input. A web page can try to instruct the model. Scope tools and confirm risky actions.</p> },
    sources: [GSRC.plugins],
  },
  {
    title: 'Function calling',
    era: 'Jun 2023',
    scale: 'Developers build agents',
    summary: 'The model returns a structured call that matches a schema, and your code decides whether to run it.',
    nodes: [CN.client, CN.edge, CN.quota, CN.chat, CN.convdb, CN.queue, CN.model, CN.tools, CN.web],
    edges: [ce('client', 'edge'), ce('edge', 'quota'), ce('edge', 'chat'), ce('chat', 'convdb'), ce('chat', 'queue'), ce('queue', 'model'), ce('chat', 'tools'), ce('tools', 'web')],
    flows: [{ name: 'Call a function', path: ['chat', 'queue', 'model'], steps: ['Orchestrator sends tool schemas with the prompt', 'Model returns JSON arguments for one function instead of prose'] }],
    problem: <p>Parsing tool requests out of free text is fragile. Apps need arguments they can validate.</p>,
    decision: <p>Describe each function with a JSON schema. The model returns a function name and JSON arguments. The app validates, executes, and sends the result back.</p>,
    tradeoff: <p>The model can still pick the wrong function or invent arguments, so validation and allow-lists stay essential.</p>,
    realWorld: <p>OpenAI added function calling to its API in June 2023.</p>,
    walkthrough: [
      'The request includes function schemas.',
      'The model returns a call with JSON arguments.',
      'The app validates arguments against the schema.',
      'The app runs the function and returns the result.',
      'The model writes the final answer.',
    ],
    numbers: [{ label: 'Function calling released', value: 'Jun 2023' }],
    components: [{ name: 'Tool schemas', role: 'Typed contracts the model fills in, checked before execution.' }],
    alternatives: [
      { option: 'Regex over free text', verdict: 'Breaks on small wording changes.' },
    ],
    breaksNext: <p>Users want the assistant to run code on their files, not just call APIs.</p>,
    interview: { q: 'Why validate function arguments the model already produced?', a: <p>The model is probabilistic. Validation turns a guess into a checked, safe call.</p> },
    sources: [GSRC.functions],
  },
]
