import type { EpisodeStage } from '../../components/ui'
import { FRONT, IN, ie, shards } from './episode-instagram-stage-nodes'
import { IG_SRC as S } from './episode-instagram-sources'

// Stages 1–6: launch through the move into Facebook's data centers.
export const INSTAGRAM_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'v0 · Launch night',
    era: 'Oct 2010',
    scale: '25,000 users on day one',
    summary: 'A tiny team ships an iPhone photo app on a few servers and one database.',
    nodes: [{ ...IN.web, sub: 'Django, few servers' }, IN.client, { ...IN.pg, sub: 'one primary' }],
    edges: [ie('client', 'web'), ie('web', 'pg')],
    flows: [{ name: 'Upload', path: ['client', 'web', 'pg'], steps: ['App uploads a filtered photo', 'Server saves the file and writes the post row'] }],
    problem: <p>Two founders launch an iPhone app. Nobody knows if it will take off. Iteration speed beats everything.</p>,
    decision: <p>Use boring, proven tools: a Python web framework on a few servers and one PostgreSQL database.</p>,
    tradeoff: <p>Uploads tie up app threads. One database is the ceiling. Fine, as long as you know which wall comes first.</p>,
    realWorld: <p>Instagram launched on October 6, 2010, and reached about 25,000 users on its first day. Its 2011 stack post describes Django and PostgreSQL, by then running on Amazon’s cloud.</p>,
    walkthrough: ['App resizes and filters the photo on the phone.', 'App uploads it to a Django server.', 'Server stores the image and inserts a row in Postgres.', 'Followers see it on their next refresh.'],
    numbers: [{ label: 'Day-one users', value: '≈ 25,000', note: 'Britannica' }, { label: 'Databases', value: '1', note: 'simplified' }],
    components: [{ name: 'Django app', role: 'All pages and APIs in one codebase. Fast to change.' }, { name: 'PostgreSQL', role: 'Users, photos metadata, likes, follows.' }],
    alternatives: [{ option: 'NoSQL from day one', verdict: 'Less familiar; relational fit the data well.' }, { option: 'Own hardware', verdict: 'No time for a 2-person team to run a data center.' }],
    breaksNext: <p>Growth is explosive. Photo bytes and page requests overload the few servers.</p>,
    interview: { q: 'What would you build first for a photo app?', a: <p>The simplest thing that works, on proven tools. Measure, then fix the first real bottleneck.</p> },
    sources: [S.launch, S.whatPowers],
  },
  {
    title: 'v1 · Stateless web + S3 + CDN',
    era: '2011',
    scale: '14M users, 3 engineers',
    summary: 'Put identical app servers behind a load balancer and serve photos from storage via a CDN.',
    added: ['lb', 'cdn', 's3'],
    nodes: [IN.client, IN.lb, IN.web, IN.pg, IN.cdn, IN.s3],
    edges: [...FRONT, ie('web', 'pg'), ie('web', 's3'), ie('client', 'cdn'), ie('cdn', 's3')],
    flows: [
      { name: 'Upload', path: ['client', 'lb', 'web', 's3'], steps: ['App uploads the photo', 'Load balancer picks any app server', 'Server writes the file to object storage'] },
      { name: 'View', path: ['client', 'cdn', 's3'], steps: ['App fetches the photo URL from the CDN', 'A miss pulls from S3 once, then the edge caches it'] },
    ],
    problem: <p>App servers are overloaded. Photo downloads dwarf API traffic. Every view of a popular photo hits your servers.</p>,
    decision: <p>Keep app servers <strong>stateless</strong> so you can add more behind a load balancer. Store photos in <strong>S3</strong>, serve them through <strong>CloudFront</strong>.</p>,
    tradeoff: <p>More pieces to monitor. Storage and CDN bills now grow with every user.</p>,
    realWorld: <p>Instagram’s 2011 stack post lists an Elastic Load Balancer with 3 nginx instances, 25+ Django servers, S3 for photos, and CloudFront. It served 14M users with 3 engineers.</p>,
    walkthrough: ['Load balancer spreads requests over identical app servers.', 'Uploads land in S3; the app keeps only the key.', 'Clients fetch images from CloudFront edges.', 'Adding capacity means adding servers, no data moves.'],
    numbers: [{ label: 'Users', value: '14M+', note: 'late 2011' }, { label: 'App servers', value: '25+', note: 'High-CPU EC2' }, { label: 'Engineers', value: '3', note: 'High Scalability' }],
    components: [{ name: 'ELB + nginx', role: 'Spreads traffic; terminates SSL.' }, { name: 'S3 + CloudFront', role: 'Durable object storage with edge caching.' }],
    alternatives: [{ option: 'Serve images from app servers', verdict: 'Wastes CPU and bandwidth on bytes.' }, { option: 'Sticky sessions', verdict: 'Blocks easy scaling and failover.' }],
    breaksNext: <p>Building each feed by querying Postgres on every open is too slow.</p>,
    interview: { q: 'Why stateless app servers?', a: <p>Any server can serve any request. Scaling and failover become “add or remove a box”.</p> },
    sources: [S.whatPowersSummary, S.whatPowers],
  },
  {
    title: 'v2 · Redis feeds + async workers',
    era: '2011',
    scale: 'hundreds of photos per second',
    summary: 'Keep feeds in memory and move slow work, like sharing and fan-out, to background workers.',
    added: ['redis', 'q', 'workers'],
    nodes: [IN.client, IN.lb, IN.web, IN.pg, IN.cdn, IN.s3, IN.redis, IN.q, IN.workers],
    edges: [...FRONT, ie('web', 'pg'), ie('web', 's3'), ie('client', 'cdn'), ie('cdn', 's3'), ie('web', 'redis'), ie('web', 'q', { async: true }), ie('q', 'workers'), ie('workers', 'redis', { label: 'fan-out' })],
    flows: [
      { name: 'Open feed', path: ['client', 'lb', 'web', 'redis'], steps: ['App opens the feed', 'Load balancer routes to an app server', 'Server reads the feed list from Redis'] },
      { name: 'Fan-out', path: ['web', 'q', 'workers', 'redis'], steps: ['New post enqueues a job', 'A worker picks it up', 'Post ID is added to followers’ feed lists'] },
    ],
    problem: <p>Feeds and activity lists are read constantly. Sharing to other networks is slow and should not block uploads.</p>,
    decision: <p>Store feeds, activity, and sessions in <strong>Redis</strong>; cache objects in <strong>memcached</strong>. Push slow jobs to a <strong>task queue</strong> served by Python workers.</p>,
    tradeoff: <p>Redis holds data in RAM, so memory cost grows. Async jobs can fail silently without good monitoring.</p>,
    realWorld: <p>The 2011 stack post says Redis powered the main feed, activity feed, and sessions. It used 6 memcached instances and about 200 Python workers on a Gearman queue.</p>,
    walkthrough: ['Upload finishes; app server enqueues follow-up jobs.', 'Workers push the post ID to followers’ Redis lists.', 'Workers also share to Twitter or Facebook if asked.', 'Opening the feed reads a ready-made list from Redis.'],
    numbers: [{ label: 'memcached instances', value: '6', note: '2011' }, { label: 'Queue workers', value: '≈ 200', note: 'Gearman, 2011' }],
    components: [{ name: 'Redis', role: 'In-memory lists for feeds, activity, sessions.' }, { name: 'Gearman workers', role: 'Background jobs off the request path.' }],
    alternatives: [{ option: 'Query followers’ posts on every open', verdict: 'Many joins per request; too slow.' }, { option: 'Threads inside the web request', verdict: 'Slow requests and lost work on crashes.' }],
    breaksNext: <p>One Postgres primary cannot hold all writes or data. You need to shard.</p>,
    interview: { q: 'Push or pull for the feed?', a: <p>Push (fan-out on write) for normal accounts makes reads cheap. Pull for huge accounts avoids millions of writes per post.</p> },
    sources: [S.whatPowersSummary],
  },
  {
    title: 'v3 · Sharded Postgres + IDs in the DB',
    era: '2011',
    scale: '25 photos + 90 likes per second',
    summary: 'Split data into thousands of logical shards and make each shard generate its own sortable IDs.',
    nodes: [IN.client, IN.lb, IN.web, shards, IN.cdn, IN.s3, IN.redis, IN.q, IN.workers],
    edges: [...FRONT, ie('web', 'pg'), ie('web', 's3'), ie('client', 'cdn'), ie('cdn', 's3'), ie('web', 'redis'), ie('web', 'q', { async: true }), ie('q', 'workers'), ie('workers', 'redis')],
    flows: [{ name: 'Write post', path: ['client', 'lb', 'web', 'pg'], steps: ['App creates a post', 'Request reaches an app server', 'Server routes to the author’s logical shard, which generates the ID'] }],
    problem: <p>Writes and data outgrow one primary. IDs must be unique across many databases and still sort by time.</p>,
    decision: <p>Create <strong>thousands of logical shards</strong> (Postgres schemas) on a few physical hosts. Each shard makes 64-bit IDs: time, shard ID, sequence.</p>,
    tradeoff: <p>Cross-user queries become scatter-gather. Each shard can mint at most 1,024 IDs per millisecond.</p>,
    realWorld: <p>The 2011 “Sharding &amp; IDs” post describes 41 bits of milliseconds, 13 bits of logical shard, and 10 bits of sequence, generated in PL/pgSQL. Growing means moving shards, never re-keying rows.</p>,
    walkthrough: ['User ID mod shard count picks the logical shard.', 'A mapping table says which host holds that shard.', 'The insert runs a function that builds the ID.', 'IDs sort by time, so “latest posts” needs no extra index.'],
    numbers: [{ label: 'ID layout', value: '41 / 13 / 10 bits', note: 'time / shard / sequence' }, { label: 'IDs per shard per ms', value: '1,024' }, { label: 'Load then', value: '25 photos/s, 90 likes/s', note: '2011 post' }],
    components: [{ name: 'Logical shards', role: 'Fixed number of buckets; hosts can change.' }, { name: 'In-DB ID function', role: 'No separate ID service on the write path.' }],
    alternatives: [{ option: 'Central ticket server', verdict: 'Extra dependency and single point of failure.' }, { option: 'UUIDs', verdict: '128 bits and not time-sortable.' }],
    breaksNext: <p>Some datasets (feeds, inboxes, fraud signals) are huge, write-heavy, and outgrow Redis memory.</p>,
    interview: { q: 'Design IDs for a sharded posts table.', a: <p>Generate them in each shard: time bits, shard bits, a local sequence. Unique, sortable, and routable without lookups.</p> },
    sources: [S.sharding],
  },
  {
    title: 'v4 · Cassandra for write-heavy data',
    era: '2012',
    scale: 'acquired by Facebook (April 2012)',
    summary: 'Move large, write-heavy datasets from in-memory Redis to a disk-based distributed store.',
    added: ['cass'],
    nodes: [IN.client, IN.lb, IN.web, shards, IN.cdn, IN.s3, IN.redis, IN.q, IN.workers, IN.cass],
    edges: [...FRONT, ie('web', 'pg'), ie('web', 's3'), ie('client', 'cdn'), ie('cdn', 's3'), ie('web', 'redis'), ie('web', 'q', { async: true }), ie('q', 'workers'), ie('workers', 'redis'), ie('web', 'cass')],
    flows: [{ name: 'Read inbox', path: ['client', 'lb', 'web', 'cass'], steps: ['App opens a feature backed by big data', 'Request reaches an app server', 'Server reads the user’s partition from Cassandra'] }],
    problem: <p>Keeping ever-growing datasets entirely in RAM gets expensive. Some need many writes and multi-node durability.</p>,
    decision: <p>Use <strong>Cassandra</strong>, which stores data on disk across nodes, for datasets like feeds, direct inboxes, and fraud signals.</p>,
    tradeoff: <p>A new database to operate. JVM garbage collection later shows up in tail latency.</p>,
    realWorld: <p>Instagram said it started using Cassandra in 2012 to replace Redis for use cases such as fraud detection, feed, and the Direct inbox. In 2018 it open-sourced Rocksandra, a RocksDB engine that cut p99 read latency sharply.</p>,
    walkthrough: ['Writes go to several replicas chosen by the partition key.', 'Reads ask enough replicas to meet the consistency level.', 'Data lives on disk, so size is not limited by RAM.'],
    numbers: [{ label: 'Cassandra adopted', value: '2012', note: 'The New Stack, 2018' }, { label: 'Rocksandra p99 read', value: '60 → 20 ms', note: 'one production cluster' }],
    components: [{ name: 'Cassandra', role: 'Partitioned, replicated store for big write-heavy data.' }],
    alternatives: [{ option: 'Keep scaling Redis', verdict: 'RAM cost grows with total data, not just hot data.' }, { option: 'More Postgres shards', verdict: 'Good for relational data; less so for huge append-heavy lists.' }],
    breaksNext: <p>Now part of Facebook, Instagram wants to run on Facebook’s infrastructure instead of AWS.</p>,
    interview: { q: 'When do you move data out of Redis?', a: <p>When the dataset’s total size, not its hot set, drives cost, or when you need stronger durability than memory offers.</p> },
    sources: [S.rocksandra, S.acquisition],
  },
  {
    title: 'v5 · Into Facebook’s data centers',
    era: '2013–2014',
    scale: '≈ 200M users',
    summary: 'Move thousands of servers from AWS to Facebook’s own data centers without downtime.',
    added: ['fbdc'],
    nodes: [IN.client, IN.lb, IN.web, shards, IN.cdn, IN.s3, IN.redis, IN.cass, IN.fbdc],
    edges: [...FRONT, ie('web', 'pg'), ie('web', 's3'), ie('client', 'cdn'), ie('cdn', 's3'), ie('web', 'redis'), ie('web', 'cass'), ie('web', 'fbdc', { label: 'migrate', async: true })],
    flows: [{ name: 'Migrate', path: ['web', 'fbdc'], steps: ['Services move step by step while traffic keeps flowing'] }],
    problem: <p>Running two separate infrastructures inside one company is wasteful. The move must happen live, with users growing fast.</p>,
    decision: <p>First move from EC2 into a private network (VPC). Then connect it to Facebook’s data centers and shift services over, piece by piece.</p>,
    tradeoff: <p>Months of engineering spent on a move users never notice. Risk of outages during the switch.</p>,
    realWorld: <p>Reporting in 2014 describes the EC2→VPC step taking about three weeks and a tool called Neti for consistent addressing. The user base doubled to about 200M during the migration.</p>,
    walkthrough: ['Build a common network between old and new environments.', 'Move instances from EC2 into a VPC.', 'Link the VPC to Facebook data centers.', 'Shift services and data over, then retire AWS capacity.'],
    numbers: [{ label: 'EC2 → VPC', value: '≈ 3 weeks', note: 'Data Center Knowledge' }, { label: 'Users during move', value: '≈ 200M', note: 'doubled during migration' }],
    components: [{ name: 'Neti', role: 'Daemon that managed IP tables so every instance had one address anywhere.' }],
    alternatives: [{ option: 'Big-bang cutover', verdict: 'Too risky at this size.' }, { option: 'Stay on AWS', verdict: 'Misses shared tooling and scale at the parent company.' }],
    breaksNext: <p>One data center is one disaster domain. Instagram needs several.</p>,
    interview: { q: 'How do you migrate infrastructure live?', a: <p>Make both sides reachable, move in small reversible steps, and keep traffic flowing with dual paths until each piece is verified.</p> },
    sources: [S.migration],
  },
]
