import type { EpisodeStage } from '../../components/ui'
import { SN, SRC, se } from './episode-spotify-stage-nodes'

// Stages 1–6: from the 2008 desktop client to the event pipeline.
export const SPOTIFY_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'Launch: servers + peers',
    era: '2008',
    scale: 'Millions of users · desktop only',
    summary: 'A desktop app streams music from Spotify’s servers and, where it can, from other listeners’ computers.',
    nodes: [SN.client, SN.ap, SN.meta, SN.audio, SN.peers],
    edges: [se('client', 'ap'), se('ap', 'meta'), se('ap', 'audio'), se('client', 'peers', { label: 'P2P' })],
    flows: [
      { name: 'Play', path: ['client', 'ap', 'audio'], steps: ['App asks its access point for a track', 'Servers stream the first part right away'] },
      { name: 'Peers', path: ['client', 'peers'], steps: ['Later parts come from nearby listeners who already have the file'] },
    ],
    problem: <p>Streaming must feel as fast as a local MP3. Bandwidth is expensive, and the catalog has millions of tracks.</p>,
    decision: <p>A native desktop client keeps one connection to an access point. It fetches the start of a track from servers and the rest from a peer-to-peer swarm when peers have it.</p>,
    tradeoff: <p>P2P saves bandwidth but adds protocol complexity, NAT traversal pain, and upload traffic on users’ machines.</p>,
    realWorld: <p>A 2010 paper by Spotify engineers describes this hybrid. It reports that only <strong>8.8%</strong> of played music data came from Spotify’s servers.</p>,
    walkthrough: [
      'The user clicks a track in the desktop app.',
      'The app asks its access point for track metadata over an already-open connection.',
      'Servers send the opening seconds so playback can start.',
      'The app finds peers holding the same file and pulls later chunks from them.',
      'If peers are slow, the app falls back to servers to avoid a stall.',
    ],
    numbers: [
      { label: 'Users (2010 paper)', value: '7M+', note: 'six European countries' },
      { label: 'Catalog (2010 paper)', value: '8M+ tracks' },
      { label: 'Data served by servers', value: '8.8%', note: 'rest from peers or cache' },
    ],
    components: [
      { name: 'Access point', role: 'Front door for the client. Holds one long-lived connection so requests skip setup.' },
      { name: 'P2P swarm', role: 'Other desktop clients that cache and share encrypted track data.' },
    ],
    alternatives: [
      { option: 'Pure client–server', verdict: 'Simpler, but bandwidth cost was the main worry at this scale.' },
      { option: 'Commercial CDN from day one', verdict: 'Possible later; early on, peers were cheaper.' },
    ],
    breaksNext: <p>Users skip constantly. Every skip is a new start, so start latency becomes the metric that matters.</p>,
    interview: { q: 'Why mix servers and P2P instead of pure P2P?', a: <p>P2P is slow to start: you must find peers first. Servers give a fast first chunk, and peers take over the bulk transfer.</p> },
    sources: [SRC.p2pPaper],
  },
  {
    title: 'Instant start',
    era: '2008–2010',
    scale: 'Skips are constant',
    summary: 'Most plays start from a local cache or a prefetch, so the user rarely waits.',
    added: ['cache'],
    nodes: [SN.client, SN.cache, SN.ap, SN.meta, SN.audio, SN.peers],
    edges: [se('client', 'cache'), se('client', 'ap'), se('ap', 'meta'), se('ap', 'audio'), se('client', 'peers')],
    flows: [
      { name: 'Cache hit', path: ['client', 'cache'], steps: ['Track is already on disk, so it plays with no network trip'] },
      { name: 'Prefetch', path: ['client', 'ap', 'audio'], steps: ['Near the end of a song, the app requests the next track', 'Its first chunk is downloaded before the user asks'] },
    ],
    problem: <p>A one-second delay on every skip feels broken. Network round trips, not bandwidth, dominate the wait.</p>,
    decision: <p>Keep a large local cache of recently played tracks. Prefetch the start of the likely next track. Reuse the open connection so no setup is needed per play.</p>,
    tradeoff: <p>The cache uses disk space. Prefetching wastes bandwidth on tracks that never play.</p>,
    realWorld: <p>The same 2010 paper reports a <strong>median playback latency of 265 ms</strong>, counting cached tracks.</p>,
    walkthrough: [
      'The app checks its local cache first.',
      'On a miss, it requests the first chunk over the warm connection.',
      'While a song plays, it prefetches the start of the next one.',
      'Playback begins as soon as a small buffer is filled.',
    ],
    numbers: [
      { label: 'Median start latency', value: '265 ms', note: '2010 paper, incl. cache hits' },
      { label: 'One 3.5-min track at 160 kbps', value: '≈ 4 MB', note: 'estimate' },
    ],
    components: [{ name: 'Client cache', role: 'Stores encrypted chunks on disk; turns repeat plays into zero-network plays.' }],
    alternatives: [
      { option: 'Bigger server fleet', verdict: 'Does not remove the round trip, which is the real cost.' },
      { option: 'No prefetch', verdict: 'Saves data but makes every skip wait on the network.' },
    ],
    breaksNext: <p>Phones arrive. They have no P2P, flaky networks, and users want music with no signal at all.</p>,
    interview: { q: 'How do you cut start latency without faster servers?', a: <p>Remove round trips: cache locally, prefetch the likely next item, and keep connections warm.</p> },
    sources: [SRC.p2pPaper],
  },
  {
    title: 'Mobile + offline',
    era: '2009',
    scale: 'Phones join · Premium only',
    summary: 'Phones can save playlists for offline play, protected by keys that expire.',
    added: ['keys'],
    nodes: [{ ...SN.client, label: 'Desktop + mobile' }, SN.cache, SN.ap, SN.meta, SN.audio, SN.peers, SN.keys],
    edges: [se('client', 'cache'), se('client', 'ap'), se('ap', 'meta'), se('ap', 'audio'), se('ap', 'keys'), se('client', 'peers', { label: 'desktop only' })],
    flows: [{ name: 'Go offline', path: ['client', 'ap', 'keys'], steps: ['User marks a playlist for offline', 'App downloads encrypted tracks, then requests a time-limited key'] }],
    problem: <p>Mobile networks drop out. Users want music on planes and subways. Labels require protection for downloaded files.</p>,
    decision: <p>Store encrypted tracks on the device. Keep keys in a separate service. Offline keys expire, so the app must check in periodically.</p>,
    tradeoff: <p>Licensing now runs on a device you do not control. Expired keys frustrate users who stay offline too long.</p>,
    realWorld: <p>Spotify’s iPhone and Android apps went live in September 2009, for Premium users, with an offline mode that cached playlists.</p>,
    walkthrough: [
      'The user marks a playlist “available offline”.',
      'The app downloads encrypted audio to local storage.',
      'The key service checks the subscription and issues a device-bound key with an expiry.',
      'Offline, the app decrypts locally until the key expires.',
    ],
    numbers: [
      { label: 'Mobile launch', value: 'Sep 2009', note: 'iPhone + Android' },
      { label: 'Offline playlist, 50 tracks', value: '≈ 200 MB', note: 'estimate at 160 kbps' },
    ],
    components: [{ name: 'Key service', role: 'Checks rights and issues device-bound, expiring keys. Audio bytes stay dumb and cacheable.' }],
    alternatives: [
      { option: 'Unencrypted downloads', verdict: 'Not acceptable to rights holders.' },
      { option: 'Keys baked into files', verdict: 'Cannot be revoked when a subscription ends.' },
    ],
    breaksNext: <p>Playlists become the main way people listen, and edits must sync across every device.</p>,
    interview: { q: 'Why keep keys separate from audio?', a: <p>Encrypted bytes can be cached anywhere. Rights checks stay in one small service that can revoke access.</p> },
    sources: [SRC.mobile, SRC.mobileBb],
  },
  {
    title: 'Playlists as change logs',
    era: 'Design pattern',
    scale: 'Many devices per user',
    summary: 'A playlist is stored as a list of edits, so every device can catch up by replaying what it missed.',
    added: ['playlist', 'pldb'],
    nodes: [SN.client, SN.cache, SN.ap, SN.meta, SN.audio, SN.keys, SN.playlist, SN.pldb],
    edges: [se('client', 'cache'), se('client', 'ap'), se('ap', 'meta'), se('ap', 'audio'), se('ap', 'keys'), se('ap', 'playlist'), se('playlist', 'pldb')],
    flows: [{ name: 'Edit', path: ['client', 'ap', 'playlist', 'pldb'], steps: ['User moves a track on the phone', 'Access point routes the edit', 'Playlist service appends it with a new version; other devices later ask for changes since theirs'] }],
    problem: <p>Users edit on a phone, then open the laptop. Some edit offline. Collaborative playlists have many editors at once.</p>,
    decision: <p>Store each playlist as a versioned log of operations (add, move, remove). Devices sync by asking for changes since version N. Concurrent edits merge by replaying operations.</p>,
    tradeoff: <p>Reads must fold the log into a list, so you snapshot periodically. Merge rules for conflicting moves are visible to users.</p>,
    realWorld: <p>This stage describes a general design, not a documented Spotify internal. The 2009 mobile launch did advertise playlist sync between phone and desktop.</p>,
    walkthrough: [
      'A device sends an operation tagged with the version it last saw.',
      'The service appends the operation and assigns the next version.',
      'Other devices fetch only the operations after their version.',
      'Periodic snapshots keep reads fast.',
    ],
    numbers: [
      { label: 'Full 1,000-track list', value: '≈ 50 KB', note: 'estimate' },
      { label: 'One edit as a delta', value: '≈ 100 B', note: 'estimate' },
    ],
    components: [
      { name: 'Playlist service', role: 'Validates edits, assigns versions, answers “what changed since N?”.' },
      { name: 'Playlist store', role: 'Append-only change log plus snapshots.' },
    ],
    alternatives: [
      { option: 'Mutable array per playlist', verdict: 'Last write wins and silently drops concurrent edits.' },
      { option: 'Full CRDT sequence', verdict: 'Merges anything, at higher metadata cost.' },
    ],
    breaksNext: <p>P2P no longer pays for itself, and phones never used it.</p>,
    interview: { q: 'How would you sync a playlist edited offline on two devices?', a: <p>Send operations, not snapshots. Replay both logs with deterministic merge rules, and show conflicts only when intent truly clashes.</p> },
    sources: [SRC.mobileBb, SRC.crdt],
  },
  {
    title: 'Drop P2P, lean on servers',
    era: '2014',
    scale: 'Listening shifts to phones',
    summary: 'Spotify retired peer-to-peer delivery and served audio from its own infrastructure.',
    added: ['cdn'],
    nodes: [SN.client, SN.ap, SN.meta, SN.audio, SN.keys, SN.playlist, SN.pldb, SN.cdn],
    edges: [se('client', 'ap'), se('ap', 'meta'), se('ap', 'keys'), se('ap', 'playlist'), se('playlist', 'pldb'), se('client', 'cdn'), se('cdn', 'audio')],
    flows: [{ name: 'Stream', path: ['client', 'cdn', 'audio'], steps: ['App fetches encrypted chunks from a nearby edge', 'An edge miss pulls from origin storage once'] }],
    problem: <p>Most listening moved to phones, which never used P2P. Keeping the swarm alive adds cost and complexity for a shrinking share of traffic.</p>,
    decision: <p>Serve all audio from Spotify-run infrastructure and caching layers. Keep the client cache and prefetch, which deliver most of the speed anyway.</p>,
    tradeoff: <p>Higher bandwidth bills. In return, one delivery path for every platform.</p>,
    realWorld: <p>In April 2014 Spotify said it was phasing out P2P. Its stated reason was that its server fleet could now deliver music well on its own.</p>,
    walkthrough: [
      'The app resolves the track to file ids and bitrates.',
      'It requests the key if not cached.',
      'It downloads encrypted chunks from the nearest edge.',
      'The edge fills from origin storage on a miss.',
    ],
    numbers: [{ label: 'P2P phased out', value: 'Apr 2014' }],
    components: [{ name: 'CDN / edge caches', role: 'Serve encrypted chunks close to users; useless without a key, so safe to cache anywhere.' }],
    alternatives: [
      { option: 'Keep P2P on desktop', verdict: 'Two delivery paths to maintain for little benefit.' },
    ],
    breaksNext: <p>Every play, skip, and pause is now an event. The event stream grows far faster than the play rate.</p>,
    interview: { q: 'When would you remove an optimization like P2P?', a: <p>When its share of traffic shrinks and its complexity cost stays fixed. Measure before and after.</p> },
    sources: [SRC.p2pDrop],
  },
  {
    title: 'Event delivery',
    era: 'up to 2016',
    scale: '700K+ events/s',
    summary: 'Every play, skip, and pause becomes an event that feeds charts, experiments, and recommendations.',
    added: ['events', 'lake'],
    nodes: [SN.client, SN.ap, SN.meta, SN.audio, SN.keys, SN.playlist, SN.pldb, SN.cdn, SN.events, SN.lake],
    edges: [se('client', 'ap'), se('ap', 'meta'), se('ap', 'keys'), se('ap', 'playlist'), se('playlist', 'pldb'), se('client', 'cdn'), se('cdn', 'audio'), se('ap', 'events', { async: true }), se('events', 'lake')],
    flows: [{ name: 'Report', path: ['client', 'ap', 'events', 'lake'], steps: ['App batches events with unique ids, buffering offline', 'Event delivery persists the batch durably', 'Pipelines deduplicate and aggregate by event time'] }],
    problem: <p>Stream counts drive charts and rights-holder reporting. Offline plays arrive days late. Retries create duplicates.</p>,
    decision: <p>Build a durable event pipeline. Clients attach unique ids and buffer offline. Downstream jobs deduplicate and count by event time, not arrival time.</p>,
    tradeoff: <p>At-least-once delivery plus deduplication is cheaper than exactly-once, but reports can only close after a lateness window.</p>,
    realWorld: <p>A 2016 Spotify post describes event delivery built on <strong>Kafka 0.7</strong>, carrying more than 700,000 events per second. It says the data feeds experiments, Discover Weekly, and streaming charts.</p>,
    walkthrough: [
      'The client logs events with a unique id and a timestamp.',
      'Offline events wait in a local buffer.',
      'Batches reach the event delivery system and are persisted.',
      'Jobs deduplicate on id and aggregate per hour of event time.',
      'Late data updates open windows until they close.',
    ],
    numbers: [
      { label: 'Event rate (2016)', value: '700K+/s', note: 'Spotify Engineering' },
      { label: 'Events per day', value: '≈ 60B', note: 'estimate from 700K/s' },
    ],
    components: [
      { name: 'Event delivery', role: 'Durable, ordered transport from clients to storage.' },
      { name: 'Data platform', role: 'Batch and streaming jobs over the raw events.' },
    ],
    alternatives: [
      { option: 'Write plays straight to a database', verdict: 'Couples the hot path to analytics load.' },
      { option: 'Exactly-once end to end', verdict: 'Costly; dedupe on ids gives the same counts.' },
    ],
    breaksNext: <p>With all this data, the next question is what to play people they have never heard.</p>,
    interview: { q: 'How do you count plays you pay money on?', a: <p>Unique event ids, dedupe downstream, aggregate on event time, and keep raw events so any report can be recomputed.</p> },
    sources: [SRC.events1, SRC.royalties],
  },
]
