import type { EpisodeStage } from '../../components/ui'
import { CN, GSRC, ce } from './episode-chatgpt-stage-nodes'

const CORE = [ce('client', 'edge'), ce('edge', 'quota'), ce('edge', 'chat'), ce('chat', 'convdb'), ce('chat', 'queue'), ce('queue', 'model')]

// Stages 7–12: code, multimodal, GPTs, memory, safety, capacity.
export const CHATGPT_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'Code sandbox + files',
    era: '2023',
    scale: 'User code runs on your servers',
    summary: 'The model writes Python, and the platform runs it in an isolated sandbox with the user’s files.',
    added: ['sandbox', 'files'],
    nodes: [CN.client, CN.edge, CN.quota, CN.chat, CN.convdb, CN.queue, CN.model, CN.sandbox, CN.files],
    edges: [...CORE, ce('chat', 'sandbox', { label: 'run code' }), ce('edge', 'files'), ce('sandbox', 'files')],
    flows: [{ name: 'Analyze a CSV', path: ['client', 'edge', 'files', 'sandbox'], steps: ['User uploads a CSV and asks for a chart', 'Edge stores the upload', 'The sandbox mounts the file and runs model-written Python'] }],
    problem: <p>Users want charts, data analysis, and file conversions. Running untrusted, model-written code on shared servers is dangerous.</p>,
    decision: <p>Run code in a firewalled sandbox per conversation, with temporary disk and strict CPU, memory, and time limits. Return outputs as files and text.</p>,
    tradeoff: <p>Sandboxes cost money while idle and add startup latency. No network access limits what the code can do.</p>,
    realWorld: <p>OpenAI’s March 2023 plugins post described a Python interpreter in a “sandboxed, firewalled execution environment” with temporary disk space.</p>,
    walkthrough: [
      'The upload is stored and linked to the conversation.',
      'The model writes code and requests execution.',
      'A sandbox starts, or is reused for this chat.',
      'Code runs with limits; outputs are captured.',
      'Results return to the model and the user.',
    ],
    numbers: [{ label: 'Sandbox lifetime', value: 'per chat session', note: 'per the 2023 post' }],
    components: [
      { name: 'Code sandbox', role: 'Isolated container or micro-VM with no network and hard resource limits.' },
      { name: 'File store', role: 'Holds uploads and generated files, scoped to one user.' },
    ],
    alternatives: [
      { option: 'Run code in the app servers', verdict: 'One bad script could reach other users’ data.' },
      { option: 'Only let the model describe code', verdict: 'Safe, but far less useful.' },
    ],
    breaksNext: <p>Users want to talk, listen, and show photos, not just type.</p>,
    interview: { q: 'How do you run model-written code safely?', a: <p>Per-session isolation, no network by default, resource limits, and scoped file access. Assume the code is hostile.</p> },
    sources: [GSRC.plugins],
  },
  {
    title: 'See, hear, speak',
    era: 'Sep 2023 → May 2024',
    scale: 'Voice needs human-like latency',
    summary: 'Speech and images join the conversation, and voice replies must start within a fraction of a second.',
    added: ['media'],
    nodes: [CN.client, CN.media, CN.edge, CN.quota, CN.chat, CN.convdb, CN.queue, CN.model],
    edges: [...CORE, ce('client', 'media'), ce('media', 'edge')],
    flows: [{ name: 'Voice turn', path: ['client', 'media', 'edge', 'chat', 'queue', 'model'], steps: ['User speaks', 'Speech is converted to text', 'Routed', 'Queued', 'Model answers; speech synthesis reads it back'] }],
    problem: <p>Typing is slow on phones. In voice, a pause of a few seconds feels broken.</p>,
    decision: <p>Add speech-to-text, text-to-speech, and image understanding. Later, move toward models that handle audio directly, cutting the hops between separate models.</p>,
    tradeoff: <p>Each extra model in a pipeline adds latency and loses tone. Native audio models are harder to build and evaluate.</p>,
    realWorld: <p>In September 2023 OpenAI added voice and image input to ChatGPT, using Whisper for speech recognition. In May 2024 it said GPT-4o can answer audio in as little as 232 ms, 320 ms on average.</p>,
    walkthrough: [
      'Audio streams from the device.',
      'Speech becomes text (or goes straight to an audio model).',
      'The model generates a reply.',
      'Speech synthesis streams audio back before the reply is finished.',
    ],
    numbers: [
      { label: 'GPT-4o audio response', value: '232 ms min · 320 ms avg', note: 'OpenAI, May 2024' },
      { label: 'Voices at launch', value: '5', note: 'Sep 2023' },
    ],
    components: [{ name: 'Speech + vision', role: 'Speech recognition, speech synthesis, and image inputs.' }],
    alternatives: [
      { option: 'Separate STT → LLM → TTS pipeline', verdict: 'Easy to build; each hop adds delay.' },
      { option: 'One native audio model', verdict: 'Fastest and keeps tone; harder to build.' },
    ],
    breaksNext: <p>Users want assistants customized for a task, with their own files as knowledge.</p>,
    interview: { q: 'Where does latency come from in a voice assistant?', a: <p>Speech recognition, prompt processing, first token, and speech synthesis. Stream every stage and cut hops.</p> },
    sources: [GSRC.seeHear, GSRC.gpt4o],
  },
  {
    title: 'Custom GPTs + retrieval',
    era: 'Nov 2023',
    scale: '100M weekly users',
    summary: 'Anyone can package instructions, files, and actions into a custom assistant that searches its own knowledge.',
    added: ['vector'],
    nodes: [CN.client, CN.edge, CN.quota, CN.chat, CN.convdb, CN.queue, CN.model, CN.vector, CN.files, CN.tools],
    edges: [...CORE, ce('chat', 'vector'), ce('files', 'vector', { label: 'index', async: true }), ce('edge', 'files'), ce('chat', 'tools')],
    flows: [{ name: 'Ask a GPT', path: ['client', 'edge', 'chat', 'vector'], steps: ['User asks a custom GPT a question', 'Routed', 'Orchestrator retrieves matching passages from that GPT’s files'] }],
    problem: <p>Power users paste the same long prompts again and again. Teams want assistants grounded in their own documents.</p>,
    decision: <p>Let users bundle instructions, knowledge files, and actions. Index the files for retrieval, and add only the most relevant passages to each prompt.</p>,
    tradeoff: <p>Retrieval can miss the right passage. Shared GPTs raise questions about data exposure and quality control.</p>,
    realWorld: <p>OpenAI announced GPTs at its first DevDay in November 2023. Sam Altman said there that ChatGPT had 100 million weekly active users.</p>,
    walkthrough: [
      'Uploaded files are split into chunks and indexed.',
      'A question is matched against that GPT’s index.',
      'The best passages join the prompt with the GPT’s instructions.',
      'The model answers, citing retrieved text.',
    ],
    numbers: [{ label: 'Weekly active users (Nov 2023)', value: '100M', note: 'TechCrunch' }],
    components: [{ name: 'Retrieval index', role: 'Chunked, embedded files searchable per GPT or per user.' }],
    alternatives: [
      { option: 'Stuff whole files into the prompt', verdict: 'Costly and often exceeds the context window.' },
      { option: 'Fine-tune per customer', verdict: 'Slow to update and poor at exact facts.' },
    ],
    breaksNext: <p>Users want the assistant to remember them across chats.</p>,
    interview: { q: 'Retrieval or a longer context window?', a: <p>Retrieval keeps prompts small and fresh. Long context is simpler but costs more on every call.</p> },
    sources: [GSRC.gpts, GSRC.wau],
  },
  {
    title: 'Memory',
    era: 'Feb 2024',
    scale: 'Personal context across chats',
    summary: 'The assistant can keep short facts about a user and add them to future prompts, with user controls.',
    added: ['memory'],
    nodes: [CN.client, CN.edge, CN.quota, CN.chat, CN.memory, CN.convdb, CN.queue, CN.model, CN.vector],
    edges: [...CORE, ce('chat', 'memory'), ce('chat', 'vector')],
    flows: [{ name: 'Recall', path: ['client', 'edge', 'chat', 'memory'], steps: ['User starts a new chat', 'Routed', 'Orchestrator loads a few saved facts into the system prompt'] }],
    problem: <p>The model forgets everything between chats. Users repeat their preferences every time.</p>,
    decision: <p>Save short, user-visible facts. Inject a small, relevant set into new prompts. Let users view, delete, or turn memory off.</p>,
    tradeoff: <p>Wrong or stale memories quietly skew answers. Stored personal data raises privacy duties.</p>,
    realWorld: <p>OpenAI began testing memory in February 2024. Users can manage or delete memories and use a temporary chat that does not use memory.</p>,
    walkthrough: [
      'The model or user marks a fact worth remembering.',
      'The fact is stored per user, visible in settings.',
      'New chats load a few relevant facts.',
      'Deleting a memory removes it from future prompts.',
    ],
    numbers: [{ label: 'Memory test began', value: '13 Feb 2024' }],
    components: [{ name: 'User memory', role: 'Small per-user store of facts with explicit controls.' }],
    alternatives: [
      { option: 'Include all past chats', verdict: 'Too many tokens and a privacy risk.' },
    ],
    breaksNext: <p>At hundreds of millions of users, misuse happens every day.</p>,
    interview: { q: 'What must a memory feature let users do?', a: <p>See what is stored, edit or delete it, and switch it off entirely.</p> },
    sources: [GSRC.memory],
  },
  {
    title: 'Safety layers',
    era: 'Ongoing',
    scale: 'Every message checked',
    summary: 'Classifiers check inputs and outputs, separate from the model, so policies can change without retraining.',
    added: ['safety'],
    nodes: [CN.client, CN.safety, CN.edge, CN.quota, CN.chat, CN.convdb, CN.queue, CN.model, CN.tools],
    edges: [...CORE, ce('chat', 'safety'), ce('chat', 'tools')],
    flows: [{ name: 'Check', path: ['client', 'edge', 'chat', 'safety'], steps: ['Message arrives', 'Routed', 'Input and streamed output are classified; violations stop or change the reply'] }],
    problem: <p>Misuse is constant at scale. Tools and files add prompt-injection risk. A behavior regression reaches millions in minutes.</p>,
    decision: <p>Wrap the model with independent checks on input and output. Detect abuse per account. Evaluate every model change offline before rollout.</p>,
    tradeoff: <p>Checks add latency. False positives frustrate honest users. Checking streamed text may mean withdrawing words already shown.</p>,
    realWorld: <p>OpenAI documents a public moderation endpoint that classifies text by policy category. Layered classifiers are common industry practice.</p>,
    walkthrough: [
      'Classify the input before generation.',
      'Classify output chunks while streaming.',
      'Apply policy: allow, refuse, or cut off.',
      'Log decisions for review and model evaluation.',
    ],
    numbers: [{ label: 'Checks per message', value: '≥ 2 (in + out)', note: 'design' }],
    components: [{ name: 'Safety checks', role: 'Classifiers and rules that run independently of the model.' }],
    alternatives: [
      { option: 'Rely only on model training', verdict: 'Slow to update when new misuse appears.' },
    ],
    breaksNext: <p>Growth outruns GPU supply. Capacity becomes a strategic, multi-year problem.</p>,
    interview: { q: 'Why keep safety checks outside the model?', a: <p>They can be updated fast, tested alone, and applied the same way to every model version.</p> },
    sources: [GSRC.moderation],
  },
  {
    title: 'Global capacity',
    era: '2023 → 2025',
    scale: 'Multi-year GPU build-out',
    summary: 'Requests are routed across GPU pools and regions, and capacity is planned years ahead.',
    nodes: [CN.client, CN.safety, CN.edge, CN.quota, CN.chat, CN.convdb, { ...CN.queue, label: 'Router', sub: 'model · region · plan' }, { ...CN.model, label: 'GPU pools', sub: 'many regions' }, { ...CN.web, label: 'Cloud partners', sub: 'compute capacity' }],
    edges: [...CORE, ce('chat', 'safety'), ce('queue', 'web', { label: 'overflow' })],
    flows: [{ name: 'Spill over', path: ['client', 'edge', 'chat', 'queue', 'web'], steps: ['Launch-day spike', 'Admitted by plan', 'Router finds the home pool full', 'Sends work to other capacity, or to a smaller model for low tiers'] }],
    problem: <p>GPUs are scarce and uneven across regions. New features launch to huge audiences overnight.</p>,
    decision: <p>Route by model, region, and plan. Under pressure, degrade in order: queue, spill to other regions, use a smaller model for low tiers, then shed free traffic with honest messages.</p>,
    tradeoff: <p>Cross-region routing adds latency and data-residency work. Model fallbacks change answer quality, so they must be visible.</p>,
    realWorld: <p>In January 2023 Microsoft extended its partnership with OpenAI, with Azure as its cloud. In January 2025 OpenAI announced Stargate, a venture planning to invest $500 billion over four years in AI infrastructure.</p>,
    walkthrough: [
      'Each request is tagged with model, plan, and region.',
      'The router picks a pool with free capacity.',
      'If none fits, it queues briefly.',
      'Then it spills to other regions or a smaller model.',
      'Free traffic is shed last, with a clear message.',
    ],
    numbers: [{ label: 'Stargate plan', value: '$500B / 4 years', note: 'announced Jan 2025' }],
    components: [
      { name: 'Router', role: 'Chooses model, region, and pool per request under capacity limits.' },
      { name: 'Cloud partners', role: 'External compute supply beyond owned capacity.' },
    ],
    alternatives: [
      { option: 'Fail randomly under load', verdict: 'Hurts paid users and feels broken.' },
      { option: 'Single region', verdict: 'Simple, but one outage takes everything down.' },
    ],
    interview: { q: 'Describe a degradation ladder for an LLM product.', a: <p>Queue, spill regions, fall back to smaller models for low tiers, then shed free traffic with honest UX.</p> },
    sources: [GSRC.microsoft, GSRC.stargate],
  },
]
