import type { EpisodeStage } from '../../components/ui'
import { CORE_EDGES, DN, de } from './episode-discord-stage-nodes'
import { DISCORD_SRC as S } from './episode-discord-sources'

// Stages 1–6: launch through voice. Numbers are from the cited posts unless marked "estimate".
export const DISCORD_STAGES_EARLY: EpisodeStage[] = [
  {
    title: 'v0 · One chat server',
    era: '2015',
    scale: 'launch · gaming groups',
    summary: 'One program holds every connection and saves every message in one database.',
    nodes: [DN.client, DN.mono, DN.mongo],
    edges: [de('client', 'mono'), de('mono', 'mongo')],
    flows: [{ name: 'Send', path: ['client', 'mono', 'mongo'], steps: ['Client sends a message over its socket', 'Server saves it and pushes it to everyone connected'] }],
    problem: <p>A small team wants low-latency voice and text chat for gamers. Nobody knows which features will stick. Speed of shipping matters most.</p>,
    decision: <p>Keep everything in one place. One service holds the sockets and the API. Messages go to a single document database.</p>,
    tradeoff: <p>Connections, logic, and storage share one failure domain. A deploy drops every socket.</p>,
    realWorld: <p>Discord launched publicly in May 2015. Its engineers later wrote that everything was first stored in a single MongoDB replica set.</p>,
    walkthrough: ['Client opens a WebSocket to the server.', 'User types a message; the server writes it to MongoDB.', 'The server loops over connected users in that channel and pushes it.'],
    numbers: [{ label: 'Databases', value: '1', note: 'single replica set' }, { label: 'Stored messages, Nov 2015', value: '≈ 100M', note: 'Discord, 2017' }],
    components: [{ name: 'Chat server', role: 'Sockets, API, and fan-out in one process group. Simple to build and debug.' }, { name: 'MongoDB', role: 'Flexible documents and quick to start with. Fine while data fits in RAM.' }],
    alternatives: [{ option: 'Peer-to-peer chat', verdict: 'No server history, hard moderation, and it leaks IP addresses.' }, { option: 'Microservices from day one', verdict: 'Too much overhead before product–market fit.' }],
    breaksNext: <p>Sockets and business logic scale differently. A community server needs one consistent view of its members.</p>,
    interview: { q: 'Why start with a monolith?', a: <p>It is the fastest way to learn what users need. Split only at a measured bottleneck, and name that bottleneck.</p> },
    sources: [S.launch, S.billions],
  },
  {
    title: 'v1 · Gateway + guild processes',
    era: '2015–2017',
    scale: 'millions of concurrent users',
    summary: 'Split “holding connections” from “owning a server’s state”, and send writes over HTTP.',
    added: ['api', 'gw', 'guild'],
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.mongo],
    edges: [...CORE_EDGES, de('api', 'mongo')],
    flows: [
      { name: 'Send', path: ['client', 'api', 'mongo'], steps: ['Client POSTs the message over HTTP', 'API checks permissions and stores it'] },
      { name: 'Deliver', path: ['api', 'guild', 'gw', 'client'], steps: ['API hands the event to the owning guild process', 'Guild picks the sessions that should see it', 'Gateways push it down each socket'] },
    ],
    problem: <p>One box cannot hold every socket. Each community (a <em>guild</em>) needs one consistent view of members, roles, and channels.</p>,
    decision: <p>A <strong>gateway</strong> tier only holds WebSockets. Each guild gets a <strong>guild process</strong> that owns its state and fans out events. Writes go through a stateless HTTP API.</p>,
    tradeoff: <p>Events must be routed to the right guild process in a cluster. A single owner is simple but can become a hotspot.</p>,
    realWorld: <p>Discord built these as lightweight Elixir processes on the Erlang VM. A 2017 post describes nearly 5 million concurrent users and a consistent-hash ring to find each process.</p>,
    walkthrough: ['Client connects to a gateway and gets a session process.', 'Session subscribes to the guild processes of the user’s servers.', 'Client sends a message by HTTP POST.', 'API stores it, then notifies the guild process.', 'Guild process sends the event to each subscribed session.'],
    numbers: [{ label: 'Concurrent users (2017)', value: '≈ 5M', note: 'Discord, 2017' }, { label: 'Largest guilds then', value: '≈ 30K online', note: 'Discord, 2017' }, { label: 'Guilds per user', value: '≈ 5 on average', note: 'Discord, 2017' }],
    components: [{ name: 'Gateway sessions', role: 'One process per connected client. Heartbeats, resume, compression.' }, { name: 'Guild process', role: 'Single owner of a server’s state. All fan-out starts here.' }, { name: 'Hash ring', role: 'Maps a guild ID to the node that runs its process.' }],
    alternatives: [{ option: 'Shared DB + stateless workers', verdict: 'Every permission check becomes a DB round-trip.' }, { option: 'Send messages over the socket', verdict: 'Harder to rate-limit, retry, and scale apart from connections.' }],
    breaksNext: <p>The document database no longer fits in memory. Reading old messages becomes slow and unpredictable.</p>,
    interview: { q: 'Who owns a chat server’s state?', a: <p>One process per guild. Coordination becomes local logic. The price is hotspots and failover of that owner.</p> },
    sources: [S.elixir, S.gatewayDocs],
  },
  {
    title: 'v2 · Messages move to Cassandra',
    era: '2015–2017',
    scale: '100M+ messages per day',
    summary: 'Store each channel’s messages together, in time order, so “latest 50” is one read.',
    added: ['cass'],
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.cass],
    edges: [...CORE_EDGES, de('api', 'cass')],
    flows: [{ name: 'History', path: ['client', 'api', 'cass'], steps: ['Client scrolls up in a channel', 'API reads one (channel, bucket) partition, newest first'] }],
    problem: <p>Past 100 million stored messages, data and indexes no longer fit in RAM. Latency becomes unpredictable. The main query is simple: <em>latest messages in one channel</em>.</p>,
    decision: <p>Move messages to <strong>Cassandra</strong>. Key rows by <code>(channel_id, bucket)</code>, then message ID. A bucket is a fixed time window.</p>,
    tradeoff: <p>No joins or ad-hoc queries. Bucket size is a guess: too big makes huge partitions, too small makes many empty reads.</p>,
    realWorld: <p>Discord’s January 2017 post describes this model. About 10 days of messages per bucket kept partitions under 100 MB. It ran 12 nodes with replication factor 3.</p>,
    walkthrough: ['API computes the bucket from the message’s timestamp.', 'Write goes to the (channel, bucket) partition on 3 replicas.', 'Reading history scans one partition backwards by message ID.', 'If the page is short, read the previous bucket.'],
    numbers: [{ label: 'Messages per day', value: '40M → 120M+', note: 'mid-2016 → Jan 2017' }, { label: 'Cluster', value: '12 nodes, RF 3', note: 'Discord, 2017' }, { label: 'Bucket', value: '≈ 10 days', note: 'kept partitions < 100 MB' }],
    components: [{ name: 'Wide-column store', role: 'Sequential reads within a partition; scales by adding nodes.' }, { name: 'Snowflake-style IDs', role: 'Time-sortable IDs double as the clustering key.' }],
    alternatives: [{ option: 'Sharded SQL', verdict: 'Workable, but resharding and failover were more manual.' }, { option: 'Bigger MongoDB machines', verdict: 'Buys months, not years.' }],
    breaksNext: <p>Users want to search years of messages. A key-value layout cannot answer “find ‘patch notes’ in this server”.</p>,
    interview: { q: 'How do you choose a partition key for chat?', a: <p>Start from the hot query. Here it is “latest N in a channel”, so partition by channel plus a time bucket to cap partition size.</p> },
    sources: [S.billions],
  },
  {
    title: 'v3 · Search on many small clusters',
    era: '2017',
    scale: 'tens of billions of messages indexed',
    summary: 'Index messages in batches into many small search clusters, and pick the cluster per server.',
    added: ['es', 'idxq'],
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.cass, DN.es, DN.idxq],
    edges: [...CORE_EDGES, de('api', 'cass'), de('api', 'idxq', { async: true }), de('idxq', 'es'), de('api', 'es')],
    flows: [
      { name: 'Index', path: ['api', 'idxq', 'es'], steps: ['New messages are queued for indexing', 'Workers bulk-index batches into the cluster for that server'] },
      { name: 'Search', path: ['client', 'api', 'es'], steps: ['User searches a server', 'API routes the query to the cluster that holds that server'] },
    ],
    problem: <p>Search needs an inverted index. One giant cluster is expensive and a single failure takes search down everywhere.</p>,
    decision: <p>Shard in the <strong>application</strong>: route each server’s messages to one of many small Elasticsearch clusters. Index in bulk from a queue. Index recent history first, the rest later.</p>,
    tradeoff: <p>Search lags a few seconds behind chat. The app owns routing and rebalancing logic.</p>,
    realWorld: <p>Discord’s March 2017 post reports about 26 billion indexed messages on 14 nodes in 2 clusters. Workers first index the last 7 days, then backfill deeper history.</p>,
    walkthrough: ['Message is stored, then an index job is queued.', 'Workers collect jobs and send bulk requests.', 'A routing table maps each server to a cluster.', 'Queries go only to that server’s cluster.'],
    numbers: [{ label: 'Documents', value: '≈ 26B', note: 'Discord, 2017' }, { label: 'Search nodes', value: '14 in 2 clusters', note: 'Discord, 2017' }, { label: 'Peak indexing', value: '≈ 30K msg/s', note: 'Discord, 2017' }],
    components: [{ name: 'Index queue', role: 'Decouples chat writes from indexing; enables bulk requests.' }, { name: 'Cluster router', role: 'Server → cluster mapping kept by the application.' }],
    alternatives: [{ option: 'One big cluster', verdict: 'Larger blast radius and harder upgrades.' }, { option: 'Index synchronously', verdict: 'Slows every message send for a feature used rarely.' }],
    breaksNext: <p>Big guilds make the Elixir tier itself the bottleneck. Sending one event to thousands of sessions costs seconds.</p>,
    interview: { q: 'Why is search eventually consistent here?', a: <p>People search history, not the last second. Bulk indexing is far cheaper, so a few seconds of lag is a good trade.</p> },
    sources: [S.search],
  },
  {
    title: 'v4 · Making fan-out cheap',
    era: '2017',
    scale: 'guilds with tens of thousands online',
    summary: 'Send one message per remote machine, not one per user, and protect the system from overload.',
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.cass, DN.es],
    edges: [...CORE_EDGES, de('api', 'cass'), de('api', 'es')],
    flows: [{ name: 'Deliver', path: ['api', 'guild', 'gw', 'client'], steps: ['Event reaches the guild process', 'Guild groups recipients by machine and sends one batch per machine', 'Each machine fans out locally to its sessions'] }],
    problem: <p>A guild process sending an event to every session is slow in big servers. Lookups of the hash ring also spike during mass reconnects.</p>,
    decision: <p>Batch sends <strong>per remote node</strong>, which then fans out locally. Keep hot read-only data in a shared heap. Cap concurrent calls to fragile services with semaphores.</p>,
    tradeoff: <p>More custom infrastructure to own. These are low-level fixes that need deep runtime knowledge.</p>,
    realWorld: <p>Discord open-sourced Manifold (batched sends), FastGlobal (shared read-only data), and Semaphore (concurrency limits) for Elixir. The 2017 post says Manifold cut some fan-outs from roughly 1–2 seconds.</p>,
    walkthrough: ['Guild process lists recipient sessions.', 'Recipients are grouped by the node they live on.', 'One message goes to each node.', 'A helper on each node delivers to local sessions.'],
    numbers: [{ label: 'Messages sent per event', value: 'nodes, not users', note: 'batched by machine' }, { label: 'Session servers', value: '≤ 500K sessions', note: 'per server, Discord 2017' }],
    components: [{ name: 'Manifold', role: 'Groups sends by destination node.' }, { name: 'Semaphore', role: 'Limits concurrent calls so a slow dependency cannot cascade.' }],
    alternatives: [{ option: 'Bigger machines', verdict: 'The work is per-event CPU in one process; vertical scale helps little.' }, { option: 'Central message broker', verdict: 'Adds a hop and a new hotspot for every event.' }],
    breaksNext: <p>Text works. Voice is a different problem: real-time media where tens of milliseconds matter.</p>,
    interview: { q: 'How do you reduce fan-out cost?', a: <p>Batch by destination machine, send only to active viewers, and shed or delay low-value events like typing.</p> },
    sources: [S.elixir],
  },
  {
    title: 'v5 · Voice on SFU servers',
    era: '2018',
    scale: '2.6M+ concurrent voice users',
    summary: 'Media goes to a nearby forwarding server that relays streams without mixing them.',
    added: ['voice'],
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.cass, DN.es, DN.idxq, DN.voice],
    edges: [...CORE_EDGES, de('api', 'cass'), de('api', 'es'), de('api', 'idxq', { async: true }), de('idxq', 'es'), de('guild', 'voice'), de('client', 'voice', { label: 'UDP media' })],
    flows: [{ name: 'Join voice', path: ['client', 'gw', 'guild', 'voice'], steps: ['Client asks to join over the gateway', 'Guild checks permissions and assigns a voice server', 'Client streams audio straight to that server'] }],
    problem: <p>Peer-to-peer calls collapse past a few people and expose IP addresses. Mixing audio on servers (MCU) burns CPU.</p>,
    decision: <p>Run a <strong>Selective Forwarding Unit</strong> (SFU). Each client uploads one stream; the SFU forwards it to others. Signaling stays on the gateway; media goes over UDP.</p>,
    tradeoff: <p>A second global fleet, placed by latency instead of cost. It needs its own failover and capacity planning.</p>,
    realWorld: <p>Discord’s 2018 post describes a homegrown C++ SFU, 850+ voice servers in 13 regions, and 2.6M+ concurrent voice users. It uses Salsa20 encryption instead of DTLS/SRTP.</p>,
    walkthrough: ['Client requests a voice channel via the gateway.', 'Voice state service picks a server near the region.', 'Client connects to the SFU over UDP.', 'SFU forwards each speaker’s packets to listeners.'],
    numbers: [{ label: 'Voice servers', value: '850+', note: 'Discord, 2018' }, { label: 'Regions', value: '13', note: '30+ data centers' }, { label: 'Egress', value: '220+ Gbps', note: 'Discord, 2018' }],
    components: [{ name: 'SFU', role: 'Forwards packets; no transcoding. Scales with bandwidth.' }, { name: 'Voice state (Elixir)', role: 'Tracks who is in which channel and on which server.' }],
    alternatives: [{ option: 'P2P mesh', verdict: 'Upload grows with every participant; leaks IPs.' }, { option: 'MCU (mixing)', verdict: 'CPU-heavy; adds latency.' }],
    breaksNext: <p>Member lists in six-figure servers are huge sorted lists. Updating them in an immutable language is slow.</p>,
    interview: { q: 'SFU or MCU for group voice?', a: <p>SFU for most apps: cheap CPU, low latency, clients decode several streams. MCU when clients are very weak.</p> },
    sources: [S.voice],
  },
]
