import type { ArchNode, EpisodeStage } from '../../components/ui'
import { CORE_EDGES, DN, de } from './episode-discord-stage-nodes'
import { DISCORD_SRC as S } from './episode-discord-sources'

const cassHot: ArchNode = { ...DN.cass, sub: '177 nodes · hot keys' }

// Stages 7–12: member lists through million-online servers.
export const DISCORD_STAGES_LATE: EpisodeStage[] = [
  {
    title: 'v6 · Lazy member lists',
    era: '2019',
    scale: '11M concurrent users',
    summary: 'Send only the part of the member list a user can see, backed by a fast sorted set.',
    added: ['members'],
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.cass, DN.es, DN.voice, DN.members],
    edges: [...CORE_EDGES, de('api', 'cass'), de('api', 'es'), de('guild', 'voice'), de('client', 'voice'), de('guild', 'members')],
    flows: [{ name: 'Scroll members', path: ['client', 'gw', 'guild', 'members'], steps: ['Client subscribes to a visible range of the list', 'Gateway forwards the request to the guild', 'Guild reads that slice from the sorted set and streams updates for it'] }],
    problem: <p>Big servers have 100K+ members. Sending the full list, or every change to it, is wasteful. Elixir’s immutable lists copy on every insert.</p>,
    decision: <p>Clients subscribe to the <strong>visible window</strong> only. The sorted member set moves into a <strong>Rust NIF</strong> (native code called from Elixir) for fast inserts and index lookups.</p>,
    tradeoff: <p>Native code can crash the VM if it misbehaves. Clients must request ranges and handle partial lists.</p>,
    realWorld: <p>Discord’s 2019 post describes a Rust-backed SortedSet via Rustler. Inserts took single-digit microseconds, even at up to 1M items in benchmarks.</p>,
    walkthrough: ['Client opens a server and asks for rows 0–100 of the list.', 'Guild returns that slice and remembers the subscription.', 'A member goes online; the sorted set updates in place.', 'Only sessions whose window includes that row get an update.'],
    numbers: [{ label: 'Insert time', value: '≈ 0.6–4 µs', note: 'Rust NIF, Discord 2019' }, { label: 'Concurrent users', value: '11M', note: 'Discord, 2019' }],
    components: [{ name: 'Sorted set NIF', role: 'Mutable, cache-friendly sorted structure inside the Elixir VM.' }, { name: 'Range subscriptions', role: 'Clients see and track only what is on screen.' }],
    alternatives: [{ option: 'Pure Elixir ordsets', verdict: 'Worst-case inserts around 27 ms in Discord’s benchmark.' }, { option: 'External cache (Redis)', verdict: 'A network hop on every member-list mutation.' }],
    breaksNext: <p>Services with huge in-memory caches suffer garbage-collection pauses. Latency spikes every few minutes.</p>,
    interview: { q: 'How do you show a member list for a 500K-member server?', a: <p>Paginate by visible range, push only diffs in that range, and keep the sorted structure in memory next to the owner.</p> },
    sources: [S.memberList],
  },
  {
    title: 'v7 · Rust for hot services',
    era: '2020',
    scale: 'tens of millions of cached read states',
    summary: 'Rewrite a latency-critical cache service in a language without garbage-collection pauses.',
    added: ['readstates'],
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.cass, DN.es, DN.voice, DN.members, DN.readstates],
    edges: [...CORE_EDGES, de('api', 'cass'), de('api', 'es'), de('guild', 'voice'), de('client', 'voice'), de('guild', 'members'), de('api', 'readstates'), de('gw', 'readstates')],
    flows: [{ name: 'Mark read', path: ['client', 'api', 'readstates'], steps: ['User opens a channel', 'API updates that user’s read marker in the Read States cache'] }],
    problem: <p>The Read States service tracks what each user has read. It is hit on every connect, send, and read. Its Go version paused for garbage collection every two minutes.</p>,
    decision: <p>Rewrite it in <strong>Rust</strong>. Memory is freed when it is no longer used, so there are no GC scans of a huge LRU cache.</p>,
    tradeoff: <p>A second systems language to hire for and maintain. Worth it only on hot, latency-sensitive paths.</p>,
    realWorld: <p>Discord’s 2020 post explains that Go forced a GC at least every 2 minutes, scanning a cache with tens of millions of entries. The Rust version removed the spikes.</p>,
    walkthrough: ['Gateway loads read states when a user connects.', 'Opening a channel updates the marker in the in-memory LRU.', 'Dirty entries are written back to the database in batches.'],
    numbers: [{ label: 'Forced GC interval (Go)', value: '≥ every 2 min', note: 'Discord, 2020' }, { label: 'Cache size after rewrite', value: '8M read states', note: 'Discord, 2020' }],
    components: [{ name: 'Read States service', role: 'Per-user, per-channel read markers and mention counts.' }],
    alternatives: [{ option: 'Tune Go GC', verdict: 'The 2-minute forced cycle still scanned the whole cache.' }, { option: 'Smaller cache', verdict: 'More DB reads and higher latency.' }],
    breaksNext: <p>The message store grows to trillions of rows. Hot partitions and JVM pauses hurt tail latency.</p>,
    interview: { q: 'When would you rewrite a service in another language?', a: <p>When the runtime itself causes the problem you can measure, the service is small and hot, and the team can own the new stack.</p> },
    sources: [S.readStates],
  },
  {
    title: 'v8 · Hot partitions',
    era: '2020–2022',
    scale: 'trillions of messages',
    summary: 'A few giant servers create “hot” data that overloads single database partitions.',
    nodes: [DN.client, DN.api, DN.gw, DN.guild, cassHot, DN.voice, DN.members, DN.readstates],
    edges: [...CORE_EDGES, de('api', 'cass'), de('guild', 'voice'), de('client', 'voice'), de('guild', 'members'), de('api', 'readstates')],
    flows: [{ name: 'Announcement', path: ['client', 'api', 'cass'], steps: ['Thousands of users open the same channel at once', 'Every request hits the same partition on the same replicas'] }],
    problem: <p>When a big server posts, thousands read one partition at once. That node falls behind. Compaction debt and JVM garbage collection make tail latency worse.</p>,
    decision: <p>Treat it as two problems: <strong>protect the database</strong> from duplicate reads, and <strong>move to a store</strong> with steadier tail latency.</p>,
    tradeoff: <p>Either fix is a big project. Migrating trillions of rows needs zero downtime and verification.</p>,
    realWorld: <p>Discord’s 2023 post says the Cassandra cluster grew to 177 nodes. p99 for fetching history ranged roughly 40–125 ms.</p>,
    walkthrough: ['A popular channel gets a burst of reads.', 'All reads map to one (channel, bucket) partition.', 'Its replicas queue requests and slow down.', 'Slow nodes hurt every query that touches them.'],
    numbers: [{ label: 'Cassandra nodes', value: '177', note: 'early 2022' }, { label: 'History fetch p99', value: '≈ 40–125 ms', note: 'Discord, 2023' }, { label: 'Insert p99', value: '≈ 5–70 ms', note: 'Discord, 2023' }],
    components: [{ name: 'Per-partition metrics', role: 'Show that load is concentrated on one key, not spread.' }],
    alternatives: [{ option: 'More cache in front', verdict: 'Stampedes arrive before the cache is warm.' }, { option: 'Smaller time buckets', verdict: 'Helps size, not the burst of identical reads.' }],
    breaksNext: <p>You need a layer that merges identical requests before they reach the database.</p>,
    interview: { q: 'p99 spikes during announcements. What do you check?', a: <p>Per-partition read rates, compaction backlog, and GC pauses. Confirm it is one hot key before changing the store.</p> },
    sources: [S.trillions],
  },
  {
    title: 'v9 · Data services + ScyllaDB',
    era: '2022',
    scale: '72 database nodes',
    summary: 'Route each channel to one service instance that merges duplicate reads, on a faster store.',
    added: ['ds', 'scylla'],
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.ds, DN.scylla, DN.voice, DN.members, DN.readstates],
    edges: [...CORE_EDGES, de('api', 'ds'), de('ds', 'scylla'), de('guild', 'voice'), de('client', 'voice'), de('guild', 'members'), de('api', 'readstates')],
    flows: [{ name: 'History', path: ['client', 'api', 'ds', 'scylla'], steps: ['Many clients request the same channel', 'API routes by channel ID to one data-service instance', 'One coalesced query hits ScyllaDB; results fan back out'] }],
    problem: <p>Duplicate reads for one channel must collapse into one query. The store itself must have lower, steadier tail latency.</p>,
    decision: <p>Add Rust <strong>data services</strong>: consistent-hash routing by channel plus <strong>request coalescing</strong>. Migrate messages to <strong>ScyllaDB</strong>, a C++ Cassandra-compatible store.</p>,
    tradeoff: <p>A new tier on the hot path. Coalesced reads can miss a write that lands mid-query; fine for chat.</p>,
    realWorld: <p>Discord’s 2023 post reports 177 Cassandra nodes replaced by 72 ScyllaDB nodes. History p99 fell to about 15 ms. A Rust migrator moved data at about 3.2M rows/s, finishing in 9 days (May 2022).</p>,
    walkthrough: ['API hashes the channel ID to pick a data-service instance.', 'If a read for that channel is in flight, the new request waits on it.', 'Otherwise the instance queries ScyllaDB once.', 'The result is returned to every waiting request.'],
    numbers: [{ label: 'Nodes', value: '177 → 72', note: 'Cassandra → ScyllaDB' }, { label: 'History p99', value: '≈ 15 ms', note: 'after migration' }, { label: 'Migration', value: '9 days', note: '≈ 3.2M rows/s' }],
    components: [{ name: 'Data services (Rust)', role: 'Thin layer between API and database: routing and coalescing.' }, { name: 'ScyllaDB', role: 'Same data model; no JVM GC pauses.' }],
    alternatives: [{ option: 'Coalescing without routing', verdict: 'Random routing still sends one query per instance.' }, { option: 'Stay on Cassandra and tune', verdict: 'GC and compaction pain remained.' }],
    breaksNext: <p>Cloud network disks add ~1–2 ms per I/O. Local SSDs are fast but not durable.</p>,
    interview: { q: 'How would you migrate trillions of rows with no downtime?', a: <p>Dual-write new data, backfill old data with a fast migrator, verify with shadow reads, then cut over with a rollback plan.</p> },
    sources: [S.trillions],
  },
  {
    title: 'v10 · Super-disks',
    era: '2022',
    scale: '≈ 2M DB requests/s',
    summary: 'Read from fast local SSDs and write to durable network disks at the same time.',
    added: ['disk'],
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.ds, DN.scylla, DN.disk, DN.voice],
    edges: [...CORE_EDGES, de('api', 'ds'), de('ds', 'scylla'), de('scylla', 'disk'), de('guild', 'voice'), de('client', 'voice')],
    flows: [{ name: 'Read', path: ['client', 'api', 'ds', 'scylla', 'disk'], steps: ['Client requests history', 'API routes to the data service', 'Data service queries ScyllaDB', 'Disk reads are served by the local SSD half of the mirror'] }],
    problem: <p>Network persistent disks add about 1–2 ms per operation. Local NVMe is about 0.5 ms but loses data with the host.</p>,
    decision: <p>Build a Linux <code>md</code> RAID1 mirror: local SSDs (RAID0) plus a persistent disk marked <strong>write-mostly</strong>. Reads hit SSD; writes go to both.</p>,
    tradeoff: <p>Unusual storage setup to operate. Write latency is still bounded by the network disk.</p>,
    realWorld: <p>Discord’s August 2022 post describes this “super-disk” for its ScyllaDB clusters. I/O wait dropped and query throughput rose on the same hardware.</p>,
    walkthrough: ['Four local NVMe SSDs form a RAID0 volume.', 'That volume is mirrored (RAID1) with a network persistent disk.', 'The persistent disk is marked write-mostly, so reads skip it.', 'Snapshots still come from the durable disk.'],
    numbers: [{ label: 'Network disk latency', value: '≈ 1–2 ms', note: 'Discord, 2022' }, { label: 'Local SSD latency', value: '≈ 0.5 ms', note: 'Discord, 2022' }, { label: 'DB load', value: '≈ 2M req/s', note: 'Discord, 2022' }],
    components: [{ name: 'md RAID1 (write-mostly)', role: 'Kernel-level mirror that prefers the SSD side for reads.' }],
    alternatives: [{ option: 'Local SSD only', verdict: 'A host failure loses data; relies on DB replication alone.' }, { option: 'Network disk only', verdict: 'Queued I/O and timeouts under load.' }],
    breaksNext: <p>A single AI community reaches over a million people online at once.</p>,
    interview: { q: 'How do you get SSD read latency with durable storage?', a: <p>Mirror a fast ephemeral device with a durable one, and send reads to the fast side.</p> },
    sources: [S.superDisk],
  },
  {
    title: 'v11 · Million-online servers',
    era: '2023',
    scale: '1M+ online in one server',
    summary: 'Split one server’s fan-out across relays and skip users who are not looking.',
    added: ['relay'],
    nodes: [DN.client, DN.api, DN.gw, DN.guild, DN.relay, DN.members, DN.ds, DN.scylla, DN.voice],
    edges: [...CORE_EDGES, de('api', 'ds'), de('ds', 'scylla'), de('guild', 'relay'), de('relay', 'gw'), de('guild', 'members'), de('guild', 'voice'), de('client', 'voice')],
    flows: [{ name: 'Deliver', path: ['api', 'guild', 'relay', 'gw', 'client'], steps: ['Event reaches the guild process', 'Guild hands fan-out to relays', 'Each relay serves a slice of sessions', 'Gateways push to clients'] }],
    problem: <p>Fan-out cost grows with online users squared: 100K online users can mean 10 billion notifications. One guild process is CPU-bound.</p>,
    decision: <p>Mark sessions not viewing the server as <strong>passive</strong>. Move fan-out to <strong>relays</strong>, each handling a slice of sessions. Keep member lists in shared memory (ETS).</p>,
    tradeoff: <p>More moving parts on the hottest path. New consistency edges between guild and relays.</p>,
    realWorld: <p>Discord’s 2023 Maxjourney post (about Midjourney’s 10M+ member server) says about 90% of connections in large servers were passive. Each relay handles up to 15,000 sessions.</p>,
    walkthrough: ['Guild process receives an event.', 'It skips passive sessions entirely.', 'It sends the event to relays, not sessions.', 'Relays check permissions and push to their sessions.'],
    numbers: [{ label: 'Passive connections', value: '≈ 90%', note: 'large servers, Discord 2023' }, { label: 'Sessions per relay', value: '≤ 15K', note: 'Discord, 2023' }, { label: 'Midjourney server', value: '10M+ members', note: 'Discord, 2023' }],
    components: [{ name: 'Relays', role: 'Spread fan-out and permission checks across machines.' }, { name: 'ETS member store', role: 'Shared in-memory table so workers can read without copying.' }],
    alternatives: [{ option: 'Bigger guild process machine', verdict: 'One process uses one scheduler; it does not scale up.' }, { option: 'Cap server size', verdict: 'Blocks the product’s biggest communities.' }],
    breaksNext: <p>The next wall is cost and tail latency at even larger scale. That is where this episode ends.</p>,
    interview: { q: 'Deliver messages to a server with 1M people online.', a: <p>Only push to active viewers, shard fan-out across relays, keep one owner for state, and measure p99 delivery lag by server size.</p> },
    sources: [S.maxjourney],
  },
]
